module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Sí',
    'key.button.cancel': 'CANCELAR',
    'key.button.apply': 'OK',
    'key.button.use': 'Usar',
    'key.button.buy': 'Comprar',
    'key.beCarefulMessage.text': 'Estate atento mientras juegas. Mira a los lados.',
    'key.creature.details.attack': 'Fuerza',
    'key.creature.details.health': 'Salud',
    'key.creature.details.powerUp': 'Potenciar',
    'key.creature.details.evolve': 'Evolucionar',
    'key.creature.details.cp': 'PC',
    'key.creature.details.cpValue': 'PC {0}',
    'key.creature.details.hp': 'PS',
    'key.creature.details.transfer': 'SOLTAR',
    'key.creature.details.creadex': 'Bestiario',
    'key.creature.registration.creadex': 'Anadido al bestiario',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Edificios conquistados',
    'key.activeObjects.library': 'Reeducar a la criatura en la Biblioteca',
    'key.activeObjects.library.empty': 'No tienes Bibliotecas conquistadas',
    'key.activeObjects.arena': 'Recoger el tributo de las Arenas',
    'key.activeObjects.arena.collect': 'Recoger',
    'key.activeObjects.arena.empty': 'No tienes Arenas conquistadas',
    'key.activeObjects.error.timer': 'El tributo no está listo. Tienes que esperar',
    'key.activeObjects.error.noMoney': 'Primero tienes que conquistar la Arena',
    'key.activeObjects.error.cannotRemaster': 'No puedes reeducar a tus criaturas. Captura bibliotecas para acelerar el cronómetro para reeducar',
    'key.activeObjects.library.remaster': 'Reeducar',
    'key.activeObjects.library.blocked': 'Las Bibliotecas no están disponibles',
    'key.activeObjects.remaster.confirmation.main': '¿Estás seguro de que quieres reeducar a {0}? ¡La habilidad principal {1} cambiará!',
    'key.activeObjects.remaster.confirmation.charged': '¿Estás seguro de que quieres reeducar a {0}? ¡La habilidad cargada {1} cambiará!',
    'key.activeObjects.remaster.error': 'Error',
    'key.activeObjects.item.weaklyBonus': 'Bonus semanal +{0} monedas',
    'key.library.remaster.selectCreature': 'Elige la criatura que quieres reeducar',
    'key.remasterPanel.title': 'Elige una habilidad',
    'key.storage.creatues': 'Criaturas',
    'key.storage.eggs': 'Huevos',
    'key.storage.eggs.simple': 'Huevos normales',
    'key.storage.eggs.super': 'Huevos antiguos',
    'key.storage.eggs.missingAny': 'No tienes huevos de criaturas',
    'key.startEgg.button': 'Colocarlo en la crisálida',
    'key.startEgg.description': 'Usa la crisálida de dragón para incubar el huevo',
    'key.startEgg.incubator.title': 'Crisálidas de dragón',
    'key.startEgg.select.title': 'Elige un huevo',
    'key.openEgg.button': 'Eclosionar el huevo',
    'key.openEgg.description': 'Una nueva criatura va a eclosionar del huevo',
    'key.startEgg.description.roost.hatching': 'La Madre de los Dragones está incubando el huevo. Solo tienes que esperar. La incubación se suspenderá si la Falla de Arcana en la que se encuentra la Madre de los Dragones desaparece',
    'key.startEgg.description.roost.notHatching': 'Entrega el huevo a la Madre de los Dragones para que lo incube por ti.',
    'key.startEgg.description.simple.hatching': 'Este huevo se está incubando en la crisálida de dragón. Camina con el juego encendido para ayudarle a eclosionar.',
    'key.startEgg.description.simple.notHatching': 'Coloca este huevo en la crisálida de dragón para incubarlo. El huevo eclosionará cuando hayas caminado la distancia requerida.',
    'key.mainMenu.wizardDuels': 'DUELO DE MAGOS',
    'key.mainMenu.quests': 'TAREAS',
    'key.mainMenu.activePoints': 'CAPTURADO',
    'key.mainMenu.creadex': 'BESTIARIO',
    'key.mainMenu.magic': 'MAGIA',
    'key.mainMenu.creatues': 'CRIATURAS',
    'key.mainMenu.shop': 'TIENDA',
    'key.mainMenu.backpack': 'MOCHILA',
    'key.error.banned': 'La cuenta está bloqueada',
    'event.log.CREATURE_CAUGHT': '¡Has atrapado a {0}!',
    'event.log.ITEM_BOUGHT': 'Has comprado {0} x{1}. Has gastado {2} monedas',
    'event.log.ARTIFACT_BOUGHT': 'Has comprado el artefacto: {0}. Has gastado {1} monedas',
    'event.log.EGG_HATCHED': '¡{0} ha eclosionado del {1} huevo!',
    'event.log.EGG_HATCHED.distance': 'km',
    'event.log.EGG_HATCHED.gold': 'de oro',
    'event.log.ROOST_EGG_HATCHED': 'La Madre de los Dragones ha incubado un huevo de {1}h. ¡{0} ahora es tuyo!',
    'event.log.CHEST_OPENED': 'En el baúl has encontrado:',
    'event.log.ARENA_LOST_CONTROL': '{1} ha sido expulsado del edificio: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} ha sido expulsado del edificio: {0}',
    'event.log.LEVEL_UP': 'Has alcanzado el nivel {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Tu mascota ha encontrado {0}',
    'event.log.QUEST_COMPLETED': 'Premio por la tarea {0}',
    'event.log.ENCOUNTER_LOOSE': 'Has logrado escapar del monstruo salvaje',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'El límite de duelos en el Duelo de Magos ha sido aumentado por {0} monedas',
    'event.log.HARD_CURRENCY_BOUGHT': 'Has comprado {0} monedas por {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Has mejorado la mochila por {0} monedas',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Has mejorado el Almacén de criaturas por {0} monedas',
    'key.shop.accesories': 'OBJETOS',
    'key.shop.artifacts': 'ARTEFACTOS',
    'key.shop.donate': 'MONEDAS',
    'key.shop.upgrade': 'MEJORAS',
    'key.shop.donate.coins': '{0} monedas',
    'key.shop.upgrade.bag': 'Mejora de la mochila',
    'key.shop.upgrade.bag.desc': 'El tamano de la mochila será aumentado de 50',
    'key.shop.upgrade.storage': 'Mejora del almacén de las criaturas',
    'key.shop.upgrade.storage.desc': 'El tamano del almacên de criaturas será aumentado de 50',
    'key.shop.donate.dialog.title': 'No tienes suficientes monedas',
    'key.shop.donate.dialog.desc': 'Recibelas aquí, o visita la Tienda para ver más opciones',
    'key.potionUseMenu.title': 'Poción',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Crea un Portal al mundo de Arcana.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Todos los jugadores de alrededor sentirán la furia de los leprechauns',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Crea un campo de Columnas de la Abundancia para 30 minutos',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Duplica el número de premios de las Columnas de la Abundancia para 30 minutos',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Pulsa y mantén el dedo sobre la localidad para iluminarla en busca de criaturas',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Aumenta el radio de búsqueda de criaturas para 30 minutos',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Aumenta el radio de visibilidad de los objetos un 30% para 7 días',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'La Arena aliada más cercana no podrá ser atacada por los enemigos durante 30 horas',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Todas las Arenas enemigas en el radio de visibilidad se vuelven neutrales. Quita la bendición de la defensa.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Crea una torre mágica, que atrae a las criaturas del elemento fuego',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Crea una torre mágica, que atrae a las criaturas del elemento agua',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Crea una torre mágica, que atrae a las criaturas del elemento aire',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Crea una torre mágica, que atrae a las criaturas del elemento tierra',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Crea una torre mágica, que atrae a las criaturas del elemento Arcana',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Falla de Arcana',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Furia de los leprechauns',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Campo de la Abundancia',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Don del Dragón de Oro',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Vista astral',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Vista de dragón',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Manos largas',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Bendición de la defensa',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Purificación con fuego',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Torre de Fuego',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Torre de Agua',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Torre de Aire',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Torre de Tierra',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Torre de Arcana',
    'key.buff.ATTACKER_CP_BOOST': 'El PC de tus criaturas ha sido aumentado por un tiempo',
    'key.buff.BEST_BALL_LUCK': 'Recibirás solo las mejores pociones en las Columnas de la Abundancia durante 30 minutos',
    'key.buff.BEST_POTION_LUCK': 'Recibirás solo las mejores pociones en las Columnas de la Abundancia durante 30 minutos',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Recibirás +2 objetos de las Columnas de la Abundancia durante 30 minutos',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'La recarga de las Bibliotecas ha sido reducida',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'El tiempo hasta la recogida de tributo de las Arenas ha sido reducido',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Aumenta el PC de las criaturas que no están defendiendo edificios',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Recibes de las Columnas de la Abundancia solo las mejores esferas disponibles para tu nivel',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Recibes de las Columnas de la Abundancia solo las mejores pociones disponibles para tu nivel',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Recibes dos objetos más de las Columnas de la Abundancia',
    'key.loot.result.dust': 'Esencia',
    'key.loot.result.exp': 'Experiencia del personaje',
    'key.loot.result.coin': 'Monedas',
    'key.loot.result.candy': 'piedras',
    'key.item.MAGIC_BALL_SIMPLE': 'Esfera del discípulo',
    'key.item.MAGIC_BALL_NORMAL': 'Esfera del maestro',
    'key.item.MAGIC_BALL_GOOD': 'Esfera del señor',
    'key.item.LURE': 'Cebo',
    'key.item.INCENSE': 'Feromonas',
    'key.item.EGG': 'Huevo',
    'key.item.SHOVEL': 'Pala',
    'key.item.POTION_HEAL_1': 'Poción pequeña',
    'key.item.POTION_HEAL_2': 'Poción mediana',
    'key.item.POTION_HEAL_3': 'Poción grande',
    'key.item.POTION_HEAL_4': 'Poción máxima',
    'key.item.POTION_RESURRECTION_1': 'Poción de resurrección',
    'key.item.POTION_RESURRECTION_2': 'Poción de resurrección grande',
    'key.item.INCUBATOR_1': 'Crisálida de dragón',
    'key.item.INCUBATOR_3': 'Crisálida de dragón',
    'key.item.INCUBATOR_PERPETUAL': 'Crisálida de dragón eterna',
    'key.item.SUPER_VISION': 'Vista de dragón',
    'key.item.RUNE_1': 'Runa I',
    'key.item.RUNE_2': 'Runa II',
    'key.item.RUNE_3': 'Runa III',
    'key.item.RUNE_4': 'Runa IV',
    'key.item.RUNE_5': 'Runa V',
    'key.item.RUNE_6': 'Runa VI',
    'key.item.FOOD_CATCH_CHANCE': 'Caramelo arcánico',
    'key.item.FOOD_MORE_DUST': 'Donuts mágico',
    'key.item.FOOD_CALM_DOWN': 'Dulce de unicornios',
    'key.item.FOOD_MORE_CANDIES': 'Helado de los cuatro elementos',
    'key.item.EXPERIENCE_BOOSTER': 'Cristal de la sabiduría',
    'key.item.EGG_KM_0': 'Huevo de Oro',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Esfera para capturar a las criaturas',
    'key.item.MAGIC_BALL_NORMAL.description': 'Esfera para capturar a las criaturas. Aumenta un poco la probabilidad de captura',
    'key.item.MAGIC_BALL_GOOD.description': 'Esfera para capturar a las criaturas. Aumenta mucho la probabilidad de captura.',
    'key.item.LURE.description': 'Cebo para las criaturas. Colócalo en una Columna de la Abundancia para atraer a las criaturas',
    'key.item.INCENSE.description': 'Las feromonas atraerán a criaturas de un cierto elemento, dependiendo del día de la semana',
    'key.item.EGG.description': 'Usa la crisálida de dragón para hacer eclosionar los huevos',
    'key.item.SHOVEL.description': 'Las palas son totalmente insustituibles a la hora de buscar tesoros',
    'key.item.POTION_HEAL_1.description': 'Restaura 200 puntos de salud de tu criatura',
    'key.item.POTION_HEAL_2.description': 'Restaura 500 puntos de salud de tu criatura',
    'key.item.POTION_HEAL_3.description': 'Restaura 1000 puntos de salud de tu criatura',
    'key.item.POTION_HEAL_4.description': 'Restaura toda la salud de tu criatura',
    'key.item.POTION_RESURRECTION_1.description': 'Revive a la criatura elegida. Tras resucitar la criatura quedará herida.',
    'key.item.POTION_RESURRECTION_2.description': 'Revive y restaura toda la salud de la criatura',
    'key.item.INCUBATOR_1.description': 'Las crisálidas de dragón sirven para incubar a las criaturas de los huevos. Desaparece después de usarla',
    'key.item.INCUBATOR_3.description': 'Las crisálidas de dragón sirven para incubar a las criaturas de los huevos. Desaparece después de 3 usos',
    'key.item.INCUBATOR_PERPETUAL.description': 'Las crisálidas de dragón sirven para incubar a las criaturas de los huevos',
    'key.item.SUPER_VISION.description': 'Muestra las criaturas en un radio mayor',
    'key.item.RUNE_1.description': 'Runa mágica de 1 nivel',
    'key.item.RUNE_2.description': 'Runa mágica de 2 nivel',
    'key.item.RUNE_3.description': 'Runa mágica de 3 nivel',
    'key.item.RUNE_4.description': 'Runa mágica de 4 nivel',
    'key.item.RUNE_5.description': 'Runa mágica de 5 nivel',
    'key.item.RUNE_6.description': 'Runa mágica de 6 nivel',
    'key.item.FOOD_CATCH_CHANCE.description': 'Golosina para atrapar a las criaturas. Aumenta la probabilidad de capturar a las criaturas con una esfera mágica',
    'key.item.FOOD_MORE_DUST.description': 'Golosina para atrapar a las criaturas. Aumenta la esencia que recibes por capturar a una criatura',
    'key.item.FOOD_CALM_DOWN.description': 'Golosina para atrapar a las criaturas. Tranquiliza a las criaturas. Dejan de saltar y atacar',
    'key.item.FOOD_MORE_CANDIES.description': 'Golosina para atrapar a las criaturas. Aumenta el número de piedras de almas que recibes por capturar a una criatura',
    'key.item.EXPERIENCE_BOOSTER.description': 'Duplica la experiencia que recibes durante 30 minutos',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Máscara del mago',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': 'Puedes colocar a distancia +1 criatura en una Arena o Biblioteca al día',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Este artefacto te permite colocar 1 vez al día a una criatura tuya en un puesto libre en una Arena o Biblioteca visible desde cualquier distancia',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Cara de vidente',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': 'Puedes colocar a distancia +2 criaturas en una Arena o Biblioteca al día',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Este artefacto te permite colocar 2 veces al día a una criatura tuya en un puesto libre en una Arena o Biblioteca visible desde cualquier distancia',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Yelmo del conquistador',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': 'Puedes colocar a distancia +3 criaturas en una Arena o Biblioteca al día',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Este artefacto te permite colocar 3 veces al día a una criatura tuya en un puesto libre en una Arena o Biblioteca visible desde cualquier distancia',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Yelmo del héroe',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': 'Puedes colocar a distancia +4 criaturas en una Arena o Biblioteca al día',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Este artefacto te permite colocar 4 veces al día a una criatura tuya en un puesto libre en una Arena o Biblioteca visible desde cualquier distancia',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Yelmo del guerrero dragón',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': 'Puedes colocar a distancia +5 criaturas en una Arena o Biblioteca al día',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Este artefacto te permite colocar 5 veces al día a una criatura tuya en un puesto libre en una Arena o Biblioteca visible desde cualquier distancia',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Bandera del señor',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Permite colocar en la Arena o Biblioteca a una criatura más',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Con este artefacto puedes poner en la defensa de una Arena o Biblioteca a dos monstruos en vez de uno',
    'key.artifact.ARTIFACT_BANK_8': 'Artefacto cortado',
    'key.artifact.ARTIFACT_BANK_8.description': '¿Pero cómo lo has encontrado?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Has visto un artefacto que no tenías que ver. Ahora tendremos que librarnos de ti como testigo',
    'key.artifact.ARTIFACT_BANK_9': 'Artefacto cortado',
    'key.artifact.ARTIFACT_BANK_9.description': '¿Pero cómo lo has encontrado?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Has visto un artefacto que no tenías que ver. Ahora tendremos que librarnos de ti como testigo.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Reloj del estudiante vago',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': 'Las Columnas de la Abundancia se recargan 20 segundos más rápido',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Con este artefacto las Columnas de la Abundancia se recargarán 20 segundos más rápido y se podrán usar más a menudo.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Despertador del tardón',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': 'Las Columnas de la Abundancia se recargan 40 segundos más rápidon',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Con este artefacto las Columnas de la Abundancia se recargarán 40 segundos más rápido y se podrán usar más a menudo.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Acelerador del espacio',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': 'Las Columnas de la Abundancia se recargan 60 segundos más rápido',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Con este artefacto las Columnas de la Abundancia se recargarán 60 segundos más rápido y se podrán usar más a menudo.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Reloj del profesor vago',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': 'Las Columnas de la Abundancia se recargan 80 segundos más rápido',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Con este artefacto las Columnas de la Abundancia se recargarán 80 segundos más rápido y se podrán usar más a menudo.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Reloj de la cebra-conejo',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': 'Las Columnas de la Abundancia se recargan 100 segundos más rápido',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Con este artefacto las Columnas de la Abundancia se recargarán 100 segundos más rápido y se podrán usar más a menudo.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Cetro del conquistador',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 al nivel de la Arena o Biblioteca después de conquistarla',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Si el propietario de este artefacto es el primero en colocar a una criatura en la Arena o Biblioteca conquistada, aquella recibe enseguida el nivel 5 en vez del nivel 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Anillo del recogedor de tributos',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 al número máximo de Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Con este artefacto podrás recoger el tributo de 11 Arenas en vez de 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Anillo de la avaricia',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 al número máximo de Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Con este artefacto podrás recoger el tributo de 12 Arenas en vez de 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Anillo doble',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 al número máximo de Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Con este artefacto podrás recoger el tributo de 13 Arenas en vez de 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Copa del devorador de tartas',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% a la gloria de las Arenas y Bibliotecas aliadas durante el entrenamiento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Con este artefacto las Arenas y Bibliotecas aliadas reciben un 20% más de gloria cuando las entrenas',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Copa para la miel',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% a la gloria de las Arenas y Bibliotecas aliadas durante el entrenamiento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Con este artefacto las Arenas y Bibliotecas aliadas reciben un 30% más de gloria cuando las entrenas',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Copa de pensamientos profundos',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% a la gloria de las Arenas y Bibliotecas aliadas durante el entrenamiento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Con este artefacto las Arenas y Bibliotecas aliadas reciben un 40% más de gloria cuando las entrenas',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Grial de Lancelop',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% a la gloria de las Arenas y Bibliotecas aliadas durante el entrenamiento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Con este artefacto las Arenas y Bibliotecas aliadas reciben un 50% más de gloria cuando las entrenas',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Copa del conquistador de monstruos',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% a la gloria de las Arenas y Bibliotecas aliadas durante el entrenamiento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Con este artefacto las Arenas y Bibliotecas aliadas reciben un 80% más de gloria cuando las entrenas',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Tótem de la clarividencia',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Expulsa a las criaturas débiles del radar',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Este artefacto expulsa del radar a las criaturas más débiles, cosa que te ayuda a concentrarte en la búsqueda de especímenes más fuertes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Libro de reglas del aventurero',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': 'Puedes recoger el tributo de las Arenas durante 15 minutos más tras ser conquistadas por el enemigo',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Con este artefacto puedes recoger el tributo de las Arenas durante 30 minutos tras su conquista en vez de 15 minutos',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Libro gordo y grande',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': 'Puedes recoger el tributo de las Arenas durante 30 minutos más tras ser conquistadas por el enemigo',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Con este artefacto puedes recoger el tributo de las Arenas durante 45 minutos tras su conquista en vez de 15 minutos',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tabla de la pretensión',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': 'Puedes recoger el tributo de las Arenas durante 45 minutos más tras ser conquistadas por el enemigo',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Con este artefacto puedes recoger el tributo de las Arenas durante 60 minutos tras su conquista en vez de 15 minutos',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Tratado sobre el poder',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': 'Puedes recoger el tributo de las Arenas durante 75 minutos más tras ser conquistadas por el enemigo',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Con este artefacto puedes recoger el tributo de las Arenas durante 90 minutos tras su conquista en vez de 15 minutos',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimorio del poder',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': 'Puedes recoger el tributo de las Arenas durante 105 minutos más tras ser conquistadas por el enemigo',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Con este artefacto puedes recoger el tributo de las Arenas durante 120 minutos tras su conquista en vez de 15 minutos',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Collar con pinchos',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': 'Recibes una piedra de almas de tu mascota un 10% más rápido',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Con este artefacto tienes que caminar con tu mascota una distancia un 10% más corta para recibir una piedra de almas. También hace a tu mascota un 17% más temible',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Zanahoria en un palo',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': 'Recibes una piedra de almas de tu mascota un 15% más rápido',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Con este artefacto tienes que caminar con tu mascota una distancia un 15% más corta para recibir una piedra de almas. Delicioso.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Rascador de espaldas',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': 'Recibes una piedra de almas de tu mascota un 25% más rápido',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Con este artefacto tienes que caminar con tu mascota una distancia un 25% más corta para recibir una piedra de almas. ¡Inclínate ante el poder del rascador de espaldas!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Cascabel de la mascota',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': 'Recibes una piedra de almas de tu mascota un 30% más rápido',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Con este artefacto tienes que caminar con tu mascota una distancia un 30% más corta para recibir una piedra de almas. ¿Quién es la cosita más bonita?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Dragón de peluche',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': 'Recibes una piedra de almas de tu mascota un 40% más rápido',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Con este artefacto tienes que caminar con tu mascota una distancia un 40% más corta para recibir una piedra de almas. El mejor juguete para la mejor mascota del mundo',
    'key.artifact.ARTIFACT_ROOST_1': 'Corazón de dragón',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 crisálida de dragón para la Madre de los Dragones',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Permite usar una crisálida de dragón adicional para los huevos en la Madre de los Dragones',
    'dialog.artifact.select_artifact': 'ESCOGE EL ARTEFACTO',
    'dialog.artifact.confirm.remove': '¿Estás seguro de que quieres eliminar el artefacto?',
    'dialog.items.title': 'MOCHILA',
    'dialog.items.cannotUse': 'No puedes usar este objeto',
    'dialog.items.remove.header': 'Eliminar objetos',
    'dialog.encounter.header': '¡Un monstruo salvaje te está atacando!',
    'dialog.encounter.button.leave': 'Escapar',
    'dialog.encounter.button.fight': 'Combatir',
    'dialog.encounter.result.outcome.win': 'Has vencido al monstruo salvaje',
    'dialog.encounter.result.outcome.lose': 'Tu criatura ha sido derrotada',
    'dialog.encounter.result.reward.dust': 'Esencia',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': 'Introduce el nombre del personaje',
    'error.nickname.validation.TOO_SHORT': 'El nombre debe contener entre 3 y 16 símbolos',
    'error.nickname.validation.TOO_LONG': 'El nombre debe contener entre 3 y 16 símbolos',
    'error.nickname.validation.INVALID_CHAR': 'Solo puedes usar letras, números y la barra baja.',
    'error.nickname.validation.DUPLICATE': 'Este nombre ya existe. Puedes coger el nombre {0}',
    'creature.MONSTER_WATER_1': 'Ranius',
    'creature.MONSTER_WATER_2': 'Gota',
    'creature.MONSTER_WATER_3': 'Espiritus',
    'creature.MONSTER_WATER_4': 'Sobraquian',
    'creature.MONSTER_WATER_5': 'Ranissimo',
    'creature.MONSTER_WATER_6': 'Arroyus',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Infalisco',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadachock',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerilisco',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Bajoquian',
    'creature.MONSTER_WATER_18': 'Dadachum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilisco',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Crystallhat',
    'creature.MONSTER_WATER_23': 'Armarrana',
    'creature.MONSTER_WATER_24': 'Neptuno',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mummyween',
    'creature.MONSTER_FIRE_3': 'Vaporex',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Zarpafuego',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dummyween',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Vaporeye',
    'creature.MONSTER_FIRE_11': 'Chispa',
    'creature.MONSTER_FIRE_12': 'Kiddra',
    'creature.MONSTER_FIRE_13': 'Daemonstar',
    'creature.MONSTER_FIRE_14': 'Fenix',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Tío de acero',
    'creature.MONSTER_FIRE_17': 'Marifuego',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Flash',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Artificius',
    'creature.MONSTER_FIRE_24': 'Picarun',
    'creature.MONSTER_FIRE_25': 'Smoargh',
    'creature.MONSTER_EARTH_1': 'Bayadil',
    'creature.MONSTER_EARTH_2': 'Florix',
    'creature.MONSTER_EARTH_3': 'Hoja',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryad',
    'creature.MONSTER_EARTH_7': 'Plantix',
    'creature.MONSTER_EARTH_8': 'Goblic',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Bellotus',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Piñetof',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Trol',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Jardix',
    'creature.MONSTER_EARTH_20': 'Priman',
    'creature.MONSTER_EARTH_21': 'Abetierr',
    'creature.MONSTER_EARTH_22': 'Florimal',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Orejago',
    'creature.MONSTER_WIND_3': 'Hongy',
    'creature.MONSTER_WIND_4': 'Suavicornio',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Miedón',
    'creature.MONSTER_WIND_8': 'Orejaton',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Bailaviento',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Airecornio',
    'creature.MONSTER_WIND_14': 'Fantomo',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Hongotopia',
    'creature.MONSTER_WIND_17': 'Harpy',
    'creature.MONSTER_WIND_18': 'Fantasmus',
    'creature.MONSTER_WIND_19': 'Puerogrifo',
    'creature.MONSTER_WIND_20': 'Almogato',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Huracdine',
    'creature.MONSTER_WIND_23': 'Grifo',
    'creature.MONSTER_WIND_24': 'Baiun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Lomopincho',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Cuquigato',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Merid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Espantapájaros',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Genie',
    'creature.MONSTER_DUNGEON_12': 'Vampirus',
    'creature.MONSTER_DUNGEON_13': 'Advise',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Softail',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Drachulo',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigromante',
    'creature.MONSTER_DUNGEON_21': 'Sharptail',
    'creature.MONSTER_DUNGEON_22': 'Broton',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Manticora',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Mordisco de tiburón',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Terror profundo',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Llamada de Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Martillo marino',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Puño de agua',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Ola',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Diluvio',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Geiser',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Chapoteo',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Llama viva',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Anillo de fuego',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Látigo de fuego',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Bola de fuego',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Cremar',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Estrella',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Carbón',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Lanzallamas',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Fusilar',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Hoz de viento',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Desgarrar',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Respiro',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Electroshock',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Centella',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Electroconvulsión',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Respiro de dragón',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Soplo',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Furia del viento',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Escupir veneno',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Colmillo de serpiente',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Envenenar',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Quiebrahuesos',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Roca',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Pedrusco',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Espíritu del bosque',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Fantasma del árbol',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Sombra de la naturaleza',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Flecha de Arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Grumo de oscuridad',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentáculo del mal',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Ojo del terror',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Esfera de la perdición',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Bola de oscuridad',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arcana Cadabra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarcus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Impericanos',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Helar',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Congelar',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Cristalizar',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Remolino',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Ventisca',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Furia fría',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Explosión de hielo',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Poder del hielo',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Depurar',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Ascender',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Quemar',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lava',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Fuente de fuego',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteoro',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Relámpago',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Trueno',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Tormenta',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Recargar',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Campo elêctrico',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Pelos de punta',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Rugido del viento',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Tiovivo',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Estruendo',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Sacudida',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Falla',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Derrumbar',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Explosión',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Remolino de piedras',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Lago de la muerte',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Charco venenoso',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Ácido',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomismo',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Desintegrar',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionizar',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Exiliar',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Maldición',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Exclusión',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Tormenta mágica',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Tormenta de mana',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Furia de Arcana',
    'key.combined.first.1': 'Sabios',
    'key.combined.first.2': 'Infernales',
    'key.combined.first.3': 'Preciosos',
    'key.combined.first.4': 'Maliciosos',
    'key.combined.first.5': 'Neutrales',
    'key.combined.first.6': 'Honestos',
    'key.combined.first.7': 'Santos',
    'key.combined.first.8': 'Antiguos',
    'key.combined.first.9': 'Subterráneos',
    'key.combined.first.10': 'Llameantes',
    'key.combined.first.11': 'Hábiles',
    'key.combined.first.12': 'Enormes',
    'key.combined.first.13': 'Azules',
    'key.combined.first.14': 'Crueles',
    'key.combined.first.15': 'Bondadosos',
    'key.combined.first.16': 'Aéreos',
    'key.combined.first.17': 'Terrestres',
    'key.combined.first.18': 'Rojos',
    'key.combined.first.19': 'Inmortales',
    'key.combined.first.20': 'Muertos',
    'key.combined.first.21': 'Aéreos',
    'key.combined.first.22': 'Espantosos',
    'key.combined.first.23': 'Acuáticos',
    'key.combined.first.24': 'Divertidos',
    'key.combined.first.25': 'Bobos',
    'key.combined.second.1': 'Héroes',
    'key.combined.second.2': 'Peces',
    'key.combined.second.3': 'Búhos',
    'key.combined.second.4': 'Malhechores',
    'key.combined.second.5': 'Adeptos',
    'key.combined.second.6': 'Magos',
    'key.combined.second.7': 'Ancianos',
    'key.combined.second.8': 'Encantadores',
    'key.combined.second.9': 'Guerreros',
    'key.combined.second.10': 'Duelistas',
    'key.combined.second.11': 'Mercaderes',
    'key.combined.second.12': 'Conejos',
    'key.combined.second.13': 'Manzanas',
    'key.combined.second.14': 'Luchadores',
    'key.combined.second.15': 'Ilusionistas',
    'key.combined.second.16': 'Caballeros',
    'key.combined.second.17': 'Bárbaros',
    'key.combined.second.18': 'Escarabajos',
    'key.combined.second.19': 'Serpientes',
    'key.combined.second.20': 'Dragones',
    'key.combined.second.21': 'Fantasmas',
    'key.combined.second.22': 'Gatitos',
    'key.combined.second.23': 'Soldados',
    'key.combined.second.24': 'Afortunados',
    'key.combined.second.25': 'Asesinos',
    'key.combined.second.26': 'Ratones',
    'key.combined.second.27': 'Elementales',
    'key.combined.second.28': 'Exploradores',
    'key.combined.second.29': 'Chamanes',
    'key.combined.second.30': 'Sacerdotes',
    'key.combined.second.31': 'Ángeles',
    'key.combined.second.32': 'Arcontes',
    'key.combined.second.33': 'Verdugos',
    'key.combined.second.34': 'Necios',
    'key.combined.second.35': 'Valientes',
    'key.combined.second.36': 'Bonachones',
    'key.combined.second.37': 'Cobardes',
    'key.combined.second.38': 'Bardos',
    'key.combined.second.39': 'Domadores',
    'key.combined.second.40': 'Defensores',
    'key.combined.arena': 'Arena de los {1} {0} ',
    'key.combined.library': 'Biblioteca de los {1} {0} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Agua',
    'element.type.WIND': 'Aire',
    'element.type.FIRE': 'Fuego',
    'element.type.EARTH': 'Tierra',
    'element.type.DUNGEON': 'Arcana',
    'spell.type.ACTIVATION_RADIUS': 'Radio de visibilidad',
    'spell.type.VISION_RADIUS': 'Vista de dragón',
    'spell.type.STOP_FIELD': 'Campo de la Abundancia',
    'spell.type.SCOUT': 'Explorar',
    'spell.type.PROTECT_ARENA': 'Defender la Arena',
    'spell.type.CREATE_PORTAL': 'Crear un Portal',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Doble drop',
    'spell.type.SLUG_PLAYERS': 'SLUG_PLAYERS',
    'quest.title.WIN_ARENA_MONSTER': 'Dominación',
    'quest.title.OPEN_EGGS': 'Fiebre de huevos',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Control del territorio',
    'quest.title.CAPTURE_LIBRARY': 'Sed del saber',
    'quest.title.CAPTURE_WILD_MONSTER': 'Parque dracónico',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Caza de los elementos',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Búsqueda de la Nacida en Arcana',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Limpiar la Falla',
    'quest.title.OPEN_CHEST': 'Antiguos tesoros',
    'quest.title.CHAIN_OF_STOP': 'Camino de la Abundancia',
    'quest.desc.WIN_ARENA_MONSTER': 'Vence a las criaturas en las Arenas o Bibliotecas. No puedes vencer a la criatura del mismo tipo dos veces.',
    'quest.desc.OPEN_EGGS': 'Incuba a las criaturas de los huevos con la ayuda de las crisálidas de dragón o la Madre de los Dragones',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Recoge el tributo de las Arenas que has conquistado',
    'quest.desc.CAPTURE_LIBRARY': 'Posee la cantidad necesaria de Bibliotecas',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Las criaturas nunca son demasiadas. Viaja y captura criaturas',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Viaja y captura criaturas del elemento Agua',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Viaja y captura criaturas del elemento Aire',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Viaja y captura criaturas del elemento Fuego',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Viaja y captura criaturas del elemento Tierra',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Viaja y captura criaturas del elemento Arcana',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Visita la Falla de Arcana, en la que se encuentra la Madre de los Dragones',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Visita la Falla de Arcana y captura a todas las criaturas que encuentres',
    'quest.desc.OPEN_CHEST': 'Encuentra y abre los baúles del tesoro',
    'quest.desc.CHAIN_OF_STOP': 'Pasa por una cadena de Columnas de la Abundancia y activalas. Cada siguiente Columna se iluminará',
    'quest.dialog.completed.rewardtext': 'Tu premio:',
    'key.tab.altar.title': 'ALTAR',
    'key.altar.remove': 'Quitar',
    'key.altar.put': 'Colocar',
    'key.altar.convert': 'Convertir',
    'key.altar.shared': 'Mostrar a los demás',
    'key.altar.pass.placeholder': 'Aquí puedes introducir una contraseña',
    'key.altar.pass.error': 'La contraseña debe contener mínimo {0} símbolos',
    'key.altar.level.error': 'Tienes que alcanzar el nivel {0} para poder usar el Altar',
    'key.altar.recipe.change': '¿Estás seguro de que quieres cambiar la receta? Las Runas serán devueltas a sus propietarios',
    'key.altar.row.title': 'Para crear un conjuro tienes que instalar un Altar',
    'key.altar.rune.descr.RUNE_1': '3 runas grises = una naranja',
    'key.altar.rune.descr.RUNE_2': '3 runas naranjas = una azul',
    'key.altar.rune.descr.RUNE_3': '3 runas azules = una esmeralda',
    'key.altar.rune.descr.RUNE_4': '3 runas esmeraldas = una roja',
    'key.altar.rune.descr.RUNE_5': '3 runas rojas = una morada',
    'key.altar.rune.descr.RUNE_6': 'Las runas moradas son las más fuertes',
    'error.altar.cannotRemove': 'No puedes quitar el Altar',
    'error.altar.cannotConvert': 'No tienes suficientes runas',
    'key.tab.altar.recipes': 'RECETAS',
    'key.altar.noRecipes': 'No tienes recetas',
    'key.altar.header': 'Coloca las runas sobre el Altar para crear un conjuro',
    'key.altar.castBtn': 'Crear',
    'key.altar.recipe.select': 'Escoge un conjuro',
    'key.altar.castDone': 'Has creado el conjuro',
    'key.arena.protected.ally': 'Protección:',
    'key.avatarCustomization.title': 'Escoge la apariencia del personaje',
    'key.buddy.walkDescription': 'Pasea con tu mascota para recibir {0}',
    'key.buddy.totalWalked': 'Ya has recorrido {0} km',
    'key.account.balance': 'Recursos:',
    'key.account.userLevel': '{0} nivel',
    'key.account.totalDistance': 'Distancia recorrida: {0} kilómetros',
    'key.acount.registerDate': 'Empezaste a jugar: {0}',
    'key.storage.sort.name': 'NOMBRE',
    'key.storage.sort.cp': 'PC',
    'key.storage.sort.group1': 'LISTA VERDE',
    'key.storage.sort.group2': 'LISTA AMARILLA',
    'key.storage.sort.group3': 'LISTA ROJA',
    'key.storage.sort.date': 'FECHA',
    'key.account.options.jurnal': 'HISTORIAL',
    'key.account.options.buddy': 'MASCOTA',
    'key.account.options.artifacts': 'ARTEFACTOS',
    'key.account.options.style': 'APARIENCIA',
    'key.error.gps.permission': 'El GPS no está disponible. Por favor, enciende el acceso al GPS en las opciones de la aplicación para poder seguir jugando',
    'key.error.gps.disabled': 'El GPS está desactivado. Activa el GPS para poder seguir jugando',
    'key.error.gps.fakePosition': 'No puedes jugar sin GPS.',
    'key.error.gps.signal.notFound': 'No hay señal de GPS',
    'key.error.gps.signal.bad': 'El juego no está disponible. La señal GPS es muy débil',
    'key.error.internet.notReachable': 'No tienes conexión a Internet',
    'key.journal.title': 'Historial',
    'key.journal.yesterday': 'Ayer',
    'key.settings.title': 'Opciones',
    'key.settings.music': 'Música',
    'key.settings.deviceAuthError': 'Por motivos de seguridad vincule la cuenta a Google o Facebook',
    'key.settings.sounds': 'Sonido',
    'key.settings.vibration': 'Vibración',
    'key.settings.batterySaver': 'Ahorro de energía',
    'key.settings.support': 'Escribir al soporte',
    'key.settings.logout': 'Salir de la cuenta',
    'key.settings.auth.deviceid': 'ID del dispositivo',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Vincular',
    'key.settings.languageTitle': 'Idioma',
    'key.settings.language': 'Espanol',
    'key.battle.result.win': 'Fin del combate',
    'key.battle.result.lose': 'Fin del combate',
    'key.wizardBattle.result.win': '¡VICTORIA!',
    'key.wizardBattle.result.lose': '¡DERROTA!',
    'key.battle.result.monster': 'Criaturas vencidas',
    'key.battle.result.exp': 'Experiencia obtenida',
    'key.battle.result.prestige_strong_enemy': 'Bonus de gloria por enemigos fuertes',
    'key.battle.result.exp_strong_enemy': 'Bonus de experiencia por enemigos fuertes',
    'key.battle.result.prestige_killed_all': 'Bonus de gloria por matar a todos',
    'key.battle.result.exp_killed_all': 'Bonus de experiencia por matar a todos',
    'key.battle.result.dust': 'Esencia',
    'key.radar.title': 'Criaturas cerca',
    'key.levelUp.title': '¡Nuevo nivel!',
    'key.wizardBattle.left': 'Límite de combates:',
    'key.wizardBattle.timer': 'El límite se reseteará dentro de',
    'key.wizardBattle.enhance.title': 'AUMENTAR EL LÍMITE',
    'key.wizardBattle.enhance.desc': 'Se puede aumentar el límite de combates hasta 7 al día durante una semana',
    'key.wizardBattle.enhance.btn': 'Aumentar',
    'key.wizardBattle.lookingForOpponent': 'Buscando un adversario para el Duelo...',
    'key.catch.result.expMonster': 'Experiencia por capturarla:',
    'key.catch.result.expMonsterNew': 'Nuevo en el Bestiario:',
    'key.catch.result.expAccurate': 'Lanzamiento certero:',
    'key.catch.result.expSpin': 'Lanzamiento curvo:',
    'key.catch.result.strike': 'Primera criatura del día:',
    'key.catch.result.total': 'Experiencia total:',
    'key.catch.fullStorage': 'El almacén de criaturas está lleno',
    'key.catch.noItems': 'No tienes esferas mágicas',
    'key.creadex.title': 'BESTIARIO',
    'key.creadex.detail.caught': 'ATRAPADO: {0}',
    'key.creadex.detail.evolution': 'EVOLUCIÓN',
    'key.tab.doll': 'PERSONAJE',
    'key.tab.artifacts': 'ARTEFACTOS',
    'key.activePoint.title': 'Columna de la Abundancia',
    'key.personalization.title': 'Encantamiento',
    'key.chest.title': 'Baúl mágico',
    'key.quest.daily.title': 'TAREA',
    'key.quest.weekly.title': 'CAZA',
    'key.quest.get': 'RECIBIR TAREA',
    'key.quest.change': 'CAMBIAR TAREA',
    'key.quest.progress': 'Progreso de la tarea: {0} de {1}',
    'key.error.quest.weekly.level': 'Tienes que alcanzar el nivel {0} para empezar la caza al Huevo de Oro',
    'key.error.quest.daily.level': 'Tienes que alcanzar el nivel {0} para recibir la tarea',
    'key.error.quest.tooFar': 'El obelisco está demasiado lejos',
    'key.quest.daily.descr.noQuest.title': 'No tienes tareas',
    'key.quest.daily.descr.noQuest': 'Usa los Obeliscos para recibir una tarea y obtener el premio',
    'key.quest.daily.timer.descr': 'Podrás cambiar la tarea en:',
    'key.quest.daily.waitForNew.descr': 'Puedes recibir una nueva tarea en: ',
    'key.quest.weekly.getFragment': 'RECIBIR UN FRAGMENTO',
    'key.quest.weekly.descr.noQuest.title': 'No participas en la caza al Huevo de Oro',
    'key.quest.weekly.descr.noQuest': 'Usa los Obeliscos para recibir un fragmento del mapa misterioso y empezar la caza',
    'key.quest.weekly.descr.getFirstFragment': 'Recibe el primer fragmento del mapa misterioso para empezar la caza al Huevo de Oro',
    'key.quest.weekly.descr.top.notAllOpen': 'Usa los obeliscos para recibir los fragmentos del mapa. Date prisa, la caza termina en',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Usa la pala en cada fragmento para encontrar el Huevo de Oro',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Ya has recibido el fragmento del mapa de este obelisco',
    'key.quest.weekly.descr.top.allOpen': 'Ya has recibido todos los fragmentos del mapa de los obeliscos. Date prisa, la caza termina en',
    'key.quest.weekly.descr.bot.allOpen': 'Usa la pala en cada fragmento para encontrar el Huevo de Oro',
    'key.quest.weekly.descr.top.completed': 'Ya has encontrado el Huevo de Oro esta semana. La próxima caza empieza en',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}h',
    'key.timer.format.H_M': '{0}h {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}h',
    'key.creatureStorage.tab.creatures': 'CRIATURAS',
    'key.creatureStorage.tab.eggs': 'HUEVOS',
    'key.creatureStorage.multiTransferText': 'Elige a quién quieres soltar',
    'key.storage.creature.transfer': 'Soltar ({0})',
    'key.error.needHigherLevelForArena': 'Necesitas el nivel {0} para entrar en la Arena',
    'key.error.needHigherLevelForLibrary': 'Necesitas el nivel {0} para entrar en la Biblioteca',
    'key.error.arenaUnderProtection': 'La arena está bajo la custodia de la Bendición de la Defensa',
    'key.error.buildingTooFar': 'El edificio está demasiado lejos',
    'key.error.noAliveCreaturesForAttack': 'No tienes criaturas vivas',
    'key.error.noHealPotion': 'No tienes pociones',
    'key.error.noResurrectionPotion': 'No tienes revivir',
    'key.error.tryAgainLater': 'Error. Vuélvelo a intentar',
    'key.error.alreadyHasLure': 'El cebo ya está instalado',
    'key.error.cannotUseLureInDungeon': 'No se puede usar el cebo en la Falla de Arcana.',
    'key.error.bagIsFull': 'No tienes sitio en la mochila',
    'key.error.cantTransferCreature': 'No puedes soltar a esta criatura',
    'key.notification.done': '¡Listo!',
    'key.modal.doYouWantToTransfer': '¿Estás seguro de que quieres soltar a estas criaturas?',
    'key.modal.youWillLoseBuddyProgress': '¿Estás seguro de que quieres cambiar de mascota? El progreso para recibir la piedra de almas se perderá',
    'key.modal.doYouWantToLeaveDungeon': '¿Quieres abandonar la Falla de Arcana?',
    'key.modal.superVisionActive': 'La vista de dragón ya está activada. Si vuelves a aplicarla, la zona mágica de visibilidad cambiará. ¿Estás seguro de que quieres volver a usarla?',
    'key.modal.experienceBoosterActive': 'El cristal de la sabiduría ya está activado. ¿Estás seguro de que quieres volver a usarlo?',
    'key.modal.youWillLooseQuestProgress': 'El progreso de la tarea actual se perderá. ¿Estás seguro?',
    'key.modal.doYouWantToEnterDungeon': '¿Quieres entrar en la Falla de Arcana a través del Portal?',
    'key.modal.doYouWantPersonalizePoint': 'La Columna de la Abundancia encantada entregará solo {0}. ¿Quieres gastar {1} monedas para encantarla?',
    'key.modal.doYouWantToDeletePersonalization': '¿Estás seguro de que quieres quitar el encanto de esta Columna de la Abundancia?',
    'key.modal.doYouWantToPowerUpThisCreature': '¿Quieres potenciar a esta criatura?',
    'key.modal.doYouWantToEvolveThisCreature': '¿Quieres convertir esta criatura en una más fuerte?',
    'key.modal.doYouWantToScoutHere': '¿Seguro que quieres iluminar esta zona?',
    'key.error.creatureHasMaxLevel': 'La criatura ya tiene el nivel máximo',
    'key.error.creatureHasMaxLevelForUser': 'Primero tienes que subir de nivel al personaje',
    'key.error.notEnoughResourcesForEnhance': 'No tienes suficientes recursos',
    'key.error.creatureIsArenaDefender': 'No puedes elegir a una criatura que está defendiendo el edificio',
    'key.modal.incenseActive': 'Las feromonas ya están activadas. ¿Estás seguro de que quieres volver a usarlas?',
    'key.error.cantHealHealthyCreature': 'Esta criatura tiene toda la salud',
    'key.error.cantRessurectAliveCreature': 'Esta criatura ya está viva',
    'key.error.noTreasureHere': 'El Huevo de Oro no está en este fragmento del mapa. Sigue buscando',
    'key.error.levelTooSmall': 'Primero tienes que subir de nivel al personaje',
    'key.error.needHigherLevelForWizardBattles': 'Necesitas el nivel {0} para participar en los Duelos de los Magos',
    'key.error.artifactBagIsFull': 'En el almacén de artefactos no hay más espacio',
    'key.error.notEnoughCoins': 'No tienes suficientes monedas',
    'key.error.allFragmentsAreOpen': 'Todos los fragmentos del mapa misterioso están abiertos',
    'key.error.questAlreadyCompleted': 'Ya has completado esta tarea',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Ya has recibido el fragmento del mapa de este Obelisco',
    'key.error.portalTooFarAway': 'El portal está demasiado lejos',
    'key.error.battleLimitAlreadyEnhanced': 'Ya has aumentado el límite de combates',
    'key.error.youAreNotAltarOwner': 'Solo el propietario del Altar puede hacer esto',
    'key.error.youAlreadyHaveAltar': 'El altar ya está instalado',
    'key.error.cantTakeAnotherUsersRune': 'No puedes llevarte la runa de otro jugador',
    'key.error.libraryBlocked': 'Tras reeducar a una criatura tienes que esperar tres días para volver a usar la Biblioteca',
    'key.error.notAuthorized': 'Usuario no autorizado',
    'key.error.eggOnlyRoost': 'Tienes que darle este huevo a la Madre de los Dragones',
    'key.error.purchase': 'Error: {0}',
    'key.error.creatureIsDead': 'Primero tienes que revivir a la criatura',
    'key.error.no_connection': 'Imposible conectarse al servidor. Vuelve a intentarlo más tarde.',
    'key.error.protocol_version_mismatch': 'La versión del juego es obsoleta. Tienes que actualizarla.',
    'key.error.update_application': 'La versión del juego es obsoleta. Tienes que actualizarla.',
    'key.modal.doYouWantToTransferSingle': '¿Estás seguro de que quieres soltar a esta criatura?',
    'key.notification.phoneNotSupportAR': 'Tu dispositivo es incompatible con la RA',
    'key.notification.turnOnARPermission': 'El juego no tiene acceso a la cámara. Tienes que aceptar el permiso en las opciones del dispositivo',
    'key.notification.dailyQuestFinished': '¡Tarea cumplida!',
    'key.modal.yesBtn': 'Sí',
    'key.modal.noBtn': 'No',
    'event.log.DAILY_QUEST_COMPLETED': 'Has terminado la tarea diaria. Has recibido:',
    'event.log.WEEKLY_QUEST_COMPLETED': '¡La caza ha terminado! Tu premio:',
    'event.log.ENCOUNTER_VICTORY': '¡Has vencido al monstruo salvaje!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Esta versión del juego es obsoleta. Tienes que actualizarla.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Error de autenticación',
    'key.ServiceException.Cause.SESSION_GONE': 'Han entrado a tu cuenta desde otro dispositivo',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'El ID del Usuario está vacío',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Este Usuario no se ha encontrado',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'La cuenta ha sido bloqueada por trampas.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'La cuenta ha sido bloqueada por pagos fraudulentos.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'La cuenta ha sido bloqueada por nombre de usuario ofensivo.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'La cuenta ha sido bloqueada por comportamiento agresivo hacia los demás jugadores.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'La cuenta ha sido bloqueada por trampas.',
    'key.ServiceException.Cause.USER_BANNED': 'La cuenta ha sido bloqueada.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'No tienes sitio en la mochila',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Número máximo de huevos',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'No tienes suficientes monedas',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'No tienes suficientes piedras de almas',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'No tienes suficiente esencia',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'No tienes espacio en el almacén de criaturas',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'La criatura ya ha alcanzado el máximo nivel',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'No puedes transformar a esta criatura',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'El nombre de la criatura no debe superar los 16 símbolos',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Se ha alcanzado el límite de defensores del edificio',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Tu mascota no puede ponerse en la defensa del edificio',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Tu criatura ya está en la defensa de este edificio',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Error',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Error al entrar en combate',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Error',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Tu criatura ya está en la defensa de este edificio',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'La Arena está bajo la custodia de la Bendición de la Defensa',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'No ha llegado el momento de recoger el tributo todavía',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Esfera incorrecta',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Edificio incorrecto',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Acceso denegado',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Objeto inexistente',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Receta inexistente',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Solo puedes instalar un Altar',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Primero tienes que subir de nivel al personaje',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Imposible empezar la captura de la criatura',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Producto inexistente',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Producto inexistente',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Edificio inexistente',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'No se ha hallado la criatura',
    'key.ServiceException.Cause.WRONG_CREATURE': 'No se ha hallado la criatura',
    'key.ServiceException.Cause.TOO_FAR': 'El edificio está demasiado lejos',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'El objeto está demasiado lejos',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'El edificio se está recargando',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'El edificio está en la Falla de Arcana',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'No puedes usar el edificio',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'No se ha hallado la crisálida de dragón',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'La crisálida de dragón está vacía',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'La crisálida de dragón está ocupada',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'No has incubado el huevo',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Huevo no hallado',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Para este huevo necesitas a la Madre de los Dragones',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Se te han acabado las cargas',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Imposible colocar el edificio',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Ha sucedido un error, y este texto misterioso habla sobre él',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'El monstruo salvaje ha escapado',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Monstruo salvaje no encontrado',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'En esta columna ya hay un cebo',
    'key.ServiceException.Cause.WRONG_ITEM': 'Objeto incorrecto',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Esta runa es la más fuerte',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Te faltan runas de este nivel',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Slot de runas incorrecto',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Este slot ya está ocupado',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'El slot de la runa está vacío',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'No puedes elegir al defensor del edificio',
    'key.ServiceException.Cause.WRONG_SPELL': 'Conjuro incorrecto',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'El conjuro requiere más runas',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'La próxima tarea todavía no está disponible',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Ya has usado este obelisco',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Todos los fragmentos del mapa ya están abiertos',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'No participas en la caza al Huevo de Oro',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Ya has intentado buscar el Huevo de Oro en este sitio',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Ya has usado esta delicia',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Ya has atrapado a la criatura',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Todavía no puedes reeducar a tus criaturas',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'La biblioteca está bloqueada por ahora',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'El servidor no responde. Vuelve a intentarlo más tarde.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Ya has aumentado el límite de combates',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Has alcanzado el límite de batallas',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Tienes que alcanzar el nivel 9 para poder participar en el Duelo de Magos',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'No se ha encontrado un adversario para el Duelo de Magos, vuelve a intentarlo más tarde',
    'key.ServiceException.Cause.MARKET_ERROR': 'Error de la tienda',
    'key.ServiceException.Cause.NO_CHEST': 'Baúl no hallado',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Error de entrega del fragmento. Vuelve a intentarlo más tarde.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Tienes que ponerte el Corazón de Dragón o el juego de Artefactos de Dragón para poder dar a la Madre de los Dragones más huevos',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Ya hay un huevo en esta casilla',
    'key.ServiceException.Cause.NO_CONNECTION': 'No hay conexión a Internet',
    'key.ServiceException.Cause.SERVER_DOWN': 'El servidor está temporalmente fuera de servicio. Intêntalo más tarde, por favor.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'El servidor está fuera de servicio por mantenimiento. Intêntalo más tarde, por favor.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Estás usando estas runas',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Te mueves demasiado rápido',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Has alcanzado el límite de Arenas capturadas',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Has alcanzado el límite de Bibliotecas capturadas',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Error. GPS no está disponible',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'No puedes usar este conjuro en la Falla de Arcana',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'El tiempo se acabó',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Protocolo equivocado. Actualiza la página.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'No hay Arenas aliadas en tu radio de visión',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'No hay Arenas enemigas en tu radio de visión',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'Esta cuenta ya está siendo usada',
    'stop.personalized.BALLS': 'esferas',
    'stop.personalized.HEALS': 'pociones',
    'stop.personalized.RESURRECTIONS': 'revivir',
    'stop.personalized.EGGS': 'huevos de criaturas',
    'stop.personalized.FOODS': 'golosinas',
    'key.button.cancelPersonal': 'Cancelar',
    'key.error.needHigherLevelForSofaBattles': 'Tienes que alcanzar el nivel {0} para poder participar en los Duelos de los Magos',
    'fraction.text.youWilLGetBonus': 'Recibirás {0} monedas por unirte a esta facción',
    'fraction.text.fractionUnavailable': 'La facción ahora no está disponible',
    'fraction.text.chooseYourAlliance': 'Elige la facción por la que quieres combatir',
    'fraction.text.redFractionName': 'Orden Roja',
    'fraction.text.blueFractionName': 'Orden Azul',
    'key.error.chestTooFarAway': 'El baúl está demasiado lejos',
    'key.button.openChest': 'Abrir',
    'key.candy.MONSTER_WATER_1': 'piedras de Ranius',
    'key.candy.MONSTER_WATER_2': 'piedras de Gota',
    'key.candy.MONSTER_WATER_3': 'piedras de Espiritus',
    'key.candy.MONSTER_WATER_4': 'piedras de Sobraquian',
    'key.candy.MONSTER_WATER_8': 'piedras de Jellyhat',
    'key.candy.MONSTER_WATER_9': 'piedras de Minor',
    'key.candy.MONSTER_WATER_10': 'piedras de Infalisco',
    'key.candy.MONSTER_WATER_12': 'piedras de Dadachock',
    'key.candy.MONSTER_WATER_13': 'piedras de Batoid',
    'key.candy.MONSTER_WATER_23': 'piedras de Armarrana',
    'key.candy.MONSTER_WATER_24': 'piedras de Neptuno',
    'key.candy.MONSTER_WATER_25': 'piedras de Leviathan',
    'key.candy.MONSTER_FIRE_1': 'piedras de Potty',
    'key.candy.MONSTER_FIRE_2': 'piedras de Mummyween',
    'key.candy.MONSTER_FIRE_3': 'piedras de Vaporex',
    'key.candy.MONSTER_FIRE_4': 'piedras de Incumus',
    'key.candy.MONSTER_FIRE_6': 'piedras de Flamy',
    'key.candy.MONSTER_FIRE_7': 'piedras de Phoby',
    'key.candy.MONSTER_FIRE_11': 'piedras de Chispa',
    'key.candy.MONSTER_FIRE_12': 'piedras de Kiddra',
    'key.candy.MONSTER_FIRE_15': 'piedras de Needlehot',
    'key.candy.MONSTER_FIRE_25': 'piedras de Smoargh',
    'key.candy.MONSTER_EARTH_1': 'piedras de Bayadil',
    'key.candy.MONSTER_EARTH_2': 'piedras de Florix',
    'key.candy.MONSTER_EARTH_3': 'piedras de Hoja',
    'key.candy.MONSTER_EARTH_4': 'piedras de Brownie',
    'key.candy.MONSTER_EARTH_8': 'piedras de Goblic',
    'key.candy.MONSTER_EARTH_9': 'piedras de Bellflow',
    'key.candy.MONSTER_EARTH_10': 'piedras de Bellotus',
    'key.candy.MONSTER_EARTH_11': 'piedras de Phylo',
    'key.candy.MONSTER_EARTH_13': 'piedras de Princie',
    'key.candy.MONSTER_EARTH_25': 'piedras de Scylla',
    'key.candy.MONSTER_DUNGEON_1': 'piedras de Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'piedras de Axolan',
    'key.candy.MONSTER_DUNGEON_3': 'piedras de Lomopincho',
    'key.candy.MONSTER_DUNGEON_4': 'piedras de Magglad',
    'key.candy.MONSTER_DUNGEON_5': 'piedras de Cuquigato',
    'key.candy.MONSTER_DUNGEON_6': 'piedras de Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'piedras de Vampirus',
    'key.candy.MONSTER_DUNGEON_13': 'piedras de Advise',
    'key.candy.MONSTER_DUNGEON_17': 'piedras de Inur',
    'key.candy.MONSTER_WIND_1': 'piedras de SunTzi',
    'key.candy.MONSTER_WIND_2': 'piedras de Orejago',
    'key.candy.MONSTER_WIND_3': 'piedras de Hongy',
    'key.candy.MONSTER_WIND_4': 'piedras de Suavicornio',
    'key.candy.MONSTER_WIND_6': 'piedras de Gamayun',
    'key.candy.MONSTER_WIND_7': 'piedras de Miedón',
    'key.candy.MONSTER_WIND_11': 'piedras de Infird',
    'key.candy.MONSTER_WIND_12': 'piedras de Undine',
    'key.candy.MONSTER_WIND_15': 'piedras de Cheshir',
    'key.candy.MONSTER_WIND_25': 'piedras de Charybdis',
    'key.button.leaveDungeon': 'Abandonar la Falla',
    'key.alias.enterNewAlias': 'Introduce el nombre de la criatura',
    'key.alias.enterText': 'Escribe el texto...',
    'key.hut.hutName': 'Madre de los Dragones',
    'key.hut.hutDescr': 'Dale los huevos antiguos a la Madre de los Dragones para que ella los incube por ti',
    'key.text.noHutEggs': 'No tienes huevos antiguos',
    'key.text.noCapturedArenas': 'No has conquistado ninguna arena',
    'key.text.noChosenPet': 'No has elegido a ninguna mascota',
    'key.text.noArtifacts': 'No tienes artefactos',
    'key.text.noCreatures': 'No tienes criaturas capturadas',
    'key.text.noLureItems': 'No tienes cebos',
    'key.descr.aboutWizardBattles': 'Participa en Duelos contra los demás jugadores para obtener experiencia y premios',
    'key.text.writeToSupport': 'Escribe al soporte',
    'key.text.regUsingFacebook': 'Registrarse a través de Facebook',
    'key.text.regUsingGoogle': 'Registrarse a través de Google',
    'key.text.logUsingFacebook': 'Entrar a través de Facebook',
    'key.text.logUsingGoogle': 'Entrar a través de Google',
    'key.text.logUsingDeviceIDCurrent': 'Entrar a través de Device ID',
    'key.text.logUsingDeviceIDNew': 'Entrar a través de Device ID (nueva cuenta)',
    'key.text.createAccount': 'Jugar',
    'key.text.connectedToFacebook': 'Conectado a Facebook',
    'key.text.connectedToGoogle': 'Conectado a Google',
    'key.text.complainAboutPoint': 'Quejarse de este punto',
    'key.text.copyCoordinates': 'Copiar las coordenadas',
    'key.text.complainEnterEmail': 'Tu e-mail',
    'key.text.complainEnterText': 'Cuèntanos tu problema',
    'key.modal.doYouWantToCloseApp': '¿Quieres cerrar la aplicación?',
    'key.catchPopup.notBad': '¡Bien!',
    'key.catchPopup.good': '¡Perfecto!',
    'key.catchPopup.sumptuously': '¡Estupendo!',
    'key.catchPopup.twistedThrow': '¡Lanzamiento curvo!',
    'key.battlePopup.strongHit': '¡Golpe fuerte!',
    'key.battlePopup.weakHit': 'Golpe débil',
    'key.battlePopup.dodge': 'Ha fallado',
    'key.battlePopup.chargedAttack': '{0} usa {1}',
    'auth.login.play': 'Jugar',
    'auth.login.nickname.placeholder': 'Introduce el nombre',
    'auth.login.nickname.busy': 'Ese nombre está ocupado',
    'auth.login.nickname.proposal': 'Puedes usar este nombre:',
    'auth.login.nickname.deviceId': 'Ya tienes un personaje',
    'auth.login.social.title': 'Entrar a través de una red social',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Conectado a {0}',
    'auth.login.social.signOut': 'Salir de la cuenta',
    'auth.login.signOut.confirmation': '¿De verdad quieres salir de la cuenta?',
    'auth.login.social.userCancelledError': 'Conexión cancelada',
    'auth.login.social.cantSignInError': 'Imposible conectarse a {0}',
    'licence.title': 'ACUERDO DE USUARIO DE DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Enviadme las noticias y las ofertas a mi correo',
    'licence.accept': 'Aceptar',
    'licence.decline': 'Rechazar',
    'key.error.wrongRoostIndex': 'La casilla no está disponible',
    'key.speed.passenger': 'Soy un pasajero',
    'key.activeObjects.addUnit.question': '¿Estás seguro de que quieres hacer a {0} defensor de este edificio?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': '¿Estás seguro de que quieres elegir esta facción? Esta elección no se podrá cambiar en el futuro',
    'key.confirm.giveUpEncounter': '¿Estás seguro de que no quieres luchar contra el monstruo salvaje?',
    'key.confirm.giveUpBattle': '¿Estás seguro de que quieres rendirte y terminar la batalla?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': '¡Nueva Liga!',
};
