module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Tak',
    'key.button.cancel': 'KASUJ',
    'key.button.apply': 'OK',
    'key.button.use': 'Użyj',
    'key.button.buy': 'Kup',
    'key.beCarefulMessage.text': 'Bądź ostrożny podczas gry. Patrz dookoła.',
    'key.creature.details.attack': 'Siła',
    'key.creature.details.health': 'Zdrowie',
    'key.creature.details.powerUp': 'Zasilenie',
    'key.creature.details.evolve': 'Przeobrażenie',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'СР {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'PUŚĆ',
    'key.creature.details.creadex': 'Bestiariusz',
    'key.creature.registration.creadex': 'Dodano do Bestiariusza',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Zdobyte budynki',
    'key.activeObjects.library': 'Ponowne nauczanie istoty w Bibliotece',
    'key.activeObjects.library.empty': 'Nie ma podbitych Bibliotek',
    'key.activeObjects.arena': 'Ściąganie danin z Aren',
    'key.activeObjects.arena.collect': 'Ściągnij',
    'key.activeObjects.arena.empty': 'Nie ma podbitych Aren',
    'key.activeObjects.error.timer': 'Ściąganie danin jest niedostępne. Zaczekaj!',
    'key.activeObjects.error.noMoney': 'Najpierw musisz podbić Arenę',
    'key.activeObjects.error.cannotRemaster': 'Ponowny trening jest niedostępny. Zdobywaj Biblioteki, aby przyspieszyć licznik ponownego treningu.',
    'key.activeObjects.library.remaster': 'Wytrenuj ponownie',
    'key.activeObjects.library.blocked': 'Biblioteki są niedostępne',
    'key.activeObjects.remaster.confirmation.main': 'Czy na pewno chcesz wytrenować {0} ponownie? Główna umiejętność {1} zostanie zmieniona!',
    'key.activeObjects.remaster.confirmation.charged': 'Czy na pewno chcesz wytrenować {0} ponownie? Aktywna umiejętność {1} zostanie zmieniona!',
    'key.activeObjects.remaster.error': 'Błąd',
    'key.activeObjects.item.weaklyBonus': 'Cotygodniowy bonus +{0} monety',
    'key.library.remaster.selectCreature': 'Wybierz istotę, którą chcesz wytrenować ponownie',
    'key.remasterPanel.title': 'Wybierz umiejętność',
    'key.storage.creatues': 'Istoty',
    'key.storage.eggs': 'Jaja',
    'key.storage.eggs.simple': 'Zwykłe jaja',
    'key.storage.eggs.super': 'Dawne jaja',
    'key.storage.eggs.missingAny': 'Nie masz żadnych jaj istot',
    'key.startEgg.button': 'Umieść w kokonie',
    'key.startEgg.description': 'Użyj smoczego kokonu, aby wysiedzieć to jajo',
    'key.startEgg.incubator.title': 'Smocze kokony',
    'key.startEgg.select.title': 'Wybierz jajo',
    'key.openEgg.button': 'Otwórz jajo',
    'key.openEgg.description': 'Nowa istota zaraz się wykluje z jaja',
    'key.startEgg.description.roost.hatching': 'Matka Smoków wysiaduje to jajo. Musisz tylko zaczekać. Wysiadywanie zakończy się, kiedy zniknie Wyłom w Arkanach, gdzie znajduje się Matka Smoków.',
    'key.startEgg.description.roost.notHatching': 'Oddaj to jajo Matce Smoków, aby wysiedziała go dla Ciebie.',
    'key.startEgg.description.simple.hatching': 'To wysiaduje się w smoczym kokonie. Miej cały czas uruchomioną grę, aby pomóc mu się wykluć . ',
    'key.startEgg.description.simple.notHatching': 'Połóż to jajo do smoczego kokonu, aby zacząć proces wysiadywania jaj. Jajo wykluje się, kiedy pokonasz wymaganą odległość.',
    'key.mainMenu.wizardDuels': 'POJEDYNEK CZARODZIEJÓW',
    'key.mainMenu.quests': 'ZADANIA',
    'key.mainMenu.activePoints': 'ZDOBYTE',
    'key.mainMenu.creadex': 'BESTIARIUSZ',
    'key.mainMenu.magic': 'MAGIA',
    'key.mainMenu.creatues': 'ISTOTY',
    'key.mainMenu.shop': 'SKLEP',
    'key.mainMenu.backpack': 'TORBA',
    'key.error.banned': 'Konto jest zablokowane',
    'event.log.CREATURE_CAUGHT': 'Złapano: {0}!',
    'event.log.ITEM_BOUGHT': 'Kupiono {0} x{1} . Stracona {2} chwila',
    'event.log.ARTIFACT_BOUGHT': 'Kupiono artefakt: {0}. Stracona {1} chwila',
    'event.log.EGG_HATCHED': '{0} wykluł się z {1} jaja!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'złotego',
    'event.log.ROOST_EGG_HATCHED': 'Matka Smoków wysiedziała {1}h jajo. {0} teraz jest Twoje!',
    'event.log.CHEST_OPENED': 'Znaleziono w kufrze:',
    'event.log.ARENA_LOST_CONTROL': '{1} został wybity z budowli: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} został wybity z budowli: {0}',
    'event.log.LEVEL_UP': 'Osiągnięto poziom {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Wychowanek znalazł {0}',
    'event.log.QUEST_COMPLETED': 'Nagroda za zadanie {0}',
    'event.log.ENCOUNTER_LOOSE': 'Uciekłeś(-aś) przed dzikim potworem',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Limit bitew w Pojedynku Czarodziejów zwiększono za {0} monet',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} monet kupiono za {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Torba została ulepszona za {0} monet',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Magazyn istot został ulepszony za {0} monet',
    'key.shop.accesories': 'PRZEDMIOTY',
    'key.shop.artifacts': 'ARTEFAKTY',
    'key.shop.donate': 'MONETY',
    'key.shop.upgrade': 'ULEPSZENIA',
    'key.shop.donate.coins': '{0} monet',
    'key.shop.upgrade.bag': 'Rozszerzenie torby',
    'key.shop.upgrade.bag.desc': 'Pojemność torby zostanie zwiększona o 50',
    'key.shop.upgrade.storage': 'Rozszerzenie magazynu istot',
    'key.shop.upgrade.storage.desc': 'Pojemność magazynu istot zostanie zwiększona o 50',
    'key.shop.donate.dialog.title': 'Brakuje Ci monet!',
    'key.shop.donate.dialog.desc': 'Otrzymaj je tutaj lub otwórz Sklep, aby zobaczyć więcej opcji',
    'key.potionUseMenu.title': 'Zioła lecznicze',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Tworzy Portal do świata Arkany',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Wszyscy gracze dookoła odczują wściekłość leprechaunów',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Tworzy pole Słupów Obfitości w ciągu 30 minut',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Podwaja ilość nagród ze Słupów Obfitości w ciągu 30 minut',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Stuknij i przytrzymaj palec na miejscowości, aby podświetlić ją, szukając istot',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Na 30 minut zwiększa zasięg wyszukiwania istot',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Na 7 dni zwiększa zasięg widoczności obiektów o 30%',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'Najbliższa sojusznicza Arena będzie niedostępna do zaatakowania przez wrogów w ciągu 30 godzin',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Wszystkie wrogie Areny w zasięgu widoczności staną się neutralne. Kasuje Błogosławieństwo obrony.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Tworzy wieżę magiczną, która przyciąga istoty żywiołu Ognia',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Tworzy wieżę magiczną, która przyciąga istoty żywiołu Wody',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Tworzy wieżę magiczną, która przyciąga istoty żywiołu Powietrza',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Tworzy wieżę magiczną, która przyciąga istoty żywiołu Ziemi',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Tworzy wieżę magiczną, która przyciąga istoty żywiołu Arkany',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Wyłom w Arkanie',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Wściekłość leprechaunów',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Pole Obfitości',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Dar Złotego Smoka',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astralne widzenie',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Smoczy wzrok',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Długie ręce',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Błogosławieństwo obrony',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Oczyszczanie ogniem',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Wieża Ognia',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Wieża Wody',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Wieża Powietrza',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Wieża Ziemi',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Wieża Arkany',
    'key.buff.ATTACKER_CP_BOOST': 'СР Twoich istot czasowo zwiększono',
    'key.buff.BEST_BALL_LUCK': 'Najlepsze sfery w Słupach Obfitości na 30 minut',
    'key.buff.BEST_POTION_LUCK': 'Najlepsze zioła w Słupach Obfitości na 30 minut',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 przedmioty ze Słupów Obfitości na 30 minut',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Cooldown Biblioteki przyspieszono o {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Czas do kolejnego ściągania daniny z Aren pomniejszono o {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Zwiększa CP istot, które nie są obrońcami budynków',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Otrzymujesz tylko najlepsze kule ze Słupów, które są dostępne dla Twojego poziomu',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Otrzymujesz tylko najlepsze zioła ze Słupów, które są dostępne dla Twojego poziomu',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Otrzymujesz o 2 przedmioty więcej ze Słupów Obfitości',
    'key.loot.result.dust': 'Esencja',
    'key.loot.result.exp': 'Doświadczenie postaci',
    'key.loot.result.coin': 'Monety',
    'key.loot.result.candy': 'kamienie',
    'key.item.MAGIC_BALL_SIMPLE': 'Kula ucznia',
    'key.item.MAGIC_BALL_NORMAL': 'Kula magistra',
    'key.item.MAGIC_BALL_GOOD': 'Kula władcy',
    'key.item.LURE': 'Przynęta',
    'key.item.INCENSE': 'Feromony',
    'key.item.EGG': 'Jajo',
    'key.item.SHOVEL': 'Łopata',
    'key.item.POTION_HEAL_1': 'Małe zioła lecznicze',
    'key.item.POTION_HEAL_2': 'Średnie zioła lecznicze',
    'key.item.POTION_HEAL_3': 'Wielkie zioła lecznicze',
    'key.item.POTION_HEAL_4': 'Zioła całkowitego uzdrowienia',
    'key.item.POTION_RESURRECTION_1': 'Zioła wskrzeszania',
    'key.item.POTION_RESURRECTION_2': 'Wielkie zioła wskrzeszania',
    'key.item.INCUBATOR_1': 'Smoczy kokon',
    'key.item.INCUBATOR_3': 'Smoczy kokon',
    'key.item.INCUBATOR_PERPETUAL': 'Wieczny smoczy kokon',
    'key.item.SUPER_VISION': 'Smoczy wzrok',
    'key.item.RUNE_1': 'Runa I',
    'key.item.RUNE_2': 'Runa II',
    'key.item.RUNE_3': 'Runa III',
    'key.item.RUNE_4': 'Runa IV',
    'key.item.RUNE_5': 'Runa V',
    'key.item.RUNE_6': 'Runa VI',
    'key.item.FOOD_CATCH_CHANCE': 'Karmel arkaniczny',
    'key.item.FOOD_MORE_DUST': 'Pączek magiczny',
    'key.item.FOOD_CALM_DOWN': 'Zefir Jednorożca',
    'key.item.FOOD_MORE_CANDIES': 'Lody czterech żywiołów',
    'key.item.EXPERIENCE_BOOSTER': 'Kryształ mądrości',
    'key.item.EGG_KM_0': 'Złote Jajo',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Kula do łapania istot.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Kula do łapania istot. Nieco zwiększa szansę złapania.',
    'key.item.MAGIC_BALL_GOOD.description': 'Kula do łapania istot. Bardzo zwiększa szansę złapania.',
    'key.item.LURE.description': 'Przynęta dla istot. Pomieść ją w Słupie Obfitości, aby przyciągnąć do niego istoty.',
    'key.item.INCENSE.description': 'Feromony przyciągną istoty określonego żywiołu, w zależności od dnia tygodnia.',
    'key.item.EGG.description': 'Użyj smoczego kokonuu, aby wysiedzieć jajo z istotą',
    'key.item.SHOVEL.description': 'Łopaty są niezbędne w poszukiwaniu skarbu',
    'key.item.POTION_HEAL_1.description': 'Uzdrawia istotę o 200 punktów zdrowia',
    'key.item.POTION_HEAL_2.description': 'Uzdrawia istotę o 500 punktów zdrowia',
    'key.item.POTION_HEAL_3.description': 'Uzdrawia istotę o 1000 punktów zdrowia',
    'key.item.POTION_HEAL_4.description': 'Całkowicie uzdrawia istotę',
    'key.item.POTION_RESURRECTION_1.description': 'Wskrzesza wybraną istotę. Po wskrzeszaniu istota będzie ranna.',
    'key.item.POTION_RESURRECTION_2.description': 'Wskrzesza i całkowicie uzdrawia istotę',
    'key.item.INCUBATOR_1.description': 'Smocze kokony są potrzebne do wysiadywania istot z jaj. Znika po wykorzystaniu.',
    'key.item.INCUBATOR_3.description': 'Smocze kokony są potrzebne do wysiadywania jaj z istotami. Znika po 3 wykorzystaniach.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Smocze kokony są potrzebne do wysiadywania jaj z istotami. ',
    'key.item.SUPER_VISION.description': 'Pokazuje istoty na wielkim terytorium',
    'key.item.RUNE_1.description': 'Magiczna runa 1 poziomu',
    'key.item.RUNE_2.description': 'Magiczna runa 2 poziomu',
    'key.item.RUNE_3.description': 'Magiczna runa 3 poziomu',
    'key.item.RUNE_4.description': 'Magiczna runa 4 poziomu',
    'key.item.RUNE_5.description': 'Magiczna runa 5 poziomu',
    'key.item.RUNE_6.description': 'Magiczna runa 6 poziomu',
    'key.item.FOOD_CATCH_CHANCE.description': 'Smakołyk do łapania istot. Zwiększa szanse złapania istoty przy pomocy magicznej kuli',
    'key.item.FOOD_MORE_DUST.description': 'Smakołyk do łapania istot. Zwiększa ilość esencji otrzymywanej za złapanie',
    'key.item.FOOD_CALM_DOWN.description': 'Smakołyk do łapania istot. Uspokaja istotę, ona przestaje skakać i atakować',
    'key.item.FOOD_MORE_CANDIES.description': 'Smakołyk do łapania istot. Zwiększa ilość dusz kamiennych otrzymywanych za złapanie',
    'key.item.EXPERIENCE_BOOSTER.description': 'Na 30 minut podwaja ilość otrzymywanego doświadczenia',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Maska prestidigitatora',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '1 zdalna czynność dziennie',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Ten artefakt pozwala jeden raz dziennie zdalnie ustawić swoją istotę na wolnym miejscu na arenie lub w Bibliotece, którą widzisz na mapie.',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Twarz jasnowidza',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '2 zdalne czynności dziennie',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Ten artefakt pozwala 2 raza dziennie zdalnie ustawić swoją istotę na wolnym miejscu na arenie lub w Bibliotece, którą widzisz na mapie.',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Hełm zdobywcy',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '3 zdalne czynności dziennie',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Ten artefakt pozwala 3 raza dziennie zdalnie ustawić swoją istotę na wolnym miejscu na arenie lub w Bibliotece, którą widzisz na mapie.',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Hełm bohatera',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '4 zdalne czynności dziennie',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Ten artefakt pozwala 4 raza dziennie zdalnie ustawić swoją istotę na wolnym miejscu na arenie lub w Bibliotece, którą widzisz na mapie.',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Hełm walczącego ze smokiem',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '5 zdalnych czynności dziennie',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Ten artefakt pozwala 5 raz dziennie zdalnie ustawić swoją istotę na wolnym miejscu na arenie lub w Bibliotece, którą widzisz na mapie.',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Sztandar władcy',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Pozwala umieścić na Arenie lub w Bibliotece jeszcze jedną istotę',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Z tym artefaktem można umieścić w obronie Areny lub Biblioteki dwie istoty zamiast jednej',
    'key.artifact.ARTIFACT_BANK_8': 'Wycięty artefakt',
    'key.artifact.ARTIFACT_BANK_8.description': 'Jak go w ogóle znalazłeś(-aś)?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Zobaczyłeś(-aś) artefakt, którego nie powinieneś był zobaczyć. Teraz będziemy musieli pozbyć się Ciebie jako świadka.',
    'key.artifact.ARTIFACT_BANK_9': 'Wycięty artefakt',
    'key.artifact.ARTIFACT_BANK_9.description': 'Jak go w ogóle znalazłeś(-aś)?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Zobaczyłeś(-aś) artefakt, którego nie powinieneś był zobaczyć. Teraz będziemy musieli pozbyć się Ciebie jako świadka.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Zegar leniwego studenta',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 sekund do czasu odnowienia Słupów Obfitości',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Z tym artefaktem Słupy Obfitości będą odnawiały się o 20 sekund szybciej i można będzie używać ich częściej.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Budzik wiecznie spóźniającego się',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 sekund do czasu odnowienia Słupów Obfitości',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Z tym artefaktem Słupy Obfitości będą odnawiały się o 40 sekund szybciej i można będzie używać ich częściej.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Przyspieszacz przestrzenny',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 sekund do czasu odnowienia Słupów Obfitości',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Z tym artefaktem Słupy Obfitości będą odnawiały się o 60 sekund szybciej i można będzie używać ich częściej.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Zegar leniwego profesora',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 sekund do czasu odnowienia Słupów Obfitości',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Z tym artefaktem Słupy Obfitości będą odnawiały się o 80 sekund szybciej i można będzie używać ich częściej.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Zegar zebry-królika',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 sekund do czasu odnowienia Słupów Obfitości',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Z tym artefaktem Słupy Obfitości będą odnawiały się o 100 sekund szybciej i można będzie używać ich częściej.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Berło zdobywcy',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 do poziomu Areny lub Biblioteki po jej przejęciu',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Jeśli właściciel tego artefaktu pierwszy umieści istotę na zagarniętej Arenie lub w Bibliotece, uzyskuje ona od razu 5 poziom zamiast 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Pierścień ściągającego daninę',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 do maksymalnej ilości zagarniętych Aren',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Z tym artefaktem możesz ściągać daninę z 11 Aren zamiast zwykłych 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Pierścień chciwości',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 do maksymalnej ilości zagarniętych Aren',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Z tym artefaktem możesz ściągać daninę z 12 Aren zamiast zwykłych 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Podwójny pierścień',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 do maksymalnej ilości zagarniętych Aren',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Z tym artefaktem możesz ściągać daninę z 13 Aren zamiast zwykłych 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Puchar pożeracza placków',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% do doświadczenia sojuszniczych Aren i Bibliotek podczas treningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Z tym artefaktem zojusznicze Areny i Biblioteki otrzymują o 20% więcej siły kiedy je trenujesz',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Puchar do miodu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% do doświadczenia sojuszniczych Aren i Bibliotek podczas treningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Z tym artefaktem zojusznicze Areny i Biblioteki otrzymują o 30% więcej siły kiedy je trenujesz',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Czara głębokich myśli',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% do doświadczenia sojuszniczych Aren i Bibliotek podczas treningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Z tym artefaktem zojusznicze Areny i Biblioteki otrzymują o 40% więcej siły kiedy je trenujesz',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Gral Lancelopa',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% do doświadczenia sojuszniczych Aren i Bibliotek podczas treningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Z tym artefaktem zojusznicze Areny i Biblioteki otrzymują o 50% więcej siły kiedy je trenujesz',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Puchar pogromcy potworów',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% do doświadczenia sojuszniczych Aren i Bibliotek podczas treningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Z tym artefaktem zojusznicze Areny i Biblioteki otrzymują o 80% więcej siły kiedy je trenujesz',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem jasnowidzenia',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Usuwa słabe istoty z radaru',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Ten artefakt usuwa z radaru słabsze istoty, abyś skupił(-a) się na wyszukiwaniu tylko tych silniejszych',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Rulebook awanturnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minut do ściągania daniny z Areny po jej zagarnięciu przez przeciwnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Z tym artefaktem Areny są dostępne dla ściągania daniny w ciągu dodatkowych 30 minut po ich zagarnięciu, zamiast zwyczajowych 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Cegła',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minut do ściągania daniny z Areny po jej zagarnięciu przez przeciwnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Z tym artefaktem Areny są dostępne dla ściągania daniny w ciągu dodatkowych 45 minut po ich zagarnięciu, zamiast zwyczajowych 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tablica roszczenia',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minut do ściągania daniny z Areny po jej zagarnięciu przez przeciwnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Z tym artefaktem Areny są dostępne dla ściągania daniny w ciągu dodatkowych 60 minut po ich zagarnięciu, zamiast zwyczajowych 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Traktat o rządach',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minut do ściągania daniny z Areny po jej zagarnięciu przez przeciwnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Z tym artefaktem Areny są dostępne dla ściągania daniny w ciągu dodatkowych 90 minut po ich zagarnięciu, zamiast zwyczajowych 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoire władzy',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minut do ściągania daniny z Areny po jej zagarnięciu przez przeciwnika',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Z tym artefaktem Areny są dostępne dla ściągania daniny w ciągu dodatkowych 120 minut po ich zagarnięciu, zamiast zwyczajowych 15 minut',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Kolczasty naszyjnik',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% przyspieszenia do otrzymania kamieni dusz od wychowańca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Z tym artefaktem możesz przejść z wychowankiem o 10% mniej, aby otrzymać kamienne dusze. Również czyni wychowanka o 17% bardziej groźnym',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Marchewka na pałce',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% przyspieszenia do otrzymania kamieni dusz od wychowańca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Z tym artefaktem możesz przejść z wychowankiem o 15% mniej, aby otrzymać kamienne dusze. Również czyni wychowanka o 17% bardziej groźnym',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Drapaczka do pleców',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% przyspieszenia do otrzymania kamieni dusz od wychowańca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Z tym artefaktem możesz przejść z wychowankiem o 25% mniej, aby otrzymać kamienne dusze. Również czyni wychowanka o 17% bardziej groźnym',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Bębenek ulubieńca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% przyspieszenia do otrzymania kamieni dusz od wychowańca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Z tym artefaktem możesz przejść z wychowankiem o 30% mniej, aby otrzymać kamienne dusze. Również czyni wychowanka o 17% bardziej groźnym',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Pluszowy smoczek',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% przyspieszenia do otrzymania kamieni dusz od wychowańca',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Z tym artefaktem możesz przejść z wychowankiem o 40% mniej, aby otrzymać kamienne dusze. Również czyni wychowanka o 17% bardziej groźnym',
    'key.artifact.ARTIFACT_ROOST_1': 'Serce smoka',
    'key.artifact.ARTIFACT_ROOST_1.description': '+ 1 smoczy kokon u Matki Smoków',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Pozwala używać dodatkowego oprzędu smoczego dla jajek u Matki Smoków',
    'dialog.artifact.select_artifact': 'WYBIERZ ARTEFAKT',
    'dialog.artifact.confirm.remove': 'Czy na pewno chcesz usunąć ten artefakt?',
    'dialog.items.title': 'TORBA',
    'dialog.items.cannotUse': 'Nie można wykorzystać tego przedmiotu',
    'dialog.items.remove.header': 'Kasowanie przedmiotów',
    'dialog.encounter.header': 'Dziki potwór atakuje Cię!',
    'dialog.encounter.button.leave': 'Uciekaj',
    'dialog.encounter.button.fight': 'Walcz',
    'dialog.encounter.result.outcome.win': 'Dziki potwór został zwyciężony',
    'dialog.encounter.result.outcome.lose': 'Twoja istota została zwyciężona',
    'dialog.encounter.result.reward.dust': 'Esencja',
    'dialog.encounter.result.reward.exp': 'Doświadczenie',
    'error.nickname.validation.IS_EMPTY': 'Musisz wpisać imię postaci',
    'error.nickname.validation.TOO_SHORT': 'Imię musi zawierać od 3 do 16 znaków',
    'error.nickname.validation.TOO_LONG': 'Imię musi zawierać od 3 do 16 znaków',
    'error.nickname.validation.INVALID_CHAR': 'Można używać tylko liter, cyfr i znaku podkreślania.',
    'error.nickname.validation.DUPLICATE': 'Wybrane imię już jest zajęte. Możesz wybrać imię {0}',
    'creature.MONSTER_WATER_1': 'Żabus',
    'creature.MONSTER_WATER_2': 'Kropla',
    'creature.MONSTER_WATER_3': 'Spirytus',
    'creature.MONSTER_WATER_4': 'Aquin',
    'creature.MONSTER_WATER_5': 'Żabissimo',
    'creature.MONSTER_WATER_6': 'Zdrojek',
    'creature.MONSTER_WATER_7': 'Wodnik',
    'creature.MONSTER_WATER_8': 'Dżemoczap',
    'creature.MONSTER_WATER_9': 'Minory',
    'creature.MONSTER_WATER_10': 'Infaliszek',
    'creature.MONSTER_WATER_11': 'Mediaquin',
    'creature.MONSTER_WATER_12': 'Dadaczek',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Pueroliszek',
    'creature.MONSTER_WATER_15': 'Falchor',
    'creature.MONSTER_WATER_16': 'Tentachat',
    'creature.MONSTER_WATER_17': 'Aquar',
    'creature.MONSTER_WATER_18': 'Dadaczum',
    'creature.MONSTER_WATER_19': 'Mantary',
    'creature.MONSTER_WATER_20': 'Bazyliszek',
    'creature.MONSTER_WATER_21': 'Melchor',
    'creature.MONSTER_WATER_22': 'Krystaliusz',
    'creature.MONSTER_WATER_23': 'Broniusz',
    'creature.MONSTER_WATER_24': 'Neptun',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Garneczek',
    'creature.MONSTER_FIRE_2': 'Mummiwin',
    'creature.MONSTER_FIRE_3': 'Parowóz',
    'creature.MONSTER_FIRE_4': 'Inkumus',
    'creature.MONSTER_FIRE_5': 'Ogniełap',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dammiwin',
    'creature.MONSTER_FIRE_9': 'Lawion',
    'creature.MONSTER_FIRE_10': 'Paropaj',
    'creature.MONSTER_FIRE_11': 'Iskra',
    'creature.MONSTER_FIRE_12': 'Cydra',
    'creature.MONSTER_FIRE_13': 'Gwiazdodemon',
    'creature.MONSTER_FIRE_14': 'Feniks',
    'creature.MONSTER_FIRE_15': 'Igłożar',
    'creature.MONSTER_FIRE_16': 'Żelazowy chłop',
    'creature.MONSTER_FIRE_17': 'Świetlik',
    'creature.MONSTER_FIRE_18': 'Cesarz',
    'creature.MONSTER_FIRE_19': 'Błysk',
    'creature.MONSTER_FIRE_20': 'Flibustiusz',
    'creature.MONSTER_FIRE_21': 'Kusiciel',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Salut',
    'creature.MONSTER_FIRE_24': 'Pikkarun',
    'creature.MONSTER_FIRE_25': 'Smaugier',
    'creature.MONSTER_EARTH_1': 'Arbuzyllo',
    'creature.MONSTER_EARTH_2': 'Kwiatuszek',
    'creature.MONSTER_EARTH_3': 'Listek',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Szamurf',
    'creature.MONSTER_EARTH_6': 'Driada',
    'creature.MONSTER_EARTH_7': 'Kiełek',
    'creature.MONSTER_EARTH_8': 'Goblin',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Żołądzień',
    'creature.MONSTER_EARTH_11': 'Filo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Szyszeń',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dwant',
    'creature.MONSTER_EARTH_18': 'Czappian',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'Springan',
    'creature.MONSTER_EARTH_21': 'Ziemios',
    'creature.MONSTER_EARTH_22': 'Zwierzekwiat',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Skylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Uchomych',
    'creature.MONSTER_WIND_3': 'Grzybio',
    'creature.MONSTER_WIND_4': 'Puszystorożec',
    'creature.MONSTER_WIND_5': 'Airwer',
    'creature.MONSTER_WIND_6': 'Gamajun',
    'creature.MONSTER_WIND_7': 'Straszyczek',
    'creature.MONSTER_WIND_8': 'Ucholot',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Wiatrotany',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Ondyna',
    'creature.MONSTER_WIND_13': 'Burzerożec',
    'creature.MONSTER_WIND_14': 'Fantomo',
    'creature.MONSTER_WIND_15': 'Cheshire',
    'creature.MONSTER_WIND_16': 'Grzybtopia',
    'creature.MONSTER_WIND_17': 'Harpia',
    'creature.MONSTER_WIND_18': 'Widmusz',
    'creature.MONSTER_WIND_19': 'Puerogryf',
    'creature.MONSTER_WIND_20': 'Poduszkot',
    'creature.MONSTER_WIND_21': 'Hippolot',
    'creature.MONSTER_WIND_22': 'Huraganna',
    'creature.MONSTER_WIND_23': 'Gryfon',
    'creature.MONSTER_WIND_24': 'Bajun',
    'creature.MONSTER_WIND_25': 'Charybda',
    'creature.MONSTER_DUNGEON_1': 'Ruuki',
    'creature.MONSTER_DUNGEON_2': 'Aksolan',
    'creature.MONSTER_DUNGEON_3': 'Kolcoplec',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Miłokot',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Maryd',
    'creature.MONSTER_DUNGEON_8': 'Agrolotel',
    'creature.MONSTER_DUNGEON_9': 'Strach',
    'creature.MONSTER_DUNGEON_10': 'Ślimalin',
    'creature.MONSTER_DUNGEON_11': 'Duszek',
    'creature.MONSTER_DUNGEON_12': 'Wampiro',
    'creature.MONSTER_DUNGEON_13': 'Gąsienica',
    'creature.MONSTER_DUNGEON_14': 'Mantyk',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Ogonek',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Drakoluz',
    'creature.MONSTER_DUNGEON_19': 'Regulum',
    'creature.MONSTER_DUNGEON_20': 'Tyrgysomant',
    'creature.MONSTER_DUNGEON_21': 'Ostrogon',
    'creature.MONSTER_DUNGEON_22': 'Pąk',
    'creature.MONSTER_DUNGEON_23': 'Falik',
    'creature.MONSTER_DUNGEON_24': 'Mantykora',
    'creature.MONSTER_DUNGEON_25': 'Morgorot',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Ugryzienie rekina',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Przerażenie z głębin',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Wołanie Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Młot morski',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Pięść wodna',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Fala',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Ulewa',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Gejzer',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Bryzgi',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Żywy płomień',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Palec ognia',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Bicz ogniowy',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Ognista kula',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Spopielacz',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Gwiazda',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Węgle',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Miotacz ognia',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Rozstrzelanie',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Sierp powietrzny',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Rozrywacz',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Oddech',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Prąd elektryczny',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Piorun kulisty',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Terapia szokowa',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Westnienie smoka',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Powiew',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Wściekłość wiatru',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Plunięcie trucizną',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Kieł żmii',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Otrucie',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Łamacz grzbietów',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Skała',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Głaz',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Duch lasu',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Widmo drzewa',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Cień natury',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Strzała Arkany',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Grudka mroku',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Macki zła',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Oko przerażenia',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Kula zagłady',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Kula mroku',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arkana Kadawra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Krucyarkus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Imperikanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Zlodowacenie',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Zamrożenie',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Krystalizacja',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Wir wodny',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Zamieć',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Zimna wściekłość',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Lodowaty wybuch',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Władza lodu',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Oczyszczenie',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Wyniesienie',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Wypalanie',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lawa',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Fontanna ognia',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteory',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dynobójstwo',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Piorun',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Grzmot',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Burza',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Przeładowanie',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Pole elektryczne',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Włosy dęba',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Ryk wiatru',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Karuzela',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Huk',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Trzęsienie',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Pęknięcie',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Katastrofa',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Wysadzenie',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Wichor kamieni',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Jezioro śmierci',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Toksyczna kałuża',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Kwas',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomizacja',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Dezintegracja',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionizacja',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Wygnanie',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Przeklęcie',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Odłączenie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Burza magiczna',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Manasztorm',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Gniew Arkany',
    'key.combined.first.1': 'Mądrych',
    'key.combined.first.2': 'Piekielnych',
    'key.combined.first.3': 'Przepięknych',
    'key.combined.first.4': 'Złośliwych',
    'key.combined.first.5': 'Neutralnych',
    'key.combined.first.6': 'Szczerych',
    'key.combined.first.7': 'Świętych',
    'key.combined.first.8': 'Dawnych',
    'key.combined.first.9': 'Podziemnych',
    'key.combined.first.10': 'Ognistych',
    'key.combined.first.11': 'Bystrych',
    'key.combined.first.12': 'Ogromnych',
    'key.combined.first.13': 'Niebieskich',
    'key.combined.first.14': 'Srogich',
    'key.combined.first.15': 'Dobrych',
    'key.combined.first.16': 'Powietrznych',
    'key.combined.first.17': 'Ziemnych',
    'key.combined.first.18': 'Czerwonych',
    'key.combined.first.19': 'Nieśmiertelnych',
    'key.combined.first.20': 'Zaginionych',
    'key.combined.first.21': 'Powietrznych',
    'key.combined.first.22': 'Strasznych',
    'key.combined.first.23': 'Wodnych',
    'key.combined.first.24': 'Zabawnych',
    'key.combined.first.25': 'Głupich',
    'key.combined.second.1': 'Bohaterów',
    'key.combined.second.2': 'Ryb',
    'key.combined.second.3': 'Sow',
    'key.combined.second.4': 'Złodziejów',
    'key.combined.second.5': 'Służących',
    'key.combined.second.6': 'Czarodziejów',
    'key.combined.second.7': 'Starzec',
    'key.combined.second.8': 'Zaklinaczy',
    'key.combined.second.9': 'Wojowników',
    'key.combined.second.10': 'Pojedynkowiczów',
    'key.combined.second.11': 'Handlarzy',
    'key.combined.second.12': 'Królików',
    'key.combined.second.13': 'Jabłek',
    'key.combined.second.14': 'Bojowników',
    'key.combined.second.15': 'Prestidigitatorów',
    'key.combined.second.16': 'Rycerzy',
    'key.combined.second.17': 'Barbarzyńców',
    'key.combined.second.18': 'Żuków',
    'key.combined.second.19': 'Żmij',
    'key.combined.second.20': 'Smoków',
    'key.combined.second.21': 'Widm',
    'key.combined.second.22': 'Kotków',
    'key.combined.second.23': 'Żołnierzy',
    'key.combined.second.24': 'Szczęściarzy',
    'key.combined.second.25': 'Asasynów',
    'key.combined.second.26': 'Mysz',
    'key.combined.second.27': 'Żywiołów',
    'key.combined.second.28': 'Eksploratorów',
    'key.combined.second.29': 'Szamanów',
    'key.combined.second.30': 'Kapłanów',
    'key.combined.second.31': 'Aniołów',
    'key.combined.second.32': 'Archontów',
    'key.combined.second.33': 'Katów',
    'key.combined.second.34': 'Głupców',
    'key.combined.second.35': 'Zuchów',
    'key.combined.second.36': 'Poczciwców',
    'key.combined.second.37': 'Tchórzy',
    'key.combined.second.38': 'Bardów',
    'key.combined.second.39': 'Poskramiaczy',
    'key.combined.second.40': 'Obrońców',
    'key.combined.arena': 'Arena {0} {1} ',
    'key.combined.library': 'Biblioteka {0} {1} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Woda',
    'element.type.WIND': 'Powietrze',
    'element.type.FIRE': 'Ogień',
    'element.type.EARTH': 'Ziemia',
    'element.type.DUNGEON': 'Arkana',
    'spell.type.ACTIVATION_RADIUS': 'Zasięg widoczności',
    'spell.type.VISION_RADIUS': 'Smoczy wzrok',
    'spell.type.STOP_FIELD': 'Pole Obfitości',
    'spell.type.SCOUT': 'Rozeznanie',
    'spell.type.PROTECT_ARENA': 'Obrona Areny',
    'spell.type.CREATE_PORTAL': 'Stwórz Portal',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Podwójny drop',
    'spell.type.SLUG_PLAYERS': 'SLUG_PLAYERS',
    'quest.title.WIN_ARENA_MONSTER': 'Dominowanie',
    'quest.title.OPEN_EGGS': 'Gorączka jajkowa',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Kontrolowanie terenu',
    'quest.title.CAPTURE_LIBRARY': 'Żądza wiedzy',
    'quest.title.CAPTURE_WILD_MONSTER': 'Smoczyjski park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Polowanie na żywioł',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Wyszukiwanie Arkanorodzonej',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Wyczyszczenie Wyłomu',
    'quest.title.OPEN_CHEST': 'Stare klejnoty',
    'quest.title.CHAIN_OF_STOP': 'Droga Obfitości',
    'quest.desc.WIN_ARENA_MONSTER': 'Zwyciężaj istoty na Arenie lub w Bibliotece. Nie można zwyciężyć istoty tego samego typu dwa razy.',
    'quest.desc.OPEN_EGGS': 'Wysiaduj istoty z jaj przy pomocy smoczych kokonów lub Matki Smoków',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Ściągnij daninę z zagarniętych Aren',
    'quest.desc.CAPTURE_LIBRARY': 'Posiadaj potrzebną ilość Bibliotek',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Nigdy nie jest za dużo istot. Wędruj i łap istoty ',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Wędruj i łap istoty żywiołu Wody',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Wędruj i łap istoty żywiołu Powietrza',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Wędruj i łap istoty żywiołu Ognia',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Wędruj i łap istoty żywiołu Ziemi',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Wędruj i łap istoty żywiołu Arkany',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Odwiedz Wyłom Arkany, gdzie znajduje się Matka Smoków',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Odwiedz Wyłom Arkany i złap wszystkie istoty, które tam znajdziesz',
    'quest.desc.OPEN_CHEST': 'Wyszukaj i otwórz kufry z klejnotami',
    'quest.desc.CHAIN_OF_STOP': 'Przejdź po szeregu Słupów Obfitości i aktywuj je. Każdy kolejny Słup będzie podświetlony.',
    'quest.dialog.completed.rewardtext': 'Twoja nagroda:',
    'key.tab.altar.title': 'OŁTARZ',
    'key.altar.remove': 'Usuń',
    'key.altar.put': 'Instaluj',
    'key.altar.convert': 'Przekształć',
    'key.altar.shared': 'Podziel się z innymi',
    'key.altar.pass.placeholder': 'Tutaj możesz wpisać hasło',
    'key.altar.pass.error': 'Hasło musi zawierać co najmniej {0} znaków',
    'key.altar.level.error': 'Musisz osiągnąć poziom {0}, aby używać Ołtarza',
    'key.altar.recipe.change': 'Czy na pewno chcesz zmienić przepis? Runy zostaną zwrócone właścicielom.',
    'key.altar.row.title': 'Aby tworzyć magię, musisz zainstalować ołtarz',
    'key.altar.rune.descr.RUNE_1': '3 szare runy = pomarańczowa',
    'key.altar.rune.descr.RUNE_2': '3 pomarańczowe runy = niebieska',
    'key.altar.rune.descr.RUNE_3': '3 niebieskie runy = szmaragdowa',
    'key.altar.rune.descr.RUNE_4': '3 szmaragdowe runy = czerwona',
    'key.altar.rune.descr.RUNE_5': '3 czerwone runy = fioletowa',
    'key.altar.rune.descr.RUNE_6': 'Fioletowe runy są najpotężniejsze',
    'error.altar.cannotRemove': 'Nie można usunąć Ołtarza',
    'error.altar.cannotConvert': 'Nie masz wystarczająco run',
    'key.tab.altar.recipes': 'PRZEPISY',
    'key.altar.noRecipes': 'Nie masz żadnych przepisów',
    'key.altar.header': 'Umieść runy na Ołtarzu, aby wytworzyć zaklęcie',
    'key.altar.castBtn': 'Wytwórz',
    'key.altar.recipe.select': 'Wybierz potrzebne zaklęcie',
    'key.altar.castDone': 'Zaklęcie zostało wytworzone',
    'key.arena.protected.ally': 'Obrona:',
    'key.avatarCustomization.title': 'Wybierz wygląd postaci:',
    'key.buddy.walkDescription': 'Spaceruj z wychowankiem, aby dostać {0}',
    'key.buddy.totalWalked': 'Już przeszedłeś (przeszłaś) {0} km',
    'key.account.balance': 'Surowce:',
    'key.account.userLevel': '{0} poziom',
    'key.account.totalDistance': 'Przechodzono: {0} kilometrów',
    'key.acount.registerDate': 'Początek gry: {0}',
    'key.storage.sort.name': 'IMIĘ',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'ZIELONA LISTA',
    'key.storage.sort.group2': 'ŻÓŁTA LISTA',
    'key.storage.sort.group3': 'CZERWONA LISTA',
    'key.storage.sort.date': 'DATA',
    'key.account.options.jurnal': 'DZIENNIK',
    'key.account.options.buddy': 'WYCHOWANIEC',
    'key.account.options.artifacts': 'ARTEFAKTY',
    'key.account.options.style': 'WYGLĄD',
    'key.error.gps.permission': 'GPS jest niedostępny. Włącz dostęp do GPS w ustawieniach aplikacji, aby kontynuować grę',
    'key.error.gps.disabled': 'GPS jest wyłączony. Włącz GPS, aby kontynuować grę',
    'key.error.gps.fakePosition': 'Nie można grać bez GPS',
    'key.error.gps.signal.notFound': 'Brak sygnału GPS',
    'key.error.gps.signal.bad': 'Gra jest niedostępna. Słaby sygnał GPS',
    'key.error.internet.notReachable': 'Brak połączenia',
    'key.journal.title': 'Dziennik',
    'key.journal.yesterday': 'Wczoraj',
    'key.settings.title': 'Ustawienia',
    'key.settings.music': 'Muzyka',
    'key.settings.deviceAuthError': 'Ze względów bezpieczeństwa proszę przywiązać konto do Google lub Facebook ',
    'key.settings.sounds': 'Dzwięki',
    'key.settings.vibration': 'Wibracja',
    'key.settings.batterySaver': 'Tryb niskiego zużycia baterii',
    'key.settings.support': 'Napisz do wsparcia technicznego',
    'key.settings.logout': 'Wyloguj',
    'key.settings.auth.deviceid': 'ID urządzenia',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Przywiąż',
    'key.settings.languageTitle': 'Język',
    'key.settings.language': 'Polski',
    'key.battle.result.win': 'Bitwa skończyła się',
    'key.battle.result.lose': 'Bitwa skończyła się',
    'key.wizardBattle.result.win': 'ZWYCIĘSTWO!',
    'key.wizardBattle.result.lose': 'PORAŻKA!',
    'key.battle.result.monster': 'Zwyciężono istot',
    'key.battle.result.exp': 'Zdobyto doświadczenia',
    'key.battle.result.prestige_strong_enemy': 'Bonus sławy za silnych wrogów',
    'key.battle.result.exp_strong_enemy': 'Bonus doświadczenia za silnych wrogów',
    'key.battle.result.prestige_killed_all': 'Bonus sławy za zabicie wszystkich',
    'key.battle.result.exp_killed_all': 'Bonus doświadczenia za zabicie wszystkich',
    'key.battle.result.dust': 'Esencja',
    'key.radar.title': 'Istoty w pobliżu',
    'key.levelUp.title': 'Nowy poziom!',
    'key.wizardBattle.left': 'Limit bitw:',
    'key.wizardBattle.timer': 'Limit zostanie skasowany za',
    'key.wizardBattle.enhance.title': 'ZWIĘKSZENIE LIMITU',
    'key.wizardBattle.enhance.desc': 'Limit bitw można zwiększyć do 7 dziennie w ciągu 1 tygodnia',
    'key.wizardBattle.enhance.btn': 'Zwiększ',
    'key.wizardBattle.lookingForOpponent': 'Wyszukiwanie przeciwnika dla Pojednynku...',
    'key.catch.result.expMonster': 'Doświadczenie za złapanie:',
    'key.catch.result.expMonsterNew': 'Nowe w Bestiariuszu:',
    'key.catch.result.expAccurate': 'Za trafny zrut:',
    'key.catch.result.expSpin': 'Za kręcony rzut:',
    'key.catch.result.strike': 'Pierwsza istota dziś:',
    'key.catch.result.total': 'Ogólne doświadczenie:',
    'key.catch.fullStorage': 'Magazyn istot jest pełny',
    'key.catch.noItems': 'Nie masz żadnych magicznych kul',
    'key.creadex.title': 'BESTIARIUSZ',
    'key.creadex.detail.caught': 'ZŁAPANO: {0}',
    'key.creadex.detail.evolution': 'EWOLUCJA',
    'key.tab.doll': 'POSTAĆ',
    'key.tab.artifacts': 'ARTEFAKTY',
    'key.activePoint.title': 'Słup Obfitości',
    'key.personalization.title': 'Zaczarowanie',
    'key.chest.title': 'Magiczny kufer',
    'key.quest.daily.title': 'ZADANIE',
    'key.quest.weekly.title': 'POLOWANIE',
    'key.quest.get': 'DOSTAĆ ZADANIE',
    'key.quest.change': 'ZMIEŃ ZADANIE',
    'key.quest.progress': 'Postęp zadania: {0} z {1}',
    'key.error.quest.weekly.level': 'Musisz osiągnąć poziom {0}, aby zacząć polowanie na Złote jajko',
    'key.error.quest.daily.level': 'Musisz osiągnąć poziom {0}, aby wziąć zadanie',
    'key.error.quest.tooFar': 'Obelisk jest zbyt daleko',
    'key.quest.daily.descr.noQuest.title': 'Nie masz zadań',
    'key.quest.daily.descr.noQuest': 'Użyj Obelisku, aby otrzymać zadanie i dostać nagrodę.',
    'key.quest.daily.timer.descr': 'Będziesz w stanie zmienić zadanie za:',
    'key.quest.daily.waitForNew.descr': 'Możesz wziąć nowe zadanie za: ',
    'key.quest.weekly.getFragment': 'DOSTAĆ FRAGMENT',
    'key.quest.weekly.descr.noQuest.title': 'Nie uczestniczysz w polowaniu na Złote Jajo',
    'key.quest.weekly.descr.noQuest': 'Użyj Obelisku, aby otrzymać fragment tajemniczej mapy i zacząć polowanie.',
    'key.quest.weekly.descr.getFirstFragment': 'Otrzymaj pierwszy fragment tajemniczej mapy, aby zacząć polowanie na Złote jajo',
    'key.quest.weekly.descr.top.notAllOpen': 'Używaj Obelisków, aby otrzymywać fragmenty mapy. Pospiesz się, polowanie skończy się za ',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Używaj łopaty na każdym fragmencie, aby odnaleźć Złote jajo',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Już otrzymałeś(-aś) fragment mapy z tego Obelisku',
    'key.quest.weekly.descr.top.allOpen': 'Otrzymano wszystkie fragmenty mapy z Obelisków. Pospiesz się, polowanie skończy się za ',
    'key.quest.weekly.descr.bot.allOpen': 'Używaj łopaty na każdym fragmencie, żeby odnaleźć Złote jajo',
    'key.quest.weekly.descr.top.completed': 'Już znalazłeś(-aś) Złote jajko w tym tygodniu. Kolejne polowanie zacznie sie za',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}g',
    'key.timer.format.H_M': '{0}g {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}g',
    'key.creatureStorage.tab.creatures': 'ISTOTY',
    'key.creatureStorage.tab.eggs': 'JAJA',
    'key.creatureStorage.multiTransferText': 'Wybierz, którą z istot chcesz wypuścić',
    'key.storage.creature.transfer': 'wypuść ({0})',
    'key.error.needHigherLevelForArena': 'Do wejścia do Areny jest potrzebny poziom {0}',
    'key.error.needHigherLevelForLibrary': 'Do wejścia do Biblioteki jest potrzebny poziom {0}',
    'key.error.arenaUnderProtection': 'Arena jest chroniona przez Błogosławieństwo obrony',
    'key.error.buildingTooFar': 'Budowla jest zbyt daleko',
    'key.error.noAliveCreaturesForAttack': 'Nie masz żywych istot',
    'key.error.noHealPotion': 'Nie masz ziół leczniczych',
    'key.error.noResurrectionPotion': 'Nie masz ziół wskrzeszających',
    'key.error.tryAgainLater': 'Błąd. Spróbuj później.',
    'key.error.alreadyHasLure': 'Przynęta jest już założóna',
    'key.error.cannotUseLureInDungeon': 'Nie można używać przynęty w Wyłomie Arkany',
    'key.error.bagIsFull': 'Brak miejsca w torbie',
    'key.error.cantTransferCreature': 'Nie można wypuścić tej istoty',
    'key.notification.done': 'Gotowe!',
    'key.modal.doYouWantToTransfer': 'Czy na pewno chcesz puścić te istoty?',
    'key.modal.youWillLoseBuddyProgress': 'Czy na pewno chcesz zmienić wychowanka? Postęp ulepszenia kamienia zostanie skasowany.',
    'key.modal.doYouWantToLeaveDungeon': 'Czy chcesz opuścić wyłom Arkany?',
    'key.modal.superVisionActive': 'Smoczy wzrok już został zaktywowany. Ponowna aktywacja przemieści magiczny zasięg widoczności. Czy na pewno chcesz użyć go jeszcze raz?',
    'key.modal.experienceBoosterActive': 'Kryształ mądrości już został zaktywizonwany. Czy na pewno chcesz użyć go jeszcze raz?',
    'key.modal.youWillLooseQuestProgress': 'Postęp w aktualnym queście zostanie skasowany. Czy jesteś pewny(-a)?',
    'key.modal.doYouWantToEnterDungeon': 'Czy chcesz wejść do wyłomu Arkany przez Portal?',
    'key.modal.doYouWantPersonalizePoint': 'Zaczarowany Słup Obfitości będzie dawał tylko {0}. Czy chcesz wydać {1} monet na zaczarowanie?',
    'key.modal.doYouWantToDeletePersonalization': 'Czy na pewno chcesz zdjąć zaczarowanie z tego Słupa Obfitości?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Chcesz wzmocnić tę istotę?',
    'key.modal.doYouWantToEvolveThisCreature': 'Chcesz przekształcić tę istotę w bardziej silną?',
    'key.modal.doYouWantToScoutHere': 'Czy na pewno chcesz podświetlić tę strefę?',
    'key.error.creatureHasMaxLevel': 'Istota już ma maksymalny poziom',
    'key.error.creatureHasMaxLevelForUser': 'Najpierw musisz zwiększyć poziom postaci',
    'key.error.notEnoughResourcesForEnhance': 'Niewystarczające surowce',
    'key.error.creatureIsArenaDefender': 'Nie można wybrać istoty, która broni budynku',
    'key.modal.incenseActive': 'Feromony już zostały zaktywizowane. Czy na pewno chcesz użyć ich jeszcze raz?',
    'key.error.cantHealHealthyCreature': 'Istota została całkowicie uzdrowiona',
    'key.error.cantRessurectAliveCreature': 'Istota już jest żywa',
    'key.error.noTreasureHere': 'Na tym fragmenice mapy nie ma Złotego jajka. Szukaj dalej.',
    'key.error.levelTooSmall': 'Najpierw musisz zwiększyć poziom postaci',
    'key.error.needHigherLevelForWizardBattles': 'Do uczestnictwa w Pojedynkach Czarodziejów potrzebny jest poziom {0}',
    'key.error.artifactBagIsFull': 'W magazynie artefaktów brak miejsca',
    'key.error.notEnoughCoins': 'Brak monet',
    'key.error.allFragmentsAreOpen': 'Odkryto wszystkie fragmenty tajemniczej mapy',
    'key.error.questAlreadyCompleted': 'Zadanie już zostało wykonane',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Już otrzymałeś(-aś) fragment mapy z tego Obelisku',
    'key.error.portalTooFarAway': 'Portal jest zbyt daleko',
    'key.error.battleLimitAlreadyEnhanced': 'Limit bitw już został zwiększony',
    'key.error.youAreNotAltarOwner': 'To może robić tylko właściciel Ołtarza',
    'key.error.youAlreadyHaveAltar': 'Ołtarz już został postawiony',
    'key.error.cantTakeAnotherUsersRune': 'Nie można zabrać runy innego gracza',
    'key.error.libraryBlocked': 'Trzeba zaczekać 3 dni po ponownym treningu, aby znów używać Bibliotek',
    'key.error.notAuthorized': 'Użytkownik nie jest autoryzowany',
    'key.error.eggOnlyRoost': 'Musisz oddać to jajko Matce Smoków',
    'key.error.purchase': 'Błąd: {0}',
    'key.error.creatureIsDead': 'Najpierw musisz wskrzesić istotę',
    'key.error.no_connection': 'Nie udało się połączyć z serwerem. Spróbuj później.',
    'key.error.protocol_version_mismatch': 'Wersja gry jest przestarzała. Aktualizacja gry jest wymagana.',
    'key.error.update_application': 'Wersja gry jest przestarzała. Aktualizacja gry jest wymagana.',
    'key.modal.doYouWantToTransferSingle': 'Czy na pewno chcesz puścić tę istotę?',
    'key.notification.phoneNotSupportAR': 'Twoje urządzenie nie podtrzymuje AR',
    'key.notification.turnOnARPermission': 'Gra nie ma dostępu do kamery. Musisz włączyć dostęp w ustawieniach urządzenia',
    'key.notification.dailyQuestFinished': 'Zadanie zostało wykonane!',
    'key.modal.yesBtn': 'Tak',
    'key.modal.noBtn': 'Nie',
    'event.log.DAILY_QUEST_COMPLETED': 'Codzienne zadanie zostało wykonane. Dostałeś/-aś nagrody:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Polowanie skończyło się! Twoja nagroda:',
    'event.log.ENCOUNTER_VICTORY': 'Zwyciężyłeś(-aś) dzikiego potwora!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Twoja wersja gry jest przestarzała. Aktualizacja gry jest wymagana.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Błąd autentykacji',
    'key.ServiceException.Cause.SESSION_GONE': 'Ktoś zalogował się na Twoje konto z innego urządzenia',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'ID użytkownika jest puste',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Nie znaleziono takiego użytkownika',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Konto zostało zablokowane za nieuczciwą grę.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Konto zostało zablokowane za oszustwa finansowe.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Konto zostało zablokowane za obrażliwy nick użytkownika.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Konto zostało zablokowane za agresję wobec innych graczy.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Konto zostało zablokowane za nieuczciwą grę.',
    'key.ServiceException.Cause.USER_BANNED': 'Konto zostało zablokowane.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Brak miejsca w torbie',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maksymalna ilość jaj',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Brak monet',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Brak kamieni dusz',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Brak esencji',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'W magazynie istot brak miejsca',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Istota już ma maksymalny poziom',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Nie można przemienić tej istoty',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Imię istoty musi zawierać co najwięcej 14 znaków',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Budynek już ma maksymalną liczbę obrońców',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Nie można uczynić obrońcy budynku wychowańcem',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Twoja istota już broni tego budynku',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Błąd',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Nie znaleziono bitwy',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Błąd',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Twoja istota już broni tego budynku',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Arena jest chroniona przez Błogosławieństwo Obrony',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Czas ściągania daniny jeszcze nie nadszedł',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Błędna kula',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Błędna budowla',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Dostęp jest zakazany',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Nieistniejący przedmiot',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Nieistniejący przepis',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Można postawić tylko jeden Ołtarz',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Najpierw musisz zwiększyć poziom postaci',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Nie udało się zacząć polowania na istotę',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Nieistniejący produkt',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Nieistniejący produkt',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Nieistniejąca budowla',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Nie znaleziono istoty',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Nie znaleziono istoty',
    'key.ServiceException.Cause.TOO_FAR': 'Budowla jest zbyt daleko',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Obiekt jest zbyt daleko',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Budowla odnawia się',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Budowla jest w Wyłomie Arkany',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Nie można użyć budowli',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Nie znaleziono smoczego kokonu',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Smoczy kokon jest pusty',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Smoczy kokon jest zajęty',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Jajo nie zostało wysiedzone',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Nie znaleziono jaja',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'To jajo potrzebuje Matki Smoków',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Skończyły się ładunki',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Nie udało się postawić budowli',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Wystąpił błąd, a to jest tajemnicza wiadomość o nim',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Dziki potwór uciekł',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Nie znaleziono dzikiego potwora',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'W tym słupie już jest przynęta',
    'key.ServiceException.Cause.WRONG_ITEM': 'Błędny przedmiot',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Ta runa jest najsilniejsza',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Brak run tego poziomu',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Błędny slot dla runy',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Ten slot jest już zajęty',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Slot runy jest pusty',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Nie można wybrać obrońcy budynku',
    'key.ServiceException.Cause.WRONG_SPELL': 'Błędne zaklęcie',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Zaklęcie potrzebuje więcej run',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Nowe zadanie jest jeszcze niedostępne',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Już użyłeś(-aś) tego Obelisku',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Wszystkie fragmenty są odkryte',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Nie uczestniczysz w polowaniu na Złote jajo',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Już próbowałeś(-aś) szukać Złotego jaja tutaj',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Już użyłeś(-aś) smakołyku',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Istota już została złapana',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Ponowne nauczanie istoty jest czasowo niedostępne',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Biblioteka jest czasowo zablokowana',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Serwer nie odpowiada. Spróbuj później',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Limit bitw już został zwiększony',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Osiągnięto limit bitw',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Musisz osiągnąć 9 poziom, aby uczestniczyć w Pojedynku Czarodziejów',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Nie znaleziono przeciwnika dla Pojedynku Carodziejów, spróbuj później',
    'key.ServiceException.Cause.MARKET_ERROR': 'Błąd sklepu',
    'key.ServiceException.Cause.NO_CHEST': 'Nie znaleziono kufra',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Błąd otrzymania fragmentu. Proszę spróbować później.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Musisz włożyć Smocze Serce lub zestaw Smoczych artefatków, aby dać MAtce Smoków więcej jaj',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'W tej komórce już jest jajko',
    'key.ServiceException.Cause.NO_CONNECTION': 'Brak połączenia internetowego',
    'key.ServiceException.Cause.SERVER_DOWN': 'Serwer gry jest czasowo niędostępny. Spróbuj później',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Serwer gry jest niedostępny z powodu prac technicznych. Proszę spróbować później.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Te runy są używane teraz',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Poruszasz się zbyt szybko',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Osiągnięto limit zdobytych Aren',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Osiągnięto limit zdobytych Bibliotek',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Błąd: GPS jest niedostępny',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Nie można rzucić tego zaklęcia w Wyłomie Arkany',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Sesja wygasła',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Wersja gry jest przestarzała. Wymagana jest aktualizacja.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Nie ma sojuszniczych Aren w zasięgu widzenia',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Nie ma wrogich Aren w zasięgu widzenia',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'kule',
    'stop.personalized.HEALS': 'zioła lecznicze',
    'stop.personalized.RESURRECTIONS': 'zioła wskrzeszenia',
    'stop.personalized.EGGS': 'jaja istot',
    'stop.personalized.FOODS': 'smakołyki',
    'key.button.cancelPersonal': 'Kasuj',
    'key.error.needHigherLevelForSofaBattles': 'Musisz osiągnąć poziom {0}, aby uczestniczyć w Pojedynku Czarodziejów',
    'fraction.text.youWilLGetBonus': 'Otrzymasz {0} monet za dołączenie do tej frakcji',
    'fraction.text.fractionUnavailable': 'Frakcja jest czasowo niedostępna',
    'fraction.text.chooseYourAlliance': 'Wybierz frakcję, za którą będziesz walczyć',
    'fraction.text.redFractionName': 'Czerwony Zakon',
    'fraction.text.blueFractionName': 'Niebieski Zakon',
    'key.error.chestTooFarAway': 'Kufer jest zbyt daleko',
    'key.button.openChest': 'Otwórz',
    'key.candy.MONSTER_WATER_1': 'kamienie Żabusa',
    'key.candy.MONSTER_WATER_2': 'kamienie Kropli',
    'key.candy.MONSTER_WATER_3': 'kamienie Spirytusa',
    'key.candy.MONSTER_WATER_4': 'kamienie Aquina',
    'key.candy.MONSTER_WATER_8': 'kamienie Dżemoczapa',
    'key.candy.MONSTER_WATER_9': 'kamienie Minory',
    'key.candy.MONSTER_WATER_10': 'kamienie Infaliszka',
    'key.candy.MONSTER_WATER_12': 'kamienie Dadaczka',
    'key.candy.MONSTER_WATER_13': 'kamienie Batoida',
    'key.candy.MONSTER_WATER_23': 'kamienie Broniusza',
    'key.candy.MONSTER_WATER_24': 'kamienie Neptuna',
    'key.candy.MONSTER_WATER_25': 'kamienie Leviathana',
    'key.candy.MONSTER_FIRE_1': 'kamienie Garneczka',
    'key.candy.MONSTER_FIRE_2': 'kamienie Mummiwina',
    'key.candy.MONSTER_FIRE_3': 'kamienie Parowoza',
    'key.candy.MONSTER_FIRE_4': 'kamienie Inkumusa',
    'key.candy.MONSTER_FIRE_6': 'kamienie Flamy',
    'key.candy.MONSTER_FIRE_7': 'kamienie Phoby',
    'key.candy.MONSTER_FIRE_11': 'kamienie Iskry',
    'key.candy.MONSTER_FIRE_12': 'kamienie Cydry',
    'key.candy.MONSTER_FIRE_15': 'kamienie Igłożara',
    'key.candy.MONSTER_FIRE_25': 'kamienie Smaugra',
    'key.candy.MONSTER_EARTH_1': 'kamienie Arbuzylla',
    'key.candy.MONSTER_EARTH_2': 'kamienie Kwiatuszka',
    'key.candy.MONSTER_EARTH_3': 'kamienie Listka',
    'key.candy.MONSTER_EARTH_4': 'kamienie Brownie',
    'key.candy.MONSTER_EARTH_8': 'kamienie Goblina',
    'key.candy.MONSTER_EARTH_9': 'kamienie Bellflow',
    'key.candy.MONSTER_EARTH_10': 'kamienie Żołędnia',
    'key.candy.MONSTER_EARTH_11': 'kamienie Filo',
    'key.candy.MONSTER_EARTH_13': 'kamienie Princie',
    'key.candy.MONSTER_EARTH_25': 'kamienie Skylli',
    'key.candy.MONSTER_DUNGEON_1': 'kamienie Ruuki',
    'key.candy.MONSTER_DUNGEON_2': 'kamienie Aksolana',
    'key.candy.MONSTER_DUNGEON_3': 'kamienie Kolcopleca',
    'key.candy.MONSTER_DUNGEON_4': 'kamienie Magglada',
    'key.candy.MONSTER_DUNGEON_5': 'kamienie Miłokota',
    'key.candy.MONSTER_DUNGEON_6': 'kamienie Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'kamienie Wampiro',
    'key.candy.MONSTER_DUNGEON_13': 'kamienie Gąsienicy',
    'key.candy.MONSTER_DUNGEON_17': 'kamienie Inura',
    'key.candy.MONSTER_WIND_1': 'kamienie SunTzi',
    'key.candy.MONSTER_WIND_2': 'kamienie Uchomycha',
    'key.candy.MONSTER_WIND_3': 'kamienie Grzybio',
    'key.candy.MONSTER_WIND_4': 'kamienie Puszystorożca',
    'key.candy.MONSTER_WIND_6': 'kamienie Gamajun',
    'key.candy.MONSTER_WIND_7': 'kamienie Straszyczka',
    'key.candy.MONSTER_WIND_11': 'kamienie Infirda',
    'key.candy.MONSTER_WIND_12': 'kamienie Ondyny',
    'key.candy.MONSTER_WIND_15': 'kamienie Cheshira',
    'key.candy.MONSTER_WIND_25': 'kamienie Charybdy',
    'key.button.leaveDungeon': 'Opuść Wyłom',
    'key.alias.enterNewAlias': 'Wpisz imię istoty',
    'key.alias.enterText': 'Wpisz tekst...',
    'key.hut.hutName': 'Matka Smoków',
    'key.hut.hutDescr': 'Oddaj dawne jaja Matce Smoków, aby je wysiedziała dla Ciebie',
    'key.text.noHutEggs': 'Nie masz żadnych dawnych jajek',
    'key.text.noCapturedArenas': 'Nie masz podbitych Aren',
    'key.text.noChosenPet': 'Nie wybrano wychowańca',
    'key.text.noArtifacts': 'Nie masz żadnych artefaktów',
    'key.text.noCreatures': 'Nie masz żadnych złapanych istot',
    'key.text.noLureItems': 'Nie masz przynęty',
    'key.descr.aboutWizardBattles': 'Bierz udział w pojedynkach przeciw innym graczom, aby otrzymać doświadczenie i nagrody',
    'key.text.writeToSupport': 'Skontaktuj się ze wsparciem technicznym',
    'key.text.regUsingFacebook': 'Zarejestruj się przez Facebook',
    'key.text.regUsingGoogle': 'Zarejestruj się przez Google',
    'key.text.logUsingFacebook': 'Zaloguj przez Facebook',
    'key.text.logUsingGoogle': 'Zaloguj przez Google',
    'key.text.logUsingDeviceIDCurrent': 'Zaloguj przez Device ID',
    'key.text.logUsingDeviceIDNew': 'Zaloguj przez Device ID (nowe konto)',
    'key.text.createAccount': 'Graj',
    'key.text.connectedToFacebook': 'Połączono z Facebook',
    'key.text.connectedToGoogle': 'Połączono z Google',
    'key.text.complainAboutPoint': 'Zgłoś punkt',
    'key.text.copyCoordinates': 'Skopiuj namiary',
    'key.text.complainEnterEmail': 'Twój e-mail',
    'key.text.complainEnterText': 'Opisz swój problem',
    'key.modal.doYouWantToCloseApp': 'Chcesz zamknąć aplikację?',
    'key.catchPopup.notBad': 'Dobrze!',
    'key.catchPopup.good': 'Świetnie!',
    'key.catchPopup.sumptuously': 'Wspaniale!',
    'key.catchPopup.twistedThrow': 'Podkręcony rzut!',
    'key.battlePopup.strongHit': 'Mocny cios!',
    'key.battlePopup.weakHit': 'Słaby cios',
    'key.battlePopup.dodge': 'Wykręt!',
    'key.battlePopup.chargedAttack': '{0} używa {1}',
    'auth.login.play': 'Graj',
    'auth.login.nickname.placeholder': 'Wpisz imię',
    'auth.login.nickname.busy': 'To imię jest zajęte',
    'auth.login.nickname.proposal': 'Możesz używać tego imienia:',
    'auth.login.nickname.deviceId': 'Już masz postać',
    'auth.login.social.title': 'Zaloguj przez serwis społecznościowy',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Połączono z {0}',
    'auth.login.social.signOut': 'Wyloguj',
    'auth.login.signOut.confirmation': 'Czy na pewno chcesz wylogować?',
    'auth.login.social.userCancelledError': 'Kasuj połączenie',
    'auth.login.social.cantSignInError': 'Nie udaje się połączyć z {0}',
    'licence.title': 'UMOWA LICENCYJNA DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Chcę otrzymywać aktualności i propozycje na email',
    'licence.accept': 'Akceptuję',
    'licence.decline': 'Odrzuć',
    'key.error.wrongRoostIndex': 'Komórka jest niedostępna',
    'key.speed.toMachSpeed': 'Poruszasz się zbyt szybko. Nie można grać w Draconius GO: Catch a Dragon! Go za kierownicą - to jest niebezpieczne dla życia.',
    'key.speed.passenger': 'Jestem pasażerem',
    'key.activeObjects.addUnit.question': 'Czy na pewno chcesz uczynić {0} obrońcą tego budynku?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} g',
    'key.confirm.selectAlliance': 'Czy na pewno chcesz wybrać tę frakcję? Tego wyboru nie da się cofnąć.',
    'key.confirm.giveUpEncounter': 'Czy na pewno chcesz zrezygnować z pojedynku przeciwko dzikiemu potworowi?',
    'key.confirm.giveUpBattle': 'Czy na pewno chcesz zrezygnować i skończyć walkę?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nowa liga!',
};
