module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': '예',
    'key.button.cancel': '취소',
    'key.button.apply': 'OK',
    'key.button.use': '사용하기',
    'key.button.buy': '구매',
    'key.beCarefulMessage.text': '게임할 때 조심하세요. 주위를 둘러보세요',
    'key.creature.details.attack': '힘',
    'key.creature.details.health': '건강',
    'key.creature.details.powerUp': '강화',
    'key.creature.details.evolve': '진화',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'CP {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': '놓아주기',
    'key.creature.details.creadex': '동물 우화',
    'key.creature.registration.creadex': '동물 우화에 추가',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': '포획된 건물',
    'key.activeObjects.library': '재훈련을 받는 크리처 도서관에 있습니다',
    'key.activeObjects.library.empty': '차지한 도서관 없음',
    'key.activeObjects.arena': '아레나 기부금을 수집',
    'key.activeObjects.arena.collect': '수집하기',
    'key.activeObjects.arena.empty': 'No captured Arenas',
    'key.activeObjects.error.timer': '기부금을 걷을 수 없습니다. 기다려주세요',
    'key.activeObjects.error.noMoney': '먼저 아레나를 점령해야 합니다',
    'key.activeObjects.error.cannotRemaster': '재훈련 기능을 사용할 수 없습니다. 재훈련의 타이머를 다시 맞추기 위해 도서관를 점령해야 합니다',
    'key.activeObjects.library.remaster': '재훈련하기',
    'key.activeObjects.library.blocked': '재훈련 기능을 사용할 수 없습니다. 재훈련의 타이머를 다시 맞추기 위해 도서관를 점령해야 합니다',
    'key.activeObjects.remaster.confirmation.main': '정말 {0}의 재훈련을 원하세요? 메인 스킬인 {1}이(가) 변경됩니다.',
    'key.activeObjects.remaster.confirmation.charged': '정말 {0}의 재훈련을 원하세요? 충전된 스킬 {1}이(가) 변경됩니다.',
    'key.activeObjects.remaster.error': '오류',
    'key.activeObjects.item.weaklyBonus': '주간 보너스 +{0} 코인',
    'key.library.remaster.selectCreature': '재훈련할 생명체를 선택하세요',
    'key.remasterPanel.title': '변경할 스킬을 선택하세요',
    'key.storage.creatues': '크리처',
    'key.storage.eggs': '알',
    'key.storage.eggs.simple': '보통 알',
    'key.storage.eggs.super': '고대 알',
    'key.storage.eggs.missingAny': '크리처',
    'key.startEgg.button': '고치에 놓기',
    'key.startEgg.description': '알을 부화하기 위해 용의 고치를 사용하세요',
    'key.startEgg.incubator.title': '용의 고치',
    'key.startEgg.select.title': '알 선택하기',
    'key.openEgg.button': '알 열기',
    'key.openEgg.description': '새로운 크리처는 알에서 부화할 것입니다',
    'key.startEgg.description.roost.hatching': '용의 어머니가 이 알을 부화합니다. 그냥 기다리십시요. 아르카나 균열이사라지면 알은 부화를 멈추게됩니다',
    'key.startEgg.description.roost.notHatching': '당신을 위해 알을 부화시키려면 용의 어머니에게 알을 주십시오',
    'key.startEgg.description.simple.hatching': '본 알은 용의 고치에서 부화하고 있습니다. 알의 부화를 돕기 위해 게임을 켜십시오',
    'key.startEgg.description.simple.notHatching': '품기를 시작하려면 알을 용의 고치에 넣으세요. 필요한 거리를 가면 알이 부화할 것입니다',
    'key.mainMenu.wizardDuels': '마술사 결투',
    'key.mainMenu.quests': '퀘스트',
    'key.mainMenu.activePoints': '포획물',
    'key.mainMenu.creadex': '동물 우화집',
    'key.mainMenu.magic': '마법',
    'key.mainMenu.creatues': '크리처',
    'key.mainMenu.shop': '가게',
    'key.mainMenu.backpack': '가방',
    'key.error.banned': '계정이 차단되었습니다',
    'event.log.CREATURE_CAUGHT': '{0}를 포획했습니다!',
    'event.log.ITEM_BOUGHT': '{0} x{1} 구입했습니다. {2}동전을 썼습니다',
    'event.log.ARTIFACT_BOUGHT': '구입된 아티팩트: {0}. {1}동전을 썼습니다',
    'event.log.EGG_HATCHED': '{0}는  {1}알에서 부화합니다',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': '금의',
    'event.log.ROOST_EGG_HATCHED': '당신 위해용의 어머니는 당신 위해 {1}km 알을 부화했습니다.{0}이제 당신의 것입니다.',
    'event.log.CHEST_OPENED': '가슴에 발견됐습니다:',
    'event.log.ARENA_LOST_CONTROL': '{1}는 {0}에서 제거했습니다',
    'event.log.LIBRARY_LIST_CONTROL': '{1}는 {0}에서 제거했습니다',
    'event.log.LEVEL_UP': '당신은 {0} 수준에 도달했습니다',
    'event.log.BUDDY_FOUND_CANDY': '애완 동물은{0}를 발견했습니다',
    'event.log.QUEST_COMPLETED': '{0}임무 보상',
    'event.log.ENCOUNTER_LOOSE': '당신은 야생 몬스터에서 도망쳤습니다',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': '마술사 결투에 전투 제한을 {0}동전으로 증가했습니다',
    'event.log.HARD_CURRENCY_BOUGHT': '{1}로 {0}동전을 구입했습니다',
    'event.log.UPGRADE_BAG_BOUGHT': '가방을 {0}동전으로 업그레이드했습니다',
    'event.log.UPGRADE_STORAGE_BOUGHT': '크리처 저장소가 {0}동전으로 업그레이드했습니다',
    'key.shop.accesories': '액세서리',
    'key.shop.artifacts': '아티팩트',
    'key.shop.donate': '동전',
    'key.shop.upgrade': '업그레이드',
    'key.shop.donate.coins': '{0} 동전',
    'key.shop.upgrade.bag': '가방의 업그레이드',
    'key.shop.upgrade.bag.desc': '가방 크기가 50만큼 증가합니다',
    'key.shop.upgrade.storage': '크리처 저장소의 업그레이드',
    'key.shop.upgrade.storage.desc': '생명체 저장소 크기가 50만큼 증가합니다',
    'key.shop.donate.dialog.title': '코인이 부족합니다!',
    'key.shop.donate.dialog.desc': '여기서 얻거나, 상점을 방문해 더 구하세요',
    'key.potionUseMenu.title': '치료 물약',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': '아르카나 세계에 포털을 만듭니다',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': '모든 플레이어들이 레프러콘의 분노를 느낄 것입니다',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': '30 분 동안 풍부 타워의 필드를 만듭니다',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': '30 분 동안 풍부 타워의 보상 수가 두 배로 늘어납니다',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': '지도를 공개하고 몬스터를 찾으려면 지역에서 버튼을 길게 누르십시오.',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': '30 분 동안 몬스터의 탐지 반경이 늘어납니다',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': '사흘 동안 30%로  물체의 활성화 반지름이 늘어납니다',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': '가장 가까운 연합군의 아레나는 30 시간 동안 적이 공격 할 수 없습니다',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': '가시반경에 있는 모든 적의 아레나는 중립 될 것입니다',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': '불의 생명체를 불러들이는 마법의 탑을 만듭니다',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': '물의 생명체를 불러들이는 마법의 탑을 만듭니다',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': '바람의 생명체를 불러들이는 마법의 탑을 만듭니다',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': '흙의 생명체를 불러들이는 마법의 탑을 만듭니다',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': '아르카나의 생명체를 불러들이는 마법의 탑을 만듭니다',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': '아르카나 균열',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': '레프러콘의 분노',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': '풍부 들판',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': '황금 용의 선물',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': '아스트랄 비전',
    'key.recipe.RECIPE_SUPER_VISION_1': '용의 시력',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': '긴 팔',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': '보호의 축복',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': '불의 정화',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': '불의 탑',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': '물의 탑',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': '바람의 탑',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': '흙의 탑',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': '아르카나의 탑',
    'key.buff.ATTACKER_CP_BOOST': '크리처의 전투력이 일시적으로 증가했습니다',
    'key.buff.BEST_BALL_LUCK': '30 분 동안 풍부 타워에 최고의 매직 볼',
    'key.buff.BEST_POTION_LUCK': '30 분 동안 풍부 타워에 최고의 매직 물약',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '30 분 동안 풍부 타워에서 +2 액세서리',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': '도서관 쿨타임이 {0} 감소합니다',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': '경기장에서의 세금 징수 시간이 {0} 감소합니다',
    'key.buff.tooltip.ATTACKER_CP_BOOST': '현재 건물을 보호하지 않는 생명체의 ��이(가) 증가합니다',
    'key.buff.tooltip.BEST_BALL_LUCK': '풍요의 기둥에서 레벨에 필요한 최고의 구만 받습니다',
    'key.buff.tooltip.BEST_POTION_LUCK': '풍요의 기둥에서 레벨에 필요한 최고의 물약만 받습니다',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '풍요의 기둥에서 받는 아이템 수가 두 배로 증가합니다',
    'key.loot.result.dust': '에센스',
    'key.loot.result.exp': '캐릭터 경험',
    'key.loot.result.coin': '동전',
    'key.loot.result.candy': '돌',
    'key.item.MAGIC_BALL_SIMPLE': '제자의 매직 볼',
    'key.item.MAGIC_BALL_NORMAL': '석사의 매직 볼',
    'key.item.MAGIC_BALL_GOOD': '주님의 매직 볼',
    'key.item.LURE': '미끼',
    'key.item.INCENSE': '페로몬',
    'key.item.EGG': '알',
    'key.item.SHOVEL': '삽',
    'key.item.POTION_HEAL_1': '치료 소물약',
    'key.item.POTION_HEAL_2': '치료 중물약',
    'key.item.POTION_HEAL_3': '치료 대물약',
    'key.item.POTION_HEAL_4': '전체 복구 물약',
    'key.item.POTION_RESURRECTION_1': '부활 물약',
    'key.item.POTION_RESURRECTION_2': '부활 대물약 ',
    'key.item.INCUBATOR_1': '용의 고치',
    'key.item.INCUBATOR_3': '용의 고치',
    'key.item.INCUBATOR_PERPETUAL': '영원한 용의 고치',
    'key.item.SUPER_VISION': '용의 시력',
    'key.item.RUNE_1': ' I룬 문자',
    'key.item.RUNE_2': ' II룬 문자',
    'key.item.RUNE_3': ' III룬 문자',
    'key.item.RUNE_4': ' IV룬 문자',
    'key.item.RUNE_5': ' V룬 문자',
    'key.item.RUNE_6': ' VI룬 문자',
    'key.item.FOOD_CATCH_CHANCE': '아르카나 캐러멜',
    'key.item.FOOD_MORE_DUST': '마법의',
    'key.item.FOOD_CALM_DOWN': '유니콘의 마시멜로',
    'key.item.FOOD_MORE_CANDIES': '네 가지 원소의 아이스크림',
    'key.item.EXPERIENCE_BOOSTER': '지혜의 크리스탈',
    'key.item.EGG_KM_0': 'Golden Egg',
    'key.item.MAGIC_BALL_SIMPLE.description': '크리처를 잡기 위한 매직 볼',
    'key.item.MAGIC_BALL_NORMAL.description': '크리처를 잡기 위한 매직 볼. 포획할 가능성이 약간 증가합니다.',
    'key.item.MAGIC_BALL_GOOD.description': '크리처를 잡기 위한 매직 볼. 포획할 가능성이 많이 증가합니다.',
    'key.item.LURE.description': '크리처를 위해 미끼. 크리처를 끌어 들이기 위해 풍부 타워에 넣으세요',
    'key.item.INCENSE.description': '페로몬은 요일에 따라 특정 요소의 크리처를 유치합니다',
    'key.item.EGG.description': '알을 부화하기 위해 용의 고치를 사용하세요',
    'key.item.SHOVEL.description': '삽은 보물 찾기에 절대적으로 필요합니다',
    'key.item.POTION_HEAL_1.description': '크리처를 200 생명력으로 회복합니다',
    'key.item.POTION_HEAL_2.description': '크리처를 500 생명력으로 회복합니다',
    'key.item.POTION_HEAL_3.description': '크리처를 1000 생명력으로 회복합니다',
    'key.item.POTION_HEAL_4.description': '크리처를 완전히 회복합니다',
    'key.item.POTION_RESURRECTION_1.description': '선택한 크리처를 부활시킵니다. 부활 후 크리처는 부상을 입을 것입니다',
    'key.item.POTION_RESURRECTION_2.description': '크리처를 부활시키고 완전히 회복합니다',
    'key.item.INCUBATOR_1.description': '용의 고치는 알에서 크리처를 부화시키기 위해 필요합니다. 사용 후 사라집니다.',
    'key.item.INCUBATOR_3.description': '용의 고치는 알에서 크리처를 부화시키기 위해 필요합니다. 3 회 사용 후 사라집니다.',
    'key.item.INCUBATOR_PERPETUAL.description': '용의 고치는 알에서 크리처를 부화시키기 위해 필요합니다.',
    'key.item.SUPER_VISION.description': '몬스터의 탐지 반경을 많이 늘어납니다',
    'key.item.RUNE_1.description': ' 1 레벨 마법 룬 문자',
    'key.item.RUNE_2.description': ' 2 레벨 마법 룬 문자',
    'key.item.RUNE_3.description': ' 3 레벨 마법 룬 문자',
    'key.item.RUNE_4.description': ' 4 레벨 마법 룬 문자',
    'key.item.RUNE_5.description': ' 5 레벨 마법 룬 문자',
    'key.item.RUNE_6.description': ' 6 레벨 마법 룬 문자',
    'key.item.FOOD_CATCH_CHANCE.description': '크리처를 잡기 위한 크리처 진미이다. 몬스터를 매직 볼로 잡을 기회를 증가합니다',
    'key.item.FOOD_MORE_DUST.description': '크리처를 잡기 위한 크리처 진미이다. 캡처를 위해 얻은 에센스의 양을 증가합니다',
    'key.item.FOOD_CALM_DOWN.description': '크리처를 잡기 위한 크리처 진미이다. 크리처를 약화시킵니다. 점프와 공격을 멈춥니다',
    'key.item.FOOD_MORE_CANDIES.description': '크리처를 잡기 위한 크리처 진미이다. 포획을 위해 얻는 영혼의 돌 수를 증가합니다',
    'key.item.EXPERIENCE_BOOSTER.description': '30 분 동안 경험을 2배 증가시킵니다',
    'key.artifact.ARTIFACT_TELEPATHY_1': '마술사의 마스크',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '아레나에 하루에 한번 크리처를 놓기',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': '본 아티팩트는 지도에 표시되는 아레나나 도서관의 자유 장소에 하루에 1 번 크리처를 원격으로 놓게 해줍니다',
    'key.artifact.ARTIFACT_TELEPATHY_2': '예언자의 얼굴',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '아레나에 하루에 2 번 크리처를 놓기',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': '본 아티팩트는 지도에 표시되는 아레나나 도서관의 자유 장소에 하루에 2 번 크리처를 원격으로 놓게 해줍니다',
    'key.artifact.ARTIFACT_TELEPATHY_3': '정복자의 투구',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '아레나에 하루에 3 번 크리처를 놓기',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': '본 아티팩트는 지도에 표시되는 아레나나 도서관의 자유 장소에 하루에 3 번 크리처를 원격으로 놓게 해줍니다',
    'key.artifact.ARTIFACT_TELEPATHY_4': '영웅의 투구',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '아레나에 하루에 4 번 크리처를 놓기',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': '본 아티팩트는 지도에 표시되는 아레나나 도서관의 자유 장소에 하루에 4 번 크리처를 원격으로 놓게 해줍니다',
    'key.artifact.ARTIFACT_TELEPATHY_5': '용의 전사의 투구',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '아레나에 하루에 5 번 크리처를 놓기',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': '본 아티팩트는 지도에 표시되는 아레나나 도서관의 자유 장소에 하루에 5 번 크리처를 원격으로 놓게 있게 해줍니다',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': '아레나 주님의 깃발',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': '아레나에 하나 더 크리처를 넣을 수 있게 합니다',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': '본 아티팩트가 있으면 한 마리 대신에 크리처 두 마리는 아레나나 도서관을 방어할 수 있습니다.',
    'key.artifact.ARTIFACT_BANK_8': '조각된 아티팩트',
    'key.artifact.ARTIFACT_BANK_8.description': '어떻게 그것을 찾았습니까?',
    'key.artifact.ARTIFACT_BANK_8.description.long': '보지 말아야 할 아티팩트를 보았습니다. 이제 증인이 되었기 때문에 우리는 당신을 제거해야 할 것입니다.',
    'key.artifact.ARTIFACT_BANK_9': '조각된 아티팩트',
    'key.artifact.ARTIFACT_BANK_9.description': '어떻게 그것을 찾았습니까?',
    'key.artifact.ARTIFACT_BANK_9.description.long': '보지 말아야 할 아티팩트를 보았습니다. 이제 증인이 되었기 때문에 우리는 당신을 제거해야 할 것입니다.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': '게으른 학생의 시계',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '풍부 타워 재충전 기간 -20 초',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': '본 아티팩트가 있으면 사용후 풍부 타워는 있습니다. 20초 더 빨리 재충전되고 그곳을 더 자주 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': '항상 지각하는 사람의 알람 시계',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '풍부 타워 재충전 기간 -40 초',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': '본 아티팩트가 있으면 사용후 풍부 타워는 40초 더 빨리 재충전되고 그곳을 더 자주 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': '공간 가속기',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '풍부 타워 재충전 기간 -60 초',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': '본 아티팩트가 있으면 사용후 풍부 타워는 60초 더 빨리 재충전되고 그곳을 더 자주 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': '게으른 교수의 시계',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '풍부 타워 재충전 기간 -80 초',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': '본 아티팩트가 있으면 사용후 풍부 타워는 80초 더 빨리 재충전되고 그곳을 더 자주 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': '얼룩말 토끼의 시계',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '풍부 타워 재충전 기간 -100 초',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': '본 아티팩트가 있으면 사용후 풍부 타워는 100초 더 빨리 재충전되고 그곳을 더 자주 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': '정복자의 깃발',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '점령한 후 아레나의 레벨에 +2',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': '본 아티팩트의 주인이 압수 점령된 아레나에 크리처를 놓으면 아레나는 3 레벨 대신에 즉시 5 레벨을 얻습니다.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': '세금 징수원의 반지',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '점령된 아레나 최대량에 +1',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': '본 아티팩트의 주인이 10 아레나 대신에 11 아레나에서 기부금을 걷을 수 있습니다',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': '탐욕의 반지',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '점령된 아레나 최대량에 +2',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': '본 아티팩트의 주인이 10 아레나 대신에 12 아레나에서 기부금을 걷을 수 있습니다',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': '더블 반지',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '기부금을 걷을 수 있는 아레나에 +3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': '본 아티팩트의 주인이 10 아레나 대신에 13 아레나에서 기부금을 걷을 수 있습니다',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': '변변치 못한 사람의 컵',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '연합군 아레나 훈련때 경험에 +20%',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': '본 아티팩트가 있으면 연합군 아레나 및 도서관은 훈련시에 추가로 20 % 경험을 받습니다.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': '꿀단지',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '연합군 아레나 훈련때 경험에 +30%',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': '본 아티팩트가 있으면 연합군 아레나 및 도서관은 훈련시에 추가로 30 % 경험을 받습니다.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': '깊은 생각의 그릇',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '연합군 아레나 훈련때 경험에 +40%',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': '본 아티팩트가 있으면 연합군 아레나 및 도서관은 훈련시에 추가로 40 % 경험을 받습니다.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': '랜셀로프의 성배',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '연합군 아레나 훈련때 경험에 +50%',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': '본 아티팩트가 있으면 연합군 아레나 및 도서관은 훈련시에 추가로 50 % 경험을 받습니다.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': '괴물 정복자의 컵',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '연합군 아레나 훈련때 경험에 +80%',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': '본 아티팩트가 있으면 연합군 아레나 및 도서관은 훈련시에 추가로 80 % 경험을 받습니다.',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': '맑은 시력의 토템',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': '레이더에서 약한 크리처를 제거합니다',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': '본 아티팩트가 레이더에서 약한 크리처를 제거합니다. 강한 크리처를 찾기에 집중하는 데 도움이 됩니다',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': '모험자',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '적으로 점령된 아레나 기부금을 걷기에 +15 분',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': '본 아티팩트가 있으면 아레나는 일반적인 15 분 대신에 포획된 후 30 분 후에 기부금을 걷기 위해 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': '두꺼운 책',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '적으로 점령된 아레나 기부금을 걷기에 +30 분',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': '본 아티팩트가 있으면 아레나는 일반적인 15 분 대신에 포획된 후 40 분 후에 기부금을 걷기 위해 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': '클레임 표',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '적으로 점령된 아레나 기부금을 걷기에 +45 분',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': '본 아티팩트가 있으면 아레나는 일반적인 15 분 대신에 포획된 후 60 분 후에 기부금을 걷기 위해 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': '이사회에서의 논문',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '적으로 점령된 아레나 기부금을 걷기에 +75 본',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': '본 아티팩트가 있으면 아레나는 일반적인 15 분 대신에 포획된 후 90 분 후에 기부금을 걷기 위해 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': '힘의 그림',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '적으로 점령된 아레나 기부금을 걷기에 +105 분',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': '본 아티팩트가 있으면 아레나는 일반적인 15 분 대신에 포획된 후 120 분 후에 기부금을 걷기 위해 사용할 수 있습니다.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': '스파이크 칼라',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '애완 동물에게서 영혼의 돌을 얻기에 10% 가속',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': '본 아티팩트가 있으면 영혼의 돌을 얻으려면 애완 동물과의 거리를 10% 덜 가야 합니다. 또한 애완 동물을 17% 더 위협적으로 만듭니다.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': '막대기에 당근',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '애완 동물에게서 영혼의 돌을 얻기에 15% 가속',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': '본 아티팩트가 있으면 영혼의 돌을 얻으려면 애완 동물과의 거리를 15% 덜 가야 합니다. 맛이 있네요',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': '등을 긁기',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '애완 동물에게서 영혼의 돌을 얻기에 25% 가속',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': '본 아티팩트가 있으면 영혼의 돌을 얻으려면 애완 동물과의 거리를 25% 덜 가야 합니다.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': '애완 동물의 종',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '애완 동물에게서 영혼의 돌을 얻기에 30% 가속',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': '본 아티팩트가 있으면 영혼의 돌을 얻으려면 애완 동물과의 거리를 30% 덜 가야 합니다. 멋있는 크리처는 누구입니까?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': '봉제 용',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '애완 동물에게서 영혼의 돌을 얻기에 40% 가속',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': '본 아티팩트가 있으면 영혼의 돌을 얻으려면 애완 동물과의 거리를 40% 덜 가야 합니다. 세계 최고의 애완 동물을 위한 최고의 장난감',
    'key.artifact.ARTIFACT_ROOST_1': '용의 심장',
    'key.artifact.ARTIFACT_ROOST_1.description': '용의 어머니 +1 용의 고치',
    'key.artifact.ARTIFACT_ROOST_1.description.long': '용의 어머니에 추가 용의 고치를 사용 가능',
    'dialog.artifact.select_artifact': '아티팩트를 선택하기',
    'dialog.artifact.confirm.remove': '정말 이 아티팩트를 제거하시겠어요?',
    'dialog.items.title': '가방',
    'dialog.items.cannotUse': '본 액세서리를 사용할 수 없습니다.',
    'dialog.items.remove.header': '액세서리를 제거',
    'dialog.encounter.header': '야생 몬스터가 공격 중입니다!',
    'dialog.encounter.button.leave': '도망가기',
    'dialog.encounter.button.fight': '전투하기',
    'dialog.encounter.result.outcome.win': '야생 몬스터를 패배시켰습니다',
    'dialog.encounter.result.outcome.lose': '귀하의 크리처를 패배시켰습니다',
    'dialog.encounter.result.reward.dust': '에센스',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': '캐릭터의 이름을 입력해야 합니다',
    'error.nickname.validation.TOO_SHORT': '이름은 3부터 16까지 문자가 포함되어야 합니다',
    'error.nickname.validation.TOO_LONG': '이름은 3부터 16까지 문자가 포함되어야 합니다',
    'error.nickname.validation.INVALID_CHAR': '라틴 문자, 숫자 및 밑줄을 사용할 수 있습니다',
    'error.nickname.validation.DUPLICATE': '선택한 이름이 이미 사용되었습니다.{0}이름을 사용할 수 있습니다.',
    'creature.MONSTER_WATER_1': '프로구스',
    'creature.MONSTER_WATER_2': '드리블',
    'creature.MONSTER_WATER_3': '스피리투스',
    'creature.MONSTER_WATER_4': '오베라킈안',
    'creature.MONSTER_WATER_5': '프로기씨모',
    'creature.MONSTER_WATER_6': '스프린클',
    'creature.MONSTER_WATER_7': '켈피',
    'creature.MONSTER_WATER_8': '젤리헷',
    'creature.MONSTER_WATER_9': '미노리',
    'creature.MONSTER_WATER_10': '인팔리스크',
    'creature.MONSTER_WATER_11': '메디아킈안',
    'creature.MONSTER_WATER_12': '다다춤',
    'creature.MONSTER_WATER_13': '바토이드',
    'creature.MONSTER_WATER_14': '푸에롤리스크',
    'creature.MONSTER_WATER_15': '팔호',
    'creature.MONSTER_WATER_16': '텐타헷',
    'creature.MONSTER_WATER_17': '운데라킈안',
    'creature.MONSTER_WATER_18': '다다촉크',
    'creature.MONSTER_WATER_19': '만타리',
    'creature.MONSTER_WATER_20': '바실리스크',
    'creature.MONSTER_WATER_21': '멜호',
    'creature.MONSTER_WATER_22': '크리스탈헷',
    'creature.MONSTER_WATER_23': '아모란크',
    'creature.MONSTER_WATER_24': '해왕성',
    'creature.MONSTER_WATER_25': '레비아단',
    'creature.MONSTER_FIRE_1': '포티',
    'creature.MONSTER_FIRE_2': '무미웨엔',
    'creature.MONSTER_FIRE_3': '스테암팔',
    'creature.MONSTER_FIRE_4': '인쿠무스',
    'creature.MONSTER_FIRE_5': '파이어파우',
    'creature.MONSTER_FIRE_6': '플라미',
    'creature.MONSTER_FIRE_7': '포비',
    'creature.MONSTER_FIRE_8': '둠미윈',
    'creature.MONSTER_FIRE_9': '라비온',
    'creature.MONSTER_FIRE_10': '헬세일러',
    'creature.MONSTER_FIRE_11': '스파크',
    'creature.MONSTER_FIRE_12': '키드라',
    'creature.MONSTER_FIRE_13': '대몬스타',
    'creature.MONSTER_FIRE_14': '피닉스',
    'creature.MONSTER_FIRE_15': '니들레혿',
    'creature.MONSTER_FIRE_16': '아이언 가이',
    'creature.MONSTER_FIRE_17': '파이어플라이',
    'creature.MONSTER_FIRE_18': '시저',
    'creature.MONSTER_FIRE_19': '블레이즈',
    'creature.MONSTER_FIRE_20': '플리부스투스',
    'creature.MONSTER_FIRE_21': '템퍼',
    'creature.MONSTER_FIRE_22': '히드라',
    'creature.MONSTER_FIRE_23': '설루트',
    'creature.MONSTER_FIRE_24': '피카룬',
    'creature.MONSTER_FIRE_25': '스모아그',
    'creature.MONSTER_EARTH_1': '배리딜로',
    'creature.MONSTER_EARTH_2': '플로위',
    'creature.MONSTER_EARTH_3': '리프렛',
    'creature.MONSTER_EARTH_4': '브라우니',
    'creature.MONSTER_EARTH_5': '샤무프',
    'creature.MONSTER_EARTH_6': '드랴드',
    'creature.MONSTER_EARTH_7': '플란틱',
    'creature.MONSTER_EARTH_8': '디스구르',
    'creature.MONSTER_EARTH_9': '벨플로우',
    'creature.MONSTER_EARTH_10': '아코늘링',
    'creature.MONSTER_EARTH_11': '필로',
    'creature.MONSTER_EARTH_12': '브라그',
    'creature.MONSTER_EARTH_13': '프린시',
    'creature.MONSTER_EARTH_14': '홉베아',
    'creature.MONSTER_EARTH_15': '다오',
    'creature.MONSTER_EARTH_16': '트롤',
    'creature.MONSTER_EARTH_17': '돤트플로우',
    'creature.MONSTER_EARTH_18': '찹피안',
    'creature.MONSTER_EARTH_19': '가드라그',
    'creature.MONSTER_EARTH_20': '스프린간',
    'creature.MONSTER_EARTH_21': '땅에서 태어인',
    'creature.MONSTER_EARTH_22': '파라비스트',
    'creature.MONSTER_EARTH_23': '요기',
    'creature.MONSTER_EARTH_24': '그렌들',
    'creature.MONSTER_EARTH_25': '스킬라',
    'creature.MONSTER_WIND_1': '순티지',
    'creature.MONSTER_WIND_2': '귀박쥐',
    'creature.MONSTER_WIND_3': '슈루미',
    'creature.MONSTER_WIND_4': '플라피코느',
    'creature.MONSTER_WIND_5': '아이버',
    'creature.MONSTER_WIND_6': '가마윤',
    'creature.MONSTER_WIND_7': '으스스인',
    'creature.MONSTER_WIND_8': '인피루스',
    'creature.MONSTER_WIND_9': '에스키모',
    'creature.MONSTER_WIND_10': '윈단스',
    'creature.MONSTER_WIND_11': '인피르드',
    'creature.MONSTER_WIND_12': '운디네',
    'creature.MONSTER_WIND_13': '애리코느',
    'creature.MONSTER_WIND_14': '판토모',
    'creature.MONSTER_WIND_15': '체셔',
    'creature.MONSTER_WIND_16': '슈루미토피아',
    'creature.MONSTER_WIND_17': '하피',
    'creature.MONSTER_WIND_18': '그호스투스',
    'creature.MONSTER_WIND_19': '푸에로그리프',
    'creature.MONSTER_WIND_20': '필로겟',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': '스토므디네',
    'creature.MONSTER_WIND_23': '그리핀',
    'creature.MONSTER_WIND_24': '바윤',
    'creature.MONSTER_WIND_25': '카리브디스',
    'creature.MONSTER_DUNGEON_1': '루키',
    'creature.MONSTER_DUNGEON_2': '악솔란',
    'creature.MONSTER_DUNGEON_3': '스파이크배그',
    'creature.MONSTER_DUNGEON_4': '마그글라드',
    'creature.MONSTER_DUNGEON_5': '귀여운겟',
    'creature.MONSTER_DUNGEON_6': '로지',
    'creature.MONSTER_DUNGEON_7': '마리드',
    'creature.MONSTER_DUNGEON_8': '그란달로들',
    'creature.MONSTER_DUNGEON_9': '허수아비',
    'creature.MONSTER_DUNGEON_10': '스나일린',
    'creature.MONSTER_DUNGEON_11': '스나일린',
    'creature.MONSTER_DUNGEON_12': '뱀파이어',
    'creature.MONSTER_DUNGEON_13': '애드와이즈',
    'creature.MONSTER_DUNGEON_14': '만티키드',
    'creature.MONSTER_DUNGEON_15': '트위스트',
    'creature.MONSTER_DUNGEON_16': '소프타일',
    'creature.MONSTER_DUNGEON_17': '이누르',
    'creature.MONSTER_DUNGEON_18': '드라쿨',
    'creature.MONSTER_DUNGEON_19': '아브솔러므',
    'creature.MONSTER_DUNGEON_20': '타이거만드',
    'creature.MONSTER_DUNGEON_21': '샤프타일',
    'creature.MONSTER_DUNGEON_22': '로즈버드',
    'creature.MONSTER_DUNGEON_23': '컬리',
    'creature.MONSTER_DUNGEON_24': '만티코레',
    'creature.MONSTER_DUNGEON_25': '모고로트',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': '상어에게 물린 것',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': '깊이 있는 공포',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': '크툴루의 부름',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': '해양의 해머',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': '물의 주먹',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': '물결',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': '소나기',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': '간헐천',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': '물보라',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': '살아있는 파이어',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': '파이어 심판',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': '파이어 채찍',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': '파이어 볼',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': '버너',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': '별',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': '석탄',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': '화염방사기',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': '총살',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': '공기의 낫',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': '브레이커',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': '호흡',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': '전기쇼크',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': '구상번개',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': '충격요법',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': '용의 호흡',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': '미풍',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': '바람의 분노',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': '독침',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': '뱀의 송곳니',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': '중독',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': '등뼈 브레이커',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': '록',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': '자갈',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': '숲의 정신',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': '나무 유령',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': '자연의 그림자',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': '아르카나의 화살표',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': '어둠의 혈전',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': '악의 촉수',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': '공포의 눈',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': '파멸의 볼',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': ' 어둠의 볼',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': '아르카나 카다브라',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': '크루스시아쿠스',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': '임페리카누스',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': '빙하작용',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': '냉동',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': '결정화',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': '월풀',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': '큰 눈보라',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': '해일',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': '싸늘한 분노',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': '한바탕 부는 칼바람',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': '얼음의 힘',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': '클렌징',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': '올리는 것',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': '소성',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': '네이팜',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': '용암',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': '화천',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': '유성',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': '디노시데',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': '아마겟돈',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': '번개',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': '우레',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': '폭풍',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': '오버로딩',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': '전기장',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': '머리털이 곤두섰다',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': '토네이도',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': '바람 소리',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': '캐러셀',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': '쿵쾅',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': '진동',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': '균열',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': '난파',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': '폭파',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': '돌개바람',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': '죽음의 호수',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': '유독한 웅덩이',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': '산성',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': '원자화',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': '분해',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': '이온화',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': '망명',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': '저주',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': '파문',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': '마법의 폭풍',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': '마나폭풍우',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': '아르카나의 분노',
    'key.combined.first.1': '현명한',
    'key.combined.first.2': '지옥과 같은',
    'key.combined.first.3': '아름다운',
    'key.combined.first.4': '표독스러운',
    'key.combined.first.5': '중립의',
    'key.combined.first.6': '정직한',
    'key.combined.first.7': '성도',
    'key.combined.first.8': '고대',
    'key.combined.first.9': '지하',
    'key.combined.first.10': '불의',
    'key.combined.first.11': '교활한',
    'key.combined.first.12': '거대한',
    'key.combined.first.13': '푸른',
    'key.combined.first.14': '잔혹한',
    'key.combined.first.15': '친절한',
    'key.combined.first.16': '공기의',
    'key.combined.first.17': '흙의',
    'key.combined.first.18': '레드',
    'key.combined.first.19': '무궁한',
    'key.combined.first.20': '죽은',
    'key.combined.first.21': '공기의',
    'key.combined.first.22': '무서운',
    'key.combined.first.23': '물의',
    'key.combined.first.24': '즐거운',
    'key.combined.first.25': '바보 같은',
    'key.combined.second.1': '영웅',
    'key.combined.second.2': '물고기',
    'key.combined.second.3': '올빼미',
    'key.combined.second.4': '악당',
    'key.combined.second.5': '미니언',
    'key.combined.second.6': '마술사',
    'key.combined.second.7': '노인',
    'key.combined.second.8': '캐스터',
    'key.combined.second.9': '무인',
    'key.combined.second.10': '결투자',
    'key.combined.second.11': '상인',
    'key.combined.second.12': '토끼',
    'key.combined.second.13': '사과',
    'key.combined.second.14': '파이터',
    'key.combined.second.15': '요술쟁이',
    'key.combined.second.16': '기사',
    'key.combined.second.17': '야만인',
    'key.combined.second.18': '딱정벌레',
    'key.combined.second.19': '뱀',
    'key.combined.second.20': '용',
    'key.combined.second.21': '유령',
    'key.combined.second.22': '물개',
    'key.combined.second.23': '병사',
    'key.combined.second.24': '행운아',
    'key.combined.second.25': '암살자',
    'key.combined.second.26': '쥐',
    'key.combined.second.27': '엘레멘탈',
    'key.combined.second.28': '연구원',
    'key.combined.second.29': '무당',
    'key.combined.second.30': '성직자',
    'key.combined.second.31': '천사',
    'key.combined.second.32': '아르콘',
    'key.combined.second.33': '형리',
    'key.combined.second.34': '바보',
    'key.combined.second.35': '용자',
    'key.combined.second.36': '호인',
    'key.combined.second.37': '겁쟁이',
    'key.combined.second.38': '시인',
    'key.combined.second.39': '조련사',
    'key.combined.second.40': '수비수',
    'key.combined.arena': '{0} {1}의 아레나',
    'key.combined.library': '{0} {1}의 도서관',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': '물',
    'element.type.WIND': '바람',
    'element.type.FIRE': '불',
    'element.type.EARTH': '지구',
    'element.type.DUNGEON': '아르카나',
    'spell.type.ACTIVATION_RADIUS': '활성화 반지름',
    'spell.type.VISION_RADIUS': '용의 시력',
    'spell.type.STOP_FIELD': '풍부 들판',
    'spell.type.SCOUT': '정찰',
    'spell.type.PROTECT_ARENA': '아레나의 보호',
    'spell.type.CREATE_PORTAL': '포털 만들기',
    'spell.type.ARMAGEDDON': '아마겟돈',
    'spell.type.DOUBLE_DROP': '더블 드롭',
    'spell.type.SLUG_PLAYERS': 'SLUG_PLAYERS',
    'quest.title.WIN_ARENA_MONSTER': '지배',
    'quest.title.OPEN_EGGS': '알의 열',
    'quest.title.COLLECT_ARENA_TRIBUTE': '지역 통제',
    'quest.title.CAPTURE_LIBRARY': '지식을 향한 갈증',
    'quest.title.CAPTURE_WILD_MONSTER': '용시대의 공원',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': '요소 사냥',
    'quest.title.FIND_DUNGEON_WITH_ROOST': '아르카나에 태어난 사람을 검색',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': '균열 제거',
    'quest.title.OPEN_CHEST': '고대 보물',
    'quest.title.CHAIN_OF_STOP': '풍부길',
    'quest.desc.WIN_ARENA_MONSTER': '아레나 또는 도서관에 크리처를 무찌르세요. 같은 크리처를 한 번만 무찌를 수 있습니다.',
    'quest.desc.OPEN_EGGS': '용의 고치나 용의 어머니의 도움으로 알에서 크리처를 품으십시오.',
    'quest.desc.COLLECT_ARENA_TRIBUTE': '점령된 아레나에서 기부금을 걷으세요',
    'quest.desc.CAPTURE_LIBRARY': '어떤 새로운 도서관을 당신의 크리처의 보호자로 만드십시오.',
    'quest.desc.CAPTURE_WILD_MONSTER': '크리처를 너무 많이 가질 수 없습니다. 여행을 하고 크리처를 포획하세요',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': '여행을 하고 물의 크리처를 포획하세요',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': '여행을 하고 바람의 크리처를 포획하세요',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': '여행을 하고 불의 크리처를 포획하세요',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': '여행을 하고 지구의 크리처를 포획하세요',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': '여행을 하고 크리처를 포획하세요',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': '용의 어머니가 있는 아르카나 균열에 가세요',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': '아르카나 균열에 가서 당신이 찾은 모든 크리처를 잡으세요',
    'quest.desc.OPEN_CHEST': '보물 가슴을 찾아 열어 주세요',
    'quest.desc.CHAIN_OF_STOP': '풍부 타워의 사슬을 걸치세요. 각각의 다음 타워가 강조 표시됩니다.표시됩니다.',
    'quest.dialog.completed.rewardtext': '보상:',
    'key.tab.altar.title': '제단',
    'key.altar.remove': '제거하기',
    'key.altar.put': '설치하기',
    'key.altar.convert': '변환하기',
    'key.altar.shared': '다른 플레이어에게 보여주기',
    'key.altar.pass.placeholder': '여기에 암호를 입력 할 수 있습니다',
    'key.altar.pass.error': '암호는 {0}문자 이상 포함되어야 합니다',
    'key.altar.level.error': '제단을 사용하기 위해 {0}레벨을 달성해야 합니다',
    'key.altar.recipe.change': '레시피를 변경하시겠습니까? 룬 문자는 소유자에게 반환됩니다.',
    'key.altar.row.title': '주문을 걸기 위해 제단을 얹어야 합니다',
    'key.altar.rune.descr.RUNE_1': '3 녹색의 룬 문자 = 오렌지색의 룬 문자',
    'key.altar.rune.descr.RUNE_2': '3 오렌지색의 룬 문자 = 파란색의 룬 문자',
    'key.altar.rune.descr.RUNE_3': '3 파란색의 룬 문자 = 에메랄드색의 룬 문자',
    'key.altar.rune.descr.RUNE_4': '3 에메랄드색의 룬 문자 = 빨간색의 룬 문자',
    'key.altar.rune.descr.RUNE_5': '3 빨간색의 룬 문자 = 보라색의 룬 문자',
    'key.altar.rune.descr.RUNE_6': '보라색의 룬 문자는 가장 강합니다',
    'error.altar.cannotRemove': '제단을 제거할 수 없습니다',
    'error.altar.cannotConvert': '룬 문자가 부족합니다',
    'key.tab.altar.recipes': '레시피',
    'key.altar.noRecipes': '레시피가 없습니다',
    'key.altar.header': '주문을 걸기 위해 룬 문자를 제단에 놓으십시오',
    'key.altar.castBtn': '주문을 걸기',
    'key.altar.recipe.select': '필요한 주문을 선택하세요',
    'key.altar.castDone': '주문이 만들어졌습니다',
    'key.arena.protected.ally': '보호',
    'key.avatarCustomization.title': '캐릭터의 외관을 선택하세요',
    'key.buddy.walkDescription': '{0}받으려면 애완 동물과 함께 걷으세요',
    'key.buddy.totalWalked': '{0}킬로미터 이미 이동했습니다',
    'key.account.balance': '자원:',
    'key.account.userLevel': '{0} 레벨',
    'key.account.totalDistance': '이동 거리: {0}킬로미터',
    'key.acount.registerDate': '게임 시작: {0}',
    'key.storage.sort.name': '이름',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': '녹색 목록',
    'key.storage.sort.group2': '황색 목록',
    'key.storage.sort.group3': '적색 목록',
    'key.storage.sort.date': '날짜',
    'key.account.options.jurnal': '잡지',
    'key.account.options.buddy': '애완 동물',
    'key.account.options.artifacts': '아티팩트',
    'key.account.options.style': '외관',
    'key.error.gps.permission': 'GPS를 사용 할 수 없습니다. 게임을 계속하기 위해 응용 프로그램 설정에서 GPS에 대한 액세스를 가능하게 하십시오.',
    'key.error.gps.disabled': 'GPS 비활성화됩니다.게임을 계속하기 위해 GPS에 대한 액세스를 가능하게 하십시오.',
    'key.error.gps.fakePosition': 'GPS 없이 플레이할 수 없습니다',
    'key.error.gps.signal.notFound': 'GPS 신호 없음',
    'key.error.gps.signal.bad': '게임할 수 없습니다. 약한 GPS 신호입니다',
    'key.error.internet.notReachable': '인터넷에 연결되어 있지 않습니다.',
    'key.journal.title': '잡지',
    'key.journal.yesterday': '어제',
    'key.settings.title': '설정',
    'key.settings.music': '음악',
    'key.settings.deviceAuthError': 'For safety reasons, please link your account to Google or Facebook',
    'key.settings.sounds': '소리',
    'key.settings.vibration': '진동',
    'key.settings.batterySaver': '에너지 보존',
    'key.settings.support': '고객센터',
    'key.settings.logout': '로그아웃',
    'key.settings.auth.deviceid': '장치 아이디',
    'key.settings.auth.google': '구글',
    'key.settings.auth.facebook': '페이스북',
    'key.settings.auth.link': '연결하기',
    'key.settings.languageTitle': '언어',
    'key.settings.language': '한국어',
    'key.battle.result.win': '전투가 끝났습니다',
    'key.battle.result.lose': '전투가 끝났습니다',
    'key.wizardBattle.result.win': '승리!',
    'key.wizardBattle.result.lose': '패배!',
    'key.battle.result.monster': '패배한 크리처',
    'key.battle.result.exp': '받는 경험',
    'key.battle.result.prestige_strong_enemy': '강력한 적을 위한 명성의 보너스',
    'key.battle.result.exp_strong_enemy': '강력한 적을 위한 명성의 보너스',
    'key.battle.result.prestige_killed_all': '모두를 물리친 명성의 보너스',
    'key.battle.result.exp_killed_all': '모두를 물리친 경험의 보너스',
    'key.battle.result.dust': '에센스',
    'key.radar.title': '주변의 크리처',
    'key.levelUp.title': '새로운 레벨',
    'key.wizardBattle.left': '전투의 제한',
    'key.wizardBattle.timer': '전투의 제한은 재설정까지',
    'key.wizardBattle.enhance.title': '제한의 증가',
    'key.wizardBattle.enhance.desc': '일주일간 하루에 7번까지 전투의 제한을 증가할 수 있습니다',
    'key.wizardBattle.enhance.btn': '증가하기',
    'key.wizardBattle.lookingForOpponent': '결투 상대 검색중',
    'key.catch.result.expMonster': '캡처 경험',
    'key.catch.result.expMonsterNew': '동물 우화의 새로운 생명체:',
    'key.catch.result.expAccurate': '정확한 전진을 위해',
    'key.catch.result.expSpin': '뒤틀린 전진을 위해',
    'key.catch.result.strike': '오늘의 첫 크리처',
    'key.catch.result.total': '총 경험',
    'key.catch.fullStorage': '크리처 저장소가 가득 찼습니다',
    'key.catch.noItems': '매직 볼이 없습니다',
    'key.creadex.title': '동물 우화집',
    'key.creadex.detail.caught': '잡음:{0}',
    'key.creadex.detail.evolution': '진화',
    'key.tab.doll': '캐릭터',
    'key.tab.artifacts': '아티팩트',
    'key.activePoint.title': '풍부 타워',
    'key.personalization.title': '마법에 걸음',
    'key.chest.title': '마법의 가슴',
    'key.quest.daily.title': '퀘스트',
    'key.quest.weekly.title': '사냥',
    'key.quest.get': '퀘스트를 얻기',
    'key.quest.change': '퀘스트를 바꾸기',
    'key.quest.progress': '퀘스트 진행: {1}에서 {0}',
    'key.error.quest.weekly.level': '황금알의 사냥을 시작하기 위해 {0}레벨을 달성해야 합니다',
    'key.error.quest.daily.level': '퀘스트를 얻기 위해 {0}레벨을 달성해야 합니다',
    'key.error.quest.tooFar': '오벨리스크가 아직 멀리있습니다',
    'key.quest.daily.descr.noQuest.title': '퀘스트가 없습니다.',
    'key.quest.daily.descr.noQuest': '퀘스트와 보상을 얻기 위해 오벨리스크를 사용하세요',
    'key.quest.daily.timer.descr': '퀘스트를 변경까지',
    'key.quest.daily.waitForNew.descr': '새로운 퀘스트 해제: ',
    'key.quest.weekly.getFragment': '조각을 얻기',
    'key.quest.weekly.descr.noQuest.title': '황금알의 사냥에 참여하지 않습니다',
    'key.quest.weekly.descr.noQuest': '신비한 지도의 조각을 얻고 사냥을 시작하기 위해 오벨리스크를 사용하세요',
    'key.quest.weekly.descr.getFirstFragment': '사냥을 시작하기 위해 신비한 지도의 첫째 조각을 얻으세요',
    'key.quest.weekly.descr.top.notAllOpen': '사냥 끝까지 지도의 조각을 얻기 위해 오벨리스크를 사용하세요. 사냥 끝까지:',
    'key.quest.weekly.descr.bot.notAllOpen.menu': '황금알을 발견 하기 위해 각 조각에 삽을 사용하세요',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': '본 오벨리스크의 지도에서 조각을 이미 받았습니다',
    'key.quest.weekly.descr.top.allOpen': '오벨리스크에서 모든 지도의 조각을 이미 받았습니다. 사냥 끝까지:',
    'key.quest.weekly.descr.bot.allOpen': '황금알을 발견 하기 위해 각 조각에 삽을 사용하세요',
    'key.quest.weekly.descr.top.completed': '이번 주에 이미 황금알을 발견했습니다. 다음 사냥이 시작까지:',
    'key.timer.format.S': '{0}초',
    'key.timer.format.M': '{0}분',
    'key.timer.format.M_S': '{0}분 {0}초',
    'key.timer.format.H': '{0}시',
    'key.timer.format.H_M': '{0}시 {0}분',
    'key.timer.format.D': '{0}일',
    'key.timer.format.D_H': '{0}일 {0}시',
    'key.creatureStorage.tab.creatures': '크리처',
    'key.creatureStorage.tab.eggs': '알',
    'key.creatureStorage.multiTransferText': '놓아주고 싶은 크리처를 선택하기',
    'key.storage.creature.transfer': '({0})를 놓아주기',
    'key.error.needHigherLevelForArena': '아레나에 나오기 위해 {0}레벨이 필요합니다',
    'key.error.needHigherLevelForLibrary': '도서관에 나오기 위해 {0}레벨이 필요합니다',
    'key.error.arenaUnderProtection': '보호의 축복의 보호를 받고 있습니다',
    'key.error.buildingTooFar': '건물이 아직 멀리있습니다',
    'key.error.noAliveCreaturesForAttack': '살아있는 크리처가 없습니다',
    'key.error.noHealPotion': '치유 물약이 없습니다',
    'key.error.noResurrectionPotion': '부활 물약이 없습니다',
    'key.error.tryAgainLater': '오류. 나중에 다시 시도하십시오.',
    'key.error.alreadyHasLure': '미끼는 이미 설치되었습니다',
    'key.error.cannotUseLureInDungeon': '미끼는 아르카나의 균열에서 사용할 수 없습니다',
    'key.error.bagIsFull': '가방에 장소가 없습니다',
    'key.error.cantTransferCreature': '본 크리처를 놓아줄 수 없습니다',
    'key.notification.done': '완성!',
    'key.modal.doYouWantToTransfer': '본 크리처를 놓아주시겠습니까?',
    'key.modal.youWillLoseBuddyProgress': '애완 동물을 바꾸시겠습니까? 이 경우에 영혼의 돌을 얻기의 진행 상태가 사라집니다',
    'key.modal.doYouWantToLeaveDungeon': '아르카나 균열을 떠나시겠습니까?',
    'key.modal.superVisionActive': '용의 시력은 이미 활성화되었습니다. 반복 사용하면 마법 구역 가시성을 바뀝니다. 반복 사용하시겠습니까?',
    'key.modal.experienceBoosterActive': '지혜의 크리스탈은 이미 활성화되었습니다. 그것을 반복 사용하시겠습니까?',
    'key.modal.youWillLooseQuestProgress': '현재 퀘스트의 진행 상태가 사라집니다. 괜찮습니까?',
    'key.modal.doYouWantToEnterDungeon': '포털을 통해 아르카나 균열에 들어가고 싶습니까?',
    'key.modal.doYouWantPersonalizePoint': '{0}를 {1}동전 발행을 위해 풍부 타워에 마법을 걸고 싶습니까?',
    'key.modal.doYouWantToDeletePersonalization': '본 풍부 타워에 마법 거는 것을 취소하고 싶습니까?',
    'key.modal.doYouWantToPowerUpThisCreature': '본 크리처를 강화하시겠습니까?',
    'key.modal.doYouWantToEvolveThisCreature': '본 크리처를 강하게 만들고 싶습니까?',
    'key.modal.doYouWantToScoutHere': '본 구역을 공개하시겠습니까?',
    'key.error.creatureHasMaxLevel': '본 크리처는 이미 최대 레벨입니다',
    'key.error.creatureHasMaxLevelForUser': '먼저 캐릭터 레벨을 증가시켜야 합니다',
    'key.error.notEnoughResourcesForEnhance': '자원이 부족합니다',
    'key.error.creatureIsArenaDefender': '건물을 보호하는 크리처를 선택할 수 없습니다',
    'key.modal.incenseActive': '페로몬은 이미 활성화되었습니다. 그것을 반복 사용하시겠습니까?',
    'key.error.cantHealHealthyCreature': '크리처는 완전히 회복되었습니다',
    'key.error.cantRessurectAliveCreature': '본 크리처는 이미 살아있습니다',
    'key.error.noTreasureHere': '본 지도의 조각에 황금알이 없습니다. 계속 검색하세요',
    'key.error.levelTooSmall': '먼저 캐릭터 레벨을 증가시켜야 합니다',
    'key.error.needHigherLevelForWizardBattles': '마술사 결투에 참여하기 위해 {0} 레벨을 달성해야 합니다',
    'key.error.artifactBagIsFull': '아티팩트 저장소에 장소가 없습니다',
    'key.error.notEnoughCoins': '동전이 부족합니다',
    'key.error.allFragmentsAreOpen': '신비한 지도의 모든 조각은 열려 있습니다',
    'key.error.questAlreadyCompleted': '퀘스트는 이미 완료되었습니다',
    'key.error.alreadyGotFragmentFromThisObelisk': '본 오벨리스크의 지도에서 조각을 이미 받았습니다',
    'key.error.portalTooFarAway': '포털은 너무 멀리있습니다',
    'key.error.battleLimitAlreadyEnhanced': '전투 제한을 이미 증가했습니다',
    'key.error.youAreNotAltarOwner': '제단의 소유자만 할 수 있습니다',
    'key.error.youAlreadyHaveAltar': '제단은 이미 설치되었습니다',
    'key.error.cantTakeAnotherUsersRune': '다른 플레이어의 룬 문자를 빼앗을 수 없습니다',
    'key.error.libraryBlocked': '도서관을 이용하려면 재훈련 후 3 일을 기다려야 합니다',
    'key.error.notAuthorized': '사용자가 승인되지 않았습니다',
    'key.error.eggOnlyRoost': '본 알을 용의 어머니에게 줄 필요가 있습니다',
    'key.error.purchase': '오류: {0}',
    'key.error.creatureIsDead': '먼저 크리처를 부활시켜야 합니다',
    'key.error.no_connection': '서버에 연결할 수 없습니다.나중에 다시 시도하십시오.',
    'key.error.protocol_version_mismatch': '게임 버전은 더 이상 사용되지 않습니다. 업데이트가 필요합니다.',
    'key.error.update_application': '게임 버전은 더 이상 사용되지 않습니다. 업데이트가 필요합니다.',
    'key.modal.doYouWantToTransferSingle': '본 크리처를 놓아주시겠습니까?',
    'key.notification.phoneNotSupportAR': '이 기기는 AR을 지원하지 않습니다.',
    'key.notification.turnOnARPermission': '게임은 카메라에의 접근이 없습니다. 장치 설정에서 액세스를 활성화해야합니다',
    'key.notification.dailyQuestFinished': '퀘스트 완수!',
    'key.modal.yesBtn': '예',
    'key.modal.noBtn': '아니요',
    'event.log.DAILY_QUEST_COMPLETED': '오늘의 퀘스트가 완료되었습니다. 접수된 보상:',
    'event.log.WEEKLY_QUEST_COMPLETED': '사냥을 완료했습니다. 보상을 받았습니다:',
    'event.log.ENCOUNTER_VICTORY': '야생 몬스터를 패배시켰습니다',
    'key.ServiceException.Cause.OLD_CLIENT': '게임 버전은 더 이상 사용되지 않습니다. 업데이트가 필요합니다.',
    'key.ServiceException.Cause.AUTH_ERROR': '입증 오류',
    'key.ServiceException.Cause.SESSION_GONE': '다른 기기에서 사용자 계정으로 로그인했습니다',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': '사용자 아이디가 비어 있습니다',
    'key.ServiceException.Cause.USER_NOT_FOUND': '사용자를 찾을 수 없음',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': '사기성 게임으로 인해 계정이 차단되었습니다',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': '사기성 지불로 인해 계정이 차단되었습니다',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': '악의적인 사용자 이름으로 인해 계정이 차단되었습니다',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': '다른 플레이어와의 적극적인 커뮤니케이션으로 인해 계정이 차단되었습니다',
    'key.ServiceException.Cause.USER_BANNED.Cheating': '사기성 게임으로 인해 계정이 차단되었습니다',
    'key.ServiceException.Cause.USER_BANNED': '계정이 차단되었습니다',
    'key.ServiceException.Cause.BAG_IS_FULL': '가방에 장소가 없습니다',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': '알의 최대 수',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': '동전이 부족합니다',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': '영혼의 돌이 부족합니다',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': '에센스가 부족합니다',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': '크리처 저장소에 장소가 없습니다',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': '본 크리처는 이미 최대 레벨입니다',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': '본 크리처를 발달시킬 수 없습니다',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': '크리처의 이름은 최대 14문자가 포함되어야 합니다',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': '건물은 최대의 보호자를 가지고 있습니다',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': '건물의 보호자는 애완 동물이 될 수 없습니다',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': '당신의 크리처가 이미 본 건물을 보호하고 있습니다',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': '오류',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': '전투를  찾을 수 없음',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': '오류',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': '당신의 크리처가 이미 본 건물을 보호하고 있습니다',
    'key.ServiceException.Cause.ARENA_PROTECTED': '아레나는 보호의 축복의 보호를 받고 있습니다',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': '기부금을 걷기까지 시간이 되지 않았습니다',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Wrong sphere',
    'key.ServiceException.Cause.WRONG_BUILDING': '틀린 건물',
    'key.ServiceException.Cause.ACCESS_DENIED': '액세스가 거부되었습니다',
    'key.ServiceException.Cause.NO_SUCH_ITEM': '존재하지 않는 액세서리',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': '존재하지 않는 레시피',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': '한 제단만 설치할 수 있습니다',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': '먼저 캐릭터 레벨을 증가시켜야 합니다',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': '크리처 포획 시작을 실패하였습니다',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': '존재하지 않는 제품',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': '존재하지 않는 제품',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': '존재하지 않는 건물',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': '크리처를 찾을 수 없음',
    'key.ServiceException.Cause.WRONG_CREATURE': '크리처를 찾을 수 없음',
    'key.ServiceException.Cause.TOO_FAR': '건물은 아직 멀리있습니다',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': '물체가 아직 멀리있습니다',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': '건물이 재충전중',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': '건물이 아르카나 균열에 있습니다',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': '건물을 사용할 수 없습니다',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': '용의 고치를 찾을 수 없음',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': '용의 고치가 비어 있습니다',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': '용의 고치가 이미 사용 중입니다',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': '알은 부화되지 않았다',
    'key.ServiceException.Cause.EGG_NOT_FOUND': '알을 찾을 수 없음',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': '본 알을 위해 용의 어머니가 필요합니다',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': '충전이 끝났습니다',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': '건물을 설치할 수 없습니다',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': '오류가 발생했으며 본 신비한 메시지의  내용은 그 오류입니다',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': '야생 몬스터가 도망쳤습니다',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': '야생 몬스터를 찾을 수 없습니다',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': '본 풍부 타워에 미끼가 이미 있습니다',
    'key.ServiceException.Cause.WRONG_ITEM': '잘못된 액세서리',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': '본 룬 문자는 가장 강합니다',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': '이 레벨의 룬 문자가 부족합니다',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': '룬 문자 위해 잘못된 슬롯',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': '슬롯은 이미 사용 중입니다',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': '룬 문자 위해 슬롯 비어 있습니다',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': '건물의 보호자를 선택할 수 없습니다',
    'key.ServiceException.Cause.WRONG_SPELL': '잘못된 주문',
    'key.ServiceException.Cause.NEED_MORE_RUNES': '주문을 위해 더 많은 룬 문자가 필요합니다',
    'key.ServiceException.Cause.QUEST_COOLDOWN': '새 퀘스트를 아직 시작할 수 없습니다',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': '본 오벨리스크를 이미 사용했습니다',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': '지도의 모든 조각은 열려 있습니다',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': '황금알의 사냥에 참여하지 않습니다',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': '이미 본 지역에서 황금알을 찾으려고 했습니다',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': '크리처 진미를 이미 사용했습니다',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': '크리처를 포획됩니다',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': '이미 크리처를 재훈련할 수 없습니다',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': '이미 도서관을 사용할 수 없습니다',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': '기다려야 합니다',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': '전투 제한을 이미 증가했습니다',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': '전투 한계에 도달했습니다',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': '오류: 상대방을 찾을 수 없음',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': '마술사 결투의 상대방을 찾을 수 없음. 나중에 다시 시도하십시오.',
    'key.ServiceException.Cause.MARKET_ERROR': '가게 오류',
    'key.ServiceException.Cause.NO_CHEST': '가슴을 찾을 수 없음',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': '조각을 발행중 오류가 발생했습니다. 나중에 다시 시도하십시오.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': '용의 어머니에게 더 많은 알을 주려면 용의 심장이나 용의 아티팩트 세트를 입어야 합니다',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': '본 세포에 이미 알이 있습니다',
    'key.ServiceException.Cause.NO_CONNECTION': '인터넷에 연결되어 있지 않습니다',
    'key.ServiceException.Cause.SERVER_DOWN': '게임 서버를 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': '유지보수로 게임 서버가 다운 상태입니다. 나중에 다시 시도하세요.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': '본 룬 문자는 이제 사용되고 있습니다',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': '당신은 너무 빨리 움직입니다',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': '점령된 아레나의 한계에 도달했습니다',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': '점령된 도서관의 한계에 도달했습니다',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': '오류:GPS 사용 가능하지 않습니다',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': '이 주문은 아르카나의 균열에서 시전할 수 없습니다',
    'key.ServiceException.Cause.BATTLE_EXPIRED': '전투가 종료되었습니다',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': '오래된 게임 버전입니다. 업데이트가 필요합니다.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': '보이는 지역에 동맹의 경기장이 없습니다',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': '보이는 지역에 적의 경기장이 없습니다',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': '크리처를 잡기 위한 매직 볼',
    'stop.personalized.HEALS': '치료 물약',
    'stop.personalized.RESURRECTIONS': '부활 물약',
    'stop.personalized.EGGS': '크리처의 알',
    'stop.personalized.FOODS': '크리처 진미',
    'key.button.cancelPersonal': '취소',
    'key.error.needHigherLevelForSofaBattles': '마술사 결투에 참여하기 위해 {0} 레벨을 달성해야 합니다',
    'fraction.text.youWilLGetBonus': '본 당파에 합류하기 위해 {0} 동전을 받게됩니다',
    'fraction.text.fractionUnavailable': '지금 당파를 사용할 수 없습니다',
    'fraction.text.chooseYourAlliance': '싸울 당파를 선택하세요',
    'fraction.text.redFractionName': '레드 오더',
    'fraction.text.blueFractionName': '블루 오더',
    'key.error.chestTooFarAway': '가슴이 너무 멀리 있습니다',
    'key.button.openChest': '열기',
    'key.candy.MONSTER_WATER_1': '프로구스의 돌',
    'key.candy.MONSTER_WATER_2': '드리블의 돌',
    'key.candy.MONSTER_WATER_3': '스피리투스의 돌',
    'key.candy.MONSTER_WATER_4': '오베라킈안의 돌',
    'key.candy.MONSTER_WATER_8': '젤리헷의 돌',
    'key.candy.MONSTER_WATER_9': '미노리의 돌',
    'key.candy.MONSTER_WATER_10': '인팔리스크의 돌',
    'key.candy.MONSTER_WATER_12': '다다춤의 돌',
    'key.candy.MONSTER_WATER_13': '바토이드의 돌',
    'key.candy.MONSTER_WATER_23': '아모란크의 돌',
    'key.candy.MONSTER_WATER_24': '해왕성의 돌',
    'key.candy.MONSTER_WATER_25': '레비아단의 돌',
    'key.candy.MONSTER_FIRE_1': '포티의 돌',
    'key.candy.MONSTER_FIRE_2': '무미웨엔의 돌',
    'key.candy.MONSTER_FIRE_3': '스테암팔의 돌',
    'key.candy.MONSTER_FIRE_4': '인쿠무스의 돌',
    'key.candy.MONSTER_FIRE_6': '플라미의 돌',
    'key.candy.MONSTER_FIRE_7': '포비의 돌',
    'key.candy.MONSTER_FIRE_11': '스파크의 돌',
    'key.candy.MONSTER_FIRE_12': '키드라의 돌',
    'key.candy.MONSTER_FIRE_15': '니들레혿의 돌',
    'key.candy.MONSTER_FIRE_25': '스모아그의 돌',
    'key.candy.MONSTER_EARTH_1': '배리딜로의 돌',
    'key.candy.MONSTER_EARTH_2': '플로위의 돌',
    'key.candy.MONSTER_EARTH_3': '리프렛의 돌',
    'key.candy.MONSTER_EARTH_4': '브라우니의 돌',
    'key.candy.MONSTER_EARTH_8': '디스구르의 돌',
    'key.candy.MONSTER_EARTH_9': '벨플로우의 돌',
    'key.candy.MONSTER_EARTH_10': '아코늘링의 돌',
    'key.candy.MONSTER_EARTH_11': '필로의 돌',
    'key.candy.MONSTER_EARTH_13': '프린시의 돌',
    'key.candy.MONSTER_EARTH_25': '스킬라의 돌',
    'key.candy.MONSTER_DUNGEON_1': '루키의 돌',
    'key.candy.MONSTER_DUNGEON_2': '악솔란의 돌',
    'key.candy.MONSTER_DUNGEON_3': '스파이크배그의 돌',
    'key.candy.MONSTER_DUNGEON_4': '마그글라드의 돌',
    'key.candy.MONSTER_DUNGEON_5': '귀여운겟의 돌',
    'key.candy.MONSTER_DUNGEON_6': '로지의 돌',
    'key.candy.MONSTER_DUNGEON_12': '뱀파이어의 돌',
    'key.candy.MONSTER_DUNGEON_13': '애드와이즈의 돌',
    'key.candy.MONSTER_DUNGEON_17': '이누르의 돌',
    'key.candy.MONSTER_WIND_1': '순티지의 돌',
    'key.candy.MONSTER_WIND_2': '귀박쥐의 돌',
    'key.candy.MONSTER_WIND_3': '슈루미의 돌',
    'key.candy.MONSTER_WIND_4': '플라피코느의 돌',
    'key.candy.MONSTER_WIND_6': '가마윤의 돌',
    'key.candy.MONSTER_WIND_7': '으스스인의 돌',
    'key.candy.MONSTER_WIND_11': '인피르드의 돌',
    'key.candy.MONSTER_WIND_12': '운디네의 돌',
    'key.candy.MONSTER_WIND_15': '체셔의 돌',
    'key.candy.MONSTER_WIND_25': '카리브디스의 돌',
    'key.button.leaveDungeon': '아르카나 균열을 떠나기',
    'key.alias.enterNewAlias': '크리처의 일음을 입력하십시오',
    'key.alias.enterText': '텍스트를 입력하십시오',
    'key.hut.hutName': '용의 어머니',
    'key.hut.hutDescr': '용의 어머니에게 알을 주면 당신을 위해 고대 알을 부화시켜 줄 것입니다',
    'key.text.noHutEggs': '고대 알이 없습니다',
    'key.text.noCapturedArenas': '점령된 아레나가 없습니다',
    'key.text.noChosenPet': '애완 동물을 선택하지 않았습니다',
    'key.text.noArtifacts': '아티팩트가 없습니다',
    'key.text.noCreatures': '포획된 크리처가 없습니다',
    'key.text.noLureItems': '미끼가 없습니다',
    'key.descr.aboutWizardBattles': '경험과 보상을 얻기 위해 다른 플레이어에 대한 결투에 참여하십시오.',
    'key.text.writeToSupport': '고객센터',
    'key.text.regUsingFacebook': '페이스북으로 등록하기',
    'key.text.regUsingGoogle': '구글로 등록하기',
    'key.text.logUsingFacebook': '페이스북으로 로그인하기',
    'key.text.logUsingGoogle': '구글로 로그인하기',
    'key.text.logUsingDeviceIDCurrent': '디바이스 아이디로 로그인하기',
    'key.text.logUsingDeviceIDNew': '디바이스 아이디로 로그인하기(새계정)',
    'key.text.createAccount': '게임 시작',
    'key.text.connectedToFacebook': '페이스북에 연결됨',
    'key.text.connectedToGoogle': '구글에 연결됨',
    'key.text.complainAboutPoint': '포인트에 대해 불평하기',
    'key.text.copyCoordinates': '좌표 복사하기',
    'key.text.complainEnterEmail': '이메일',
    'key.text.complainEnterText': '문제를 묘사하세요',
    'key.modal.doYouWantToCloseApp': '응용 프로그램을 닫고 싶습니까?',
    'key.catchPopup.notBad': '괜찮습니다',
    'key.catchPopup.good': '좋습니다',
    'key.catchPopup.sumptuously': '화려하게',
    'key.catchPopup.twistedThrow': '뒤틀린 전진',
    'key.battlePopup.strongHit': '강타',
    'key.battlePopup.weakHit': '약한 히트',
    'key.battlePopup.dodge': '다지',
    'key.battlePopup.chargedAttack': '{0} 님이 {1}을(를) 사용 중입니다',
    'auth.login.play': '플레이',
    'auth.login.nickname.placeholder': '이름을 입력하기',
    'auth.login.nickname.busy': '이름이 이미 사용 중입니다',
    'auth.login.nickname.proposal': '본 이름을 사용할 수 있습니다:',
    'auth.login.nickname.deviceId': '캐릭터가 이미 있습니다',
    'auth.login.social.title': '소셜 네트워크를 통해 로그인',
    'auth.login.social.facebook': '페이스북',
    'auth.login.social.google': '구글',
    'auth.login.social.connected': '{0}에 연결됨',
    'auth.login.social.signOut': '로그아웃',
    'auth.login.signOut.confirmation': '로그아웃하시겠습니까?',
    'auth.login.social.userCancelledError': '연결 실행 취소',
    'auth.login.social.cantSignInError': '{0}에 서버에 연결할 수 없습니다',
    'licence.title': '«DRACONIUS GO: CATCH A DRAGON!» 최종 사용자 사용권 계약',
    'licence.checkbox': '전자 메일로 뉴스 및 제안 받고 싶습니다',
    'licence.accept': '동의',
    'licence.decline': '거절',
    'key.error.wrongRoostIndex': '셀을 사용할 수 없습니다.',
    'key.speed.toMachSpeed': '너무 빨리 움직입니다. 운전중 드라코니우스 고 게임하면 안 됩니다. 그것은 생명에 위협이 됩니다.',
    'key.speed.passenger': '승객입니다',
    'key.activeObjects.addUnit.question': '정말 {0}을(를) 이 건물의 방어자로 만드시겠어요?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2}/{2}시간',
    'key.confirm.selectAlliance': '정말 이 파벌을 선택하시겠어요? 지금 선택하면 나중에 다시 변경할 수 없습니다.',
    'key.confirm.giveUpEncounter': '정말 이 야생 몬스터와의 싸움을 포기하시겠어요?',
    'key.confirm.giveUpBattle': '정말 싸움을 포기하시겠어요?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': '불러오는 중...',
    'key.layerUp.title': '새로운 리그!',
};
