module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Si',
    'key.button.cancel': 'ANNULLA',
    'key.button.apply': 'OK',
    'key.button.use': 'Usa',
    'key.button.buy': 'Comprare',
    'key.beCarefulMessage.text': 'Stai attento mentre giochi. Guarda bene ai lati.',
    'key.creature.details.attack': 'Forza',
    'key.creature.details.health': 'Salute',
    'key.creature.details.powerUp': 'Potenzia',
    'key.creature.details.evolve': 'Fai evolvere',
    'key.creature.details.cp': 'PL',
    'key.creature.details.cpValue': 'PL {0}',
    'key.creature.details.hp': 'PS',
    'key.creature.details.transfer': 'TRASFERIRE',
    'key.creature.details.creadex': 'Bestiario',
    'key.creature.registration.creadex': 'Aggiunto al bestiario',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Edifici conquistati',
    'key.activeObjects.library': 'Rieducare la creatura nella biblioteca',
    'key.activeObjects.library.empty': 'Non hai Biblioteche conquistate',
    'key.activeObjects.arena': 'Raccogliere il tributo dalle arene',
    'key.activeObjects.arena.collect': 'Raccogliere',
    'key.activeObjects.arena.empty': 'Non hai Arene conquistate',
    'key.activeObjects.error.timer': 'Il tributo non è pronto. Devi aspettare',
    'key.activeObjects.error.noMoney': 'Prima devi conquistare l\'Arena',
    'key.activeObjects.error.cannotRemaster': 'Non può rieducare le proprie creature. Cattura biblioteche per accelerare il cronometro e poter rieducare.',
    'key.activeObjects.library.remaster': 'Rieducare',
    'key.activeObjects.library.blocked': 'Le Biblioteche non sono disponibili',
    'key.activeObjects.remaster.confirmation.main': 'Sei sicuro di voler rieducare {0}? L\'abilità principale {1} verrà cambiata!',
    'key.activeObjects.remaster.confirmation.charged': 'Sei sicuro di voler rieducare {0}? L\'abilità caricata {1} verrà cambiata!',
    'key.activeObjects.remaster.error': 'Errore',
    'key.activeObjects.item.weaklyBonus': 'Bonus settimanale +{0} monete',
    'key.library.remaster.selectCreature': 'Scegli la creatura da rieducare',
    'key.remasterPanel.title': 'Scegli l\'abilità',
    'key.storage.creatues': 'Creature',
    'key.storage.eggs': 'Uova',
    'key.storage.eggs.simple': 'Uova normali',
    'key.storage.eggs.super': 'Uova antiche',
    'key.storage.eggs.missingAny': 'Non hai uova di creature',
    'key.startEgg.button': 'Metti nel bozzolo',
    'key.startEgg.description': 'Usa il bozzolo di drago per incubare le uova',
    'key.startEgg.incubator.title': 'Bozzoli di drago',
    'key.startEgg.select.title': 'Scegli l\'uovo',
    'key.openEgg.button': 'Schiudi l\'uovo',
    'key.openEgg.description': 'Una nuova creatura si schiuderà ora dall\'uovo',
    'key.startEgg.description.roost.hatching': 'La Madre dei Draghi sta incubando l\'uovo. Devi solo aspettare. L\'incubazione verrà sospesa se la faglia di Arcana nella quale si trova la Madre dei Draghi scompare',
    'key.startEgg.description.roost.notHatching': 'Lascia l\'uovo alla Madre dei Draghi e lei lo incuberà per te',
    'key.startEgg.description.simple.hatching': 'Quest\'uovo si sta incubando nel bozzolo di drago. Cammina con il gioco acceso per aiutarlo a schiudersi',
    'key.startEgg.description.simple.notHatching': 'Metti quest\'uovo nel bozzolo di drago per incubarlo. L\'uovo si schiuderà quando avrai camminato la distanza richiesta',
    'key.mainMenu.wizardDuels': 'DUELLO DI MAGHI',
    'key.mainMenu.quests': 'COMPITI',
    'key.mainMenu.activePoints': 'CATTURATO',
    'key.mainMenu.creadex': 'BESTIARIO',
    'key.mainMenu.magic': 'MAGIA',
    'key.mainMenu.creatues': 'CREATURE',
    'key.mainMenu.shop': 'BOTTEGA',
    'key.mainMenu.backpack': 'ZAINO',
    'key.error.banned': 'L\'account è bloccato',
    'event.log.CREATURE_CAUGHT': 'Hai catturato {0}!',
    'event.log.ITEM_BOUGHT': 'Hai comprato {0} x{1}. Hai speso {2} monete',
    'event.log.ARTIFACT_BOUGHT': 'Hai comprato l\'artefatto: {0}. Hai speso {1} monete',
    'event.log.EGG_HATCHED': '{0} si è schiuso dall\'uovo {1}!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'd\'oro',
    'event.log.ROOST_EGG_HATCHED': 'La Madre dei Draghi ha incubato l\'uovo di {1}h. {0} ora è tuo!',
    'event.log.CHEST_OPENED': 'Nel cofano hai trovato:',
    'event.log.ARENA_LOST_CONTROL': '{1} è stato buttato fuori dall\'edificio: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} è stato buttato fuori dall\'edificio: {0}',
    'event.log.LEVEL_UP': 'Hai raggiunto il livello {0}',
    'event.log.BUDDY_FOUND_CANDY': 'La tua mascotte ha trovato {0}',
    'event.log.QUEST_COMPLETED': 'Premio per il compito {0}',
    'event.log.ENCOUNTER_LOOSE': 'Sei riuscito a scappare dal mostro selvaggio',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Il limite di duelli di maghi è stato aumentato per {0} monete',
    'event.log.HARD_CURRENCY_BOUGHT': 'Hai comprato {0} monete per {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Hai migliorato lo zaino per {0} monete',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Hai migliorato il Magazzino di creature per {0} monete',
    'key.shop.accesories': 'OGGETTO',
    'key.shop.artifacts': 'ARTEFATTI',
    'key.shop.donate': 'MONETE',
    'key.shop.upgrade': 'MIGLIORIE',
    'key.shop.donate.coins': '{0} monete',
    'key.shop.upgrade.bag': 'Migliorare lo zaino',
    'key.shop.upgrade.bag.desc': 'Le dimensioni dello zaino saranno aumentate di 50',
    'key.shop.upgrade.storage': 'Migliorare il magazzino delle creature',
    'key.shop.upgrade.storage.desc': 'Le dimensioni del magazzino delle creature saranno aumentate di 50.',
    'key.shop.donate.dialog.title': 'Non hai sufficienti monete!',
    'key.shop.donate.dialog.desc': 'Ottienile qui, o visita la Bottega per vedere più opzioni',
    'key.potionUseMenu.title': 'Pozione',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Crea un Portale al mondo di Arcana',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Tutti i giocatori nei dintorni sentiranno la furia dei leprechaun',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Crea un campo di Colonne dell\'Abbondanza per 30 minuti',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Raddoppia il numero di premi dalle Colonne dell\'Abbondanza per 30 minuti',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Premi e mantieni il dito sopra la località per illuminarla nella ricerca di creature',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Aumenta il raggio di ricerca di creature per 30 minuti',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Aumenta il raggio di visualizzazione degli oggetti un 30% per 7 giorni',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'L\'arena alleata più vicina non potrà essere attaccata dai nemici durante 30 ore',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Tutte le arene nemiche nel raggio di vista diventano neutrali. Toglie la Benedizione di difesa.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Crea una torre magica che attrae le creature dell\'elemento fuoco',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Crea una torre magica che attrae le creature dell\'elemento acqua',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Crea una torre magica che attrae le creature dell\'elemento aria',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Crea una torre magica che attrae le creature dell\'elemento terra',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Crea una torre magica che attrae le creature dell\'elemento Arcana',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Faglia di Arcana',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Furia dei leprechaun',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Campo dell\'Abbondanza',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Dono del Drago Dorato',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Vista astrale',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Vista di drago',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Mani lunghe',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Benedizione della difesa',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Purificazione con fuoco',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Torre di Fuoco',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Torre d\'Acqua',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Torre d\'Aria',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Torre di Terra',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Torre di Arcana',
    'key.buff.ATTACKER_CP_BOOST': 'Il PL delle tue creature è stato aumentato per un tempo',
    'key.buff.BEST_BALL_LUCK': 'Riceverai solo le migliori sfere nelle Colonne dell\'Abbondanza durante 30 minuti',
    'key.buff.BEST_POTION_LUCK': 'Riceverai solo le migliori pozioni nelle Colonne dell\'Abbondanza durante 30 minuti',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Riceverai +2 oggetti dalle Colonne dell\'Abbondanza durante 30 minuti',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Il cooldown della Biblioteca è stato ridotto',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Il tempo fino alla raccolta del tributo dalle Arene è stato ridotto',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Aumenta il PL delle creature che non difendono gli edifici',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Ricevi solo le migliori sfere, disponibili per il tuo livello, dalle Colonne dell\'Abbondanza',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Ricevi solo le migliori pozioni, disponibili per il tuo livello, dalle Colonne dell\'Abbondanza',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Ricevi due oggetti in più dalle Colonne dell\'Abbondanza',
    'key.loot.result.dust': 'Essenza',
    'key.loot.result.exp': 'Esperienza del personaggio',
    'key.loot.result.coin': 'Monete',
    'key.loot.result.candy': 'pietre',
    'key.item.MAGIC_BALL_SIMPLE': 'Sfera del discepolo',
    'key.item.MAGIC_BALL_NORMAL': 'Sfera del maestro',
    'key.item.MAGIC_BALL_GOOD': 'Sfera del signore',
    'key.item.LURE': 'Esca',
    'key.item.INCENSE': 'Feromoni',
    'key.item.EGG': 'Uovo',
    'key.item.SHOVEL': 'Pala',
    'key.item.POTION_HEAL_1': 'Pozione piccola',
    'key.item.POTION_HEAL_2': 'Pozione media',
    'key.item.POTION_HEAL_3': 'Pozione grande',
    'key.item.POTION_HEAL_4': 'Pozione massima',
    'key.item.POTION_RESURRECTION_1': 'Pozione di risurrezione',
    'key.item.POTION_RESURRECTION_2': 'Pozione di risurrezione grande',
    'key.item.INCUBATOR_1': 'Bozzolo di drago',
    'key.item.INCUBATOR_3': 'Bozzolo di drago',
    'key.item.INCUBATOR_PERPETUAL': 'Bozzolo di drago eterno',
    'key.item.SUPER_VISION': 'Vista di drago',
    'key.item.RUNE_1': 'Runa I',
    'key.item.RUNE_2': 'Runa II',
    'key.item.RUNE_3': 'Runa III',
    'key.item.RUNE_4': 'Runa IV',
    'key.item.RUNE_5': 'Runa V',
    'key.item.RUNE_6': 'Runa VI',
    'key.item.FOOD_CATCH_CHANCE': 'Caramella arcanica',
    'key.item.FOOD_MORE_DUST': 'Donuts magico',
    'key.item.FOOD_CALM_DOWN': 'Dolce di unicornio',
    'key.item.FOOD_MORE_CANDIES': 'Gelato dei quattro elementi',
    'key.item.EXPERIENCE_BOOSTER': 'Cristallo della sapienza',
    'key.item.EGG_KM_0': 'Uovo d\'oro',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sfera per catturare le creature',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sfera per catturare le creature. Aumenta un po\' la probabilità di catturare le creature',
    'key.item.MAGIC_BALL_GOOD.description': 'Sfera per catturare le creature. Aumenta di tanto la probabilità di catturare le creature.',
    'key.item.LURE.description': 'Esca per le creature. Mettila in una Colonna dell\'Abbondanza per atrarre le creature',
    'key.item.INCENSE.description': 'I feromoni attrarranno creature di un certo elemento, dipendendo dal giorno della settimana',
    'key.item.EGG.description': 'Usa il bozzolo di drago per far schiudere le uova',
    'key.item.SHOVEL.description': 'Le pale sono totalmente insostituibili all\'ora di ricercare tesori',
    'key.item.POTION_HEAL_1.description': 'Ripristina 200 punti di salute della tua creatura',
    'key.item.POTION_HEAL_2.description': 'Ripristina 500 punti di salute della tua creatura',
    'key.item.POTION_HEAL_3.description': 'Ripristina 1000 punti di salute della tua creatura',
    'key.item.POTION_HEAL_4.description': 'Ripristina tutta la salute della tua creatura',
    'key.item.POTION_RESURRECTION_1.description': 'Rivitalizza la creatura scelta. La creatura rimane ferita',
    'key.item.POTION_RESURRECTION_2.description': 'Rivitalizza e ripristina tutta la salute della creatura',
    'key.item.INCUBATOR_1.description': 'I bozzoli di drago servono per incubare le creature delle uova. Scompare dopo essere stata usata',
    'key.item.INCUBATOR_3.description': 'I bozzoli di drago servono per incubare le creature delle uova. Scompare dopo 3 usi',
    'key.item.INCUBATOR_PERPETUAL.description': 'I bozzoli di drago servono per incubare le creature delle uova',
    'key.item.SUPER_VISION.description': 'Mostra le creature in un raggio più grande',
    'key.item.RUNE_1.description': 'Runa magica di 1 livello',
    'key.item.RUNE_2.description': 'Runa magica di 2 livello',
    'key.item.RUNE_3.description': 'Runa magica di 3 livello',
    'key.item.RUNE_4.description': 'Runa magica di 4 livello',
    'key.item.RUNE_5.description': 'Runa magica di 5 livello',
    'key.item.RUNE_6.description': 'Runa magica di 6 livello',
    'key.item.FOOD_CATCH_CHANCE.description': 'Dolce per catturare le creature. Aumenta la probabilità di catturare creature con una sfera magica',
    'key.item.FOOD_MORE_DUST.description': 'Dolce per catturare le creature. Aumenta l\'essenza che ricevi catturando una creatura',
    'key.item.FOOD_CALM_DOWN.description': 'Dolce per catturare le creature. Tranquillizza le creature. Smettono di saltare ed attaccare',
    'key.item.FOOD_MORE_CANDIES.description': 'Dolce per catturare le creature. Aumenta il numero di pietre di anime che ricevi catturando una creatura',
    'key.item.EXPERIENCE_BOOSTER.description': 'Raddoppia l\'esperienza che ricevi durante 30 minuti',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Maschera del mago',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': 'Puoi collocare nell\'Arena o Biblioteca a distanza +1 creatura al giorno',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Quest\'artefatto ti permette di collocare 1 volta al giorno una delle tue creature in un posto libero in un\'Arena o Biblioteca visibile nella mappa da qualsiasi distanza',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Faccia di vidente',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': 'Puoi collocare nell\'Arena o Biblioteca a distanza +2 creature al giorno',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Quest\'artefatto ti permette di collocare 2 volte al giorno una delle tue creature in un posto libero in un\'Arena o Biblioteca visibile nella mappa da qualsiasi distanza',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Elmo del conquistatore',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': 'Puoi collocare nell\'Arena o Biblioteca a distanza +3 creature al giorno',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Quest\'artefatto ti permette di collocare 3 volte al giorno una delle tue creature in un posto libero in un\'Arena o Biblioteca visibile nella mappa da qualsiasi distanza',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Elmo dell\'eroe',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': 'Puoi collocare nell\'Arena o Biblioteca a distanza +4 creature al giorno',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Quest\'artefatto ti permette di collocare 4 volte al giorno una delle tue creature in un posto libero in un\'Arena o Biblioteca visibile nella mappa da qualsiasi distanza',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Elmo del guerriero dragone',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': 'Puoi collocare nell\'Arena o Biblioteca a distanza +5 creature al giorno',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Quest\'artefatto ti permette di collocare 5 volte al giorno una delle tue creature in un posto libero in un\'Arena o Biblioteca visibile nella mappa da qualsiasi distanza',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Bandiera del signore',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Permette di mettere nell\'Arena o Biblioteca una creatura in più',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Con quest\'artefatto puoi mettere nella difesa di un\'Arena o Biblioteca a due mostri invece che a uno',
    'key.artifact.ARTIFACT_BANK_8': 'Artefatto tagliato',
    'key.artifact.ARTIFACT_BANK_8.description': ' come l\'hai trovato?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Hai visto un artefatto che non dovevi vedere. Ora dobbiamo liberarci di te come testimone',
    'key.artifact.ARTIFACT_BANK_9': 'Artefatto tagliato',
    'key.artifact.ARTIFACT_BANK_9.description': 'Ma come l\'hai trovato?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Hai visto un artefatto che non dovevi vedere. Ora dobbiamo liberarci di te come testimone.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Orologio dello studente pigro',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': 'Le Colonne dell\'Abbondanza si ricaricano 20 secondi più veloce',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Con quest\'artefatto le Colonne dell\'Abbondanza si ricaricano 20 secondi più velocemente e potranno essere usati più frequentemente',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Sveglia del ritardatore',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': 'Le Colonne dell\'Abbondanza si ricaricano 40 secondi più veloce',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Con quest\'artefatto le Colonne dell\'Abbondanza si ricaricano 40 secondi più velocemente e potranno essere usati più frequentemente.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Acceleratore dello spazio',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': 'Le Colonne dell\'Abbondanza si ricaricano 60 secondi più veloce',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Con quest\'artefatto le Colonne dell\'Abbondanza si ricaricano 60 secondi più velocemente e potranno essere usati più frequentemente.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Orologio del professore pigro',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': 'Le Colonne dell\'Abbondanza si ricaricano 80 secondi più veloce',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Con quest\'artefatto le Colonne dell\'Abbondanza si ricaricano 80 secondi più velocemente e potranno essere usati più frequentemente.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Orologio della zebra-coniglio',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': 'Le Colonne dell\'Abbondanza si ricaricano 100 secondi più veloce',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Con quest\'artefatto le Colonne dell\'Abbondanza si ricaricano 100 secondi più velocemente e potranno essere usati più frequentemente.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Cetro del conquistatore',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 al livello dell\'Arena o Biblioteca dopo averle conquistate',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Se il proprietario di questo artefatto è il primo a mettere una creatura nell\'Arena o Biblioteca conquistata, essa riceve subito il livello 5 invece che il 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Anello del raccoglitore del tributo',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 al numero massimo di Arene',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Con quest\'artefatto potrai raccogliere il tributo da 11 Arene invece che 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Anello dell\'avidità',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 al numero massimo delle Arene',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Con quest\'artefatto potrai raccogliere il tributo da 12 Arene invece che 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Anello doppio',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 al numero massimo delle Arene',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Con quest\'artefatto potrai raccogliere il tributo da 13 Arene invece che 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Coppa del divoratore di torte',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% alla gloria delle Arene e Biblioteche alleate durante l\'allenamento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Con quest\'artefatto le Arene e Biblioteche alleate ricevono un 20% più di gloria quando le alleni',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Coppa per il miele',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% alla gloria delle Arene e Biblioteche alleate durante l\'allenamento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Con quest\'artefatto le Arene e Biblioteche alleate ricevono un 30% più forza quando le alleni',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Coppa dei pensieri profondi',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% alla gloria delle Arene e Biblioteche alleate durante l\'allenamento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Con quest\'artefatto le Arene e Biblioteche alleate ricevono un 40% più forza quando le alleni',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Graal di Lancelop',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% alla gloria delle Arene e Biblioteche alleate durante l\'allenamento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Con quest\'artefatto le Arene e Biblioteche alleate ricevono un 50% più forza quando le alleni',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Coppa del conquistatore dei mostri',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% alla gloria delle Arene e Biblioteche alleate durante l\'allenamento',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Con quest\'artefatto le Arene e Biblioteche alleate ricevono un 80% più forza quando le alleni',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem della chiaroveggenza',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Espelle le creature debole dal radar',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Quest\'artefatto espelle dal radar le creature più deboli, cosa che ti aiuta a concentrarti nella ricerca di creature più forti',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Libro di regole dell\'avventuriero',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': 'Puoi raccogliere il ttributo dalle Arene durante 15 minuti in più dopo essere state conquistate dal nemico',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Con quest\'artefatto puoi raccogliere il tributo delle Arene durante 45 minuti in più dopo averle conquistate invece che 15 minuti',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Libro grande e grosso',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': 'Puoi raccogliere il ttributo dalle Arene durante 30 minuti in più dopo essere state conquistate dal nemico',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Con quest\'artefatto puoi raccogliere il tributo delle Arene durante 45 minuti in più dopo averle conquistate invece che 15 minuti',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tavola della pretensione',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': 'Puoi raccogliere il ttributo dalle Arene durante 45 minuti in più dopo essere state conquistate dal nemico',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Con quest\'artefatto puoi raccogliere il tributo delle Arene durante 60 minuti in più dopo averle conquistate invece che 15 minuti',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Trattato sul potere',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': 'Puoi raccogliere il ttributo dalle Arene durante 75 minuti in più dopo essere state conquistate dal nemico',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Con quest\'artefatto puoi raccogliere il tributo delle Arene durante 90 minuti in più dopo averle conquistate invece che 15 minuti',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimorio del potere',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': 'Puoi raccogliere il ttributo dalle Arene durante 105 minuti in più dopo essere state conquistate dal nemico',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Con quest\'artefatto puoi raccogliere il tributo delle Arene durante 120 minuti in più dopo averle conquistate invece che 15 minuti',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Collana appuntita',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': 'Ricevi una pietra di anime dalla tua mascotte il 10% più velocemente',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Con quest\'artefatto devi camminare con la tua mascotte una distanza del 10% più corta per ricevere una pietra di anime. La tua mascotte diventa anche il 17% più temibile',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Carota in un palo',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': 'Ricevi una pietra di anime dalla tua mascotte il 15% più velocemente',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Con quest\'artefatto devi camminare con la tua mascotte una distanza del 25% più corta per ricevere una pietra di anime. Delizioso.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Grattatore di schiena',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': 'Ricevi una pietra di anime dalla tua mascotte il 25% più velocemente',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Con quest\'artefatto devi camminare con la tua mascotte una distanza del 25% più corta per ricevere una pietra di anime. Chinati davanti al potere del grattatore di schiena!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Sonaglio della mascotte',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': 'Ricevi una pietra di anime dalla tua mascotte il 30% più velocemente',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Con quest\'artefatto devi camminare con la tua mascotte una distanza del 30% più corta per ricevere una pietra di anime. Chi è la creatura più bella?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Drago di pelusche',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': 'Ricevi una pietra di anime dalla tua mascotte il 40% più velocemente',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Con quest\'artefatto devi camminare con la tua mascotte una distanza del 40% più corta per ricevere una pietra di anime. Il miglior giocattolo per la miglior mascotte del mondo',
    'key.artifact.ARTIFACT_ROOST_1': 'Cuore di drago',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 bozzolo di drago dalla Madre dei Draghi',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Permette di usare un bozzolo di drago addizionale per le uova dalla Madre dei Draghi',
    'dialog.artifact.select_artifact': 'SCEGLI L\'ARTEFATTO',
    'dialog.artifact.confirm.remove': 'Sei sicuro di voler rimuovere l\'artefatto?',
    'dialog.items.title': 'ZAINO',
    'dialog.items.cannotUse': 'Non puoi usare quest\'oggetto',
    'dialog.items.remove.header': 'Elimina oggetti',
    'dialog.encounter.header': 'Un mostro selvaggio ti sta attaccando!',
    'dialog.encounter.button.leave': 'Scappa',
    'dialog.encounter.button.fight': 'Combatti',
    'dialog.encounter.result.outcome.win': 'Hai sconfitto il mostro selvaggio',
    'dialog.encounter.result.outcome.lose': 'La tua creatura è stata sconfitta',
    'dialog.encounter.result.reward.dust': 'Essenza',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': 'Introduci il nome del personaggio',
    'error.nickname.validation.TOO_SHORT': 'Il nome deve contenere tra 3 e 16 simboli',
    'error.nickname.validation.TOO_LONG': 'Il nome deve contenere tra 3 e 16 simboli',
    'error.nickname.validation.INVALID_CHAR': 'Solo puoi usare lettere, numeri e il trattino basso',
    'error.nickname.validation.DUPLICATE': 'Questo nome esiste già. Puoi prendere il nome {0}',
    'creature.MONSTER_WATER_1': 'Rospus',
    'creature.MONSTER_WATER_2': 'Goccia',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Sopraquian',
    'creature.MONSTER_WATER_5': 'Rospissimus',
    'creature.MONSTER_WATER_6': 'Ruscellux',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Infalisco',
    'creature.MONSTER_WATER_11': 'Mezzaquian',
    'creature.MONSTER_WATER_12': 'Dadachock',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisco',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Sottaquian',
    'creature.MONSTER_WATER_18': 'Dadachum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilisco',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Crystallhat',
    'creature.MONSTER_WATER_23': 'Armaturos',
    'creature.MONSTER_WATER_24': 'Nettuno',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mummyween',
    'creature.MONSTER_FIRE_3': 'Vaporex',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Fuocartiglio',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dummyween',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Vapopeye',
    'creature.MONSTER_FIRE_11': 'Scintilla',
    'creature.MONSTER_FIRE_12': 'Kiddra',
    'creature.MONSTER_FIRE_13': 'Daemonstar',
    'creature.MONSTER_FIRE_14': 'Fenix',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Ragazzo acciaio',
    'creature.MONSTER_FIRE_17': 'Fuocorfalla',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Flash',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Artificius',
    'creature.MONSTER_FIRE_24': 'Picaroon',
    'creature.MONSTER_FIRE_25': 'Smoargh',
    'creature.MONSTER_EARTH_1': 'Baccadil',
    'creature.MONSTER_EARTH_2': 'Fiorix',
    'creature.MONSTER_EARTH_3': 'Foglia',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryad',
    'creature.MONSTER_EARTH_7': 'Piantix',
    'creature.MONSTER_EARTH_8': 'Goblic',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Nocciolus',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Pignetoff',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Giardix',
    'creature.MONSTER_EARTH_20': 'Priman',
    'creature.MONSTER_EARTH_21': 'Apeterr',
    'creature.MONSTER_EARTH_22': 'Fiorimale',
    'creature.MONSTER_EARTH_23': 'Yoghi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Orecchiago',
    'creature.MONSTER_WIND_3': 'Funghy',
    'creature.MONSTER_WIND_4': 'Tenericornio',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Paurion',
    'creature.MONSTER_WIND_8': 'Orecchion',
    'creature.MONSTER_WIND_9': 'Eschimo',
    'creature.MONSTER_WIND_10': 'Ballavento',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Aericornio',
    'creature.MONSTER_WIND_14': 'Fantomo',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Fungotopia',
    'creature.MONSTER_WIND_17': 'Harpy',
    'creature.MONSTER_WIND_18': 'Fantasmus',
    'creature.MONSTER_WIND_19': 'Puerogrifo',
    'creature.MONSTER_WIND_20': 'Cuscigatto',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Huracdine',
    'creature.MONSTER_WIND_23': 'Grifone',
    'creature.MONSTER_WIND_24': 'Baiun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Pungischien',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Dolcigatto',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Merid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Spaventapasseri',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Genie',
    'creature.MONSTER_DUNGEON_12': 'Vampirus',
    'creature.MONSTER_DUNGEON_13': 'Advise',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Softail',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigromante',
    'creature.MONSTER_DUNGEON_21': 'Sharptail',
    'creature.MONSTER_DUNGEON_22': 'Germol',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Manticora',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Morso di squalo',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Terrore profondo',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Chiamata di Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Martello marino',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Pugno d\'acqua',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Onda',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Diluvio',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Geyser',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Sguazzo',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Fiamma viva',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Anello di fuoco',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Frusta di fuoco',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Palla di fuoco',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Cremare',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Stella',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Carbone',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Lanciafiamme',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Fucilare',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Falce di vento',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Lacerare',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Respiro',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Electroshock',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Scintilla',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Elettroconvulsione',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Respiro di drago',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Soffio',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Furia del vento',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Sputaveleno',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Zanna di serpente',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Avvelenare',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Frantuma-ossa',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Roccia',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Sasso enorme',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Spirito del bosco',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Fantasma dell\'albero',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Ombra della natura',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Freccia di arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Grumo di oscurità',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentacolo del male',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Occhio del terrore',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sfera della perdizione',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Palla di oscurità',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arcana Kadabra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarcus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Impericanos',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Gelare',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Congelare',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Cristallizzare',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Vortice',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Bufera',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Furia fredda',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Esplosione di ghiaccio',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Potere del ghiaccio',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Depurare',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Ascendere',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Bruciare',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lava',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Fontana di fuoco',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteorite',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Fulmine',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Tuono',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Tormenta',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Ricarica',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Campo elettrico',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Brivido',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Ruggito del vento',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Giostra',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Frastuono',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Scossa',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Faglia',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Abbattere',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Esplosione',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Vortice di pietre',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Lago della morte',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Pozzanghera velenosa',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Acido',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomismo',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Disintegrare',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionizzare',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Esiliare',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Maledizione',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Esclusione',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Tormenta magica',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Tormenta di manna',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Furia di Arcana',
    'key.combined.first.1': 'Saggi',
    'key.combined.first.2': 'Infernali',
    'key.combined.first.3': 'Bellissimi',
    'key.combined.first.4': 'Maligni',
    'key.combined.first.5': 'Neutrali',
    'key.combined.first.6': 'Onesti',
    'key.combined.first.7': 'Santi',
    'key.combined.first.8': 'Antichi',
    'key.combined.first.9': 'Sotterranei',
    'key.combined.first.10': 'Fiammeggianti',
    'key.combined.first.11': 'Abili',
    'key.combined.first.12': 'Enormi',
    'key.combined.first.13': 'Blu',
    'key.combined.first.14': 'Crudeli',
    'key.combined.first.15': 'Gentili',
    'key.combined.first.16': 'Aerei',
    'key.combined.first.17': 'Terrestri',
    'key.combined.first.18': 'Rossi',
    'key.combined.first.19': 'Immortali',
    'key.combined.first.20': 'Morti',
    'key.combined.first.21': 'Aerei',
    'key.combined.first.22': 'Spaventosi',
    'key.combined.first.23': 'Acquatici',
    'key.combined.first.24': 'Divertenti',
    'key.combined.first.25': 'Sciocchi',
    'key.combined.second.1': 'Eroi',
    'key.combined.second.2': 'Pesci',
    'key.combined.second.3': 'Gufi',
    'key.combined.second.4': 'Malfattori',
    'key.combined.second.5': 'Addetti',
    'key.combined.second.6': 'Maghi',
    'key.combined.second.7': 'Anziani',
    'key.combined.second.8': 'Incantevoli',
    'key.combined.second.9': 'Guerrieri',
    'key.combined.second.10': 'Duelisti',
    'key.combined.second.11': 'Mercanti',
    'key.combined.second.12': 'Conigli',
    'key.combined.second.13': 'Mele',
    'key.combined.second.14': 'Combattenti',
    'key.combined.second.15': 'Ilusionisti',
    'key.combined.second.16': 'Cavalieri',
    'key.combined.second.17': 'Barbari',
    'key.combined.second.18': 'Scarafaggi',
    'key.combined.second.19': 'Serpenti',
    'key.combined.second.20': 'Draghi',
    'key.combined.second.21': 'Fantasmi',
    'key.combined.second.22': 'Gattini',
    'key.combined.second.23': 'Soldati',
    'key.combined.second.24': 'Fortunati',
    'key.combined.second.25': 'Assassini',
    'key.combined.second.26': 'Topi',
    'key.combined.second.27': 'Elementari',
    'key.combined.second.28': 'Esploratori',
    'key.combined.second.29': 'Sciamani',
    'key.combined.second.30': 'Sacerdoti',
    'key.combined.second.31': 'Angeli',
    'key.combined.second.32': 'Arconti',
    'key.combined.second.33': 'Aguzzini',
    'key.combined.second.34': 'Stolti',
    'key.combined.second.35': 'Coraggiosi',
    'key.combined.second.36': 'Gentiloni',
    'key.combined.second.37': 'Codardi',
    'key.combined.second.38': 'Bardi',
    'key.combined.second.39': 'Domatori',
    'key.combined.second.40': 'Difensori',
    'key.combined.arena': 'Arena dei {1} {0}',
    'key.combined.library': 'Biblioteca dei {1} {0} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Acqua',
    'element.type.WIND': 'Aria',
    'element.type.FIRE': 'Fuoco',
    'element.type.EARTH': 'Terra',
    'element.type.DUNGEON': 'Arcana',
    'spell.type.ACTIVATION_RADIUS': 'Raggio di visualizzazione',
    'spell.type.VISION_RADIUS': 'Vista di Drago',
    'spell.type.STOP_FIELD': 'Campo dell\'Abbondanza',
    'spell.type.SCOUT': 'Esplorare',
    'spell.type.PROTECT_ARENA': 'Difendere l\'arena',
    'spell.type.CREATE_PORTAL': 'Creare un Portale',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Doppio drop',
    'spell.type.SLUG_PLAYERS': 'SLUG_PLAYERS',
    'quest.title.WIN_ARENA_MONSTER': 'Dominio',
    'quest.title.OPEN_EGGS': 'Febbre di uova',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Controllo del territorio',
    'quest.title.CAPTURE_LIBRARY': 'Sete del sapere',
    'quest.title.CAPTURE_WILD_MONSTER': 'Dragon Park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Caccia all\'elemento',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Ricerca della Nata in Arcana',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Pulire la faglia',
    'quest.title.OPEN_CHEST': 'Antichi tesori',
    'quest.title.CHAIN_OF_STOP': 'Cammino dell\'Abbondanza',
    'quest.desc.WIN_ARENA_MONSTER': 'Vinci le creature nelle Arene o Biblioteche. Non puoi vincere una creatura dello stesso tipo due volte.',
    'quest.desc.OPEN_EGGS': 'Incuba le creature delle uova con l\'aiuto dei bozzoli di drago o la Madre dei Draghi',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Raccogli il tributo dalle Arene che hai conquistato',
    'quest.desc.CAPTURE_LIBRARY': 'Possiedi il numero richiesto di Biblioteche',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Le creature non sono mai troppe. Viaggia e cattura creature',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Viaggia e cattura creature dell\'elemento Acqua',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Viaggia e cattura creature dell\'elemento Aria',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Viaggia e cattura creature dell\'elemento Fuoco',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Viaggia e cattura creature dell\'elemento Terra',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Viaggia e cattura creature dell\'elemento Arcana',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Visita la faglia di Arcana, nella quale si trova la Madre dei Draghi',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Visita la faglia di Arcana e cattura tutte le creature che trovi',
    'quest.desc.OPEN_CHEST': 'Trova e apri i cofani del tesoro',
    'quest.desc.CHAIN_OF_STOP': 'Passa attraverso una catena di Colonne dell\'Abbondanza e attivale. Ogni prossima Colonna si illuminerà',
    'quest.dialog.completed.rewardtext': 'Il tuo premio:',
    'key.tab.altar.title': 'ALTARE',
    'key.altar.remove': 'Togli',
    'key.altar.put': 'Metti',
    'key.altar.convert': 'Converti',
    'key.altar.shared': 'Mostra agli altri',
    'key.altar.pass.placeholder': 'Qui puoi introdurre una password',
    'key.altar.pass.error': 'La password deve contenere minimo {0} simboli',
    'key.altar.level.error': 'Devi raggiungere il livello {0} per poter usare l\'Altare',
    'key.altar.recipe.change': 'Sei sicuro di voler cambiare la ricetta? Le Rune ritorneranno ai loro proprietari',
    'key.altar.row.title': 'Per creare un incantesimo devi installare un Altare',
    'key.altar.rune.descr.RUNE_1': '3 rune grigge = una arancione',
    'key.altar.rune.descr.RUNE_2': '3 rune arancioni = una blu',
    'key.altar.rune.descr.RUNE_3': '3 rune blu = una smeralda',
    'key.altar.rune.descr.RUNE_4': '3 rune smeralda = una rossa',
    'key.altar.rune.descr.RUNE_5': '3 rune rosse = una viola',
    'key.altar.rune.descr.RUNE_6': 'Le rune viola sono le più forti',
    'error.altar.cannotRemove': 'Non puoi togliere l\'Altare',
    'error.altar.cannotConvert': 'Non hai sufficienti rune',
    'key.tab.altar.recipes': 'RICETTE',
    'key.altar.noRecipes': 'Non hai ricette',
    'key.altar.header': 'Metti le rune sopra l\'Altare per creare un incantesimo',
    'key.altar.castBtn': 'Crea',
    'key.altar.recipe.select': 'Scegli un incantesimo',
    'key.altar.castDone': 'Hai creato l\'incantesimo',
    'key.arena.protected.ally': 'Difesa:',
    'key.avatarCustomization.title': 'Scegli l\'aspetto del personaggio',
    'key.buddy.walkDescription': 'Passeggia con la tua mascotte per ricevere {0}',
    'key.buddy.totalWalked': 'Hai già percorso {0} km',
    'key.account.balance': 'Risorse',
    'key.account.userLevel': 'livello {0}',
    'key.account.totalDistance': 'Distanza percorsa: {0} chilometri',
    'key.acount.registerDate': 'Inizio del gioco: {0}',
    'key.storage.sort.name': 'NOME',
    'key.storage.sort.cp': 'PL',
    'key.storage.sort.group1': 'LISTA VERDE',
    'key.storage.sort.group2': 'LISTA GIALLA',
    'key.storage.sort.group3': 'LISTA ROSSA',
    'key.storage.sort.date': 'DATA',
    'key.account.options.jurnal': 'STORICO',
    'key.account.options.buddy': 'MASCOTTE',
    'key.account.options.artifacts': 'ARTEFATTI',
    'key.account.options.style': 'ASPETTO',
    'key.error.gps.permission': 'Il GPS non è disponibile. Per favore, accendi l\'accesso al GPS nelle impostazioni per poter giocare',
    'key.error.gps.disabled': 'Il GPS è disattivato. Attiva il GPS per poter giocare',
    'key.error.gps.fakePosition': 'Non puoi giocare senza GPS',
    'key.error.gps.signal.notFound': 'Nessun segnale GPS',
    'key.error.gps.signal.bad': 'Il gioco non è disponibile. Il segnale GPS è molto debole',
    'key.error.internet.notReachable': 'Non hai connessione a Internet',
    'key.journal.title': 'Storico',
    'key.journal.yesterday': 'Ieri',
    'key.settings.title': 'Impostazioni',
    'key.settings.music': 'Musica',
    'key.settings.deviceAuthError': 'Per motivi di sicurezza vinculi l\'account a Google o Facebook',
    'key.settings.sounds': 'Suoni',
    'key.settings.vibration': 'Vibrazione',
    'key.settings.batterySaver': 'Risparmio di energia',
    'key.settings.support': 'Scrivere al supporto',
    'key.settings.logout': 'Uscire dall\'account',
    'key.settings.auth.deviceid': 'ID del dispositivo',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Vincolare',
    'key.settings.languageTitle': 'Lingua',
    'key.settings.language': 'Italiano',
    'key.battle.result.win': 'Fine della battaglia',
    'key.battle.result.lose': 'Fine della battaglia',
    'key.wizardBattle.result.win': 'VITTORIA!',
    'key.wizardBattle.result.lose': 'DISFATTA!',
    'key.battle.result.monster': 'Creature sconfitte',
    'key.battle.result.exp': 'Esperienza ricevuta',
    'key.battle.result.prestige_strong_enemy': 'Bonus di gloria per nemici forti',
    'key.battle.result.exp_strong_enemy': 'Bonus di esperienza per nemici forti',
    'key.battle.result.prestige_killed_all': 'Bonus di gloria per aver ucciso tutti',
    'key.battle.result.exp_killed_all': 'Bonus di esperienza per aver ucciso tutti',
    'key.battle.result.dust': 'Essenza',
    'key.radar.title': 'Creature vicine',
    'key.levelUp.title': 'Nuovo livello!',
    'key.wizardBattle.left': 'Limite di battaglie',
    'key.wizardBattle.timer': 'Il limite si azzererà fra',
    'key.wizardBattle.enhance.title': 'AUMENTARE IL LIMITE',
    'key.wizardBattle.enhance.desc': 'Puoi aumentare il limite di combattimenti fino a 7 per una settimana',
    'key.wizardBattle.enhance.btn': 'Aumenta',
    'key.wizardBattle.lookingForOpponent': 'Ricerca di avversario per il Duello...',
    'key.catch.result.expMonster': 'Esperienza per la cattura:',
    'key.catch.result.expMonsterNew': 'Nuovo nel Bestiario:',
    'key.catch.result.expAccurate': 'Lancio preciso:',
    'key.catch.result.expSpin': 'Lancio curvo:',
    'key.catch.result.strike': 'Prima creatura del giorno:',
    'key.catch.result.total': 'Esperienza totale:',
    'key.catch.fullStorage': 'Il magazzino di creature è pieno',
    'key.catch.noItems': 'Non hai sfere magiche',
    'key.creadex.title': 'BESTIARIO',
    'key.creadex.detail.caught': 'CATTURATO: {0}',
    'key.creadex.detail.evolution': 'EVOLUZIONE',
    'key.tab.doll': 'PERSONAGGIO',
    'key.tab.artifacts': 'ARTEFATTI',
    'key.activePoint.title': 'Colonna dell\'Abbondanza',
    'key.personalization.title': 'Incantesimo',
    'key.chest.title': 'Cofano magico',
    'key.quest.daily.title': 'COMPITO',
    'key.quest.weekly.title': 'CACCIA',
    'key.quest.get': 'RICEVERE COMPITO',
    'key.quest.change': 'CAMBIARE COMPITO',
    'key.quest.progress': 'Progresso del compito: {0} su {1}',
    'key.error.quest.weekly.level': 'Devi raggiungere il livello {0} per cominciare la caccia all\'Uovo d\'Oro',
    'key.error.quest.daily.level': 'Devi raggiungere il livello {0} per ricevere il compito',
    'key.error.quest.tooFar': 'L\'Obelisco è troppo lontano',
    'key.quest.daily.descr.noQuest.title': 'Non hai compiti',
    'key.quest.daily.descr.noQuest': 'Usa gli Obelischi per ricevere un compito e ottenere il premio',
    'key.quest.daily.timer.descr': 'Potrai cambiare il compito tra:',
    'key.quest.daily.waitForNew.descr': 'Puoi ricevere un nuovo compito in: ',
    'key.quest.weekly.getFragment': 'RICEVI UN PEZZO',
    'key.quest.weekly.descr.noQuest.title': 'Non partecipi alla caccia all\'Uovo d\'Oro.',
    'key.quest.weekly.descr.noQuest': 'Usa gli Obelischi per ricevere un pezzo della mappa misteriosa e cominciare la caccia',
    'key.quest.weekly.descr.getFirstFragment': 'Ricevi il primo pezzo della mappa misteriosa per cominciare la caccia all\'Uovo d\'Oro',
    'key.quest.weekly.descr.top.notAllOpen': 'Usa gli Obelischi per ricevere i pezzi della mappa. Sbrigati, la caccia finisce tra',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Usa la pala in ogni pezzo per trovare l\'Uovo d\'Oro',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Hai già ricevuto il pezzo della mappa da questo Obelisco',
    'key.quest.weekly.descr.top.allOpen': 'Hai già ricevuto tutti i pezzi della mappa dagli Obelischi. Sbrigati, la caccia finisce tra',
    'key.quest.weekly.descr.bot.allOpen': 'Usa la pala in ogni pezzo per trovare l\'Uovo d\'Oro',
    'key.quest.weekly.descr.top.completed': 'Hai già trovato l\'Uovo d\'Oro questa settimana. La prossima caccia comincia tra',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}o',
    'key.timer.format.H_M': '{0}o {1}m',
    'key.timer.format.D': '{0}g',
    'key.timer.format.D_H': '{0}g {1}o',
    'key.creatureStorage.tab.creatures': 'CREATURE',
    'key.creatureStorage.tab.eggs': 'UOVA',
    'key.creatureStorage.multiTransferText': 'Scegli chi vuoi trasferire',
    'key.storage.creature.transfer': 'Trasferire ({0})',
    'key.error.needHigherLevelForArena': 'Devi avere il livello {0} per entrare nell\'Arena',
    'key.error.needHigherLevelForLibrary': 'Devi avere il livello {0} per entrare nella Biblioteca',
    'key.error.arenaUnderProtection': 'L\'arena è sotto custodia della Benedizione della Difesa',
    'key.error.buildingTooFar': 'L\'edificio è troppo lontanoa',
    'key.error.noAliveCreaturesForAttack': 'Non hai creature vive',
    'key.error.noHealPotion': 'Non hai pozioni',
    'key.error.noResurrectionPotion': 'Non hai pozioni di risurrezione',
    'key.error.tryAgainLater': 'Errore. Riprova',
    'key.error.alreadyHasLure': 'L\'esca è già installata',
    'key.error.cannotUseLureInDungeon': 'Non puoi usare l\'esca nella Faglia di Arcana',
    'key.error.bagIsFull': 'Non hai spazio nello zaino',
    'key.error.cantTransferCreature': 'Non puoi trasferire questa creatura',
    'key.notification.done': 'Fatto!',
    'key.modal.doYouWantToTransfer': 'Sei sicuro di voler trasferire queste creature?',
    'key.modal.youWillLoseBuddyProgress': 'Sei sicuro di voler cambiare mascotte? Il progresso per ricevere le pietre di anime verrà perso',
    'key.modal.doYouWantToLeaveDungeon': 'Vuoi abbandonare la Faglia di Arcana?',
    'key.modal.superVisionActive': 'La vista di drago è già attiva. Se la attivi di nuovo sposterai la zona magica di visualizzazione. Sei sicuro di voler usarla di nuovo?',
    'key.modal.experienceBoosterActive': 'Il cristallo della sapienza è già attivo. Sei sicuro di voler usarlo di nuovo?',
    'key.modal.youWillLooseQuestProgress': 'Il progresso del compito attuale verrà perso. Sei sicuro?',
    'key.modal.doYouWantToEnterDungeon': 'Vuoi entrare nella Faglia di attraverso il Portale?',
    'key.modal.doYouWantPersonalizePoint': 'La Colonna dell\'Abbondanza incantata darà solo {0}. Vuoi spendere {1} monete per incantarla?',
    'key.modal.doYouWantToDeletePersonalization': 'Sei sicuro di voler togliere l\'incantesimo da questa Colonna dell\'Abbondanza?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Vuoi potenziare questa creatura?',
    'key.modal.doYouWantToEvolveThisCreature': 'Vuoi trasformare questa creatura in una più forte?',
    'key.modal.doYouWantToScoutHere': 'Sei sicuro di voler illuminare questa zona?',
    'key.error.creatureHasMaxLevel': 'La creatura ha già il livello massimo',
    'key.error.creatureHasMaxLevelForUser': 'Prima devi aumentare il livello del personaggio',
    'key.error.notEnoughResourcesForEnhance': 'Non hai sufficienti risorse',
    'key.error.creatureIsArenaDefender': 'Non puoi scegliere una creatura che sta defendendo l\'edificio',
    'key.modal.incenseActive': 'I feromoni sono già attivi. Sei sicuro di voler usarli di nuovo?',
    'key.error.cantHealHealthyCreature': 'Questa creatura ha già la salute piena',
    'key.error.cantRessurectAliveCreature': 'Questa creatura è già viva',
    'key.error.noTreasureHere': 'L\'Uovo d\'Oro non è in questo pezzo della mappa. Continua a cercare',
    'key.error.levelTooSmall': 'Prima devi aumentare il livello del personaggio',
    'key.error.needHigherLevelForWizardBattles': 'Devi avere il livello {0} per partecipare nel Duello dei Maghi',
    'key.error.artifactBagIsFull': 'Non c\'è spazio nel magazzino di artefatti',
    'key.error.notEnoughCoins': 'Non hai sufficienti monete',
    'key.error.allFragmentsAreOpen': 'Tutti i pezzi della mappa misteriosa sono aperti',
    'key.error.questAlreadyCompleted': 'Hai già completato questo compito',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Hai già ricevuto il pezzo della mappa da questo Obelisco',
    'key.error.portalTooFarAway': 'Il portale è troppo lontano',
    'key.error.battleLimitAlreadyEnhanced': 'Hai già aumentato il limite di battaglie',
    'key.error.youAreNotAltarOwner': 'Solo il proprietario dell\'Altare può fare questo',
    'key.error.youAlreadyHaveAltar': 'L\'altare è già installato',
    'key.error.cantTakeAnotherUsersRune': 'Non puoi prendere la runa di un altro giocatore',
    'key.error.libraryBlocked': 'Dopo la rieducazione devi aspettare 3 giorni prima di poter usare le Biblioteche',
    'key.error.notAuthorized': 'Utente non autorizzato',
    'key.error.eggOnlyRoost': 'Devi dare questo uovo alla Madre dei Draghi',
    'key.error.purchase': 'Errore: {0}',
    'key.error.creatureIsDead': 'Prima devi risuscitare la creatura',
    'key.error.no_connection': 'Impossibile connettersi al server. Riprova più tardi.',
    'key.error.protocol_version_mismatch': 'La versione del gioco è obsoleta. Devi aggiornarla.',
    'key.error.update_application': 'La versione del gioco è obsoleta. Devi aggiornarla.',
    'key.modal.doYouWantToTransferSingle': 'Sei sicuro di voler trasferire questa creatura?',
    'key.notification.phoneNotSupportAR': 'Il tuo dispositivo è incompatibile con la AR',
    'key.notification.turnOnARPermission': 'Il gioco non ha accesso alla camera. Devi accettare il permesso nelle impostazioni del dispositivo',
    'key.notification.dailyQuestFinished': 'Compito completato!',
    'key.modal.yesBtn': 'Si',
    'key.modal.noBtn': 'No',
    'event.log.DAILY_QUEST_COMPLETED': 'Hai finito il compito giornaliere. Hai ricevuto:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'La caccia è finita. Il tuo premio:',
    'event.log.ENCOUNTER_VICTORY': 'Hai sconfitto il mostro selvaggio!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Questa versione del gioco è obsoleta. Devi aggiornarla.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Errore di autenticazione',
    'key.ServiceException.Cause.SESSION_GONE': 'Qualcuno è entrato nel tuo account da un altro dispositivo',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'Il ID di Utente è vuoto',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Utente non trovato',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'L\'account è stato bloccato per un gioco ingiusto.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'L\'account è stato bloccato per frode. Verrà sbloccato : [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'L\'account è stato bloccato per un nome di utente offensivo.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'L\'account è stato bloccato per comportamento aggressivo verso gli altri giocatori.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'L\'account è stato bloccato per gioco ingiusto.',
    'key.ServiceException.Cause.USER_BANNED': 'L\'account è stato bloccato.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Non hai spazio nello zaino',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Numero massimo di uova',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Non hai sufficienti monete',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Non hai sufficienti pietre di anime',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Non hai sufficiente essenza',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Non hai sufficiente spazio nel magazzino di creature',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'La creatura ha già raggiunto il livello massimo',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Non puoi trasformare questa creatura',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Il nome della creatura non deve superare i 16 simboli',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'E\' stato raggiunto il limite di difensori nell\'edificio',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'La tua mascotte non può mettersi in difesa dell\'edificio',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'La tua creatura è già nella difesa di quest\'edificio',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Errore',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Errore nella battaglia',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Errore',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'La tua creatura è già nella difesa di quest\'edificio',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'L\'arena è sotto la custodia della Benedizione della Difesa',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Ancora non è arrivato il momento di raccogliere il tributo',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Sfera sbagliata',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Edificio sbagliato',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Accesso negato',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Oggetto inesistente',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Ricetta inesistente',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Puoi installare un solo Altare',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Prima devi aumentare il livello del personaggio',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Impossibile cominciare la cattura della creatura',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Prodotto inesistente',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Prodotto inesistente',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Edificio inesistente',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Creatura non trovata',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Creatura non trovata',
    'key.ServiceException.Cause.TOO_FAR': 'L\'edificio è troppo lontano',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'L\'oggetto è troppo lontano',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'L\'edificio si sta ricaricando',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'L\'edificio è nella Faglia di Arcana',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Non puoi usare l\'edificio',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Bozzolo di drago non trovato',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Il bozzolo di drago è vuoto',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Il bozzolo di drago è occupato',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Non hai incubato l\'uovo',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Uovo non trovato',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Questo uovo richiede la Madre dei Draghi',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Hai finito le ricariche',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Impossibile sistemare l\'edificio',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'E\' successo un errore, e questo misterioso testo parla di esso',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Il mostro selvaggio è scappato',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Mostro selvaggio non trovato',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'In questa Colonna dell\'Abbondanza c\'è già un\'esca',
    'key.ServiceException.Cause.WRONG_ITEM': 'Oggetto sbagliato',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Questa runa è la più forte',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Ti mancano rune di questo livello',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Slot di rune sbagliato',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Questo slot è già occupato',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Lo slot della runa è vuoto',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Non puoi scegliere il difensore dell\'edificio',
    'key.ServiceException.Cause.WRONG_SPELL': 'Incantesimo sbagliato',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'L\'incantesimo richiede più rune',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Il prossimo compito non è ancora disponibile',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Hai già usato questo Obelisco',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Tutti i pezzi della mappa sono già aperti',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Non partecipi nella caccia all\'Uovo d\'Oro',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Hai già cercato di trovare l\'Uovo d\'Oro in questo posto',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Hai già usato questo dolce',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Hai già catturato la creatura',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Per ora non puoi rieducare le creature',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'La biblioteca è bloccata per ora',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Il server non risponde. Riprova più tardi.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Hai già aumentato il limite di battaglie',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Hai raggiunto il limite di battaglie',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Devi raggiungere il livello 9 per partecipare nel Duello dei Maghi',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Nessun avversario trovato per il Duello dei Maghi. Riprova più tardi',
    'key.ServiceException.Cause.MARKET_ERROR': 'Errore del negozio',
    'key.ServiceException.Cause.NO_CHEST': 'Cofano non trovato',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Errore per ottenere il pezzo. Riprova più tardi.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Devi indossare il Cuore di Drago, o il set di Artefatti di Drago per poter dare più uova alla Madre dei Draghi',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'In questa casella c\'è già un uovo',
    'key.ServiceException.Cause.NO_CONNECTION': 'Nessuna connesione a Internet',
    'key.ServiceException.Cause.SERVER_DOWN': 'Il server è temporalmente fuori uso. Riprova più tardi, per favore.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Il server è fuori uso per manutenzione. Riprova più tardi, per favore.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Stai già usando queste rune',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Ti sposti troppo veloce',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Hai raggiunto il limite di Arene conquistate',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Hai raggiunto il limite di Biblioteche conquistate',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Errore. GPS non trovato',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Non puoi usare quest\'incantesimo nella Faglia di Arcana',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Tempo scaduto',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Protocollo sbagliato. Rinnova la pagina.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Non ci sono Arene alleate nel tuo raggio di visione',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Non ci sono Arene nemiche nel tuo raggio di visione',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'sfere',
    'stop.personalized.HEALS': 'pozioni',
    'stop.personalized.RESURRECTIONS': 'rivitalizzanti',
    'stop.personalized.EGGS': 'uova di creature',
    'stop.personalized.FOODS': 'dolci',
    'key.button.cancelPersonal': 'Cancella',
    'key.error.needHigherLevelForSofaBattles': 'Devi raggiungere il livello {0} per poter partecipare nei Duelli dei Maghi',
    'fraction.text.youWilLGetBonus': 'Riceverai {0} monete per unirti a questa fazione',
    'fraction.text.fractionUnavailable': 'La fazione non è ancora disponibile',
    'fraction.text.chooseYourAlliance': 'Scegli la fazione per la quale vuoi combattere',
    'fraction.text.redFractionName': 'Ordine Rosso',
    'fraction.text.blueFractionName': 'Ordine Blu',
    'key.error.chestTooFarAway': 'Il cofano è troppo lontano',
    'key.button.openChest': 'Aprire',
    'key.candy.MONSTER_WATER_1': 'pietre di Rospus',
    'key.candy.MONSTER_WATER_2': 'pietre di Goccia',
    'key.candy.MONSTER_WATER_3': 'pietre di Spiritus',
    'key.candy.MONSTER_WATER_4': 'pietre di Sopraquian',
    'key.candy.MONSTER_WATER_8': 'pietre di Jellyhat',
    'key.candy.MONSTER_WATER_9': 'pietre di Minor',
    'key.candy.MONSTER_WATER_10': 'pietre di Infalisco',
    'key.candy.MONSTER_WATER_12': 'pietre di Dadachock',
    'key.candy.MONSTER_WATER_13': 'pietre di Batoid',
    'key.candy.MONSTER_WATER_23': 'pietre di Armaturos',
    'key.candy.MONSTER_WATER_24': 'pietre di Nettuno',
    'key.candy.MONSTER_WATER_25': 'pietre di Leviathan',
    'key.candy.MONSTER_FIRE_1': 'pietre di Potty',
    'key.candy.MONSTER_FIRE_2': 'pietre di Mummyween',
    'key.candy.MONSTER_FIRE_3': 'pietre di Vaporex',
    'key.candy.MONSTER_FIRE_4': 'pietre di Incumus',
    'key.candy.MONSTER_FIRE_6': 'pietre di Flamy',
    'key.candy.MONSTER_FIRE_7': 'pietre di Phoby',
    'key.candy.MONSTER_FIRE_11': 'pietre di Scintilla',
    'key.candy.MONSTER_FIRE_12': 'pietre di Kiddra',
    'key.candy.MONSTER_FIRE_15': 'pietre di Needlehot',
    'key.candy.MONSTER_FIRE_25': 'pietre di Smoargh',
    'key.candy.MONSTER_EARTH_1': 'pietre di Baccadil',
    'key.candy.MONSTER_EARTH_2': 'pietre di Fiorix',
    'key.candy.MONSTER_EARTH_3': 'pietre di Foglia',
    'key.candy.MONSTER_EARTH_4': 'pietre di Brownie',
    'key.candy.MONSTER_EARTH_8': 'pietre di Goblic',
    'key.candy.MONSTER_EARTH_9': 'pietre di Bellflow',
    'key.candy.MONSTER_EARTH_10': 'pietre di Nocciolus',
    'key.candy.MONSTER_EARTH_11': 'pietre di Phylo',
    'key.candy.MONSTER_EARTH_13': 'pietre di Princie',
    'key.candy.MONSTER_EARTH_25': 'pietre di Scylla',
    'key.candy.MONSTER_DUNGEON_1': 'pietre di Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'pietre di Axolan',
    'key.candy.MONSTER_DUNGEON_3': 'pietre di Pungischien',
    'key.candy.MONSTER_DUNGEON_4': 'pietre di Magglad',
    'key.candy.MONSTER_DUNGEON_5': 'pietre di Dolcigatto',
    'key.candy.MONSTER_DUNGEON_6': 'pietre di Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'pietre di Vampirus',
    'key.candy.MONSTER_DUNGEON_13': 'pietre di Advise',
    'key.candy.MONSTER_DUNGEON_17': 'pietre di Inur',
    'key.candy.MONSTER_WIND_1': 'pietre di SunTzi',
    'key.candy.MONSTER_WIND_2': 'pietre di Orecchiago',
    'key.candy.MONSTER_WIND_3': 'pietre di Funghy',
    'key.candy.MONSTER_WIND_4': 'pietre di Tenericornio',
    'key.candy.MONSTER_WIND_6': 'pietre di Gamayun',
    'key.candy.MONSTER_WIND_7': 'pietre di Paurion',
    'key.candy.MONSTER_WIND_11': 'pietre di Infird',
    'key.candy.MONSTER_WIND_12': 'pietre di Undine',
    'key.candy.MONSTER_WIND_15': 'pietre di Cheshir',
    'key.candy.MONSTER_WIND_25': 'pietre di Charybdis',
    'key.button.leaveDungeon': 'Abbandonare la faglia',
    'key.alias.enterNewAlias': 'Introduci il nome della creatura',
    'key.alias.enterText': 'Scrivi il testo...',
    'key.hut.hutName': 'Madre dei Draghi',
    'key.hut.hutDescr': 'Dai le uova antiche alla Madre dei Draghi e lei li incuberà per te',
    'key.text.noHutEggs': 'Non hai uova antiche',
    'key.text.noCapturedArenas': 'Non hai conquistato nessun\'arena',
    'key.text.noChosenPet': 'Non hai scelto nessuna mascotte',
    'key.text.noArtifacts': 'Non hai artefatti',
    'key.text.noCreatures': 'Non hai creature catturate',
    'key.text.noLureItems': 'Non hai esche',
    'key.descr.aboutWizardBattles': 'Partecipa nei Duelli contro gli altri giocatori per ottenere esperienza e premi',
    'key.text.writeToSupport': 'Scrivi al supporto',
    'key.text.regUsingFacebook': 'Registrati tramite Facebook',
    'key.text.regUsingGoogle': 'Registrati tramite Google',
    'key.text.logUsingFacebook': 'Entra tramite Facebook',
    'key.text.logUsingGoogle': 'Entra tramite Google',
    'key.text.logUsingDeviceIDCurrent': 'Entra tramite Device ID',
    'key.text.logUsingDeviceIDNew': 'Entra tramite Device ID (nuevo account)',
    'key.text.createAccount': 'Gioca',
    'key.text.connectedToFacebook': 'Connesso a Facebook',
    'key.text.connectedToGoogle': 'Connesso a Google',
    'key.text.complainAboutPoint': 'Richiama il punto',
    'key.text.copyCoordinates': 'Copia le coordinate',
    'key.text.complainEnterEmail': 'La tua e-mail',
    'key.text.complainEnterText': 'Raccontaci il tuo problema',
    'key.modal.doYouWantToCloseApp': 'Vuoi chiudere l\'app?',
    'key.catchPopup.notBad': 'Bene!',
    'key.catchPopup.good': 'Perfetto!',
    'key.catchPopup.sumptuously': 'Stupendo!',
    'key.catchPopup.twistedThrow': 'Lancio curvo!',
    'key.battlePopup.strongHit': 'Colpo forte!',
    'key.battlePopup.weakHit': 'Colpo debole',
    'key.battlePopup.dodge': 'Fallito',
    'key.battlePopup.chargedAttack': '{0} usa {1}',
    'auth.login.play': 'Gioca',
    'auth.login.nickname.placeholder': 'Introduci il nome',
    'auth.login.nickname.busy': 'Questo nome è occupato',
    'auth.login.nickname.proposal': 'Puoi usare questo nome:',
    'auth.login.nickname.deviceId': 'Hai già un personaggio',
    'auth.login.social.title': 'Entra tramite una rete sociale',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Connesso a {0}',
    'auth.login.social.signOut': 'Esci dal account',
    'auth.login.signOut.confirmation': 'Sei sicuro di voler uscire dal account?',
    'auth.login.social.userCancelledError': 'Connessione cancellata',
    'auth.login.social.cantSignInError': 'Impossibile connettersi a {0}',
    'licence.title': 'ACCORDO CON L\'UTENTE DEL GIOCO «DRACONIUS GO: CATCH A DRAGON!»',
    'licence.checkbox': 'Inviatemi le notizie e le offerte al mio e-mail',
    'licence.accept': 'Accetta',
    'licence.decline': 'Rifiuta',
    'key.error.wrongRoostIndex': 'La casella non è disponibile',
    'key.speed.passenger': 'Sono un passeggero',
    'key.activeObjects.addUnit.question': 'Sei sicuro di fare a {0} il difensore di quest\'edificio?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Sei sicuro di voler scegliere questa fazione? Questa scelta non potrà essere cambiata.',
    'key.confirm.giveUpEncounter': 'Sei sicuro di non voler combattere contro il mostro selvaggio?',
    'key.confirm.giveUpBattle': 'Sei sicuro di non voler combattere?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nuova Lega!',
};
