module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Ja',
    'key.button.cancel': 'ABBRECHEN',
    'key.button.apply': 'OK',
    'key.button.use': 'Verwenden',
    'key.button.buy': 'Kaufen',
    'key.beCarefulMessage.text': 'Sei vorsichtig während du spielst. Schau dich um.',
    'key.creature.details.attack': 'Stärke',
    'key.creature.details.health': 'Gesundheit',
    'key.creature.details.powerUp': 'Power-up',
    'key.creature.details.evolve': 'Entwickeln',
    'key.creature.details.cp': 'WP',
    'key.creature.details.cpValue': 'WP {0}',
    'key.creature.details.hp': 'KP',
    'key.creature.details.transfer': 'VERSCHICKEN',
    'key.creature.details.creadex': 'Bestiarium',
    'key.creature.registration.creadex': 'Zum Bestiarium hinzugefügt',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Gebäude besetzt',
    'key.activeObjects.library': 'Das Geschöpf in der Bibliothek neu ausbilden',
    'key.activeObjects.library.empty': 'Du hast keine Bibliothek',
    'key.activeObjects.arena': 'Den Tribut der Arenen sammeln',
    'key.activeObjects.arena.collect': 'Sammeln',
    'key.activeObjects.arena.empty': 'Du hast keine Arena',
    'key.activeObjects.error.timer': 'Der Tribut ist noch nicht fertig. Du musst warten',
    'key.activeObjects.error.noMoney': 'Erst musst du die Arena besetzen',
    'key.activeObjects.error.cannotRemaster': 'Du kannst deine Geschöpfe nicht neu ausbilden. Besetze Bibliotheken um die Stoppuhr der Ausbildung zu beschleunigen',
    'key.activeObjects.library.remaster': 'Neu ausbilden',
    'key.activeObjects.library.blocked': 'Die Bibliotheken sind nicht verfügbar',
    'key.activeObjects.remaster.confirmation.main': 'Bist du sicher, dass du das Geschöpf {0} neu ausbilden willst? Die Hauptfertigkeit {1} wird geändert!',
    'key.activeObjects.remaster.confirmation.charged': 'Bist du sicher, dass du das Geschöpf {0} neu ausbilden willst? Die geladene Fertogkeit {1} wird geändert!',
    'key.activeObjects.remaster.error': 'Fehler',
    'key.activeObjects.item.weaklyBonus': 'Wöchentliches Bonus +{0} Münzen',
    'key.library.remaster.selectCreature': 'Wähle das Geschöpf, das du neu ausbilden willst',
    'key.remasterPanel.title': 'Wähle die Fertigkeit',
    'key.storage.creatues': 'Geschöpfe',
    'key.storage.eggs': 'Eier',
    'key.storage.eggs.simple': 'Normale Eier',
    'key.storage.eggs.super': 'Antike Eier',
    'key.storage.eggs.missingAny': 'Sie haben keine Eier vom Geschöpf',
    'key.startEgg.button': 'In einem Drachenkokon ablegen',
    'key.startEgg.description': 'Verwende den Drachenkokon um das Ei auszubrüten',
    'key.startEgg.incubator.title': 'Drachenkokons',
    'key.startEgg.select.title': 'Wähle das Ei aus',
    'key.openEgg.button': 'Das Ei schlüpfen lassen',
    'key.openEgg.description': 'Ein neues Geschöpf wird aus dem Ei schlüpfen',
    'key.startEgg.description.roost.hatching': 'Die Drachenmutter brütet dieses Ei. Du musst nur warten. Das Brüten wird unterbrochen, falls die Verwerfung von Arcana, in welcher sich die Drachenmutter befindet, verschwindet',
    'key.startEgg.description.roost.notHatching': 'Gib das Ei der Drachenmutter ab, sodass sie es für dich ausbrütet.',
    'key.startEgg.description.simple.hatching': 'Dieses Ei wird im Drachenkokon bebrütet. Lauf mit geöffnetem Spiel um es auszubrüten. ',
    'key.startEgg.description.simple.notHatching': 'Leg dieses Ei in den Drachenkokon ab um es zu bebrüten. Ein Geschöpf wird schlüpfen, wenn du eine festgelegte Distanz zurücklegst',
    'key.mainMenu.wizardDuels': 'DUELL DER MAGIER',
    'key.mainMenu.quests': 'AUFGABEN',
    'key.mainMenu.activePoints': 'BESETZT',
    'key.mainMenu.creadex': 'BESTIARIUM',
    'key.mainMenu.magic': 'MAGIE',
    'key.mainMenu.creatues': 'GESCHÖPFE',
    'key.mainMenu.shop': 'LADEN',
    'key.mainMenu.backpack': 'BEUTEL',
    'key.error.banned': 'Der Account ist gesperrt',
    'event.log.CREATURE_CAUGHT': 'Du hast {0} gefangen!',
    'event.log.ITEM_BOUGHT': 'Du hast {0} x{1} gekauft. Du hast {2} Münzen ausgegeben',
    'event.log.ARTIFACT_BOUGHT': 'Du hast das Artefakt gekauft: {0}. Du hast {1} Münzen ausgegeben',
    'event.log.EGG_HATCHED': '{0} ist aus dem Ei {1} geschlüpft!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'Golden',
    'event.log.ROOST_EGG_HATCHED': 'Die Drachenmutter hat das {1}Km Ei ausgebrütet. {0} ist jetzt dein!',
    'event.log.CHEST_OPENED': 'Gefunden in der Truhe:',
    'event.log.ARENA_LOST_CONTROL': '{1} wurde vom Gebäude {0} herausgeworfen',
    'event.log.LIBRARY_LIST_CONTROL': '{1} wurde vom Gebäude {0} herausgeworfen',
    'event.log.LEVEL_UP': 'Du hast das Level {0} erreicht',
    'event.log.BUDDY_FOUND_CANDY': 'Dein Haustier hat {0} gefunden',
    'event.log.QUEST_COMPLETED': 'Belohnung für die Aufgabe {0}',
    'event.log.ENCOUNTER_LOOSE': 'Du bist vor dem wilden Monster geflüchtet',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Das Limit von Kämpfen im Duell der Magier wurde um {0} Münzen erhöht',
    'event.log.HARD_CURRENCY_BOUGHT': 'Du hast {0} Münzen für {1} gekauft',
    'event.log.UPGRADE_BAG_BOUGHT': 'Du hast den Beutel für {0} Münzen verbessert',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Du hast das Geschöpfe-Lager für {0} Münzen verbessert',
    'key.shop.accesories': 'GEGENSTÄNDE',
    'key.shop.artifacts': 'ARTEFAKTE',
    'key.shop.donate': 'MÜNZEN',
    'key.shop.upgrade': 'VERBESSERUNGEN',
    'key.shop.donate.coins': '{0} Münzen',
    'key.shop.upgrade.bag': 'den Beutel verbessern',
    'key.shop.upgrade.bag.desc': 'die Größe des Beutels wird auf 50 erhöht',
    'key.shop.upgrade.storage': 'das Geschöpfe-Lager verbessern',
    'key.shop.upgrade.storage.desc': 'die Größe des Geschöüfe-Lagers wird auf 50 erhöht',
    'key.shop.donate.dialog.title': 'Du hast nicht genug Münzen',
    'key.shop.donate.dialog.desc': 'Erhalte sie hier, oder besuche das Laden um mehr Varianten zu sehen',
    'key.potionUseMenu.title': 'Trank',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Schafft ein Portal zur Welt Arkana.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Alle Spieler ringsherum werden die Wut der Kobolde spüren',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Schafft ein Feld von Füllsäulen für 30 Minuten',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Verdoppelt die Anzahl von Belohnungen aus den Füllsäulen für 30 Minuten',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Tippe und halte über den Ort um ihn zu erleuchten und Geschöpfe zu finden',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Erhöht 30 Minuten lang den Suchradius von Geschöpfen',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Erhöht 7 Tage lang den Sichtradius für Gegenständen um 30%',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'Die nächstliegende alliierte Arena kann 30 Stunden lang von Gegnern nicht angegriffen werden',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Alle gegnerischen Arenen in deinem Sichtradius werden neutral. Nimmt den Segen des Schützes weg-',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Schafft einen Turm des Elements Feuer',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Schafft einen Turm des Elements Wasser',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Schafft einen Turm des Elements Luft',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Schafft einen Turm des Elements Erde',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Schafft einen Turm des Elements Arkana',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Arkanas Verwerfung',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Wut der Kobolde',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Füllfeld',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Gabe des goldenen Drachens',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astralsicht',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Drachensicht',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Lange Arme',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Segen des Schutzes',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Reinigung mit Feuer',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Feuerturm',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Wasserturm',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Luftturm',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Erdeturm',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Turm Arkanas',
    'key.buff.ATTACKER_CP_BOOST': 'Die WP deiner Geschöpfe wurde zeitlich erhöht',
    'key.buff.BEST_BALL_LUCK': 'Du bekommst 30 Minuten lang nur die beste Sphäre in den Füllsäulen',
    'key.buff.BEST_POTION_LUCK': 'Du bekommst 30 Minuten lang nur die beste Tränke in den Füllsäulen',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Du bekommst 30 Minuten lang +2 Gegenstände von den Füllsäulen',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Die Aufladungszeit der Bibliothek wurde reduziert',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Erhöht die WP der Geschöpfe, die verteidigen nicht die Gebäude',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Erhöht die WP der Geschöpfe, die verteidigen nicht die Gebäude',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Du bekommst von den Füllsäulen nur die beste Sphäre, die für dein Level verfügbar sind',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Du bekommst von den Füllsäulen nur die beste Tränke, die für dein Level verfügbar sind',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Du bekommst von den Füllsäulen zwei mehr Gegenstände',
    'key.loot.result.dust': 'Essenz',
    'key.loot.result.exp': 'Erfahrung',
    'key.loot.result.coin': 'Münzen',
    'key.loot.result.candy': 'Steine',
    'key.item.MAGIC_BALL_SIMPLE': 'Sphäre des Schülers',
    'key.item.MAGIC_BALL_NORMAL': 'Sphäre des Magisters',
    'key.item.MAGIC_BALL_GOOD': 'Sphäre des Herrens',
    'key.item.LURE': 'Köder',
    'key.item.INCENSE': 'Pheromone',
    'key.item.EGG': 'Ei',
    'key.item.SHOVEL': 'Schaufel',
    'key.item.POTION_HEAL_1': 'Kleiner Heiltrank',
    'key.item.POTION_HEAL_2': 'Mittlerer Heiltrank',
    'key.item.POTION_HEAL_3': 'Großer Heiltrank',
    'key.item.POTION_HEAL_4': 'Kompletter Heiltrank',
    'key.item.POTION_RESURRECTION_1': 'Beleber',
    'key.item.POTION_RESURRECTION_2': 'Großer Beleber',
    'key.item.INCUBATOR_1': 'Drachenkokon',
    'key.item.INCUBATOR_3': 'Drachenkokon',
    'key.item.INCUBATOR_PERPETUAL': 'Ewiger Drachenkokon',
    'key.item.SUPER_VISION': 'Drachensicht',
    'key.item.RUNE_1': 'Rune I',
    'key.item.RUNE_2': 'Rune II',
    'key.item.RUNE_3': 'Rune III',
    'key.item.RUNE_4': 'Rune IV',
    'key.item.RUNE_5': 'Rune V',
    'key.item.RUNE_6': 'Rune VI',
    'key.item.FOOD_CATCH_CHANCE': 'Arkanas Karamell',
    'key.item.FOOD_MORE_DUST': 'Magisches Doughnut',
    'key.item.FOOD_CALM_DOWN': 'Marshmallow des Einhornes',
    'key.item.FOOD_MORE_CANDIES': 'Eis von den vier Elementen',
    'key.item.EXPERIENCE_BOOSTER': 'Kristall der Weisheit',
    'key.item.EGG_KM_0': 'Goldenes Ei',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sphäre zum Fangen wilder Geschöpfe',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sphäre zum Fangen wilder Geschöpfe. Erhöht ein bisschen die Fangchance',
    'key.item.MAGIC_BALL_GOOD.description': 'Sphäre zum Fangen wilder Geschöpfe. Erhöht wesentlich die Fangchance',
    'key.item.LURE.description': 'Köder für die Geschöpfe. Leg es in einer Füllsäule ab um Geschöpfe  anzulocken',
    'key.item.INCENSE.description': 'Die Pheromone locken die Geschöpfe eines bestimmten Elements an, abhängig vom Wochentag',
    'key.item.EGG.description': 'Verwende den Drachenkokon um die Eier auszubrüten',
    'key.item.SHOVEL.description': 'Schaufeln sind unersetzlich zur Schatzsuche',
    'key.item.POTION_HEAL_1.description': 'Füllt 200 der KP deines Geschöpfes',
    'key.item.POTION_HEAL_2.description': 'Füllt 500 der KP deines Geschöpfes',
    'key.item.POTION_HEAL_3.description': 'Füllt 1000 der KP deines Geschöpfes',
    'key.item.POTION_HEAL_4.description': 'Füllt alle KP deines Geschöpfes',
    'key.item.POTION_RESURRECTION_1.description': 'Belebt das gewählte Geschöpf. Nach der Belebung bleibt das Geschöpf verwundet',
    'key.item.POTION_RESURRECTION_2.description': 'Belebt und füllt alle KP des Geschöpfes',
    'key.item.INCUBATOR_1.description': 'Die Drachenkokons brüten die Eier der Geschöpfe aus. Sie verschwinden nach der Verwendung',
    'key.item.INCUBATOR_3.description': 'Die Drachenkokons brüten die Eier der Geschöpfe aus. Sie verschwinden nach der dritten Verwendung',
    'key.item.INCUBATOR_PERPETUAL.description': 'Die Drachenkokons brüten die Eier der Geschöpfe aus',
    'key.item.SUPER_VISION.description': 'Zeigt dir Geschöpfe in einem weit größeren Umfeld an',
    'key.item.RUNE_1.description': 'Magische Rune Level 1',
    'key.item.RUNE_2.description': 'Magische Rune Level 2',
    'key.item.RUNE_3.description': 'Magische Rune Level 3',
    'key.item.RUNE_4.description': 'Magische Rune Level 4',
    'key.item.RUNE_5.description': 'Magische Rune Level 5',
    'key.item.RUNE_6.description': 'Magische Rune Level 6',
    'key.item.FOOD_CATCH_CHANCE.description': 'Süßigkeit zum Fangen der Geschöpfe. Erhöht die Chance, die Geschöpfe mit einer magischen Sphäre zu fangen',
    'key.item.FOOD_MORE_DUST.description': 'Süßigkeit zum Fangen der Geschöpfe. Erhöht die Anzahl von Essenz, das du für das Fangen des Geschöpfes bekommst',
    'key.item.FOOD_CALM_DOWN.description': 'Süßigkeit zum Fangen der Geschöpfe. Beruhigt die Geschöpfe. Sie hören zu springen und angreifen auf.',
    'key.item.FOOD_MORE_CANDIES.description': 'Süßigkeit zum Fangen der Geschöpfe. Erhöht die Anzahl von Seelensteinen, die du fürs Fangen eines Geschöpfes bekommst',
    'key.item.EXPERIENCE_BOOSTER.description': 'Verdoppelt 30 Minute lang die Erfahrung die du bekommst',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Maske des Magiers',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '+1 Fernplatzierung eines Geschöpfs in der Arena oder Bibliothek pro Tag',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Dieses Artefakt erlaubt Dir 1 Mal täglich ein Geschöpf in einen freien Platz in einer Arena oder in einer Bibliothek zu stationieren, welche Du auf der Karte siehst.',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Gesicht des Hellsehers',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '+2 Fernplatzierung eines Geschöpfs in der Arena oder Bibliothek pro Tag',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Dieses Artefakt erlaubt Dir 2 Mal täglich ein Geschöpf in einen freien Platz in einer Arena oder in einer Bibliothek zu stationieren, welche Du auf der Karte siehst.',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Helm des Eroberers',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '+3 Fernplatzierung eines Geschöpfs in der Arena oder Bibliothek pro Tag',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Dieses Artefakt erlaubt Dir 3 Mal täglich ein Geschöpf in einen freien Platz in einer Arena oder in einer Bibliothek zu stationieren, welche Du auf der Karte siehst.',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Helm des Helden',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '+4 Fernplatzierung eines Geschöpfs in der Arena oder Bibliothek pro Tag',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Dieses Artefakt erlaubt Dir 4 Mal täglich ein Geschöpf in einen freien Platz in einer Arena oder in einer Bibliothek zu stationieren, welche Du auf der Karte siehst.',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Helm des Drachenkriegers',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '+5 Fernplatzierung eines Geschöpfs in der Arena oder Bibliothek pro Tag',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Dieses Artefakt erlaubt Dir 5 Mal täglich ein Geschöpf in einen freien Platz in einer Arena oder in einer Bibliothek zu stationieren, welche Du auf der Karte siehst.',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Fahne des Herrschers',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Erlaubt noch ein Geschöpf in der Arena oder Bibliothek zu stationieren',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Mit diesem Artefakt kannst du zwei Geschöpfe, für die Verteidigung der Arena oder der Bibliothek, stationieren anstatt eines',
    'key.artifact.ARTIFACT_BANK_8': 'Zerschnittenes Artefakt',
    'key.artifact.ARTIFACT_BANK_8.description': 'Wie hast Du es gefunden?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Du hast ein Artefakt gesehen, welches Du nicht sehen solltest. Jetzt müssen wir Dich als Zeuge loswerden',
    'key.artifact.ARTIFACT_BANK_9': 'Zerschnittenes Artefakt',
    'key.artifact.ARTIFACT_BANK_9.description': 'Wie hast Du es gefunden?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Du hast ein Artefakt gesehen, welches Du nicht sehen solltest. Jetzt müssen wir Dich als Zeuge loswerden.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Uhr des faulen Studenten',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': 'Die Füllsäulen laden sich 20 Sekunden schneller auf',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Mit diesem Artefakt werden sich die Füllsäulen 20 Sekunden schneller aufladen und du wirst sie öfter anwenden können.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Wecker des Faulenzers',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': 'Die Füllsäulen laden sich 40 Sekunden schneller auf',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Mit diesem Artefakt werden sich die Füllsäulen 40 Sekunden schneller aufladen und du wirst sie öfter anwenden können.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Beschleuniger des Weltraums',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': 'Die Füllsäulen laden sich 60 Sekunden schneller auf',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Mit diesem Artefakt werden sich die Füllsäulen 60 Sekunden schneller aufladen und du wirst sie öfter anwenden können.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Uhr des faulen Professors',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': 'Die Füllsäulen laden sich 80 Sekunden schneller auf',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Mit diesem Artefakt werden sich die Füllsäulen 80 Sekunden schneller aufladen und du wirst sie öfter anwenden können.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Uhr  des Zebra-Hasens',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': 'Die Füllsäulen laden sich 100 Sekunden schneller auf',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Mit diesem Artefakt werden sich die Füllsäulen 100 Sekunden schneller aufladen und du wirst sie öfter anwenden können.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Zepter des Eroberers',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 zum Level der Arena oder Bibliothek nach ihrer Eroberung',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Wenn der Besitzer dieses Artefaktes in einer eroberten Arena oder Bibliothek ein Geschöpf als erster stationiert, dann bekommt die sofort das Level 5 statt des Levels 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Ring der Tributsammler',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 zur Maximalanzahl von eroberten Arenen',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Mit diesem Artefakt wirst du den Tribut von 11 Arenen sammeln können statt von 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Ring des Geizes',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 zur Maximalanzahl von eroberten Arenen',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Mit diesem Artefakt wirst Du den Tribut von 12 Arenen sammeln können statt von 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Doppelter Ring',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 zur Maximalanzahl von eroberten Arenen',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Mit diesem Artefakt wirst Du den Tribut von 13 Arenen sammeln können statt von 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Pokal des Kuchenfressers',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% zum Ruhm von alliierten Arenen und Bibliotheken während des Trainings',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Mit diesem Artefakt bekommen die alliierte Arenen und Bibliotheken um 20% mehr Ruhm wenn Du sie trainierst',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Kelch für den Honig',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% zum Ruhm von alliierten Arenen und Bibliotheken während des Trainings',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Mit diesem Artefakt bekommen die alliierte Arenen und Bibliotheken um 30% mehr Ruhm wenn Du sie trainierst',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Kelch des tiefen Denkens',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% zum Ruhm von alliierten Arenen und Bibliotheken während des Trainings',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Mit diesem Artefakt bekommen die alliierte Arenen und Bibliotheken um 40% mehr Ruhm wenn Du sie trainierst',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Gral von Lancelop',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% zum Ruhm von alliierten Arenen und Bibliotheken während des Trainings',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Mit diesem Artefakt bekommen die alliierte Arenen und Bibliotheken um 50% mehr Ruhm wenn Du sie trainierst',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Pokal des Eroberers der Monster',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% zur Erfahrung von alliierten Arenen und Bibliotheken während dem Training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Mit diesem Artefakt bekommen die alliierte Arenen und Bibliotheken um 80% mehr Ruhm wenn Du sie trainierst',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem des Hellsehers',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Hält schwache Geschöpfe vom Radar fern',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Dieses Artefakt hält schwache Geschöpfe vom Radar fern, was Dir bei der Suche nach stärkeren Geschöpfen hilft',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Regelbuch des Abenteurers',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': 'Du kannst für weitere 15 Minuten den Tribut von Arenen sammeln, nachdem sie vom Gegner erobert wurden',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Mit diesem Artefakt kannst Du für weitere 30 Minuten den Tribut von Arenen sammeln, nachdem sie erobert wurden, anstatt den üblichen 15 Minuten',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Dickes und großes Buch',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': 'Du kannst für weitere 30 Minuten den Tribut von Arenen sammeln, nachdem sie vom Gegner erobert wurden',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Mit diesem Artefakt kannst Du für weitere 45 Minuten den Tribut von Arenen sammeln, nachdem sie erobert wurden, anstatt den üblichen 15 Minuten',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tafel des Eigentums',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': 'Du kannst für weitere 45 Minuten den Tribut von Arenen sammeln, nachdem sie vom Gegner erobert wurden',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Mit diesem Artefakt kannst Du für weitere 60 Minuten den Tribut von Arenen sammeln, nachdem sie erobert wurden, anstatt den üblichen 15 Minuten',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Vertrag über die Macht',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': 'Du kannst für weitere 75 Minuten den Tribut von Arenen sammeln, nachdem sie vom Gegner erobert wurden',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Mit diesem Artefakt kannst Du für weitere 90 Minuten den Tribut von Arenen sammeln, nachdem sie erobert wurden, anstatt den üblichen 15 Minuten',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoire der Macht',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': 'Du kannst für weitere 105 Minuten den Tribut von Arenen sammeln, nachdem sie vom Gegner erobert wurden',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Mit diesem Artefakt kannst Du für weitere 120 Minuten den Tribut von Arenen sammeln, nachdem sie erobert wurden, anstatt den üblichen 15 Minuten',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Stachelhalsband',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': 'Du bekommst einen Seelenstein von Deinem Haustier 10% schneller',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Mit diesem Artefakt musst Du 10% weniger Strecke zurücklegen, damit Dein Haustier Seelensteine erhält. Dein Haustier wird auch um 17% gefährlicher',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Karotte am Stock',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': 'Du bekommst einen Seelenstein von Deinem Haustier 15% schneller',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Mit diesem Artefakt musst Du 15% weniger Strecke zurücklegen, damit Dein Haustier Seelensteine erhält. Lecker.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Rückenkratzer',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': 'Du bekommst einen Seelenstein von Deinem Haustier 25% schneller',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Mit diesem Artefakt musst Du 25% weniger Strecke zurücklegen, damit Dein Haustier Seelensteine erhält.  Beuge Dich von der Macht des Rückenkratzers!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Glöckchen des Haustiers',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': 'Du bekommst einen Seelenstein von Deinem Haustier 30% schneller',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Mit diesem Artefakt musst Du 30% weniger Strecke zurücklegen, damit Dein Haustier Seelensteine erhält.  Wer ist ein guter Junge?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Kuscheldrachen',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': 'Du bekommst einen Seelenstein von Deinem Haustier 40% schneller',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Mit diesem Artefakt musst Du 40% weniger Strecke zurücklegen, damit Dein Haustier Seelensteine erhält. Das beste Spielzeug für das beste Haustier der Welt',
    'key.artifact.ARTIFACT_ROOST_1': 'Drachenherz',
    'key.artifact.ARTIFACT_ROOST_1.description': '+ 1 Drachenkokon für die Drachenmutter',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Erlaubt Dir einen zusätzlichen Drachenkokon bei der Drachenmutter zu verwenden',
    'dialog.artifact.select_artifact': 'WÄHLE DAS ARTEFAKT',
    'dialog.artifact.confirm.remove': 'Willst du wirklich das Artefakt löschen?',
    'dialog.items.title': 'BEUTEL',
    'dialog.items.cannotUse': 'Du kannst diesen Gegenstand nicht verwenden',
    'dialog.items.remove.header': 'Gegenstände entfernen',
    'dialog.encounter.header': 'Ein wildes Monster greift Dich an!',
    'dialog.encounter.button.leave': 'Fliehen',
    'dialog.encounter.button.fight': 'Kämpfen',
    'dialog.encounter.result.outcome.win': 'Du hast das wilde Monster besiegt',
    'dialog.encounter.result.outcome.lose': 'Dein Monster wurde besiegt',
    'dialog.encounter.result.reward.dust': 'Essenz',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': 'Gib den Namen deines Avatars ein',
    'error.nickname.validation.TOO_SHORT': 'Der Name muss zwischen 3 und 16 Zeichen lang sein',
    'error.nickname.validation.TOO_LONG': 'Der Name muss zwischen 3 und 16 Zeichen lang sein',
    'error.nickname.validation.INVALID_CHAR': 'Du kannst nur Buchstaben, Ziffern und Unterstriche verwenden',
    'error.nickname.validation.DUPLICATE': 'Dieser Name existiert schon. Du kannst den Namen {0} wählen',
    'creature.MONSTER_WATER_1': 'Froschus',
    'creature.MONSTER_WATER_2': 'Tropf',
    'creature.MONSTER_WATER_3': 'Geistus',
    'creature.MONSTER_WATER_4': 'Überwasserian',
    'creature.MONSTER_WATER_5': 'Froschissimo',
    'creature.MONSTER_WATER_6': 'Bächlein',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Infalisk',
    'creature.MONSTER_WATER_11': 'Mittelwasserian',
    'creature.MONSTER_WATER_12': 'Dadachock',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisk',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Unterwasserian',
    'creature.MONSTER_WATER_18': 'Dadachum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilisk',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Crystallhat',
    'creature.MONSTER_WATER_23': 'Panzerus',
    'creature.MONSTER_WATER_24': 'Neptun',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mummyween',
    'creature.MONSTER_FIRE_3': 'Dampfex',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Fuerkralle',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dummyween',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Dampfeye',
    'creature.MONSTER_FIRE_11': 'Funk',
    'creature.MONSTER_FIRE_12': 'Kiddra',
    'creature.MONSTER_FIRE_13': 'Daemonstar',
    'creature.MONSTER_FIRE_14': 'Phoenix',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Stahlkerl',
    'creature.MONSTER_FIRE_17': 'Fuerling',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Blitz',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Fuerwerkus',
    'creature.MONSTER_FIRE_24': 'Picaroon',
    'creature.MONSTER_FIRE_25': 'Smoargh',
    'creature.MONSTER_EARTH_1': 'Beeredil',
    'creature.MONSTER_EARTH_2': 'Blümix',
    'creature.MONSTER_EARTH_3': 'Blatt',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryad',
    'creature.MONSTER_EARTH_7': 'Pflantix',
    'creature.MONSTER_EARTH_8': 'Goblic',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Eichus',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Pinientoff',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Gartenix',
    'creature.MONSTER_EARTH_20': 'Frühlan',
    'creature.MONSTER_EARTH_21': 'Erdbien',
    'creature.MONSTER_EARTH_22': 'Blümtier',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Ohrenplaf',
    'creature.MONSTER_WIND_3': 'Pilzy',
    'creature.MONSTER_WIND_4': 'Flauschhorn',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Angston',
    'creature.MONSTER_WIND_8': 'Ohrenum',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Tanzewind',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Stormhorn',
    'creature.MONSTER_WIND_14': 'Geistomo',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Pilzotopia',
    'creature.MONSTER_WIND_17': 'Harpyie',
    'creature.MONSTER_WIND_18': 'Geistumus',
    'creature.MONSTER_WIND_19': 'Puerogreif',
    'creature.MONSTER_WIND_20': 'Kissenkatze',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Hurrikdine',
    'creature.MONSTER_WIND_23': 'Greif',
    'creature.MONSTER_WIND_24': 'Baiun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Stachelrücken',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Süßkatze',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Vogelscheuche',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Genie',
    'creature.MONSTER_DUNGEON_12': 'Vampiro',
    'creature.MONSTER_DUNGEON_13': 'Advise',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Softail',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigermant',
    'creature.MONSTER_DUNGEON_21': 'Sharptail',
    'creature.MONSTER_DUNGEON_22': 'Sprossy',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Mantikor',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Haibiss',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Tiefer Schreck',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Ruf von Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Seehammer',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Wasserfaust',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Welle',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Diluvium',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Geiser',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Platschen',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Lebendige Flamme',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Feuerring',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Feuerknute',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Feuerball',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Einäschern',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Stern',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Kohle',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Flammenwerfer',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Erschießung',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Windsichel',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Riss',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Atmen',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Elektroschock',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Funke',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Elektrokonvulsion',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Drachenatem',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Blasen',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Windwut',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Giftspucke',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Schlangenzahn',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Vergiften',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Knochen reißen',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Fels',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Stein',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Waldgeist',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Baumgeist',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Naturschatten',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Arkanas Pfeil',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Schattenklumpen',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentakel der Bosheit',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Auge des Schreckens',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sphäre der Verdammnis',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Schattenball',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arkana Kadabra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Kruciarkus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Imperikanos',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Frieren',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Tiefkühlen',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Erstarren',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Wirbelsturm',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Schneesturm',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Kalte Wut',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Eisexplosion',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Eismacht',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Reinigen',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Ansteigung',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Brennen',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lava',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Feuerquelle',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteor',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Blitz',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Donner',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Sturm',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Neustart',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Elektrofeld',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Gänsehaut',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Windgebrüll',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Karussell',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Knall',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Erschüttern',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Verwerfung',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Abstürzen',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Explosion',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Steinwirbel',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'See des Todes',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Giftlache',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Säure',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomismus',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Zerlegen',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ausschneiden',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Exil',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Fluch',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Ausschließung',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Magiesturm',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Manasturm',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Arkanas Wut',
    'key.combined.first.1': 'Weisen',
    'key.combined.first.2': 'Teuflischen',
    'key.combined.first.3': 'Wunderschönen',
    'key.combined.first.4': 'Bösartigen',
    'key.combined.first.5': 'Neutralen',
    'key.combined.first.6': 'Ehrlichen',
    'key.combined.first.7': 'Heiligen',
    'key.combined.first.8': 'Antiken',
    'key.combined.first.9': 'Unterirdischen',
    'key.combined.first.10': 'Flammenden',
    'key.combined.first.11': 'Schlauen',
    'key.combined.first.12': 'Riesigen',
    'key.combined.first.13': 'Blauen',
    'key.combined.first.14': 'Unbarmherzigen',
    'key.combined.first.15': 'Gütigen',
    'key.combined.first.16': 'Luftigen',
    'key.combined.first.17': 'Irdischen',
    'key.combined.first.18': 'Roten',
    'key.combined.first.19': 'Unsterblichen',
    'key.combined.first.20': 'Toten',
    'key.combined.first.21': 'Luftigen',
    'key.combined.first.22': 'Fürchterlichen',
    'key.combined.first.23': 'Aquatischen',
    'key.combined.first.24': 'Lustigen',
    'key.combined.first.25': 'Dummen',
    'key.combined.second.1': 'Helden',
    'key.combined.second.2': 'Fische',
    'key.combined.second.3': 'Eulen',
    'key.combined.second.4': 'Übeltäter',
    'key.combined.second.5': 'Adepte',
    'key.combined.second.6': 'Magier',
    'key.combined.second.7': 'Alte Männer',
    'key.combined.second.8': 'Zauberer',
    'key.combined.second.9': 'Krieger',
    'key.combined.second.10': 'Duellanten',
    'key.combined.second.11': 'Händler',
    'key.combined.second.12': 'Hasen',
    'key.combined.second.13': 'Äpfel',
    'key.combined.second.14': 'Kämpfer',
    'key.combined.second.15': 'Betrüger',
    'key.combined.second.16': 'Ritter',
    'key.combined.second.17': 'Barbaren',
    'key.combined.second.18': 'Käfer',
    'key.combined.second.19': 'Schlangen',
    'key.combined.second.20': 'Drachen',
    'key.combined.second.21': 'Geiste',
    'key.combined.second.22': 'Kätzchen',
    'key.combined.second.23': 'Soldaten',
    'key.combined.second.24': 'Glückspilze',
    'key.combined.second.25': 'Mörder',
    'key.combined.second.26': 'Mäuse',
    'key.combined.second.27': 'Elementarwesen',
    'key.combined.second.28': 'Ermittler',
    'key.combined.second.29': 'Schamanen',
    'key.combined.second.30': 'Geistlichen',
    'key.combined.second.31': 'Engel',
    'key.combined.second.32': 'Archonen',
    'key.combined.second.33': 'Henker',
    'key.combined.second.34': 'Narren',
    'key.combined.second.35': 'Mutigen',
    'key.combined.second.36': 'Gutmenschen',
    'key.combined.second.37': 'Feiglinge',
    'key.combined.second.38': 'Minnesänger',
    'key.combined.second.39': 'Dompteure',
    'key.combined.second.40': 'Verteidiger',
    'key.combined.arena': 'Arena der {0} {1} ',
    'key.combined.library': 'Bibliothek der {0} {1} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Wasser',
    'element.type.WIND': 'Wind',
    'element.type.FIRE': 'Feuer',
    'element.type.EARTH': 'Erde',
    'element.type.DUNGEON': 'Arkana',
    'spell.type.ACTIVATION_RADIUS': 'Sichtradius',
    'spell.type.VISION_RADIUS': 'Drachensicht',
    'spell.type.STOP_FIELD': 'Füllfeld',
    'spell.type.SCOUT': 'Erforschen',
    'spell.type.PROTECT_ARENA': 'Die Arena verteidigen',
    'spell.type.CREATE_PORTAL': 'Ein Portal schaffen',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Doppelter drop',
    'spell.type.SLUG_PLAYERS': 'Langsame Spieler',
    'quest.title.WIN_ARENA_MONSTER': 'Vorherrschaft',
    'quest.title.OPEN_EGGS': 'Eierfieber',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Gebietskontrolle',
    'quest.title.CAPTURE_LIBRARY': 'Wissensdrang',
    'quest.title.CAPTURE_WILD_MONSTER': 'Drachenpark',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Element Jagd',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Suche nach den  Arkana geborenen',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Die Verwerfung reinigen',
    'quest.title.OPEN_CHEST': 'Antike Schätze',
    'quest.title.CHAIN_OF_STOP': 'Weg der Fülle',
    'quest.desc.WIN_ARENA_MONSTER': 'Besiege die Geschöpfe in den Arenen oder Bibliotheken. Du kannst das Geschöpf desselben Typs nicht zweimal besiegen',
    'quest.desc.OPEN_EGGS': 'Brüte Geschöpfe aus Eiern, mit der Hilfe von Drachenkokons oder der Drachenmutter, aus',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Sammle den Tribut der eroberten Arenen',
    'quest.desc.CAPTURE_LIBRARY': 'Habe die benötigte Anzahl von Bibliotheken',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Es gibt nie zu viele Geschöpfe. Reise und fange welche',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Reise und fange Wasser-Element Geschöpfe',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Reise und fange Luft-Element Geschöpfe',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Reise und fange Feuer-Element Geschöpfe',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Reise und fange Erd-Element Geschöpfe',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Reise und fange Arkana-Element Geschöpfe',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Besuche die Verwerfung Arkanas, um die Drachenmutter zu finden',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Besuche die Verwerfung Arkanas und fange alle Geschöpfe die Du finden kannst',
    'quest.desc.OPEN_CHEST': 'Finde und öffne die Schatztruhen',
    'quest.desc.CHAIN_OF_STOP': 'Gehe entlang der Reihe von Füllsäulen und aktiviere sie. Jede Säule wird gekennzeichnet sein',
    'quest.dialog.completed.rewardtext': 'Deine Belohnung:',
    'key.tab.altar.title': 'ALTAR',
    'key.altar.remove': 'Entfernen',
    'key.altar.put': 'Einrichten',
    'key.altar.convert': 'Umwandeln',
    'key.altar.shared': 'Den anderen zeigen',
    'key.altar.pass.placeholder': 'Hier kannst du dein Passwort eingeben',
    'key.altar.pass.error': 'Das Passwort muss mindestens {0} Zeichen lang sein',
    'key.altar.level.error': 'Du musst Level {0} erreichen um den Altar nutzen zu können',
    'key.altar.recipe.change': 'Willst du wirklich das Rezept ändern? Die Runen werden zu ihren Besitzern zurückgesendet',
    'key.altar.row.title': 'Um Magie erschaffen zu können brauchst Du einen Altar',
    'key.altar.rune.descr.RUNE_1': '3 graue Runen = eine Orange',
    'key.altar.rune.descr.RUNE_2': '3 orange Runen = eine Blaue',
    'key.altar.rune.descr.RUNE_3': '3 blaue Runen = eine Smaragdgrüne',
    'key.altar.rune.descr.RUNE_4': '3 smaragdgrüne Runen = eine Rote',
    'key.altar.rune.descr.RUNE_5': '3 rote Runen = eine Violette',
    'key.altar.rune.descr.RUNE_6': 'Violette Runen sind die stärksten',
    'error.altar.cannotRemove': 'Du kannst deinen Altar nicht entfernen',
    'error.altar.cannotConvert': 'Du kannst nicht genug Runen',
    'key.tab.altar.recipes': 'REZEPTE',
    'key.altar.noRecipes': 'Du hast keine Rezepte',
    'key.altar.header': 'Lege die Runen auf den Altar um einen Zauberspruch zu erschaffen',
    'key.altar.castBtn': 'Erschaffen',
    'key.altar.recipe.select': 'Wähle den benötigten Zauberspruch',
    'key.altar.castDone': 'Der Zauberspruch wurde erschafft',
    'key.arena.protected.ally': 'Protected:',
    'key.avatarCustomization.title': 'Wähle das Aussehen deines Avatars',
    'key.buddy.walkDescription': 'Spaziere mit deinem Haustier um {0} zu bekommen',
    'key.buddy.totalWalked': 'Du hast schon {0} Km zurückgelegt',
    'key.account.balance': 'Rohstoffe:',
    'key.account.userLevel': '{0} lvl',
    'key.account.totalDistance': 'Zurückgelegte Distanz: {0} Kilometer',
    'key.acount.registerDate': 'Anfang des Spiels: {0}',
    'key.storage.sort.name': 'NAME',
    'key.storage.sort.cp': 'WP',
    'key.storage.sort.group1': 'GRÜNE LISTE',
    'key.storage.sort.group2': 'GELBE LISTE',
    'key.storage.sort.group3': 'ROTE LISTE',
    'key.storage.sort.date': 'DATUM',
    'key.account.options.jurnal': 'VERLAUF',
    'key.account.options.buddy': 'HAUSTIER',
    'key.account.options.artifacts': 'ARTEFAKTE',
    'key.account.options.style': 'AUSSEHEN',
    'key.error.gps.permission': 'Der GPS Zugriff wurde verweigert. Bitte erlauben Sie den GPS-Zugriff in Anwendungsberechtigungen, um weiter spielen zu können',
    'key.error.gps.disabled': 'Das GPS ist deaktiviert. Schalte das GPS ein um weiter zu spielen',
    'key.error.gps.fakePosition': 'You cannot play without GPS',
    'key.error.gps.signal.notFound': 'Kein GPS-Signal',
    'key.error.gps.signal.bad': 'Das Spiel ist nicht verfügbar. Das GPS-Signal ist zu schwach',
    'key.error.internet.notReachable': 'Keine Internetverbindung',
    'key.journal.title': 'Verlauf',
    'key.journal.yesterday': 'Gestern',
    'key.settings.title': 'Einstellungen',
    'key.settings.music': 'Musik',
    'key.settings.deviceAuthError': 'Aus Sicherheitsgründen verknüpfen Sie den Account mit Google oder Facebook',
    'key.settings.sounds': 'Ton',
    'key.settings.vibration': 'Vibration',
    'key.settings.batterySaver': 'Energiesparen',
    'key.settings.support': 'An den Kundendienst schreiben ',
    'key.settings.logout': 'Ausloggen',
    'key.settings.auth.deviceid': 'ID des Geräts',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Verbinden',
    'key.settings.languageTitle': 'Sprache',
    'key.settings.language': 'Deutsch',
    'key.battle.result.win': 'Der Kampf ist vorbei',
    'key.battle.result.lose': 'Der Kampf ist vorbei',
    'key.wizardBattle.result.win': 'VICTORY!',
    'key.wizardBattle.result.lose': 'LOSE!',
    'key.battle.result.monster': 'Gewonnte Geschöüfe',
    'key.battle.result.exp': 'Bekommene Erfahrung',
    'key.battle.result.prestige_strong_enemy': 'Bonus zum Ruhm für starke Gegner',
    'key.battle.result.exp_strong_enemy': 'Bonus zur Erfahrung für starke Gegner',
    'key.battle.result.prestige_killed_all': 'Bonus zum Ruhm für das Töten aller Gegnern',
    'key.battle.result.exp_killed_all': 'Bonus zur Erfahrung für das Töten aller Gegnern',
    'key.battle.result.dust': 'Essenz',
    'key.radar.title': 'Geschöpfe in der Nähe',
    'key.levelUp.title': 'Neues Level!',
    'key.wizardBattle.left': 'Kampflimit:',
    'key.wizardBattle.timer': 'Das Limit wird zurückgesetzt in',
    'key.wizardBattle.enhance.title': 'LIMIT ERHÖHEN',
    'key.wizardBattle.enhance.desc': 'Das Limit kann bis auf 7 Kämpfe täglich für eine Woche erhöht werden',
    'key.wizardBattle.enhance.btn': 'Erhöhen',
    'key.wizardBattle.lookingForOpponent': 'Suche einen Gegner für das Duell...',
    'key.catch.result.expMonster': 'Erfahrung fürs Fangen:',
    'key.catch.result.expMonsterNew': 'Neu im Bestiarium:',
    'key.catch.result.expAccurate': 'Guter Wurf:',
    'key.catch.result.expSpin': 'Kurver Wurf:',
    'key.catch.result.strike': 'Erster Fang des Tages:',
    'key.catch.result.total': 'Erfahrung insgesamt:',
    'key.catch.fullStorage': 'Das Geschöpfe-Lager ist voll',
    'key.catch.noItems': 'Du hast keine magische Sphäre',
    'key.creadex.title': 'BESTIARIUM',
    'key.creadex.detail.caught': 'GEFANGEN: {0}',
    'key.creadex.detail.evolution': 'EVOLUTION',
    'key.tab.doll': 'AVATAR',
    'key.tab.artifacts': 'ARTEFAKTE',
    'key.activePoint.title': 'Füllsäule',
    'key.personalization.title': 'Bezauberung',
    'key.chest.title': 'Magische Truhe',
    'key.quest.daily.title': 'AUFGABE',
    'key.quest.weekly.title': 'JAGD',
    'key.quest.get': 'AUFGABE BEKOMMEN',
    'key.quest.change': 'AUFGABE ÄNDERN',
    'key.quest.progress': 'Fortschritt der Aufgabe: {0} von {1}',
    'key.error.quest.weekly.level': 'Du musst Level {0} erreichen um die Jagd auf das Goldenen Ei zu beginnen',
    'key.error.quest.daily.level': 'Du musst Level {0} erreichen um eine Aufgabe zu bekommen',
    'key.error.quest.tooFar': 'Der Obelisk ist zu weit entfernt',
    'key.quest.daily.descr.noQuest.title': 'Du hast keine Aufgabe',
    'key.quest.daily.descr.noQuest': 'Benutze die Obelisken um eine Aufgabe zu bekommen und die Belohnung dafür zu erhalten',
    'key.quest.daily.timer.descr': 'Du kannst die Aufgabe ändern in:',
    'key.quest.daily.waitForNew.descr': 'Du nimmst an der Jagd auf das Goldenen Ei nicht teil: ',
    'key.quest.weekly.getFragment': 'EINEN AUSSCHNITT BEKOMMEN',
    'key.quest.weekly.descr.noQuest.title': 'Du nimmst an der Jagd auf das Goldenen Ei nicht teil:',
    'key.quest.weekly.descr.noQuest': 'Benutze die Obelisken um einen Ausschnitt von der mysteriösen Karte zu bekommen und die Jagd zu beginnen',
    'key.quest.weekly.descr.getFirstFragment': 'Bekomme den ersten Ausschnitt von der mysteriösen Karte um die Jagd auf das Goldenen Ei zu beginnen',
    'key.quest.weekly.descr.top.notAllOpen': 'Benutze Obelisken um Ausschnitte der Karte zu bekommen. Beeile dich, die Jagd endet in:',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Verwende die Schaufel für jeden Ausschnitt, um das Goldenen Ei zu finden',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Du hast bereits den Ausschnitt der Karte von diesem Obelisken bekommen',
    'key.quest.weekly.descr.top.allOpen': 'Du hast schon alle Ausschnitte der Karte von diesem Obelisken bekommen. Beeile dich, die Jagd endet in ',
    'key.quest.weekly.descr.bot.allOpen': 'Verwende die Schaufel in jedem Ausschnitt um das Goldenen Ei zu finden',
    'key.quest.weekly.descr.top.completed': 'Du hast das Goldenen Ei in dieser Woche schon gefunden. Die nächste Jagd beginnt in',
    'key.timer.format.S': '{0}Sek',
    'key.timer.format.M': '{0}Min',
    'key.timer.format.M_S': '{0}Min {1}Sek',
    'key.timer.format.H': '{0}Std',
    'key.timer.format.H_M': '{0}Std {1}Min',
    'key.timer.format.D': '{0}T',
    'key.timer.format.D_H': '{0}T {1}Std',
    'key.creatureStorage.tab.creatures': 'GESCHÖPFE',
    'key.creatureStorage.tab.eggs': 'EIER',
    'key.creatureStorage.multiTransferText': 'Wähle welches Geschöpf Du weggeben werden soll',
    'key.storage.creature.transfer': '({0}) weggeben',
    'key.error.needHigherLevelForArena': 'Du brauchst Level {0} um der Arena beizutreten',
    'key.error.needHigherLevelForLibrary': 'Du brauchst Level {0} um der Bibliothek beizutreten',
    'key.error.arenaUnderProtection': 'Die Arena ist unter dem Schutz des Segens des Schutzes',
    'key.error.buildingTooFar': 'Das Gebäude ist zu weit entfernt',
    'key.error.noAliveCreaturesForAttack': 'Du hast keine lebendigen Geschöpf',
    'key.error.noHealPotion': 'Du hast kein Trank',
    'key.error.noResurrectionPotion': 'Du hast kein Beleber',
    'key.error.tryAgainLater': 'Fehler. Versuche es später noch einmal',
    'key.error.alreadyHasLure': 'Der Köder wurde ausgelegt',
    'key.error.cannotUseLureInDungeon': 'The lure can\'t be used in the Rift of Arcana',
    'key.error.bagIsFull': 'Du hast kein Platz im Beutel',
    'key.error.cantTransferCreature': 'Es ist unmöglich dieses Geschöpf wegzugeben',
    'key.notification.done': 'Fertig!',
    'key.modal.doYouWantToTransfer': 'Willst du wirklich diese Geschöpfe weggeben?',
    'key.modal.youWillLoseBuddyProgress': 'Willst du wirklich Dein Haustier ändern? Der Fortschritt um den Seelenstein zu bekommen wird verloren gehen.',
    'key.modal.doYouWantToLeaveDungeon': 'Willst du die Verwerfung Arkanas verlassen?',
    'key.modal.superVisionActive': 'Die Drachensicht ist schon aktiviert. Wenn du es neu aktivierst, wird die Sichtzone umgesetzt. Willst du wirklich es neu aktivieren?',
    'key.modal.experienceBoosterActive': 'Der Kristall der Weisheit wurde bereits aktiviert. Willst du ihn wirklich erneut benutzen?',
    'key.modal.youWillLooseQuestProgress': 'Der Fortschritt der aktuelle Aufgabe wird verloren gehen. Bist du sicher?',
    'key.modal.doYouWantToEnterDungeon': 'Willst du in die Verwerfung Arkanas durch den Portal beitreten?',
    'key.modal.doYouWantPersonalizePoint': 'Die verzauberte Fullsaule wird nur {0} geben. Willst du {1} Münzen fur die Verzauberung der Fullsaule ausgeben?',
    'key.modal.doYouWantToDeletePersonalization': 'Willst du wirklich den Zauber von dieser Füllsäule entfernen?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Willst du dieses Geschöpf verstärken?',
    'key.modal.doYouWantToEvolveThisCreature': 'Willst du dieses Geschöpf sich entwickeln lassen?',
    'key.modal.doYouWantToScoutHere': 'Willst du wirklich dieses Gebiet erkunden?',
    'key.error.creatureHasMaxLevel': 'Das Geschöpf hat bereits des maximale Level erreicht',
    'key.error.creatureHasMaxLevelForUser': 'Erst musst du dein Level steigen',
    'key.error.notEnoughResourcesForEnhance': 'Du hast nicht genug Rohstoffe',
    'key.error.creatureIsArenaDefender': 'Du kannst kein Geschöpf wählen, welches ein Gebäude verteidigt',
    'key.modal.incenseActive': 'Die Pheromone wurden schon aktiviert. Willst du Sie wirklich erneut aktivieren?',
    'key.error.cantHealHealthyCreature': 'Dieses Geschöpf wurde vollständig geheilt',
    'key.error.cantRessurectAliveCreature': 'Dieses Geschöpf lebt bereits',
    'key.error.noTreasureHere': 'Das Goldenen Ei befindet sich nicht in diesem Ausschnitt. Suche weiter',
    'key.error.levelTooSmall': 'Erst musst du dein Level steigen',
    'key.error.needHigherLevelForWizardBattles': 'Du brauchst mindestens Level {0} um an den Duellen der Magier teilzunehmen',
    'key.error.artifactBagIsFull': 'Nicht genug Platz im Artefaktenlager',
    'key.error.notEnoughCoins': 'Du hast nicht genug Münzen',
    'key.error.allFragmentsAreOpen': 'Alle Ausschnitte der mysteriösen Karte wurden geöffnet',
    'key.error.questAlreadyCompleted': 'Diese Aufgabe wurde bereits erledigt',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Du hast schon den Ausschnitt der Karte von diesem Obelisk bekommen',
    'key.error.portalTooFarAway': 'Das Portal ist zu weit entfernt',
    'key.error.battleLimitAlreadyEnhanced': 'Das Kampflimit wurde erhöht',
    'key.error.youAreNotAltarOwner': 'Nur der Besitzer des Altars kann das machen',
    'key.error.youAlreadyHaveAltar': 'Der Altar wurde schon eingerichtet',
    'key.error.cantTakeAnotherUsersRune': 'Du kannst die Rune eines anderen Spielers nicht nehmen',
    'key.error.libraryBlocked': 'Du musst 3 Tage nach der Umschulung wwarten, bis du die Bibliotheken wieder benutzen kannst',
    'key.error.notAuthorized': 'Der Benutzer ist nicht autorisiert',
    'key.error.eggOnlyRoost': 'Du musst dieses Ei der Drachenmutter geben',
    'key.error.purchase': 'Fehler: {0}',
    'key.error.creatureIsDead': 'Du musst zuerst die Kreatur wiederbeleben',
    'key.error.no_connection': 'Keine Serververbindung. Versuche es später noch einmal.',
    'key.error.protocol_version_mismatch': 'Diese Version des Spieles ist veraltet. Du sollst sie aktualisieren.',
    'key.error.update_application': 'Diese Version des Spieles ist veraltet. Ein Update ist erforderlich.',
    'key.modal.doYouWantToTransferSingle': 'Willst du wirklich dieses Geschöpf weggeben?',
    'key.notification.phoneNotSupportAR': 'AR wird von Ihrem Gerät nicht unterstützt',
    'key.notification.turnOnARPermission': 'Das Spiel hat keinen Zugriff auf die Kamera. Du musst das Zugriffsrecht in den Einstellungen des Gerätes akzeptieren',
    'key.notification.dailyQuestFinished': 'Aufgabe erfüllt!',
    'key.modal.yesBtn': 'Ja',
    'key.modal.noBtn': 'Nein',
    'event.log.DAILY_QUEST_COMPLETED': 'Du hast die tägliche Aufgabe beendet. Du bekommst:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Die Jagd ist beendet! Du bekommst:',
    'event.log.ENCOUNTER_VICTORY': 'Du hast das wilde Monster besiegt!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Diese Version des Spieles ist veraltet. Du musst sie aktualisieren.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Authentifizierungsfehler',
    'key.ServiceException.Cause.SESSION_GONE': 'Jemand hat sich in deinem Account von einem anderen Gerät angemeldet',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'Die Benutzer ID ist leer',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Benutzer nicht gefunden',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Der Account wurde wegen unfairem Spielens gesperrt',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Der Account wurde wegen betrügerischen Zahlungen gesperrt',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Der Account wurde wegen einem beleidigendem Benutzernamen gesperrt',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Der Account wurde wegen aggressiven Verhalten gegenüber anderen Spielern  gesperrt',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Der Account wurde wegen unfairem Spielens gesperrt',
    'key.ServiceException.Cause.USER_BANNED': 'Der Account wurde gesperrt',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Es gibt kein Platz im Beutel',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maximalanzahl von Eiern',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Du hast nicht genug Münzen',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Du hast nicht genug Seelensteine',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Du hast nicht genug Essenz',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Du hast nicht genug Raum im Geschöpfe-Lager',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Das Geschöpf hat bereits das maximalen Level erreicht',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Du kannst dieses Geschöpf nicht entwickeln',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Der Name des Geschöpfes kann nur 14 Zeichen lang sein',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Verteidigerlimit im Gebäude erreicht',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Dein Haustier kann das Gebäude nicht verteidigen',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Dein Geschöpf verteidigt bereits dieses Gebäude',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Fehler',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Kampf nicht gefunden',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Fehler',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Dein Geschöpf verteidigt bereits dieses Gebäude',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Diese Arena wird beschützt durch den Segen der Verteidigung',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Es ist noch nicht an der Zeit für das Sammeln der Tribute',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Falsche Sphäre',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Falsches Gebäude',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Zugriff  verweigert',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Unbedeutender Gegenstand',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Unbedeutendes Rezept',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Du kannst nur einen Altar einrichten',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Erst musst du im Level steigen',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Das Fangen wurde unmöglich',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Unbedeutendes Produkt',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Unbedeutendes Produkt',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Unbedeutendes Gebäude',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Geschöpf nicht gefunden',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Geschöpf nicht gefunden',
    'key.ServiceException.Cause.TOO_FAR': 'Das Gebäude ist zu weit entfernt',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Das Gegenstand ist zu wei entfernt',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Das Gebäude lädt sich gerade auf',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Das Gebäude befindet sich in der Verwerfung Arkanas',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Das Gebäude kann nicht benutzt werden',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Drachenkokon nicht gefunden',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Der Drachenkokon ist leer',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Der Drachenkokon ist besetzt',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Das Ei ist noch nicht ausgebrütet',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Ei nicht gefunden',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Für dieses Ei brauchst du die Drachenmutter',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Du hast keine Aufladungen mehr',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Du kannst das Gebäude nicht setzen',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Es ist ein Fehler aufgetreten und diese mysteriösen Nachricht geht darüber',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Das wilde Monster ist geflohen',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Kein wildes Monster gefunden',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'Es gibt schon einen Köder an dieser Säule',
    'key.ServiceException.Cause.WRONG_ITEM': 'Falscher Gegenstand',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Diese Rune ist die stärkste',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Du hast nicht genug Runen von diesem Level',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Falscher Runensteckplatz',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Dieser Steckplatz ist bereits besetzt',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Der Runensteckplatz ist leer',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Du kannst den Verteidiger des Gebäudes nicht wählen',
    'key.ServiceException.Cause.WRONG_SPELL': 'Unkorrekter Zauberspruch',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Es sind mehr Runen für den Zauberspruch erforderlich',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Die nächste Aufgabe ist noch nicht verfügbar',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Du hast diesen Obelisk schon benutzt',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Alle Ausschnitte der Karte wurden bereits geöffnet',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Du nimmst nicht an der Jagd auf das Goldenen Ei teil',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Du hast schon versucht das Goldenen Ei an diesem Ort zu finden',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Du hast diese Leckerei schon benutzt',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Du hast das Geschöpf bereits gefangen',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Du kannst das Geschöpf noch nicht neu ausbilden',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Die Bibliotheken sind zur Zeit nicht verfügbar',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Der Server antwortet nicht. Versuche es bitte später.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Du hast das Kampflimit bereits erhöht',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Du hast den Kampflimit erreicht',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Du musst Level 9 erreichen um an den Duellen der Magier teilzunehmen',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Kein Gegner für das Duell der Magier gefunden, versuche es später noch einmal',
    'key.ServiceException.Cause.MARKET_ERROR': 'Fehler des Shops',
    'key.ServiceException.Cause.NO_CHEST': 'Truhe nicht gefunden',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Fehler beim Bekommen des Ausschnitts. Versuche es später erneut.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Kein Gegner für das Duell der Magier gefunden, versuche es später erneut',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Es gibt schon ein Ei in diesem Feld',
    'key.ServiceException.Cause.NO_CONNECTION': 'Keine Internetverbindung',
    'key.ServiceException.Cause.SERVER_DOWN': 'Der Spielserver ist zeitlich nicht verfügbar. Versuche es bitte später.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Der Spielserver ist wegen Unterhaltsarbeiten nicht verfügbar. Versuche es bitte später.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Diese Rune werden gerade verwendet',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Du bewegst dich zu schnell',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Du hast dein Limit fürs besetzten von Arenen erreicht',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Du hast dein Limit fürs besetzten von Bibliotheken erreicht',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Fehler: GPS nicht verfügbar',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Dieser Zauberspruch kann in der Verwerfung Arkanas nicht verwendet werden',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Die Zeit ist zu Ende',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Diese Version ist veraltet. Ein Update ist erforderlich.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Es gibt keine alliierte Arena in deinem Sichtradius',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Es gibt keine gegnerische Arena in deinem Sichtradius',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'Sphäre fürs Geschöpfe fangen',
    'stop.personalized.HEALS': 'Tränke',
    'stop.personalized.RESURRECTIONS': 'Beleber',
    'stop.personalized.EGGS': 'Eier der Geschöpfe',
    'stop.personalized.FOODS': 'Leckereien',
    'key.button.cancelPersonal': 'Abbrechen',
    'key.error.needHigherLevelForSofaBattles': 'Du musst Level {0} erreichen, um an den Duellen der Magier teilzunehmen',
    'fraction.text.youWilLGetBonus': 'Du wirst {0} Münzen erhalten, wenn du dich dieser Faktion anschließt',
    'fraction.text.fractionUnavailable': 'Diese Fraktion ist zur Zeit nicht verfügbar',
    'fraction.text.chooseYourAlliance': 'Wähle eine Fraktion, welcher du dich anschließen willst',
    'fraction.text.redFractionName': 'Roter Orden',
    'fraction.text.blueFractionName': 'Blauer Orden',
    'key.error.chestTooFarAway': 'Die Truhe ist zu weit entfernt',
    'key.button.openChest': 'Öffnen',
    'key.candy.MONSTER_WATER_1': 'Steine von Froschus',
    'key.candy.MONSTER_WATER_2': 'Steine von Tropf',
    'key.candy.MONSTER_WATER_3': 'Steine von Geistus',
    'key.candy.MONSTER_WATER_4': 'Steine von Überwasserian',
    'key.candy.MONSTER_WATER_8': 'Steine von Jellyhat',
    'key.candy.MONSTER_WATER_9': 'Steine von Minor',
    'key.candy.MONSTER_WATER_10': 'Steine von Infalisk',
    'key.candy.MONSTER_WATER_12': 'Steine von Dadachock',
    'key.candy.MONSTER_WATER_13': 'Steine von Batoid',
    'key.candy.MONSTER_WATER_23': 'Steine von Panzerus',
    'key.candy.MONSTER_WATER_24': 'Steine von Neptun',
    'key.candy.MONSTER_WATER_25': 'Steine von Leviathan',
    'key.candy.MONSTER_FIRE_1': 'Steine von Potty',
    'key.candy.MONSTER_FIRE_2': 'Steine von Mummyween',
    'key.candy.MONSTER_FIRE_3': 'Steine von Dampfex',
    'key.candy.MONSTER_FIRE_4': 'Steine von Incumus',
    'key.candy.MONSTER_FIRE_6': 'Steine von Flamy',
    'key.candy.MONSTER_FIRE_7': 'Steine von Phoby',
    'key.candy.MONSTER_FIRE_11': 'Steine von Funk',
    'key.candy.MONSTER_FIRE_12': 'Steine von Kiddra',
    'key.candy.MONSTER_FIRE_15': 'Steine von Needlehot',
    'key.candy.MONSTER_FIRE_25': 'Steine von Smoargh',
    'key.candy.MONSTER_EARTH_1': 'Steine von Beeredil',
    'key.candy.MONSTER_EARTH_2': 'Steine von Blümix',
    'key.candy.MONSTER_EARTH_3': 'Steine von Blatt',
    'key.candy.MONSTER_EARTH_4': 'Steine von Brownie',
    'key.candy.MONSTER_EARTH_8': 'Steine von Goblic',
    'key.candy.MONSTER_EARTH_9': 'Steine von Bellflow',
    'key.candy.MONSTER_EARTH_10': 'Steine von Eichus',
    'key.candy.MONSTER_EARTH_11': 'Steine von Phylo',
    'key.candy.MONSTER_EARTH_13': 'Steine von Princie',
    'key.candy.MONSTER_EARTH_25': 'Steine von Scylla',
    'key.candy.MONSTER_DUNGEON_1': 'Steine von Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'Steine von Axolan',
    'key.candy.MONSTER_DUNGEON_3': 'Steine von Stachelrücken',
    'key.candy.MONSTER_DUNGEON_4': 'Steine von Magglad',
    'key.candy.MONSTER_DUNGEON_5': 'Steine von Süßkatze',
    'key.candy.MONSTER_DUNGEON_6': 'Steine von Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'Steine von Vampiro',
    'key.candy.MONSTER_DUNGEON_13': 'Steine von Advise',
    'key.candy.MONSTER_DUNGEON_17': 'Steine von Inur',
    'key.candy.MONSTER_WIND_1': 'Steine von SunTzi',
    'key.candy.MONSTER_WIND_2': 'Steine von Ohrenplaf',
    'key.candy.MONSTER_WIND_3': 'Steine von Pilzy',
    'key.candy.MONSTER_WIND_4': 'Steine von Flauschhorn',
    'key.candy.MONSTER_WIND_6': 'Steine von Gamayun',
    'key.candy.MONSTER_WIND_7': 'Steine von Angston',
    'key.candy.MONSTER_WIND_11': 'Steine von Infird',
    'key.candy.MONSTER_WIND_12': 'Steine von Undine',
    'key.candy.MONSTER_WIND_15': 'Steine von Cheshir',
    'key.candy.MONSTER_WIND_25': 'Steine von Charybdis',
    'key.button.leaveDungeon': 'Verwerfung verlassen',
    'key.alias.enterNewAlias': 'Gib den Namen des Geschöpfes ein',
    'key.alias.enterText': 'Schreibe einen Text...',
    'key.hut.hutName': 'Drachenmutter',
    'key.hut.hutDescr': 'Gib die antiken Eier bei der Drachenmutter ab und sie wird sie für Dich ausbrüten',
    'key.text.noHutEggs': 'Du hast kein antikes Ei',
    'key.text.noCapturedArenas': 'Du hast keine Arena besetzt',
    'key.text.noChosenPet': 'Du hast kein Haustier ausgewählt',
    'key.text.noArtifacts': 'Du hast kein Artefakt',
    'key.text.noCreatures': 'Du hast keine gefangenen Geschöpfe',
    'key.text.noLureItems': 'Du hast keine Köder',
    'key.descr.aboutWizardBattles': 'Nimm an Duellen gegen andere Spieler teil und bekomme Erfahrung und Belohnungen',
    'key.text.writeToSupport': 'An den Kundendienst schreiben',
    'key.text.regUsingFacebook': 'Sich über Facebook registrieren',
    'key.text.regUsingGoogle': 'Sich über Google registrieren',
    'key.text.logUsingFacebook': 'Sich über Facebook anmelden',
    'key.text.logUsingGoogle': 'Sich über Google anmelden',
    'key.text.logUsingDeviceIDCurrent': 'Sich über Device ID anmelden',
    'key.text.logUsingDeviceIDNew': 'Sich über Device ID anmelden (neuer Account)',
    'key.text.createAccount': 'Spielen',
    'key.text.connectedToFacebook': 'Mit Facebook verbunden',
    'key.text.connectedToGoogle': 'Mit Google verbunden',
    'key.text.complainAboutPoint': 'Sich über diesen Ort beschweren',
    'key.text.copyCoordinates': 'Koordinate kopieren',
    'key.text.complainEnterEmail': 'Deine E-Mail-Adresse',
    'key.text.complainEnterText': 'Erzähl uns dein Problem',
    'key.modal.doYouWantToCloseApp': 'Willst du die App schließen?',
    'key.catchPopup.notBad': 'Gut!',
    'key.catchPopup.good': 'Prima!',
    'key.catchPopup.sumptuously': 'Augezeichnet!',
    'key.catchPopup.twistedThrow': 'Kurver Wurf!',
    'key.battlePopup.strongHit': 'Starker Schlag!',
    'key.battlePopup.weakHit': 'Schwacher Schlag',
    'key.battlePopup.dodge': 'Nicht getroffen!',
    'key.battlePopup.chargedAttack': '{0} benutzt {1}',
    'auth.login.play': 'Spielen',
    'auth.login.nickname.placeholder': 'Gib den Name ein',
    'auth.login.nickname.busy': 'Dieser Name wird schon benutzt',
    'auth.login.nickname.proposal': 'Du kannst diesen Name verwenden:',
    'auth.login.nickname.deviceId': 'Du hast schon einen Avatar',
    'auth.login.social.title': 'Sich durch ein soziales Netzwerk anmelden',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Mit {0} verbunden',
    'auth.login.social.signOut': 'Abmelden',
    'auth.login.signOut.confirmation': 'Willst du dich wirklich abmelden?',
    'auth.login.social.userCancelledError': 'Verbindung abgebrochen',
    'auth.login.social.cantSignInError': 'Keine Verbindung mit {0}',
    'licence.title': 'BENUTZERABKOMMEN VON DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Senden Sie mir die Neuigkeiten und Angebote an meine E-Mail-Adresse',
    'licence.accept': 'Akzeptieren',
    'licence.decline': 'Ablehnen',
    'key.error.wrongRoostIndex': 'Das Feld ist nicht verfügbar',
    'key.speed.toMachSpeed': 'Du bewegst dich zu schnell. Spiele nicht Draconius GO: Catch a Dragon! während du fähst - es ist gefährlich für dein Leben.',
    'key.speed.passenger': 'Ich bin ein Fahrgast',
    'key.activeObjects.addUnit.question': 'Bist du sicher, dass du {0} in der Verteidigung des Gebäudes setzen willst?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} Std',
    'key.confirm.selectAlliance': 'Bist du sicher, dass du diese Fraktion auswählen willst? Du wirst diese Entscheidung in Zukunft nicht ändern können.',
    'key.confirm.giveUpEncounter': 'Bist du sicher, dass du mit dem wilden Monster nicht kämpfen will?',
    'key.confirm.giveUpBattle': 'Are you sure you want to give up fighting?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Neues Liga!',
};
