module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'YES',
    'key.button.cancel': 'CANCEL',
    'key.button.apply': 'APPLY',
    'key.button.use': 'USE',
    'key.button.buy': 'Buy',
    'key.beCarefulMessage.text': 'Remember to be alert at all times. Stay aware of your surroundings.',
    'key.creature.details.attack': 'Strength',
    'key.creature.details.health': 'Health',
    'key.creature.details.powerUp': 'Power-Up',
    'key.creature.details.evolve': 'Evolving',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'CP {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'GIVE AWAY',
    'key.creature.details.creadex': 'Bestiary',
    'key.creature.registration.creadex': 'Added to bestiary',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Captured buildings',
    'key.activeObjects.library': 'Creature retraining in the Library',
    'key.activeObjects.library.empty': 'No captured Libraries',
    'key.activeObjects.arena': 'Tax collection from Arenas',
    'key.activeObjects.arena.collect': 'Collect',
    'key.activeObjects.arena.empty': 'No captured Arenas',
    'key.activeObjects.error.timer': 'Tax collection is unavailable. Please wait',
    'key.activeObjects.error.noMoney': 'You need to capture the Arena first',
    'key.activeObjects.error.cannotRemaster': 'Retraining is unavailable. Capture Libraries to speed up the retraining timer.',
    'key.activeObjects.library.remaster': 'Retrain',
    'key.activeObjects.library.blocked': 'Libraries are not accessible',
    'key.activeObjects.remaster.confirmation.main': 'Are you sure you want to retrain {0}? Its main skill {1} will be changed.',
    'key.activeObjects.remaster.confirmation.charged': 'Are you sure you want to retrain {0}? The charged skill {1} will be changed.',
    'key.activeObjects.remaster.error': 'Error',
    'key.activeObjects.item.weaklyBonus': 'Weekly bonus +{0} coins',
    'key.library.remaster.selectCreature': 'Select the creature you want to retrain',
    'key.remasterPanel.title': 'Select the skill you want to change',
    'key.storage.creatues': 'Creatures',
    'key.storage.eggs': 'Eggs',
    'key.storage.eggs.simple': 'Common Eggs',
    'key.storage.eggs.super': 'Ancient Eggs',
    'key.storage.eggs.missingAny': 'You don\'t have any creature eggs',
    'key.startEgg.button': 'Put in a cocoon',
    'key.startEgg.description': 'Use the Dragon\'s Cocoon to hatch this egg',
    'key.startEgg.incubator.title': 'Dragon\'s cocoons',
    'key.startEgg.select.title': 'Choose an egg',
    'key.openEgg.button': 'Crack the egg',
    'key.openEgg.description': 'A new creature is about to hatch from the egg',
    'key.startEgg.description.roost.hatching': 'The Mother of Dragons is hatching this egg. You just need to wait. The hatching will stop if the Rift of Arcana where the Mother of Dragons is situated, disappears.',
    'key.startEgg.description.roost.notHatching': 'Give this egg to the Mother of Dragons so that she can hatch it for you.',
    'key.startEgg.description.simple.hatching': 'This egg is being incubated in a dragon\'s cocoon. Walk around with the game active to help it hatch.',
    'key.startEgg.description.simple.notHatching': 'Put this egg in a dragon\'s cocoon to start incubating it. The egg will hatch after you\'ve walked the required distance.',
    'key.mainMenu.wizardDuels': 'DUEL OF WIZZARDS',
    'key.mainMenu.quests': 'QUEST',
    'key.mainMenu.activePoints': 'CAPTURED',
    'key.mainMenu.creadex': 'BESTIARY',
    'key.mainMenu.magic': 'MAGIC',
    'key.mainMenu.creatues': 'CREATURES',
    'key.mainMenu.shop': 'SHOP',
    'key.mainMenu.backpack': 'BAG',
    'key.error.banned': 'This account has been blocked',
    'event.log.CREATURE_CAUGHT': '{0} has been caught!',
    'event.log.ITEM_BOUGHT': '{0} x{1} has been bought. You\'ve spent {2} coins',
    'event.log.ARTIFACT_BOUGHT': 'Artifact bought: {0}. {1} coins spent',
    'event.log.EGG_HATCHED': '{0} has hatched out of {1} egg!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'golden',
    'event.log.ROOST_EGG_HATCHED': 'Mother of Dragons has hatched a {1} h egg. {0} is yours now!',
    'event.log.CHEST_OPENED': 'Found in the chest:',
    'event.log.ARENA_LOST_CONTROL': '{1} has been knocked out of the building: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} has been knocked out of the building: {0}',
    'event.log.LEVEL_UP': 'You have reached level {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Pet has found {0}',
    'event.log.QUEST_COMPLETED': 'Reward for quest {0}',
    'event.log.ENCOUNTER_LOOSE': 'You\'ve escaped a wild monster',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'The limit of duels in the Duel of Wizards has been increased for {0} coins',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} coins bought for {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'The bag has been upgraded for {0} coins',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'The creature storage has been upgraded for {0} coins',
    'key.shop.accesories': 'ITEMS',
    'key.shop.artifacts': 'ARTIFACTS',
    'key.shop.donate': 'COINS',
    'key.shop.upgrade': 'UPGRADES',
    'key.shop.donate.coins': '{0} coins',
    'key.shop.upgrade.bag': 'Bag upgrade',
    'key.shop.upgrade.bag.desc': 'The size of the Bag will be increased by 50',
    'key.shop.upgrade.storage': 'Creature storage upgrade',
    'key.shop.upgrade.storage.desc': 'The size of the Creature Storage will be increased by 50',
    'key.shop.donate.dialog.title': 'Not enough coins!',
    'key.shop.donate.dialog.desc': 'Get them here, or visit the shop to for more',
    'key.potionUseMenu.title': 'Healing potions',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Creates a Portal to Arcana',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'All surrounding players will feel the rage of the leprechauns',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Creates a field of Pillars of Abundance for 30 minutes',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Doubles the number of rewards from Pillars of Abundance for 30 minutes',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Tap and hold on the terrain to highlight it while searching for creatures',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Increases the range for finding creatures for 30 minutes',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Increases the vision range for objects by 30% for 7 days',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'The nearest allied Arena will be safe from enemy attacks for the next 30 hours',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'All enemy Arenas within the vision range will become neutral. Cancels the Blessing of Defense.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Creates magical tower that attracts fire creatures',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Creates magical tower that attracts water creatures',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Creates magical tower that attracts wind creatures',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Creates magical tower that attracts earth creatures',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Creates magical tower that attracts arcana creatures',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Rift of Arcana',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Rage of Leprechauns',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Field of Abundance',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Gift of the Golden Dragon',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astral vision',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Dragon\'s eyesight',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Long hands',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Blessing for Defense',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Purification by Fire',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Tower of Fire',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Tower of Water',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Tower of Wind',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Tower of Earth',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Tower of Arcana',
    'key.buff.ATTACKER_CP_BOOST': 'The СР of your creatures has been temporarily increased',
    'key.buff.BEST_BALL_LUCK': 'Only the best spheres in Pillars of Abundance for 30 mins',
    'key.buff.BEST_POTION_LUCK': 'Only the best potions in Pillars of Abundance for 30 mins',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 items from Pillars of Abundance for 30 mins',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Library cooldown decreased by {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Time for tax collection from Arenas decreased by {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Increases the СР of creatures that are not currently defending buildings',
    'key.buff.tooltip.BEST_BALL_LUCK': 'You receive only the best spheres for your level from the Pillars of Abundance',
    'key.buff.tooltip.BEST_POTION_LUCK': 'You receive only the best potions for your level from the Pillars of Abundance',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'The number of items you receive from the Pillars of Abundance increases by two',
    'key.loot.result.dust': 'Essence',
    'key.loot.result.exp': 'Character\'s XP',
    'key.loot.result.coin': 'Coins',
    'key.loot.result.candy': 'stones',
    'key.item.MAGIC_BALL_SIMPLE': 'Apprentice\'s sphere',
    'key.item.MAGIC_BALL_NORMAL': 'Master\'s sphere',
    'key.item.MAGIC_BALL_GOOD': 'Ruler\'s sphere',
    'key.item.LURE': 'Lure',
    'key.item.INCENSE': 'Pheromones',
    'key.item.EGG': 'Egg',
    'key.item.SHOVEL': 'Shovel',
    'key.item.POTION_HEAL_1': 'Small Healing Potion',
    'key.item.POTION_HEAL_2': 'Medium Healing Potion',
    'key.item.POTION_HEAL_3': 'Great Healing Potion',
    'key.item.POTION_HEAL_4': 'Potion of Complete Recovery',
    'key.item.POTION_RESURRECTION_1': 'Resurrecting Potion',
    'key.item.POTION_RESURRECTION_2': 'Great Resurrecting Potion',
    'key.item.INCUBATOR_1': 'Dragon\'s Cocoon',
    'key.item.INCUBATOR_3': 'Dragon\'s Cocoon',
    'key.item.INCUBATOR_PERPETUAL': 'Perpetual Dragon\'s Cocoon',
    'key.item.SUPER_VISION': 'Dragon\'s Eyesight',
    'key.item.RUNE_1': 'Rune I',
    'key.item.RUNE_2': 'Rune II',
    'key.item.RUNE_3': 'Rune III',
    'key.item.RUNE_4': 'Rune IV',
    'key.item.RUNE_5': 'Rune V',
    'key.item.RUNE_6': 'Rune VI',
    'key.item.FOOD_CATCH_CHANCE': 'Arcana Caramel',
    'key.item.FOOD_MORE_DUST': 'Magical Doughnut',
    'key.item.FOOD_CALM_DOWN': 'Unicorn\'s Marshmallow',
    'key.item.FOOD_MORE_CANDIES': 'Ice-Cream of Four Elements',
    'key.item.EXPERIENCE_BOOSTER': 'Crystal of Wisdom',
    'key.item.EGG_KM_0': 'Golden Egg',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sphere for catching creatures',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sphere for catching creatures. Slightly increases the chance of a successful catch.',
    'key.item.MAGIC_BALL_GOOD.description': 'Sphere for catching creatures. Significantly increases the chance of a successful catch.',
    'key.item.LURE.description': 'Lure for creatures. Place it inside a Pillar of Abundance to attract creatures to it',
    'key.item.INCENSE.description': 'Pheromones will attract creatures of a certain element to you, depending on the day of the week',
    'key.item.EGG.description': 'Use the Dragon\'s Cocoon to hatch a creature from the egg',
    'key.item.SHOVEL.description': 'Shovels are essential in treasure hunting',
    'key.item.POTION_HEAL_1.description': 'Heals a creature by 200 health points',
    'key.item.POTION_HEAL_2.description': 'Heals a creature by 500 health points',
    'key.item.POTION_HEAL_3.description': 'Heals a creature by 1000 health points',
    'key.item.POTION_HEAL_4.description': 'Heals a creature completely',
    'key.item.POTION_RESURRECTION_1.description': 'Resurrects selected creature. The resurrected creature will be wounded.',
    'key.item.POTION_RESURRECTION_2.description': 'Resurrects and fully heals a creature',
    'key.item.INCUBATOR_1.description': 'You need Dragon cocoons to hatch creatures from eggs. They disappear after being used.',
    'key.item.INCUBATOR_3.description': 'You need Dragon cocoons to hatch creatures from eggs. They disappear after being used three times.',
    'key.item.INCUBATOR_PERPETUAL.description': 'You need Dragon cocoons to hatch creatures from eggs. They disappear after being used.',
    'key.item.SUPER_VISION.description': 'Shows creatures in a large area',
    'key.item.RUNE_1.description': '1st Power Level Magical Rune',
    'key.item.RUNE_2.description': '2nd Power Level Magical Rune',
    'key.item.RUNE_3.description': '3rd Power Level Magical Rune',
    'key.item.RUNE_4.description': '4th Power Level Magical Rune',
    'key.item.RUNE_5.description': '5th Power Level Magical Rune',
    'key.item.RUNE_6.description': '6th Power Level Magical Rune',
    'key.item.FOOD_CATCH_CHANCE.description': 'A treat for catching creatures. Increases the chance of catching a creature with a magical sphere',
    'key.item.FOOD_MORE_DUST.description': 'A treat for catching creatures. Increases the amount of essence you get for catching a creature',
    'key.item.FOOD_CALM_DOWN.description': 'A treat for catching creatures. Calms a creature down so that it stops jumping and attacking',
    'key.item.FOOD_MORE_CANDIES.description': 'A treat for catching creatures. Increases the number of soulstones you receive for catching a creature',
    'key.item.EXPERIENCE_BOOSTER.description': 'Doubles the amount of XP you get for 30 minutes',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Trickster\'s Mask',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '+1 remote placing a creature to Arena or Library per day',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'This artifact allows you to put your creature on a free place in an Arena or Library you can see on the map remotely once per day',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Visionary\'s Face',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '+2 remote placings a creature to Arena or Library per day',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'This artifact allows you to put your creature on a free place in an Arena or Library you can see on the map remotely twice per day',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Conqueror\'s Helmet',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '+3 remote placings a creature to Arena or Library per day',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'This artifact allows you to put your creature on a free place in an Arena or Library you can see on the map remotely 3 times per day',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Hero\'s Helmet',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '+4 remote placings a creature to Arena or Library per day',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'This artifact allows you to put your creature on a free place in an Arena or Library you can see on the map remotely 4 times per day',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Dragonslayer\'s Helmet',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '+5 remote placings a creature to Arena or Library per day',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'This artifact allows you to put your creature on a free place in an Arena or Library you can see on the map remotely 5 times per day',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Banner of the Ruler',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Allows you to place one more creature in the Arena or Library',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'With this artifact, you can place two creatures to defend the Arena or Library instead of one',
    'key.artifact.ARTIFACT_BANK_8': 'Cutout artifact',
    'key.artifact.ARTIFACT_BANK_8.description': 'How did you manage to find it at all?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'You\'ve seen an artifact you were not supposed to see. We\'ll now have to get rid of you as an unwanted witness.',
    'key.artifact.ARTIFACT_BANK_9': 'Cutout artifact',
    'key.artifact.ARTIFACT_BANK_9.description': 'How did you manage to find it at all?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'You\'ve seen an artifact you were not supposed to see. We\'ll now have to get rid of you as an unwanted witness.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Lazy Student\'s Clock',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 seconds to the recharging of Pillars of Abundance',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'With this artifact, the Pillars of Abundance will take 20 seconds less to recharge, which means you will be able to use them more often.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'The Habitually Late\'s Alarm clock',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 seconds to the recharging of Pillars of Abundance',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'With this artifact, the Pillars of Abundance will take 40 seconds less to recharge, which means you will be able to use them more often.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Space Accelerator',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 seconds to the recharging of Pillars of Abundance',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'With this artifact, the Pillars of Abundance will take 60 seconds less to recharge, which means you will be able to use them more often.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Lazy Professor\'s Watch',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 seconds to the recharging of Pillars of Abundance',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'With this artifact, the Pillars of Abundance will take 80 seconds less to recharge, which means you will be able to use them more often.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Zebra-Rabbit\'s Watch',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 seconds to the recharging of Pillars of Abundance',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'With this artifact, the Pillars of Abundance will take 100 seconds less to recharge, which means you will be able to use them more often.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Conqueror\'s Rod',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 to the level of an Arena or Library after its capture',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'If the owner of this artifact is the first to put a creature in the captured Arena or Library, it immediately reaches level 5 instead of level 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Tax Collector\'s Ring',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 to maximum number of captured Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'With this artifact you will be able to collect taxes from 11 Arenas instead of 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Ring of Greed',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 to maximum number of captured Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'With this artifact you will be able to collect taxes from 12 Arenas instead of 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Double Ring',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 to maximum number of captured Arenas',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'With this artifact you will be able to collect taxes from 13 Arenas instead of 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Pie Eater\'s Cup',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% to fame of allied Arenas and Libraries during training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'This artifact gives allied Arenas and Libraries 20% more fame when you train them',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Honey Mug',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% to fame of allied Arenas and Libraries during training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'This artifact gives allied Arenas and Libraries 30% more fame when you train them',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Bowl of Deep Thoughts',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% to fame of allied Arenas and Libraries during training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'This artifact gives allied Arenas and Libraries 40% more fame when you train them',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Lancelop\'s Grail',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% to fame of allied Arenas and Libraries during training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'This artifact gives allied Arenas and Libraries 50% more fame when you train them',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Monster Defeater\'s Cup',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% to fame of allied Arenas and Libraries during training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'This artifact gives allied Arenas and Libraries 80% more fame when you train them',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem of Second Vision',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Takes weak creatures off the radar',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'This artifact takes weak creatures off the radar so that you only search for powerful ones',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Adventurer\'s Rulebook',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minutes to owning an Arena after it\'s been captured by an opponent',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'This artifact makes Arenas available for tax collection for an additional 30 minutes after they\'ve been captured, instead of the usual 15 mins.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Thick Solid Book',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minutes to owning an Arena after it\'s been captured by an opponent',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'This artifact makes Arenas available for tax collection for an additional 45 minutes after they\'ve been captured, instead of the usual 15 mins.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tablet of Possession',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minutes to owning an Arena after it\'s been captured by an opponent',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'This artifact makes Arenas available for tax collection for an additional 60 minutes after they\'ve been captured, instead of the usual 15 mins.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Treatise on Governing',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minutes to owning an Arena after it\'s been captured by an opponent',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'This artifact makes Arenas available for tax collection for an additional 90 minutes after they\'ve been captured, instead of the usual 15 mins.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoire of Authority',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minutes to owning an Arena after it\'s been captured by an opponent',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'This artifact makes Arenas available for tax collection for an additional 120 minutes after they\'ve been captured, instead of the usual 15 mins.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Spiked Collar',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% increase in speed of receiving soulstones from your pet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'With this artifact, you will need to walk 10% less distance for your pet to receive soulstones. It also makes your pet more formidable by 17%',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Carrot on a Stick',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% increase in speed of receiving soulstones from your pet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'With this artifact, you will need to walk 15% less distance for your pet to receive soulstones. Yummy!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Back Scratcher',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% increase in speed of receiving soulstones from your pet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'With this artifact, you will need to walk 25% less distance for your pet to receive soulstones. Submit to the power of the back scratcher!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Favorite\'s Jingle',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% increase in speed of receiving soulstones from your pet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'With this artifact, you will need to walk 30% less distance for your pet to receive soulstones. Who is our pretty boy?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Teddy Dragon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% increase in speed of receiving soulstones from your pet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'With this artifact, you will need to walk 40% less distance for your pet to receive soulstones. The best toy for the best pet in the world.',
    'key.artifact.ARTIFACT_ROOST_1': 'Dragon\'s Heart',
    'key.artifact.ARTIFACT_ROOST_1.description': '+ 1 cocoon for Mother of Dragons',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Allows you to use an additional cocoon for Mother of Dragons\' eggs',
    'dialog.artifact.select_artifact': 'SELECT ARTIFACT',
    'dialog.artifact.confirm.remove': 'Are you sure you want to remove this artifact?',
    'dialog.items.title': 'ITEMS',
    'dialog.items.cannotUse': 'This item cannot be used',
    'dialog.items.remove.header': 'Removal of Items',
    'dialog.encounter.header': 'A wild monster is attacking!',
    'dialog.encounter.button.leave': 'Run away',
    'dialog.encounter.button.fight': 'Fight',
    'dialog.encounter.result.outcome.win': 'The wild monster has been defeated',
    'dialog.encounter.result.outcome.lose': 'Your creature has been defeated',
    'dialog.encounter.result.reward.dust': 'Essence',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': 'You have to enter the character\'s name',
    'error.nickname.validation.TOO_SHORT': 'The name should be between 3 and 16 characters long',
    'error.nickname.validation.TOO_LONG': 'The name should be between 3 and 16 characters long',
    'error.nickname.validation.INVALID_CHAR': 'Forbidden symbol. You can only use Latin letters,  numbers and underscores',
    'error.nickname.validation.DUPLICATE': 'This name has already been taken. You can take the name {0}',
    'creature.MONSTER_WATER_1': 'Frogus',
    'creature.MONSTER_WATER_2': 'Dribble',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Overaquian',
    'creature.MONSTER_WATER_5': 'Frogissimo',
    'creature.MONSTER_WATER_6': 'Sprinkle',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Infalisk',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadachum',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisk',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Underaquian',
    'creature.MONSTER_WATER_18': 'Dadachock',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilisk',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Crystallhat',
    'creature.MONSTER_WATER_23': 'Armorank',
    'creature.MONSTER_WATER_24': 'Neptune',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mymmyween',
    'creature.MONSTER_FIRE_3': 'Steampal',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Firepaw',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dummyween',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Helsailor',
    'creature.MONSTER_FIRE_11': 'Spark',
    'creature.MONSTER_FIRE_12': 'Kiddra',
    'creature.MONSTER_FIRE_13': 'Daemonstar',
    'creature.MONSTER_FIRE_14': 'Phoenix',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Ironguy',
    'creature.MONSTER_FIRE_17': 'Firefly',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Blaze',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Salute',
    'creature.MONSTER_FIRE_24': 'Picaroon',
    'creature.MONSTER_FIRE_25': 'Smoargh',
    'creature.MONSTER_EARTH_1': 'Berrydillo',
    'creature.MONSTER_EARTH_2': 'Flowy',
    'creature.MONSTER_EARTH_3': 'Leaflet',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryad',
    'creature.MONSTER_EARTH_7': 'Plantic',
    'creature.MONSTER_EARTH_8': 'Disguir',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Acornling',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Hopbear',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'Twigo',
    'creature.MONSTER_EARTH_21': 'Earthborn',
    'creature.MONSTER_EARTH_22': 'Parabeast',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Earbat',
    'creature.MONSTER_WIND_3': 'Shroomy',
    'creature.MONSTER_WIND_4': 'Fluffycorn',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Spooky',
    'creature.MONSTER_WIND_8': 'Earaught',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Windance',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Aerycorn',
    'creature.MONSTER_WIND_14': 'Phantomo',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Mushtopia',
    'creature.MONSTER_WIND_17': 'Harpy',
    'creature.MONSTER_WIND_18': 'Ghostus',
    'creature.MONSTER_WIND_19': 'Puerogryph',
    'creature.MONSTER_WIND_20': 'Pillowcat',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Stormdine',
    'creature.MONSTER_WIND_23': 'Gryphon',
    'creature.MONSTER_WIND_24': 'Bajun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Spikeback',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Cuticat',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Scarecrow',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Genie',
    'creature.MONSTER_DUNGEON_12': 'Vampiro',
    'creature.MONSTER_DUNGEON_13': 'Advise',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Softail',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigermant',
    'creature.MONSTER_DUNGEON_21': 'Sharptail',
    'creature.MONSTER_DUNGEON_22': 'Rosebud',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Manticore',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Shark\'s Bite',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Horror from the Depths',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Katulu\'s Call',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Sea Hammer',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Water Fist',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Wave',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Rainfall',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Hot Spring',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Splash',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Living Flame',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Finger of Fire',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Fire Whip',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Fire Sphere',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Cinderer',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Star',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Coal',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Fire Thrower',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Shooting',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Air Sickle',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Burster',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Breathing',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Electric Shock',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Fireball',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Shock Therapy',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Dragon\'s Sigh',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Waft',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Rage of Wind',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Poisonous Spit',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Snake\'s Tooth',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Poisoning',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Spine Breaker',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Rock',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Pebble',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Spirit of Forest',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Tree Ghost',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Nature\'s Shadow',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Arrow of Arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Clot of Darkness',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentacle of Evil',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Eye of Horror',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sphere of Peril',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Sphere of Darkness',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Cadaur\'s Arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarcus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Impericanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Glaciation',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Freezing',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Crystallization',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Whirlwind',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Blizzard',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Cold Fury',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Icy Blast',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Power of Ice',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Purification',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Ascension',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Scorching',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lava',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Fountain of Fire',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteors',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dynocide',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Lightning',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Thunder',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Storm',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Recharging',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'X-Rays',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Goosebumps',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Roar of Wind',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Roundabout',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Rumble',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Shaking',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Rift',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Crash',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Explosion',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Swirl of Stones',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Lake of Death',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Poisonous Puddle',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Acid',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomization',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Disintegration',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionization',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Banishment',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Curse',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Excluding',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Magical Tempest',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Manastorm',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Wrath of Arcana',
    'key.combined.first.1': 'Wise',
    'key.combined.first.2': 'Hellish',
    'key.combined.first.3': 'Beautiful',
    'key.combined.first.4': 'Malicious',
    'key.combined.first.5': 'Neutral',
    'key.combined.first.6': 'Honest',
    'key.combined.first.7': 'Saintly',
    'key.combined.first.8': 'Ancient',
    'key.combined.first.9': 'Underground',
    'key.combined.first.10': 'Fire',
    'key.combined.first.11': 'Deft',
    'key.combined.first.12': 'Huge',
    'key.combined.first.13': 'Blue',
    'key.combined.first.14': 'Cruel',
    'key.combined.first.15': 'Kind',
    'key.combined.first.16': 'Air',
    'key.combined.first.17': 'Earth',
    'key.combined.first.18': 'Red',
    'key.combined.first.19': 'Immortal',
    'key.combined.first.20': 'Perished',
    'key.combined.first.21': 'Air',
    'key.combined.first.22': 'Frightful',
    'key.combined.first.23': 'Water',
    'key.combined.first.24': 'Amusing',
    'key.combined.first.25': 'Silly',
    'key.combined.second.1': 'Heroes',
    'key.combined.second.2': 'Fish',
    'key.combined.second.3': 'Owls',
    'key.combined.second.4': 'Villains',
    'key.combined.second.5': 'Minions',
    'key.combined.second.6': 'Wizzards',
    'key.combined.second.7': 'Elder',
    'key.combined.second.8': 'Summoners',
    'key.combined.second.9': 'Warriors',
    'key.combined.second.10': 'Duelists',
    'key.combined.second.11': 'Traders',
    'key.combined.second.12': 'Rabbits',
    'key.combined.second.13': 'Apples',
    'key.combined.second.14': 'Fighters',
    'key.combined.second.15': 'Tricksters',
    'key.combined.second.16': 'Knights',
    'key.combined.second.17': 'Barbarians',
    'key.combined.second.18': 'Beetles',
    'key.combined.second.19': 'Snakes',
    'key.combined.second.20': 'Dragons',
    'key.combined.second.21': 'Ghosts',
    'key.combined.second.22': 'Kittens',
    'key.combined.second.23': 'Soldiers',
    'key.combined.second.24': 'Lucky Ones',
    'key.combined.second.25': 'Assassins',
    'key.combined.second.26': 'Mice',
    'key.combined.second.27': 'Elementals',
    'key.combined.second.28': 'Investigators',
    'key.combined.second.29': 'Shamans',
    'key.combined.second.30': 'Priests',
    'key.combined.second.31': 'Angels',
    'key.combined.second.32': 'Archons',
    'key.combined.second.33': 'Executioners',
    'key.combined.second.34': 'Simpletons',
    'key.combined.second.35': 'Bravehearts',
    'key.combined.second.36': 'Kindly Souls',
    'key.combined.second.37': 'Cowards',
    'key.combined.second.38': 'Minstrels',
    'key.combined.second.39': 'Tamers',
    'key.combined.second.40': 'Defenders',
    'key.combined.arena': 'Arena of {0} {1} ',
    'key.combined.library': 'Library of {0} {1} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Water',
    'element.type.WIND': 'Wind',
    'element.type.FIRE': 'Fire',
    'element.type.EARTH': 'Earth',
    'element.type.DUNGEON': 'Dungeon',
    'spell.type.ACTIVATION_RADIUS': 'Vision Range',
    'spell.type.VISION_RADIUS': 'Dragon\'s Eyesight',
    'spell.type.STOP_FIELD': 'Field of Abundance',
    'spell.type.SCOUT': 'Scouting',
    'spell.type.PROTECT_ARENA': 'Arena defense',
    'spell.type.CREATE_PORTAL': 'Create a Portal',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Double drop',
    'spell.type.SLUG_PLAYERS': 'Slug players',
    'quest.title.WIN_ARENA_MONSTER': 'Domination',
    'quest.title.OPEN_EGGS': 'Egg Fever',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Territory Control',
    'quest.title.CAPTURE_LIBRARY': 'Thirst for Knowledge',
    'quest.title.CAPTURE_WILD_MONSTER': 'Dragonian Park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Element Hunt',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Search for the Arcana-Born',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Mopping up a Rift',
    'quest.title.OPEN_CHEST': 'Ancient Treasure',
    'quest.title.CHAIN_OF_STOP': 'Way of Abundance',
    'quest.desc.WIN_ARENA_MONSTER': 'Defeat creatures in an Arena or Library. You cannot defeat a creature of the same type twice.',
    'quest.desc.OPEN_EGGS': 'Hatch creatures from eggs by using dragon cocoons or the Mother of Dragons',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Collect taxes from the captured Arenas',
    'quest.desc.CAPTURE_LIBRARY': 'Be the owner of the right number of Libraries',
    'quest.desc.CAPTURE_WILD_MONSTER': 'You can never have too many creatures. Travel and catch them',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Travel and capture creatures of Water Element',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Travel and capture creatures of Air Element',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Travel and capture creatures of Fire Element',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Travel and capture creatures of Earth Element',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Travel and capture creatures of Arcana Element',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Visit the Rift of Arcana to find the Mother of Dragons',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Visit the Rift of Arcana and catch all creatures you can find there',
    'quest.desc.OPEN_CHEST': 'Find and open treasure chests',
    'quest.desc.CHAIN_OF_STOP': 'Walk along the series of Pillars of Abundance and activate them. Each next Pillar will be highlighted.',
    'quest.dialog.completed.rewardtext': 'Your reward:',
    'key.tab.altar.title': 'ALTAR',
    'key.altar.remove': 'Remove',
    'key.altar.put': 'Install',
    'key.altar.convert': 'Convert',
    'key.altar.shared': 'Share with others',
    'key.altar.pass.placeholder': 'You can enter your password here',
    'key.altar.pass.error': 'Your password has to be at least {0} characters long',
    'key.altar.level.error': 'You have to reach level {0} to use the altar',
    'key.altar.recipe.change': 'Are you sure you want to change the recipe? The runes will be returned to their owners',
    'key.altar.row.title': 'To cast a spell, you need an altar',
    'key.altar.rune.descr.RUNE_1': '3 gray runes = an orange one',
    'key.altar.rune.descr.RUNE_2': '3 orange runes = a blue one',
    'key.altar.rune.descr.RUNE_3': '3 blue runes = an emerald one',
    'key.altar.rune.descr.RUNE_4': '3 emerald runes = a red one',
    'key.altar.rune.descr.RUNE_5': '3 red runes = a purple one',
    'key.altar.rune.descr.RUNE_6': 'Purple runes are the most powerful ones',
    'error.altar.cannotRemove': 'You cannot remove your altar',
    'error.altar.cannotConvert': 'Not enough runes',
    'key.tab.altar.recipes': 'RECIPES',
    'key.altar.noRecipes': 'You have no recipes',
    'key.altar.header': 'Place runes on the altar to cast a spell',
    'key.altar.castBtn': 'Cast',
    'key.altar.recipe.select': 'Choose the required spell',
    'key.altar.castDone': 'The spell has been cast',
    'key.arena.protected.ally': 'Protection',
    'key.avatarCustomization.title': 'Choose your character:',
    'key.buddy.walkDescription': 'Walk with your pet to receive {0}',
    'key.buddy.totalWalked': 'You\'ve walked {0} km',
    'key.account.balance': 'Resources:',
    'key.account.userLevel': '{0} lvl',
    'key.account.totalDistance': 'Distance walked: {0} kilometers',
    'key.acount.registerDate': 'Starting date: {0}',
    'key.storage.sort.name': 'NAME',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'GREEN LIST',
    'key.storage.sort.group2': 'YELLOW LIST',
    'key.storage.sort.group3': 'RED LIST',
    'key.storage.sort.date': 'DATE',
    'key.account.options.jurnal': 'JOURNAL',
    'key.account.options.buddy': 'PET',
    'key.account.options.artifacts': 'ARTIFACTS',
    'key.account.options.style': 'STYLE',
    'key.error.gps.permission': 'GPS access is denied. Please allow GPS access in application permissions to continue playing',
    'key.error.gps.disabled': 'GPS is turned off. Turn on your GPS to continue playing',
    'key.error.gps.fakePosition': 'You cannot play without GPS',
    'key.error.gps.signal.notFound': 'No GPS signal',
    'key.error.gps.signal.bad': 'The game is unavailable. The GPS signal is too low',
    'key.error.internet.notReachable': 'No internet connection',
    'key.journal.title': 'Journal',
    'key.journal.yesterday': 'Yesterday',
    'key.settings.title': 'Settings',
    'key.settings.music': 'Music',
    'key.settings.deviceAuthError': 'For safety reasons, please link your account to Google or Facebook',
    'key.settings.sounds': 'Sounds',
    'key.settings.vibration': 'Vibration',
    'key.settings.batterySaver': 'Battery Saving',
    'key.settings.support': 'Contact support',
    'key.settings.logout': 'Logout',
    'key.settings.auth.deviceid': 'ID of the device',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Link',
    'key.battle.result.win': 'The battle is over',
    'key.battle.result.lose': 'The battle is over',
    'key.wizardBattle.result.win': 'VICTORY!',
    'key.wizardBattle.result.lose': 'DEFEAT!',
    'key.battle.result.monster': 'Creature',
    'key.battle.result.exp': 'Experience',
    'key.battle.result.prestige_strong_enemy': 'Fame bonus for strong enemies',
    'key.battle.result.exp_strong_enemy': 'XP bonus for strong enemies',
    'key.battle.result.prestige_killed_all': 'Fame bonus for killing all',
    'key.battle.result.exp_killed_all': 'XP bonus for killing all',
    'key.battle.result.dust': 'Essence',
    'key.radar.title': 'Creatures nearby',
    'key.levelUp.title': 'New level!',
    'key.wizardBattle.left': 'Battle limit:',
    'key.wizardBattle.timer': 'The limit will be reset in',
    'key.wizardBattle.enhance.title': 'LIMIT INCREASE',
    'key.wizardBattle.enhance.desc': 'You can increase your battle limit to 7 per day for one week',
    'key.wizardBattle.enhance.btn': 'Increase',
    'key.wizardBattle.lookingForOpponent': 'Searching for opponent for a duel...',
    'key.catch.result.expMonster': 'XP for catching:',
    'key.catch.result.expMonsterNew': 'New in the Bestiary:',
    'key.catch.result.expAccurate': 'For an accurate throw:',
    'key.catch.result.expSpin': 'For a twisted throw:',
    'key.catch.result.strike': 'Your first creature today:',
    'key.catch.result.total': 'Total XP:',
    'key.catch.fullStorage': 'Creature storage is full',
    'key.catch.noItems': 'You have no magical spheres',
    'key.creadex.title': 'BESTIARY',
    'key.creadex.detail.caught': 'CAUGHT: {0}',
    'key.creadex.detail.evolution': 'Evolution',
    'key.tab.doll': 'CHARACTER',
    'key.tab.artifacts': 'ARTIFACTS',
    'key.activePoint.title': 'Pillar of Abundance',
    'key.personalization.title': 'Enchantment',
    'key.chest.title': 'Magical Chest',
    'key.quest.daily.title': 'QUEST',
    'key.quest.weekly.title': 'HUNT',
    'key.quest.get': 'GET A QUEST',
    'key.quest.change': 'CHANGE QUEST',
    'key.quest.progress': 'Quest progress: {0} of {1}',
    'key.error.quest.weekly.level': 'Level {0} is required to start hunting the Golden Egg',
    'key.error.quest.daily.level': 'Level {0} is required to receive a quest',
    'key.error.quest.tooFar': 'The Obelisk is too far away',
    'key.quest.daily.descr.noQuest.title': 'You have no quests',
    'key.quest.daily.descr.noQuest': 'Use the Obelisk to get a quest and earn a reward',
    'key.quest.daily.timer.descr': 'You can change the quest in:',
    'key.quest.daily.waitForNew.descr': 'A new quest will be unlocked in: ',
    'key.quest.weekly.getFragment': 'RECEIVE A FRAGMENT',
    'key.quest.weekly.descr.noQuest.title': 'You are not participating in the hunt for the Golden Egg',
    'key.quest.weekly.descr.noQuest': 'Use the Obelisk to receive a fragment of a mysterious map and start hunting',
    'key.quest.weekly.descr.getFirstFragment': 'Receive the first fragment of a mysterious map to start the quest for the Golden Egg',
    'key.quest.weekly.descr.top.notAllOpen': 'Use Obelisks to receive fragments of the map. Hurry up, the quest will end in ',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Use the shovel on each fragment to find the Golden Egg',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'You\'ve already received a fragment of the map from this Obelisk',
    'key.quest.weekly.descr.top.allOpen': 'All fragments of the map from the Obelisk have been received. Hurry up, the quest will end in ',
    'key.quest.weekly.descr.bot.allOpen': 'Use the shovel on each fragment to find the Golden Egg',
    'key.quest.weekly.descr.top.completed': 'You\'ve already found a Golden Egg this week. The next quest will start in ',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}h',
    'key.timer.format.H_M': '{0}h {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}h',
    'key.creatureStorage.tab.creatures': 'CREATURES',
    'key.creatureStorage.tab.eggs': 'EGGS',
    'key.creatureStorage.multiTransferText': 'Choose which creature to give away',
    'key.storage.creature.transfer': 'Give away ({0})',
    'key.error.needHigherLevelForArena': 'Level {0} is required to enter the Arena',
    'key.error.needHigherLevelForLibrary': 'Level {0} is required to enter the Library',
    'key.error.arenaUnderProtection': 'The Arena is protected by the Blessing of Defense',
    'key.error.buildingTooFar': 'The building is too far away',
    'key.error.noAliveCreaturesForAttack': 'You have no available living creatures',
    'key.error.noHealPotion': 'You have no heal potions',
    'key.error.noResurrectionPotion': 'You have no resurrection potions',
    'key.error.tryAgainLater': 'Error. Try again later.',
    'key.error.alreadyHasLure': 'The lure has been set',
    'key.error.cannotUseLureInDungeon': 'The lure cannot be used in the Rift of Arcana',
    'key.error.bagIsFull': 'No space in the bag',
    'key.error.cantTransferCreature': 'It is impossible to give away this creature',
    'key.notification.done': 'Done!',
    'key.modal.doYouWantToTransfer': 'Are you sure you want to give these creatures away?',
    'key.modal.youWillLoseBuddyProgress': 'Are you sure you want to change your pet? The progress of receiving a soulstone will be canceled.',
    'key.modal.doYouWantToLeaveDungeon': 'Do you want to leave the Rift of Arcana?',
    'key.modal.superVisionActive': 'Dragon\'s Eyesight has already been activated. If you activate it again, the magical area of vision will be moved. Are you sure you want to use it one more time?',
    'key.modal.experienceBoosterActive': 'The Crystal of Wisdom has already been activated. Are you sure you want to use it again?',
    'key.modal.youWillLooseQuestProgress': 'The progress of your current quest will be lost. Are you sure?',
    'key.modal.doYouWantToEnterDungeon': 'Do you want to enter the Rift of Arcana through the Portal?',
    'key.modal.doYouWantPersonalizePoint': 'After enchanting, the Pillar will always give {0}. Do you want to spend {1} coins for enchanting?',
    'key.modal.doYouWantToDeletePersonalization': 'Are you sure you want to cancel the enchantment of this Pillar of Abundance?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Do you want to power up this creature?',
    'key.modal.doYouWantToEvolveThisCreature': 'Do you want to evolve this creature?',
    'key.modal.doYouWantToScoutHere': 'Are you sure you want to scout this location?',
    'key.error.creatureHasMaxLevel': 'The creature has already reached the maximum level',
    'key.error.creatureHasMaxLevelForUser': 'First, you need to increase the level of your character',
    'key.error.notEnoughResourcesForEnhance': 'Not enough resources',
    'key.error.creatureIsArenaDefender': 'You cannot choose a creature that is defending the Arena',
    'key.modal.incenseActive': 'The pheromones have already been activated. Are you sure you want to use them again?',
    'key.error.cantHealHealthyCreature': 'The creature has been completely healed',
    'key.error.cantRessurectAliveCreature': 'The creature is already alive',
    'key.error.noTreasureHere': 'This fragment of the map does not contain the Golden Egg. Keep searching.',
    'key.error.levelTooSmall': 'You need to increase the level of your character first',
    'key.error.needHigherLevelForWizardBattles': 'Level {0} is required to participate in the Duels of Wizzards',
    'key.error.artifactBagIsFull': 'No space in the Artifact Storage',
    'key.error.notEnoughCoins': 'Not enough coins',
    'key.error.allFragmentsAreOpen': 'All the fragments of the mysterious map have been opened',
    'key.error.questAlreadyCompleted': 'The quest has already been completed',
    'key.error.alreadyGotFragmentFromThisObelisk': 'You\'ve already received a fragment of the map from this Obelisk',
    'key.error.portalTooFarAway': 'The Portal is too far away',
    'key.error.battleLimitAlreadyEnhanced': 'The Limit of battles has been increased',
    'key.error.youAreNotAltarOwner': 'Only the owner of the altar can do this',
    'key.error.youAlreadyHaveAltar': 'The altar has been installed already',
    'key.error.cantTakeAnotherUsersRune': 'You cannot take another player\'s rune',
    'key.error.libraryBlocked': 'You have to wait 3 days after the retraining to use the Libraries again',
    'key.error.notAuthorized': 'The user is not authorized',
    'key.error.eggOnlyRoost': 'You have to give this egg to the Mother of Dragons',
    'key.error.purchase': 'Error: {0}',
    'key.error.creatureIsDead': 'You need to resurrect the creature first',
    'key.error.no_connection': 'No connection to host. Try again later.',
    'key.error.protocol_version_mismatch': 'This version of the game is outdated. An update is required.',
    'key.error.update_application': 'This version of the game is outdated. An update is required.',
    'key.modal.doYouWantToTransferSingle': 'Are you sure you want to give this creature away?',
    'key.notification.phoneNotSupportAR': 'AR is not supported on your device',
    'key.notification.turnOnARPermission': 'The game has no access to the camera. You need to allow access in the settings',
    'key.notification.dailyQuestFinished': 'The quest is complete!',
    'key.modal.yesBtn': 'Yes',
    'key.modal.noBtn': 'No',
    'event.log.DAILY_QUEST_COMPLETED': 'The daily quest has been completed. You\'ve received rewards:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'The hunt has been completed. You\'ve received rewards:',
    'event.log.ENCOUNTER_VICTORY': 'You\'ve defeated a wild monster!',
    'key.ServiceException.Cause.OLD_CLIENT': 'The current version of the game is outdated. An update is required.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Authentication error',
    'key.ServiceException.Cause.SESSION_GONE': 'Someone logged in to your account from a different device',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'The user ID is empty',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'The user hasn\'t been found',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'The account has been banned for cheating.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'The account has been banned for frauding.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'The account has been banned for an abusive nickname.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'The account has been banned for harassment.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'The account has been banned for cheating.',
    'key.ServiceException.Cause.USER_BANNED': 'The account has been banned.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'No space in the bag',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maximum quantity of eggs',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Not enough coins',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Not enough soulstones',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Not enough essence',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'No space in the creature storage',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'The creature has already reached the maximum level',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'You cannot evolve this creature',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'The creature\'s name cannot exceed 14 characters',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'The building already has the maximum number of defenders',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'You cannot make a building defender your pet',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Your creature is already defending this building',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Error',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'No battle found',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Error',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Your creature is already defending this building',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'The Arena is protected by the Blessing of Defense',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'The time for collecting taxes hasn\'t come yet',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Wrong sphere',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Wrong building',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Access denied',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'No such item',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'No such recipe',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'You can only install one altar',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'First you need to increase the level of your character',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Failed to start catching the creature',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'No such product',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'No such product',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'No such building',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'No such creature',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Wrong creature',
    'key.ServiceException.Cause.TOO_FAR': 'The building is too far away',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'The object is too far',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'The building is recharging',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'The building is in the Rift of Arcana',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'The building cannot be used',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'The Dragon\'s Cocoon wasn\'t found',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'The Dragons\' Cocoon is empty',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'The Dragon\'s Cocoon has been taken',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'The egg hasn\'t been hatched',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'No egg found',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'This egg requires the Mother of Dragons',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'No charges left',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Failed to place the building',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'An error has occurred, and this is a mysterious message about it',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'The wild monster has run away',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'No wild monster found',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'This Pillar already has a lure',
    'key.ServiceException.Cause.WRONG_ITEM': 'Wrong item',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'This rune is the most powerful',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Not enough runes of this level',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Wrong rune slot',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'This slot has already been taken',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'The rune slot is empty',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'You cannot choose the building defender',
    'key.ServiceException.Cause.WRONG_SPELL': 'Wrong spell',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'The spell requires more runes',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'No new quests available yet',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'You\'ve already used this Obelisk',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'All the fragments of the map have been opened',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'You are not participating in the quest for the Golden Egg',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'You\'ve already tried to find the Golden Egg on this territory',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'You\'ve already used the treat',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'The creature is already captured',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Retraining of the creature is unavailable',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Libraries are not accessible at the moment',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'The server is not responding. Try again later',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'The battle limit has already been increased',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'You have reached the limit of battles',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'You need to be level 9 to participate in the Duel of Wizzards',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'No opponent for the Duel of Wizzards found, try again later.',
    'key.ServiceException.Cause.MARKET_ERROR': 'Market error',
    'key.ServiceException.Cause.NO_CHEST': 'No chest found',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Error in obtaining fragment. Please, try again later',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'You have to put on the Dragon\'s Heart or the Dragon\'s Artifact set to give more eggs to the Mother of Dragons',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'There is an egg in this slot already',
    'key.ServiceException.Cause.NO_CONNECTION': 'No internet connection',
    'key.ServiceException.Cause.SERVER_DOWN': 'The game server is temporarily not available. Please try again later.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'The game server is down for maintenance. Please try again later.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Those runes are in use',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'You\'re moving too fast',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'You\'ve reached the limit of captured Arenas',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'You\'ve reached the limit of captured Libriaries',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Error: No GPS signal',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'This spell cannot be cast while in the Rift of Arcana',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'The battle has expired',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'This version of the game is outdated. An update is required.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'No allied Arenas in the area of vision',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'No enemy Arenas in the area of vision',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'spheres',
    'stop.personalized.HEALS': 'healing potions',
    'stop.personalized.RESURRECTIONS': 'resurrection potions',
    'stop.personalized.EGGS': 'creature eggs',
    'stop.personalized.FOODS': 'treats',
    'key.button.cancelPersonal': 'Cancel',
    'key.error.needHigherLevelForSofaBattles': 'You need to get to lvl {0} to participate in the Duel of Wizzards',
    'fraction.text.youWilLGetBonus': 'You will get {0} coins for joining this faction',
    'fraction.text.fractionUnavailable': 'Faction is unavailable',
    'fraction.text.chooseYourAlliance': 'Choose your faction',
    'fraction.text.redFractionName': 'Red Order',
    'fraction.text.blueFractionName': 'Blue Order',
    'key.error.chestTooFarAway': 'The chest is too far away',
    'key.button.openChest': 'Open',
    'key.candy.MONSTER_WATER_1': 'Frogus\' stones',
    'key.candy.MONSTER_WATER_2': 'Dribble\'s stones',
    'key.candy.MONSTER_WATER_3': 'Spiritus\' stones',
    'key.candy.MONSTER_WATER_4': 'Aquian\'s stones',
    'key.candy.MONSTER_WATER_8': 'Jellyhat\'s stones',
    'key.candy.MONSTER_WATER_9': 'Minor\'s stones',
    'key.candy.MONSTER_WATER_10': 'Infalisk\'s stones',
    'key.candy.MONSTER_WATER_12': 'Dadachock\'s stones',
    'key.candy.MONSTER_WATER_13': 'Batoid\'s stones',
    'key.candy.MONSTER_WATER_23': 'Armorank\'s stones',
    'key.candy.MONSTER_WATER_24': 'Neptune\'s stones',
    'key.candy.MONSTER_WATER_25': 'Leviathan\'s stones',
    'key.candy.MONSTER_FIRE_1': 'Potty\'s stones',
    'key.candy.MONSTER_FIRE_2': 'Mymmyween\'s stones',
    'key.candy.MONSTER_FIRE_3': 'Steampal\'s stones',
    'key.candy.MONSTER_FIRE_4': 'Incumus\' stones',
    'key.candy.MONSTER_FIRE_6': 'Flamy\'s stones',
    'key.candy.MONSTER_FIRE_7': 'Phoby\'s stones',
    'key.candy.MONSTER_FIRE_11': 'Spark\'s stones',
    'key.candy.MONSTER_FIRE_12': 'Kiddra\'s stones',
    'key.candy.MONSTER_FIRE_15': 'Needlehot\'s stones',
    'key.candy.MONSTER_FIRE_25': 'Smoargh\'s stones',
    'key.candy.MONSTER_EARTH_1': 'Berrydillo stones',
    'key.candy.MONSTER_EARTH_2': 'Flowy stones',
    'key.candy.MONSTER_EARTH_3': 'Leaflet\'s stones',
    'key.candy.MONSTER_EARTH_4': 'Brownie\'s stones',
    'key.candy.MONSTER_EARTH_8': 'Disguir\'s stones',
    'key.candy.MONSTER_EARTH_9': 'Bellflow\'s stones',
    'key.candy.MONSTER_EARTH_10': 'Acornling\'s stones',
    'key.candy.MONSTER_EARTH_11': 'Phylo\'s stones',
    'key.candy.MONSTER_EARTH_13': 'Princie\'s stones',
    'key.candy.MONSTER_EARTH_25': 'Scylla\'s stones',
    'key.candy.MONSTER_DUNGEON_1': 'Rookie\'s stones',
    'key.candy.MONSTER_DUNGEON_2': 'Axolan\'s stones',
    'key.candy.MONSTER_DUNGEON_3': 'Spikeback\'s stones',
    'key.candy.MONSTER_DUNGEON_4': 'Magglad\'s stones',
    'key.candy.MONSTER_DUNGEON_5': 'Cuticat\'s stones',
    'key.candy.MONSTER_DUNGEON_6': 'Rosie\'s stones',
    'key.candy.MONSTER_DUNGEON_12': 'Vampiro\'s stones',
    'key.candy.MONSTER_DUNGEON_13': 'Advise\'s stones',
    'key.candy.MONSTER_DUNGEON_17': 'Inur\'s stones',
    'key.candy.MONSTER_WIND_1': 'SunTzi\'s stones',
    'key.candy.MONSTER_WIND_2': 'Earbat\'s stones',
    'key.candy.MONSTER_WIND_3': 'Shroomy\'s stones',
    'key.candy.MONSTER_WIND_4': 'Fluffycorn\'s stones',
    'key.candy.MONSTER_WIND_6': 'Gamayun\'s stones',
    'key.candy.MONSTER_WIND_7': 'Spooky\'s stones',
    'key.candy.MONSTER_WIND_11': 'Infird\'s stones',
    'key.candy.MONSTER_WIND_12': 'Undine\'s stones',
    'key.candy.MONSTER_WIND_15': 'Cheshir\'s stones',
    'key.candy.MONSTER_WIND_25': 'Charybdis\' stones',
    'key.button.leaveDungeon': 'Leave the Rift',
    'key.alias.enterNewAlias': 'Enter the creature\'s name',
    'key.alias.enterText': 'Enter the text...',
    'key.hut.hutName': 'Mother of Dragons',
    'key.hut.hutDescr': 'Give the Mother of Dragons ancient eggs so that she can hatch them for you',
    'key.text.noHutEggs': 'You have no ancient eggs',
    'key.text.noCapturedArenas': 'You have not captured Arenas',
    'key.text.noChosenPet': 'You haven\'t chosen your pet',
    'key.text.noArtifacts': 'You have no artifacts',
    'key.text.noCreatures': 'You have no creatures',
    'key.text.noLureItems': 'You have no lure',
    'key.descr.aboutWizardBattles': 'Participate in duels against other players to earn XP and rewards',
    'key.text.writeToSupport': 'Contact Support',
    'key.text.regUsingFacebook': 'Sign up via Facebook',
    'key.text.regUsingGoogle': 'Sign up via Google',
    'key.text.logUsingFacebook': 'Log in via Facebook',
    'key.text.logUsingGoogle': 'Log in via Google',
    'key.text.logUsingDeviceIDCurrent': 'Log in via Device ID',
    'key.text.logUsingDeviceIDNew': 'Log in via Device ID (new account)',
    'key.text.createAccount': 'Play',
    'key.text.connectedToFacebook': 'Linked to Facebook',
    'key.text.connectedToGoogle': 'Linked to Google',
    'key.text.complainAboutPoint': 'Report the spot',
    'key.text.copyCoordinates': 'Copy coordinates',
    'key.text.complainEnterEmail': 'Your email',
    'key.text.complainEnterText': 'Describe your problem',
    'key.modal.doYouWantToCloseApp': 'Do you want to close the application?',
    'key.catchPopup.notBad': 'Good!',
    'key.catchPopup.good': 'Excellent!',
    'key.catchPopup.sumptuously': 'Fantastic!',
    'key.catchPopup.twistedThrow': 'Twisted throw!',
    'key.battlePopup.strongHit': 'Strong hit!',
    'key.battlePopup.weakHit': 'Weak hit',
    'key.battlePopup.dodge': 'Dodged!',
    'key.battlePopup.chargedAttack': '{0} is using {1}',
    'auth.login.play': 'Play',
    'auth.login.nickname.placeholder': 'Enter your nickname',
    'auth.login.nickname.busy': 'This nickname is already taken',
    'auth.login.nickname.proposal': 'You can use this nickname:',
    'auth.login.nickname.deviceId': 'You already have a character',
    'auth.login.social.title': 'Log in via social network',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Connected to {0}',
    'auth.login.social.signOut': 'Log Out',
    'auth.login.signOut.confirmation': 'Are you sure you want to log out?',
    'auth.login.social.userCancelledError': 'Connecting has been canceled',
    'auth.login.social.cantSignInError': 'Cannot connect to {0}',
    'licence.title': 'DRACONIUS GO: CATCH A DRAGON! GAME END USER LICENSE AGREEMENT',
    'licence.checkbox': 'Email me events, offers, and updates',
    'licence.accept': 'Accept',
    'licence.decline': 'Decline',
    'key.error.wrongRoostIndex': 'The slot is unavailable',
    'key.speed.passenger': 'I am a passenger',
    'key.activeObjects.addUnit.question': 'Are you sure you want to make {0} the defender of this building?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Are you sure you want to select this faction? This choice cannot be changed in the future.',
    'key.confirm.giveUpEncounter': 'Are you sure you want to give up fighting with the wild monster?',
    'key.confirm.giveUpBattle': 'Are you sure you want to surrender and end the battle?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'New League!',
};
