module.exports = {
    'key.system.application.name': '«Draconius GO: Catch a Dragon!»',
    'key.button.ok': 'OK',
    'key.button.yes': 'Evet',
    'key.button.cancel': 'İPTAL',
    'key.button.apply': 'OK',
    'key.button.use': 'Kullan',
    'key.button.buy': 'Satın al',
    'key.beCarefulMessage.text': 'Oynarken dikkatli olun. Etrafınıza bakın.',
    'key.creature.details.attack': 'Güç',
    'key.creature.details.health': 'Sağlık',
    'key.creature.details.powerUp': 'Güçlendirme',
    'key.creature.details.evolve': 'Dönüştürme',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'CP {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'Kov',
    'key.creature.details.creadex': 'Yaratıklar Ansiklopedisi',
    'key.creature.registration.creadex': 'Yaratıklar Ansiklopedisi\'ne katılmıştır',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Ele geçirilen objeler',
    'key.activeObjects.library': 'Kütüphanede yaratığın dönüştürülmesi',
    'key.activeObjects.library.empty': 'Ele geçirilmiş Kütüphaneler yok',
    'key.activeObjects.arena': 'Arenalardan haraç toplanması',
    'key.activeObjects.arena.collect': 'Topla',
    'key.activeObjects.arena.empty': 'Ele geçirdiğiniz Arena yok',
    'key.activeObjects.error.timer': 'Haraç toplanmaz. Bekleyin',
    'key.activeObjects.error.noMoney': 'Önce Arena\'yı ele geçirin',
    'key.activeObjects.error.cannotRemaster': 'Yeni eğitim verilmez. Dönüştürmeyi hızlandırmak için Kütüphaneleri ele geçirin.',
    'key.activeObjects.library.remaster': 'Yeni eğitim ver',
    'key.activeObjects.library.blocked': 'Kütüphaneler müsait değil',
    'key.activeObjects.remaster.confirmation.main': '{0} dönüştürmek istiyor musunuz? {1} ana özelliği değiştirilecek.',
    'key.activeObjects.remaster.confirmation.charged': '{0} dönüştürmek istiyor musunuz? Mevcut {1} özelliği değiştirilecek.',
    'key.activeObjects.remaster.error': 'Hata',
    'key.activeObjects.item.weaklyBonus': 'Haftalık bonus: +{0} coin',
    'key.library.remaster.selectCreature': 'Dönüştürülecek yaratığı seç',
    'key.remasterPanel.title': 'Değiştirilecek özelliği seç',
    'key.storage.creatues': 'Yaratık',
    'key.storage.eggs': 'Yumurta',
    'key.storage.eggs.simple': 'Standart yumurtalar',
    'key.storage.eggs.super': 'Antik yumurtalar',
    'key.storage.eggs.missingAny': 'Sizde Yaratık yumurtaları yok',
    'key.startEgg.button': 'Koza içine koy',
    'key.startEgg.description': 'Bu yumurtayı yumurtlamak için Ejderha kozasını kullan',
    'key.startEgg.incubator.title': 'Ejderha Kozaları',
    'key.startEgg.select.title': 'Yumurtayı seçin',
    'key.openEgg.button': 'Yumurtayı aç',
    'key.openEgg.description': 'Yeni yaratık yumurtadan çıkmak üzere',
    'key.startEgg.description.roost.hatching': 'Bu yumurtayı Ejderhalar Annesi yumurtluyor. Beklemek gerek. Ejderhalar Annesi\'nin bulunduğu Arkana Vadisi\'nin kaybolması halinde yumurtlama gerçekleşmez.',
    'key.startEgg.description.roost.notHatching': 'Bu yumurtayı Ejderhalar Annesi\'ne verin, Sizin için bunu yumurtlasın.',
    'key.startEgg.description.simple.hatching': 'Bu yumurta Ejderha Kozası içinde yumurtlanır. Çatlanması için oyunu açık tutun. ',
    'key.startEgg.description.simple.notHatching': 'Yumurtayı yumurtlatmaya başlamak için bunu Ejderha Kozası içine koyun. Siz gerekli mesafeyi yürüdükten sonra yumurta çatlayacaktır.',
    'key.mainMenu.wizardDuels': 'BÜYÜCÜLER SAVAŞLARI',
    'key.mainMenu.quests': 'GÖREV',
    'key.mainMenu.activePoints': 'ELE GEÇİRİLEN EŞYALAR',
    'key.mainMenu.creadex': 'YARATIKLAR ANSİKLOPEDİSİ',
    'key.mainMenu.magic': 'BÜYÜ',
    'key.mainMenu.creatues': 'YARATIKLAR',
    'key.mainMenu.shop': 'MAĞAZA',
    'key.mainMenu.backpack': 'ÇANTA',
    'key.error.banned': 'Hesabınız kilitlidir',
    'event.log.CREATURE_CAUGHT': '{0} yakalandı!',
    'event.log.ITEM_BOUGHT': '{0} x{1} satın alındı. {2} coin harcandı',
    'event.log.ARTIFACT_BOUGHT': 'Artefaktı satın aldınız: {0}. {1} coin harcandı',
    'event.log.EGG_HATCHED': '{1} yumurtadan {0} çıktı!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'altın',
    'event.log.ROOST_EGG_HATCHED': 'Ejderhalar Annesi {1} yumurta yumurtladı. Artık {0} kullanabilirsiniz!',
    'event.log.CHEST_OPENED': 'Sandıkta bulunan eşyalar:',
    'event.log.ARENA_LOST_CONTROL': 'Savaş sonucunda {1} {0} binasını bıraktı',
    'event.log.LIBRARY_LIST_CONTROL': 'Savaş sonucunda {1} {0} binasını bıraktı',
    'event.log.LEVEL_UP': '{0}.seviyeye ulaştınız',
    'event.log.BUDDY_FOUND_CANDY': 'Yaratık {0} buldu',
    'event.log.QUEST_COMPLETED': 'Görev için ödül: {0}',
    'event.log.ENCOUNTER_LOOSE': 'Vahşi canavardan kaçtınız',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Büyücüler Savaşlarında düello limiti {0} coin için azaltıldı',
    'event.log.HARD_CURRENCY_BOUGHT': '{1} karşılığına {0} coin satın alındı',
    'event.log.UPGRADE_BAG_BOUGHT': 'Çantanın kapasitesi {0} coin için yükseltildi',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Yaratıklar deposu {0} coin için genişletildi',
    'key.shop.accesories': 'EŞYA',
    'key.shop.artifacts': 'ARTEFAKT',
    'key.shop.donate': 'COİN',
    'key.shop.upgrade': 'GELİŞMELER',
    'key.shop.donate.coins': '{0} coin',
    'key.shop.upgrade.bag': 'çantanın genişlenmesi',
    'key.shop.upgrade.bag.desc': 'Çanta kapasitesi +50 büyüyor',
    'key.shop.upgrade.storage': 'yaratıklar deposunun genişlenmesi',
    'key.shop.upgrade.storage.desc': 'Yaratıklar deposu kapasitesi +50 büyüyor',
    'key.shop.donate.dialog.title': 'Coin yetmiyor!',
    'key.shop.donate.dialog.desc': 'Burada al veya seçim yapmak için için Mağazaya geç',
    'key.potionUseMenu.title': 'Tedavi edici iksirler',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Arkana Vadisi\'ne Portal kuruyor.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Etrafınızdaki tüm oyuncular kendileri üzerinde Leprekon öfkesini hissederler',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': '30 dk. için Bolluk Obelisk Tarlasını açıyor',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': '30 dk. için Bolluk Obelisk\'lerinden düşen bonusları iki katına çıkarıyor',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Yaratıkları aramak için harita üzerine tıklayın',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': '30 dk. için yaratık bulma radyusünü yükseltiyor.',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Objeleri bulma radyusünü 7 gün için %30 yükseltiyor.',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': '30 saat boyunca en yakın müttefik Arena\'ya düşman saldıramaz.',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Tüm düşman Arenaları görüş radyusünde nötr olacak. İlahi Korumayı etkisiz hale getiriyor.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Alev Öğesi yaratıklarını çeken Büyülü Kuleyi kuruyor',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Su Öğesi yaratıklarını çeken Büyülü Kuleyi kuruyor',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Rüzgar Öğesi yaratıklarını çeken Büyülü Kuleyi kuruyor',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Toprak Öğesi yaratıklarını çeken Büyülü Kuleyi kuruyor',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Arkana Öğesi yaratıklarını çeken Büyülü Kuleyi kuruyor',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Arkana Vadisi\'',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Leprekon öfkesi',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Bolluk Tarlası',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Altın Ejderha\'nın Armağanı',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astral vizyon',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Ejderha vizyonu',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Uzun eller',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Koruma için Hayır Duası',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Yangınla temizlenme',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Alev Kulesi',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Su Kulesi',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Rüzgar Kulesi',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Toprak Kulesi',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Arkana Kulesi',
    'key.buff.ATTACKER_CP_BOOST': 'Yaratıklarınızın СР puanı geçici olarak arttı',
    'key.buff.BEST_BALL_LUCK': 'Bolluk Obelisk\'dan 30 dk. içinde en güzel küreler düşüyor',
    'key.buff.BEST_POTION_LUCK': 'Bolluk Obelisk\'dan 30 dk. içinde en güzel iksirler düşüyor',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Bolluk Obelisk\'lerdan 30 dk. içinde +2 eşya düşüyor',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Kütüphane\'nin yenileme süresi {0} azaldı',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Arenalardan haraç toplama süresi {0} azaldı',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Yapı koruyucusu olmayan yaratıkların CP puanını arttırıyor',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Bolluk Obelisk\'dan seviyenize göre en güzel küre alıyorsunuz',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Bolluk Obelisk\'dan seviyenize göre en güzel sihir alıyorsunuz',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Bolluk Obelisk\'dan iki eşya ekstra alırsınız',
    'key.loot.result.dust': 'Esans',
    'key.loot.result.exp': 'Karakterin tecrübesi',
    'key.loot.result.coin': 'Coin',
    'key.loot.result.candy': 'taşlar',
    'key.item.MAGIC_BALL_SIMPLE': 'Öğrenci Küresi',
    'key.item.MAGIC_BALL_NORMAL': 'Uzman Küresi',
    'key.item.MAGIC_BALL_GOOD': 'Hükümdar Küresi',
    'key.item.LURE': 'Yem',
    'key.item.INCENSE': 'Feromonlar',
    'key.item.EGG': 'Yumurta',
    'key.item.SHOVEL': 'Kürek',
    'key.item.POTION_HEAL_1': 'Küçük tedavi edici iksir',
    'key.item.POTION_HEAL_2': 'Orta tedavi edici iksir',
    'key.item.POTION_HEAL_3': 'Büyük tedavi edici iksir',
    'key.item.POTION_HEAL_4': 'Tam tedavi edici iksir',
    'key.item.POTION_RESURRECTION_1': 'Canlandırma iksiri',
    'key.item.POTION_RESURRECTION_2': 'Büyük canlandırma iksiri',
    'key.item.INCUBATOR_1': 'Ejderha Kozası',
    'key.item.INCUBATOR_3': 'Ejderha Kozası',
    'key.item.INCUBATOR_PERPETUAL': 'Ebedi Ejderha Kozası',
    'key.item.SUPER_VISION': 'Ejderha vizyonu',
    'key.item.RUNE_1': 'Runik Taş I',
    'key.item.RUNE_2': 'Runik Taş II',
    'key.item.RUNE_3': 'Runik Taş III',
    'key.item.RUNE_4': 'Runik Taş IV',
    'key.item.RUNE_5': 'Runik Taş V',
    'key.item.RUNE_6': 'Runik Taş VI',
    'key.item.FOOD_CATCH_CHANCE': 'Arkana karamel çubuğu',
    'key.item.FOOD_MORE_DUST': 'Büyülü tatlı çörek',
    'key.item.FOOD_CALM_DOWN': 'Tekboynuz zefiri',
    'key.item.FOOD_MORE_CANDIES': 'Dört Öğe Dondurması',
    'key.item.EXPERIENCE_BOOSTER': 'Hikmet Kristalı',
    'key.item.EGG_KM_0': 'Altın Yumurta',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Yaratıkları Yakalama Küresi.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Yaratıkları Yakalama Küresi. Yakalama şansı biraz artıyor.',
    'key.item.MAGIC_BALL_GOOD.description': 'Yaratıkları Yakalama Küresi. Yakalama şansı önemli ölçüde artıyor.',
    'key.item.LURE.description': 'Yaratıklar için yem. Yaratıkların dikkatini çekmek için bunu Bolluk Obelisk içine koyun.',
    'key.item.INCENSE.description': 'Feromonlar, haftanın gününe göre belirli öğeden yaratıkları Size çeker.',
    'key.item.EGG.description': 'Yumurtadan yaratığı çıkartmak için Ejderha Kozasını kullanın.',
    'key.item.SHOVEL.description': 'Hazineyi bulma konusunda kürekten güzel bir şey yok.',
    'key.item.POTION_HEAL_1.description': 'Yaratığın sağlığına 200 puan veriyor',
    'key.item.POTION_HEAL_2.description': 'Yaratığın sağlığına 500 puan veriyor',
    'key.item.POTION_HEAL_3.description': 'Yaratığın sağlığına 1000 puan veriyor',
    'key.item.POTION_HEAL_4.description': 'Yaratığı tamamen tedavi ediyor',
    'key.item.POTION_RESURRECTION_1.description': 'Seçilen yaratığı canlandırıyor. Yaratık canlandırıldıktan sonra yaralı gözüküyor.',
    'key.item.POTION_RESURRECTION_2.description': 'Yaratığı canlandırıp bunu tamamen tedavi ediyor.',
    'key.item.INCUBATOR_1.description': 'Yaratıkları yumurtalardan yetiştirmek için Ejderha Kozaları gerekiyor. Kullanıldıktan sonra kaybolur.',
    'key.item.INCUBATOR_3.description': 'Yaratıkları yumurtalardan yetiştirmek için Ejderha Kozaları gerekiyor. 3 kere kullanıldıktan sonra kaybolur.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Yaratıkları yumurtalardan yetiştirmek için Ejderha Kozaları gerekiyor',
    'key.item.SUPER_VISION.description': 'Yaratıkları tespit çapı önemli ölçüde artıyor.',
    'key.item.RUNE_1.description': '1. seviye Güç isimli büyülü Runik Taş',
    'key.item.RUNE_2.description': '2. seviye Güç isimli büyülü Runik Taş',
    'key.item.RUNE_3.description': '3. seviye Güç isimli büyülü Runik Taş',
    'key.item.RUNE_4.description': '4. seviye Güç isimli büyülü Runik Taş',
    'key.item.RUNE_5.description': '5. seviye Güç isimli büyülü Runik Taş',
    'key.item.RUNE_6.description': '6. seviye Güç isimli büyülü Runik Taş',
    'key.item.FOOD_CATCH_CHANCE.description': 'Yaratıkları yakalamak için yem. Yaratığı büyülü küre ile yakalama şansını yükseltiyor.',
    'key.item.FOOD_MORE_DUST.description': 'Yaratıkları yakalamak için yem. Yaratığın yakalanması için daha çok esans kazandırıyor',
    'key.item.FOOD_CALM_DOWN.description': 'Yaratıkları yakalamak için yem. Yaratığı sakinleştiriyor, yaratık sıçramayı ve saldırmayı bitiriyor.',
    'key.item.FOOD_MORE_CANDIES.description': 'Yaratıkları yakalamak için yem. Yakalanması için verilen ruhlar taşı miktarını yükseltiyor.',
    'key.item.EXPERIENCE_BOOSTER.description': '30 dk. içerisinde kazanılan XP iki kat artıyor',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Hokkabaz Maskesi',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '24 saatte Arenaya veya Kütüphaneye uzaktan yaratık koymaya yarar +1',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Bu artefakt sayesine 24 saatte bir kere her hangi bir mesafeden Arenadaki veya Kütüphanedeki boş yere yaratığınızı koyabilirsiniz.',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Falcının yüzü',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '24 saatte Arenaya veya Kütüphaneye uzaktan yaratık koymaya yarar +2',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Bu artefakt sayesine 24 saatte iki kere her hangi bir mesafeden Arenadaki veya Kütüphanedeki boş yere yaratığınızı koyabilirsiniz.',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Fatih Başlığı',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '24 saatte Arenaya veya Kütüphaneye uzaktan yaratık koymaya yarar +3',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Bu artefakt sayesine 24 saatte üç kere her hangi bir mesafeden Arenadaki veya Kütüphanedeki boş yere yaratığınızı koyabilirsiniz.',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Kahraman Başlığı',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '24 saatte Arenaya veya Kütüphaneye uzaktan yaratık koymaya yarar +4',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Bu artefakt sayesine 24 saatte dört kere her hangi bir mesafeden Arenadaki veya Kütüphanedeki boş yere yaratığınızı koyabilirsiniz.',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Ejderha Savaşçısı Başlığı',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '24 saatte Arenaya veya Kütüphaneye uzaktan yaratık koymaya yarar +5',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Bu artefakt sayesine 24 saatte beş kere her hangi bir mesafeden Arenadaki veya Kütüphanedeki boş yere yaratığınızı koyabilirsiniz.',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Arenalar Hükümdarı Sancağı',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Arena\'ya bir tane daha yaratık gönderilebilir.',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Bu artefakt sayesine Arena veya Kütüphane\'yi korumak için bir yaratık yerine 2 yaratık kullanabilirsiniz.',
    'key.artifact.ARTIFACT_BANK_8': 'Boş artefakt',
    'key.artifact.ARTIFACT_BANK_8.description': 'Bu gereksiz artefaktı nasıl bulabildiniz?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Görmeyeceğiniz artefaktı buldunuz. Şimdi tanık olarak Sizden kurtulmalıyız.',
    'key.artifact.ARTIFACT_BANK_9': 'Boş artefakt',
    'key.artifact.ARTIFACT_BANK_9.description': 'Bu gereksiz artefaktı nasıl bulabildiniz?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Görmeyeceğiniz artefaktı buldunuz. Şimdi tanık olarak Sizden kurtulmalıyız.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Tembel öğrencinin saati',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': 'Bolluk Obelisk\'lerin yenilenme süresine -20 sn.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Bu artefakt sayesine Bolluk Obelisk’ler kullanıldıktan sonra 20 sn. çabuk yenilenecek ve bunları daha çok kullanabileceksiniz.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Daima geç kalanlar için uyandırıcı saat',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': 'Bolluk Obelisk\'lerin yenilenme süresine -40 sn.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Bu artefakt sayesine Bolluk Obelisk’ler kullanıldıktan sonra 40 sn. çabuk yenilenecek ve bunları daha çok kullanabileceksiniz.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Zaman hızlandırıcısı',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': 'Bolluk Obelisk\'lerin yenilenme süresine -60 sn.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Bu artefakt sayesine Bolluk Obelisk’ler kullanıldıktan sonra 60 sn. çabuk yenilenecek ve bunları daha çok kullanabileceksiniz.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Tembel profesörün saati',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': 'Bolluk Obelisk\'lerin yenilenme süresine -80 sn.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Bu artefakt sayesine Bolluk Obelisk’ler kullanıldıktan sonra 80 sn. çabuk yenilenecek ve bunları daha çok kullanabileceksiniz.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Çizgili tavşanın saati',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': 'Bolluk Obelisk\'lerin yenilenme süresine -100 sn.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Bu artefakt sayesine Bolluk Obelisk’ler kullanıldıktan sonra 100 sn. çabuk yenilenecek ve bunları daha çok kullanabileceksiniz.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Fatih Sancağı',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': 'Arena ele geçirildikten sonra bunun seviyesine +2 eklenecek',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Bu artefakta sahip olan, ele geçirilen Arena\'ya ilk olarak yaratık gönderdiğnde Arena\'nın seviyesi 3.seviye yerine doğrudan 5.seviyeye çıkar.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Haraç toplayıcısı yüzüğü',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': 'Ele geçirilebilen Arena\'nın maksimum sayısına +1',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Bu artefaktla 10 Arena yerine 11 Arena\'dan haraç toplayabilirsiniz',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Cimrilik Yüzüğü',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': 'Ele geçirilebilen Arena\'nın maksimum sayısına +2',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Bu artefaktla 10 Arena yerine 12 Arena\'dan haraç toplayabilirsiniz',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Çift Yüzük',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': 'Ele geçirilebilen Arena\'nın maksimum sayısına +3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Bu artefaktla 10 Arena yerine 13 Arena\'dan haraç toplayabilirsiniz',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Pasta Yutucusu Kupası',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': 'Eğitim sırasında Ortak Arena ve Kütüphane\'nin tecrübesine +%20',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Bu artefaktla Siz ortak Arena ve Kütüphane\'yi geliştirirken bunların gücüne %20 ekleniyor.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Bal Kabı',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': 'Eğitim sırasında Ortak Arena ve Kütüphane\'nin tecrübesine +%30',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Bu artefaktla Siz ortak Arena ve Kütüphane\'yi geliştirirken bunların gücüne %30 ekleniyor.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Derin Fikirler Kabı',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': 'Eğitim sırasında Ortak Arena ve Kütüphane\'nin tecrübesine +%40',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Bu artefaktla Siz ortak Arena ve Kütüphane\'yi geliştirirken bunların gücüne %40 ekleniyor.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Lanselot\'ın Graali',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': 'Eğitim sırasında Ortak Arena ve Kütüphane\'nin tecrübesine +%50',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Bu artefaktla Siz ortak Arena ve Kütüphane\'yi geliştirirken bunların gücüne %50 ekleniyor.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Yaratıkların Fatihi Kupası',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': 'Eğitim sırasında Ortak Arena ve Kütüphane\'nin tecrübesine +%80',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Bu artefaktla Siz ortak Arena ve Kütüphane\'yi geliştirirken bunların gücüne %80 ekleniyor.',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Net vizyon totem sembolü',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Zayıf yaratıklar radarda gösterilmiyor',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Bu artefakt sayesinde radarda zayıf yaratıklar görünmediği için daha güçlü yaratıkları arayabilirsiniz.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Maceracının Kural Kitabı',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': 'Arena düşmanca ele geçirildikten sonra bundan haraç alma sürenize +15 dk.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Bu artefakt sayesinde Arena\'lar ele geçirildikten sonra 15 dk. yerine 30 dk. boyunca haraç alabilirsiniz.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Kalın ve ciddi kitap',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': 'Arena düşmanca ele geçirildikten sonra bundan haraç alma sürenize +30 dk.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Bu artefakt sayesinde Arena\'lar ele geçirildikten sonra 15 dk. yerine 45 dk. boyunca haraç alabilirsiniz.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Mülk Hakkı Tahtası',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': 'Arena düşmanca ele geçirildikten sonra bundan haraç alma sürenize +45 dk.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Bu artefakt sayesinde Arena\'lar ele geçirildikten sonra 15 dk. yerine 60 dk. boyunca haraç alabilirsiniz.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Hükümdarlık Anlaşması',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': 'Arena düşmanca ele geçirildikten sonra bundan haraç alma sürenize +75 dk.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Bu artefakt sayesine Arena\'lar ele geçirildikten sonra 15 dk. yerine 90 dk. boyunca haraç alabilirsiniz.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'İktidar ve Kara Büyü Kitabı',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': 'Arena düşmanca ele geçirildikten sonra bundan haraç alma sürenize +105 dk.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Bu artefakt sayesine Arena\'lar ele geçirildikten sonra 30 dk. yerine 120 dk. boyunca haraç alabilirsiniz.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Dikenli tasma',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': 'Yaratıktan Ruhlar taşını alma süresi %10 hızlı oluyor',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Bu artefakt sayesine Ruhlar taşını kazanmak için yaratığınızla %10 az mesafe yürürsünüz. Ayrıca, yaratığın korkunç görünüşünü %17 arttırmış olursunuz.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Sopaya asılı havuç',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': 'Yaratıktan Ruhlar taşını alma süresi %15 hızlı oluyor',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Bu artefakt sayesine Ruhlar taşını kazanmak için yaratığınızla %15 az mesafe yürürsünüz. Çok tatlı bir şey.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Sırt kaşıyıcısı',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': 'Yaratıktan Ruhlar taşını alma süresi %25 hızlı oluyor',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Bu artefakt sayesine Ruhlar taşını kazanmak için yaratığınızla %25 az mesafe yürürsünüz. Sırt kaşıyıcısı karşısında başını eğ!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Evcil varlık çıngırağı',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': 'Yaratıktan Ruhlar taşını alma süresi %30 hızlı oluyor',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Bu artefakt sayesine Ruhlar taşını kazanmak için yaratığınızla %30 az mesafe yürürsünüz. Kimdir bu güzel varlık?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Lastik Ejderha',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': 'Yaratıktan Ruhlar taşını alma süresi %40 hızlı oluyor',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Bu artefakt sayesine Ruhlar taşını kazanmak için yaratığınızla %40 az mesafe yürürsünüz. En güzel evcil varlık için en güzel oyuncak',
    'key.artifact.ARTIFACT_ROOST_1': 'Ejderha\'nın Kalbi',
    'key.artifact.ARTIFACT_ROOST_1.description': 'Ejderhalar Annesi\'ne +1 slot',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Ejderhalar Annesi\'ne 1 ekstra yumurta slotunu veriyor',
    'dialog.artifact.select_artifact': 'ARTEFAKTI SEÇ',
    'dialog.artifact.confirm.remove': 'Artefaktı kaldırmak istiyor musunuz?',
    'dialog.items.title': 'Çanta',
    'dialog.items.cannotUse': 'Bu item kullanılamaz',
    'dialog.items.remove.header': 'Eşyaları sil',
    'dialog.encounter.header': 'Vahşi canavar saldırıyor!',
    'dialog.encounter.button.leave': 'Kaçır',
    'dialog.encounter.button.fight': 'Savaş',
    'dialog.encounter.result.outcome.win': 'Vahşi canavar yenildi',
    'dialog.encounter.result.outcome.lose': 'Yaratığınız yenildi',
    'dialog.encounter.result.reward.dust': 'Esans',
    'dialog.encounter.result.reward.exp': 'Tecrübe',
    'error.nickname.validation.IS_EMPTY': 'Kahraman adını girin',
    'error.nickname.validation.TOO_SHORT': 'İsim en az 6 ve en fazla 12 karakter olmalı',
    'error.nickname.validation.TOO_LONG': 'İsim en az 6 ve en fazla 12 karakter olmalı',
    'error.nickname.validation.INVALID_CHAR': 'Yanlış karakter. Ancak harf, rakam ve alt çizgi kullanılabilir.',
    'error.nickname.validation.DUPLICATE': 'Seçtiğiniz isim artık kullanılmakta. {0} adını seçebilirsiniz',
    'creature.MONSTER_WATER_1': 'Kurbağacık',
    'creature.MONSTER_WATER_2': 'Damlacık',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Overaquian',
    'creature.MONSTER_WATER_5': 'Frogissimo',
    'creature.MONSTER_WATER_6': 'Derecik',
    'creature.MONSTER_WATER_7': 'Su Ata',
    'creature.MONSTER_WATER_8': 'Jöle Şapkalı',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Kunduzcuk',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadachock',
    'creature.MONSTER_WATER_13': 'Tırpanacık',
    'creature.MONSTER_WATER_14': 'Su papağancığı',
    'creature.MONSTER_WATER_15': 'Su Ejderhası',
    'creature.MONSTER_WATER_16': 'Dikenli Şapkalı',
    'creature.MONSTER_WATER_17': 'Underaquian',
    'creature.MONSTER_WATER_18': 'Keredes',
    'creature.MONSTER_WATER_19': 'Vatoz',
    'creature.MONSTER_WATER_20': 'Basilisk',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Kristal Şapkalı',
    'creature.MONSTER_WATER_23': 'Armorank',
    'creature.MONSTER_WATER_24': 'Neptün',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Kazancık',
    'creature.MONSTER_FIRE_2': 'Kabakkafalı Mumyacık',
    'creature.MONSTER_FIRE_3': 'Buharcı',
    'creature.MONSTER_FIRE_4': 'Ejderha Yavrusu',
    'creature.MONSTER_FIRE_5': 'Ateş Pençeli',
    'creature.MONSTER_FIRE_6': 'Alevcik',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Kabakkafalı',
    'creature.MONSTER_FIRE_9': 'Lav Aslan',
    'creature.MONSTER_FIRE_10': 'Сehennem Denizcisi',
    'creature.MONSTER_FIRE_11': 'Kıvılcım',
    'creature.MONSTER_FIRE_12': 'Hydra',
    'creature.MONSTER_FIRE_13': 'Demon Yıldız',
    'creature.MONSTER_FIRE_14': 'Feniks',
    'creature.MONSTER_FIRE_15': 'Sıcak İğne',
    'creature.MONSTER_FIRE_16': 'Demir Erkek',
    'creature.MONSTER_FIRE_17': 'Ateş Böceği',
    'creature.MONSTER_FIRE_18': 'Sezar',
    'creature.MONSTER_FIRE_19': 'Parlama',
    'creature.MONSTER_FIRE_20': 'Korsan Ruhu',
    'creature.MONSTER_FIRE_21': 'Şeytan',
    'creature.MONSTER_FIRE_22': 'Parabeast',
    'creature.MONSTER_FIRE_23': 'Salute',
    'creature.MONSTER_FIRE_24': 'Kaktüs',
    'creature.MONSTER_FIRE_25': 'Dumancık',
    'creature.MONSTER_EARTH_1': 'Kirpicik',
    'creature.MONSTER_EARTH_2': 'Çiçek Ejderhası',
    'creature.MONSTER_EARTH_3': 'Orman Perisi',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryad',
    'creature.MONSTER_EARTH_7': 'Filizcik',
    'creature.MONSTER_EARTH_8': 'Goblincik',
    'creature.MONSTER_EARTH_9': 'Çağanozcuk',
    'creature.MONSTER_EARTH_10': 'Palamutçuk',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Cırboğacık',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Kozalakçık',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Trol',
    'creature.MONSTER_EARTH_17': 'Yengeç',
    'creature.MONSTER_EARTH_18': 'Mirket',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'İlkbahar Perisi',
    'creature.MONSTER_EARTH_21': 'Çim Hokkabaz',
    'creature.MONSTER_EARTH_22': 'Ayı',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Buzlu Ork',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Yarasa',
    'creature.MONSTER_WIND_3': 'Shroomy',
    'creature.MONSTER_WIND_4': 'Tüylü Boynuzlu',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Ürkütücü',
    'creature.MONSTER_WIND_8': 'Earaught',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Mantarcık',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Su Perisi',
    'creature.MONSTER_WIND_13': 'Oğlak',
    'creature.MONSTER_WIND_14': 'Hayalet',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Mushtopia',
    'creature.MONSTER_WIND_17': 'Harpya',
    'creature.MONSTER_WIND_18': 'Hayalet',
    'creature.MONSTER_WIND_19': 'Grifoncuk',
    'creature.MONSTER_WIND_20': 'Kedicik',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Fırtına Perisi',
    'creature.MONSTER_WIND_23': 'Dev Grifon',
    'creature.MONSTER_WIND_24': 'Bajun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Aksolan',
    'creature.MONSTER_DUNGEON_3': 'Dikenli',
    'creature.MONSTER_DUNGEON_4': 'Salyangoz',
    'creature.MONSTER_DUNGEON_5': 'Şirin Kedi',
    'creature.MONSTER_DUNGEON_6': 'Fok Yavrusu',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Korkuluk',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Cin',
    'creature.MONSTER_DUNGEON_12': 'Vampir Yarasa',
    'creature.MONSTER_DUNGEON_13': 'Yaşlı Kaz',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Kuyrukçuk',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Drakula',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigermant',
    'creature.MONSTER_DUNGEON_21': 'Sivri Kuyruk',
    'creature.MONSTER_DUNGEON_22': 'Gül Goncası',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Manticore',
    'creature.MONSTER_DUNGEON_25': 'Morgorot',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Köpekbalığı ısırması',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Uçurum dehşeti',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Cthulhu\'nun Çağrısı',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Deniz Balyozu',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Su yumruğu',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Dalga',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Yağmur',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Gayzer',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Serpintiler',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Canlı Ateş',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Ateş Parmağı',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Ateş Kamçısı',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Ateş Topu',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Yakıcı',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Yıldız',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Kor',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Alev Makinesi',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Kurşunlama',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Havai Arak',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Parçalayıcı',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Solunum',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Elektroşok',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Yıldırım topu',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Elektroşok tedavisi',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Ejderha\'nın nefesi',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Esinti',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Rüzgar Öfkesi',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Zehirli Tükürük',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Yılan Dişi',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Zehirleme',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Bel kemeği kırıcısı',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Kaya',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Taş',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Orman Ruhu',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Ağaç Hayaleti',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Tabiatın gölgesi',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Arkana Oku',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Karanlık pıhtısı',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Kötülüğün dokunaçları',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Dehşet gözü',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Ölüm Küresi',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Karanlık Topu',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arkanakadabra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Krusiarkus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'İmperikanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Buz tutulması',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Dondurma',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Kristalleşme',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Hava Hortumu',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Kar Fırtınası',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Soğuk Öfke',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Buz Patlaması',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Buz Egemenliği',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Temizlenme',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Göğe Çıkış',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Yakma',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lav',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Ateş Fıskıyesi',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Akanyıldızlar',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinosid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Mahşer',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Yıldırım',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Gök Gürültüsü',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Fırtına',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Aşırı Yükleme',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Röntgen',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Dimdik Saçlar',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Kasırga',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Rüzgar Sesi',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Atlıkarınca',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Gümbürtü',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Sarsılma',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Vadi',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Kırıltı',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Patlama',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Taş Kasırgası',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Ölüm Gölü',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Zehirli su birikintisi',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Asit',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomizasyon',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Parçalama',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Bölme',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Sürgün',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Lanet',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Aforoz',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Büyü fırtınası',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Mana Fırtınası',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Arkana Öfkesi',
    'key.combined.first.1': 'Bilgeli',
    'key.combined.first.2': 'Cehennem',
    'key.combined.first.3': 'Güzel',
    'key.combined.first.4': 'Kızgın',
    'key.combined.first.5': 'Yeşil',
    'key.combined.first.6': 'Açık gönüllü',
    'key.combined.first.7': 'Kutsal',
    'key.combined.first.8': 'Eski',
    'key.combined.first.9': 'Yeraltı',
    'key.combined.first.10': 'Ateş',
    'key.combined.first.11': 'Becerikli',
    'key.combined.first.12': 'Dev',
    'key.combined.first.13': 'Mav',
    'key.combined.first.14': 'Acımasız',
    'key.combined.first.15': 'İyi hayırlı',
    'key.combined.first.16': 'Hava',
    'key.combined.first.17': 'Toprak',
    'key.combined.first.18': 'Kırmızı',
    'key.combined.first.19': 'Ölümsüz',
    'key.combined.first.20': 'Ölü',
    'key.combined.first.21': 'Hava',
    'key.combined.first.22': 'Korkunç',
    'key.combined.first.23': 'Su',
    'key.combined.first.24': 'Tatlı',
    'key.combined.first.25': 'Aptal',
    'key.combined.second.1': 'Kahramanlar',
    'key.combined.second.2': 'Balıklar',
    'key.combined.second.3': 'Baykuşlar',
    'key.combined.second.4': 'Hırsızlar',
    'key.combined.second.5': 'Salatalıklar',
    'key.combined.second.6': 'Büyücüler',
    'key.combined.second.7': 'İhtiyarlar',
    'key.combined.second.8': 'Sihirbazlar',
    'key.combined.second.9': 'Savaşçılar',
    'key.combined.second.10': 'Düellocular',
    'key.combined.second.11': 'Тüccarlar',
    'key.combined.second.12': 'Tavşanlar',
    'key.combined.second.13': 'Elmalar',
    'key.combined.second.14': 'Askerler',
    'key.combined.second.15': 'Hokkabazlar',
    'key.combined.second.16': 'Şovalyeler',
    'key.combined.second.17': 'Barbarlar',
    'key.combined.second.18': 'Böcekler',
    'key.combined.second.19': 'Yılanlar',
    'key.combined.second.20': 'Ejderhalar',
    'key.combined.second.21': 'Hayaletler',
    'key.combined.second.22': 'Kediler',
    'key.combined.second.23': 'Erler',
    'key.combined.second.24': 'Şanslılar',
    'key.combined.second.25': 'Katiller',
    'key.combined.second.26': 'Fareler',
    'key.combined.second.27': 'Elementaller',
    'key.combined.second.28': 'Satıcılar',
    'key.combined.second.29': 'Şamanlar',
    'key.combined.second.30': 'Rahipler',
    'key.combined.second.31': 'Melekler',
    'key.combined.second.32': 'Arhontlar',
    'key.combined.second.33': 'Cellatlar',
    'key.combined.second.34': 'Salaklar',
    'key.combined.second.35': 'Yiğitler',
    'key.combined.second.36': 'Hayırlılar',
    'key.combined.second.37': 'Korkaklar',
    'key.combined.second.38': 'Şairler',
    'key.combined.second.39': 'Terbiyeciler',
    'key.combined.second.40': 'Korumacılar',
    'key.combined.arena': 'Arenası {0} {1} ',
    'key.combined.library': 'Kütüphanesi {0} {1} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Su',
    'element.type.WIND': 'Hava',
    'element.type.FIRE': 'Alev',
    'element.type.EARTH': 'Toprak',
    'element.type.DUNGEON': 'Arkana',
    'spell.type.ACTIVATION_RADIUS': 'Görüş alanı',
    'spell.type.VISION_RADIUS': 'Ejderha vizyonu',
    'spell.type.STOP_FIELD': 'Bolluk Tarlası',
    'spell.type.SCOUT': 'İstihbarat',
    'spell.type.PROTECT_ARENA': 'Arena\'yı koru',
    'spell.type.CREATE_PORTAL': 'Portal\'ı kur',
    'spell.type.ARMAGEDDON': 'Mahşer',
    'spell.type.DOUBLE_DROP': 'Çift düşüş',
    'spell.type.SLUG_PLAYERS': 'SLUG_PLAYERS',
    'quest.title.WIN_ARENA_MONSTER': 'Hakimiyet',
    'quest.title.OPEN_EGGS': 'Yumurtaya Hücum',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Arazinin kontrolü',
    'quest.title.CAPTURE_LIBRARY': 'Bilgiye susamışlık',
    'quest.title.CAPTURE_WILD_MONSTER': 'Ejderhalar Çağı Parkı',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Öğe için avlama',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Arkana Ejderhalar Annesi\'nin aranması',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Vadinin temizlenmesi',
    'quest.title.OPEN_CHEST': 'Eski servetler',
    'quest.title.CHAIN_OF_STOP': 'Bereket Yolu',
    'quest.desc.WIN_ARENA_MONSTER': 'Arena\'da veya Kütüphane\'de yaratıkları yenin. Aynı tip yaratık iki kere yenilmez.',
    'quest.desc.OPEN_EGGS': 'Ejderha kozasını kullanarak veya Ejderhalar Annesi\'nin yardımıyla yumurtalardan yaratıkları yetiştirin.',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Ele geçirdiğiniz Arenalar\'dan haraç toplayın',
    'quest.desc.CAPTURE_LIBRARY': 'Gerekli miktarda Kütüphane ele geçirin.',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Fazla yaratık olmaz. Gezin, seyahat edin ve yaratıkları yakalayın',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Su Öğesi yaratıklarını yakalayın',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Rüzgar Öğesi yaratıklarını yakalayın',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Alev Öğesi yaratıklarını yakalayın',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Toprak Öğesi yaratıklarını yakalayın',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Arkana Öğesi yaratıklarını yakalayın',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Ejderhalar Annesi\'nin bulunduğu Arkana Vadisi\'ni ziyaret edin',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Arkana Vadisi\'ni ziyaret edin ve orada bulacağınız tüm yaratıkları yakalayın',
    'quest.desc.OPEN_CHEST': 'Hazine bulunan sandıkları bulun ve bunları açın',
    'quest.desc.CHAIN_OF_STOP': 'Bolluk Obelisk dizisini gezin ve bunları aktif hale getirin. Her sonraki Obelisk ışıkla işaretli olacak.',
    'quest.dialog.completed.rewardtext': 'Ödülünüz:',
    'key.tab.altar.title': 'SUNAK',
    'key.altar.remove': 'Kaldır',
    'key.altar.put': 'Kur',
    'key.altar.convert': 'Dönüştür',
    'key.altar.shared': 'Diğer oyunculara göster',
    'key.altar.pass.placeholder': 'Şifreyi buraya girin',
    'key.altar.pass.error': 'Şifre en az {0} karakter olmalı',
    'key.altar.level.error': 'Sunağı kullanmak için {0}.seviyeye ulaşmanız gerek.',
    'key.altar.recipe.change': 'Formülü değiştirmek istiyor musunuz? Runik Taşlar bunun sahibine geri dönecek.',
    'key.altar.row.title': 'Büyü yapmak için Sunak kurmak gerekiyor',
    'key.altar.rune.descr.RUNE_1': '3 gri Runik Taş = 1 turuncu Runik Taş',
    'key.altar.rune.descr.RUNE_2': '3 turuncu Runik Taş = 1 mavi Runik Taş',
    'key.altar.rune.descr.RUNE_3': '3 mavi Runik Taş = 1 zümrüt Runik Taş',
    'key.altar.rune.descr.RUNE_4': '3 zümrüt Runik Taş = 1 kırmızı Runik Taş',
    'key.altar.rune.descr.RUNE_5': '3 kırmızı Runik Taş = 1 mor Runik Taş',
    'key.altar.rune.descr.RUNE_6': 'Mor Runik Taş en güçlü rünlerdir',
    'error.altar.cannotRemove': 'Sunak kaldırılmaz',
    'error.altar.cannotConvert': 'Runik Taş yetmiyor',
    'key.tab.altar.recipes': 'FORMÜLLER',
    'key.altar.noRecipes': 'Sizde bir formül yok',
    'key.altar.header': 'Büyüyü hazırlamak için Sunak üzerine Runik Taşları koy',
    'key.altar.castBtn': 'Hazırla',
    'key.altar.recipe.select': 'Gerekli büyüyü seç',
    'key.altar.castDone': 'Büyü hazır',
    'key.arena.protected.ally': 'Koruma',
    'key.avatarCustomization.title': 'Kahramanı seç:',
    'key.buddy.walkDescription': '{0} almak için yaratığınızla beraber gezin',
    'key.buddy.totalWalked': '{0} km. geçtiniz',
    'key.account.balance': 'Kaynaklar:',
    'key.account.userLevel': '{0} lvl',
    'key.account.totalDistance': 'Yürüdüğünüz toplam mesafe: {0} kilometre',
    'key.acount.registerDate': 'Oyuna başlama tarihi: {0}',
    'key.storage.sort.name': 'İSİM',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'YEŞİL LİSTE',
    'key.storage.sort.group2': 'SARI LİSTE',
    'key.storage.sort.group3': 'KIRMIZI LİSTE',
    'key.storage.sort.date': 'TARİH',
    'key.account.options.jurnal': 'NOT DEFTERİ',
    'key.account.options.buddy': 'YARATIK',
    'key.account.options.artifacts': 'ARTEFAKTLAR',
    'key.account.options.style': 'GÖRÜNÜM',
    'key.error.gps.permission': 'GPS sinyalı yok. Oyuna devam etmek için ayarlarda GPS açın',
    'key.error.gps.disabled': 'GPS sinyalı yok. Oyuna devam etmek için GPS açın',
    'key.error.gps.fakePosition': 'GPS olmadan oynayamazsınız',
    'key.error.gps.signal.notFound': 'GPS sinyalı yok',
    'key.error.gps.signal.bad': 'Oynamak için GPS sinyalı zayıf',
    'key.error.internet.notReachable': 'İnternet bağlantısı yok',
    'key.journal.title': 'Not Defteri',
    'key.journal.yesterday': 'Dün',
    'key.settings.title': 'Ayarlar',
    'key.settings.music': 'Müzik',
    'key.settings.deviceAuthError': 'Güvenlik amaçlarında hesabınızı Google veya Facebook\'a bağlayınız.',
    'key.settings.sounds': 'Ses',
    'key.settings.vibration': 'Titreşim',
    'key.settings.batterySaver': 'Enerji Tasarrufu',
    'key.settings.support': 'Teknik desteğe yaz',
    'key.settings.logout': 'Hesaptan çık',
    'key.settings.auth.deviceid': 'Cihazın ID',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Bağla',
    'key.settings.languageTitle': 'Dil',
    'key.settings.language': 'Türkçe',
    'key.battle.result.win': 'Savaş bitti',
    'key.battle.result.lose': 'Savaş bitti',
    'key.wizardBattle.result.win': 'ZAFER',
    'key.wizardBattle.result.lose': 'YENİLGE',
    'key.battle.result.monster': 'Yenilmiş Yaratık sayısı',
    'key.battle.result.exp': 'Kazanılmış XP',
    'key.battle.result.prestige_strong_enemy': 'Güçlü düşmanlar için Ün bonusu',
    'key.battle.result.exp_strong_enemy': 'Güçlü düşmanlar için XP bonusu',
    'key.battle.result.prestige_killed_all': 'Tüm düşmanlar için Ün bonusu',
    'key.battle.result.exp_killed_all': 'Tüm düşmanlar için XP bonusu',
    'key.battle.result.dust': 'Esans',
    'key.radar.title': 'Yakındaki yaratıklar',
    'key.levelUp.title': 'Yeni seviyeye ulaştınız!',
    'key.wizardBattle.left': 'Savaş limiti:',
    'key.wizardBattle.timer': 'Limit bitmesine kalan zaman ',
    'key.wizardBattle.enhance.title': 'LİMİT YÜKSELT',
    'key.wizardBattle.enhance.desc': 'Günlük Savaş limitini 1 haftalığına 10\'a kadar yükseltilebilir',
    'key.wizardBattle.enhance.btn': 'Yükselt',
    'key.wizardBattle.lookingForOpponent': 'Düello için düşman aranıyor...',
    'key.catch.result.expMonster': 'Yakalama için XP puanı:',
    'key.catch.result.expMonsterNew': 'Yaratıklar Ansiklopedisi\'nde yenilikler:',
    'key.catch.result.expAccurate': 'İsabetli atış için:',
    'key.catch.result.expSpin': 'Bükülü atış için:',
    'key.catch.result.strike': 'Bugünkü birinci yaratık:',
    'key.catch.result.total': 'Toplam XP puanı:',
    'key.catch.fullStorage': 'Yaratıklar Deposu dolu',
    'key.catch.noItems': 'Sizde büyülü küre yok',
    'key.creadex.title': 'YARATIKLAR ANSİKLOPEDİSİ',
    'key.creadex.detail.caught': 'YAKALANMIŞ: {0}',
    'key.creadex.detail.evolution': 'GELİŞİM',
    'key.tab.doll': 'KAHRAMAN',
    'key.tab.artifacts': 'ARTEFAKTLAR',
    'key.activePoint.title': 'Bolluk Obelisk',
    'key.personalization.title': 'Büyü',
    'key.chest.title': 'Büyülü Sandık',
    'key.quest.daily.title': 'GÖREV',
    'key.quest.weekly.title': 'AVLAMA',
    'key.quest.get': 'GÖREV AL',
    'key.quest.change': 'GÖREVİ DEĞİŞTİR',
    'key.quest.progress': 'İlerleme durumu: {1}\'dan {0}',
    'key.error.quest.weekly.level': 'Altın Yumurta\'ya avlamaya başlamak için {0}.seviyeye ulaşmanız gerek',
    'key.error.quest.daily.level': 'Göreve başlamak için {0}.seviyeye ulaşmanız gerek',
    'key.error.quest.tooFar': 'Bolluk Obelisk çok uzak',
    'key.quest.daily.descr.noQuest.title': 'Görev almadınız',
    'key.quest.daily.descr.noQuest': 'Göreve başlamak ve ödül kazanmak için Bolluk Obelisk kullanın.',
    'key.quest.daily.timer.descr': 'Görevi az sonra değiştirebilirsiniz:',
    'key.quest.daily.waitForNew.descr': 'Yeni görevi az sonra alabilirsiniz: ',
    'key.quest.weekly.getFragment': 'HARİTANIN PARÇASINI GÖSTER',
    'key.quest.weekly.descr.noQuest.title': 'Altın Yumurta\'ya avlamaya katılmadınız',
    'key.quest.weekly.descr.noQuest': 'Altın Yumurta\'ya avlamaya katılmadınız. Haritanın bir parçasını görmek ve arayışlara başlamak için Bolluk Obelisk kullanın.',
    'key.quest.weekly.descr.getFirstFragment': 'Altın Yumurta\'ya avlamaya başlamak için haritanın 1. parçasını alın',
    'key.quest.weekly.descr.top.notAllOpen': 'Haritanın parçalarını almak için Bolluk Obelisk kullanın. Acele edin, avlama birazdan bitecek: ',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Altın Yumurta\'yı bulmak için haritanın her parçasında Kürek kullanın',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Bu Obelisk\'dan haritanın parçasını az önce aldınız',
    'key.quest.weekly.descr.top.allOpen': 'Obelisk’lardan haritanın tüm parçalarını önce aldınız. Acele edin, avlama birazdan zona erecek: ',
    'key.quest.weekly.descr.bot.allOpen': 'Altın Yumurta\'yı bulmak için haritanın her parçasında Kürek kullanın',
    'key.quest.weekly.descr.top.completed': 'Bu hafta Altın Yumurtayı buldunuz. Sonraki avlama birazdan başlayacak: ',
    'key.timer.format.S': '{0}sn.',
    'key.timer.format.M': '{0}dk.',
    'key.timer.format.M_S': '{0}dk. {1}sn.',
    'key.timer.format.H': '{0}sa.',
    'key.timer.format.H_M': '{0}sa. {1}dk.',
    'key.timer.format.D': '{0}gün',
    'key.timer.format.D_H': '{0}gün {1}sa.',
    'key.creatureStorage.tab.creatures': 'YARATIKLAR',
    'key.creatureStorage.tab.eggs': 'YUMURTALAR',
    'key.creatureStorage.multiTransferText': 'Kovmak istediğiniz yaratığı seçin',
    'key.storage.creature.transfer': 'Kov ({0})',
    'key.error.needHigherLevelForArena': 'Arena\'ya girmek için {0}. seviyeye ulaşmanız gerek',
    'key.error.needHigherLevelForLibrary': 'Kütüphane\'ye girmek için {0}. seviyeye ulaşmanız gerek',
    'key.error.arenaUnderProtection': 'Arena İlahi Koruma altında bulunuyor',
    'key.error.buildingTooFar': 'Bu yapı çok uzak',
    'key.error.noAliveCreaturesForAttack': 'Hayatta kalan yaratık yok',
    'key.error.noHealPotion': 'Tedavi edici sihir yok',
    'key.error.noResurrectionPotion': 'Canlandırma büyüsü yok',
    'key.error.tryAgainLater': 'Hata. Az sonra bir daha deneyin',
    'key.error.alreadyHasLure': 'Yem az önce kullanılmıştı',
    'key.error.cannotUseLureInDungeon': 'Arkana Vadisi\'nde yem kullanılmaz',
    'key.error.bagIsFull': 'Çantada boş yer kalmadı',
    'key.error.cantTransferCreature': 'Bu yaratık kovulmaz',
    'key.notification.done': 'Hazır!',
    'key.modal.doYouWantToTransfer': 'Bu yaratıkları kovmak istiyor musunuz?',
    'key.modal.youWillLoseBuddyProgress': 'Yaratığı değiştirmek istiyor musunuz? Ruhlar taşı alımı sıfırlanır.',
    'key.modal.doYouWantToLeaveDungeon': 'Arkana Vadisi\'nden çıkmak istiyor musunuz?',
    'key.modal.superVisionActive': 'Ejderha vizyonu az önce aktif hale getirilmişti. Bunu bir daha kullanmak istiyor musunuz?',
    'key.modal.experienceBoosterActive': 'Hikmet Kristalı az önce aktif hale getirilmişti. Bunu bir daha kullanmak istiyor musunuz?',
    'key.modal.youWillLooseQuestProgress': 'Yapılan görevin kaydı silinecek. Devam etmek istiyor musunuz?',
    'key.modal.doYouWantToEnterDungeon': 'Portal üzerinden Arkana Vadisi\'ne geçmek istiyor musunuz?',
    'key.modal.doYouWantPersonalizePoint': '{1} coin karşılığına Bolluk Obelisk\'dan {0} almak istiyor musunuz?',
    'key.modal.doYouWantToDeletePersonalization': 'Bu Bolluk Obelisk üzerinden büyüyü kaldırmak istiyor musunuz?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Bu yaratığı güçlendirmek istiyor musunuz?',
    'key.modal.doYouWantToEvolveThisCreature': 'Bu yaratığı daha güçlü yapmak istiyor musunuz?',
    'key.modal.doYouWantToScoutHere': 'Bu alanı görmek istiyor musunuz?',
    'key.error.creatureHasMaxLevel': 'Bu yaratık artık maksimum seviyeye geliştirildi',
    'key.error.creatureHasMaxLevelForUser': 'Önce Kahramanın seviyesini yükseltmek gerek',
    'key.error.notEnoughResourcesForEnhance': 'Kaynak yetmiyor',
    'key.error.creatureIsArenaDefender': 'Yapıyı koruyan yaratık seçilmez',
    'key.modal.incenseActive': 'Feromonlar az önce aktif hale getirilmişti. Bunları bir daha kullanmak istiyor musunuz?',
    'key.error.cantHealHealthyCreature': 'Yaratık tamamen tedavi edildi',
    'key.error.cantRessurectAliveCreature': 'Yaratık canlandırıldı',
    'key.error.noTreasureHere': 'Haritanın bu parçasında Altın Yumurta bulunmadı. Aramaya devam edin.',
    'key.error.levelTooSmall': 'Önce Kahramanın seviyesini yükseltmek gerek',
    'key.error.needHigherLevelForWizardBattles': 'Büyücüler Savaşları\'na katılmak için {0}.seviyeye ulaşmanız gerek',
    'key.error.artifactBagIsFull': 'Artefakt Hazinesi dolu',
    'key.error.notEnoughCoins': 'Coin yetmiyor',
    'key.error.allFragmentsAreOpen': 'Haritanın tüm parçaları gösterilmiş',
    'key.error.questAlreadyCompleted': 'Bu görev artık tamamlandı',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Haritanın parçası bu Obelisk\'dan artık alındı',
    'key.error.portalTooFarAway': 'Portal uzak bulunuyor',
    'key.error.battleLimitAlreadyEnhanced': 'Savaş limiti artık yükleltildi',
    'key.error.youAreNotAltarOwner': 'Bu işlemi ancak Sunağın sahibi yapabilir',
    'key.error.youAlreadyHaveAltar': 'Sunak artık kurulmuş durumda',
    'key.error.cantTakeAnotherUsersRune': 'Runik Taşlar diğer oyuncudan çalınmaz',
    'key.error.libraryBlocked': 'Dönüştürme yapıldıktan sonra Kütüphane kullanmak için 3 gün beklemek gerek.',
    'key.error.notAuthorized': 'Kullanıcı oyunda değil',
    'key.error.eggOnlyRoost': 'Bu yumurtayı Ejderhalar Annesi\'ne teslim etmek gerek',
    'key.error.purchase': 'Hata: {0}',
    'key.error.creatureIsDead': 'Önce yaratığı canlandırmak gerek',
    'key.error.no_connection': 'Server ile bağlantı yok. Az sonra bir daha deneyin.',
    'key.error.protocol_version_mismatch': 'Oyun sayfasını yenileyin.',
    'key.error.update_application': 'Oyun sayfasını yenileyin.',
    'key.modal.doYouWantToTransferSingle': 'Bu yaratığı kovmak istiyor musunuz?',
    'key.notification.phoneNotSupportAR': 'Cihazınızda AR desteklenmiyor',
    'key.notification.turnOnARPermission': 'Kamera açık değil. Ayarlarda kamerayı açın',
    'key.notification.dailyQuestFinished': 'Görev başarıyla tamamlandı!',
    'key.modal.yesBtn': 'Evet',
    'key.modal.noBtn': 'Hayır',
    'event.log.DAILY_QUEST_COMPLETED': 'Günlük görev tamamlandı. Kazandığınız bonus:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Avlama sona erdi. Kazandığınız bonus:',
    'event.log.ENCOUNTER_VICTORY': 'Vahşi canavar yenildi!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Oyunun son versiyonunu yükleyin.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Kimlik doğrulama hatası',
    'key.ServiceException.Cause.SESSION_GONE': 'Oyun hesabınıza diğer cihazdan giriş yapıldı',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'Kullanıcı ID boş',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Kullanıcı bulunamadı',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Dürüst olmayan şekilde oynadığınız için hesabınız kilitlendi.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Dolandırıcılık ödemelerin yapılması nedeniyle hesabınız kilitlendi.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Kullanıcı adının küfür içerikli olması nedeniyle hesabınız kilitlendi.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Diğer oyuncularla agresif şekilde konuşmanız nedeniyle hesabınız kilitlendi.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Dürüst olmayan şekilde oynadığınız için hesabınız kilitlendi.',
    'key.ServiceException.Cause.USER_BANNED': 'Hesabınız kilitlendi.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Çantada boş yer kalmadı',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maksimum yumurta sayısı',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Coin yetmiyor',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Ruhlar Taş yetmiyor',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Esans yetmiyor',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Yaratıklar Deposu dolu',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Yaratık maksimum seviyeye geliştirildi',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Bu yaratığı dönüştüremezsiniz',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Yaratık adı maksimum 14 karakter olmalı',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Arena artık maksimum derecede korumalıdır',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Arena\'yı koruyan yaratık evcilleştirilmez',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Yaratığınız bu Arena\'yı korumaya az önce gönderildi',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Hata',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Savaş bulunamadı',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Hata',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Yaratığınız artık bu yapıyı koruyor',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Arena İlahi Koruma altındadır',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Haraç toplama zamanı gelmedi',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Yanlış Küre',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Yanlış bina',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Erişim engellendi',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'İtem bulunamadı',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Formül bulunamadı',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Sadece bir Sunak kurulabilir',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Önce Kahramanın seviyesini yükseltin',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Yaratık yakalamaya başlayamadınız',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Bu tür mal yok',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Bu tür mal yok',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Bu tür bina yok',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Yaratık bulunamadı',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Yaratık bulunamadı',
    'key.ServiceException.Cause.TOO_FAR': 'Bina çok uzak bulunuyor',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Obje çok uzak',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Bina yenileniyor',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Yapı Arkana Vadisi\'nde bulunuyor',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Yapı kullanılır durumda değil',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Ejderha Kozası bulunamadı',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Ejderha Kozası boş',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Ejderha Kozası dolu',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Yumurta yumurtlanmadı',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Yumurta bulunmadı',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Bu yumurta için Ejderhalar Annesi gerek',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Güç tükendi',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Yapı kurulmadı',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Hata konulu bildiri',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Vahşi canavar kaçtı',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Vahşi canavar bulunamadı',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'Bu Obelisk\'de yem var',
    'key.ServiceException.Cause.WRONG_ITEM': 'Yanlış item',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Bu Runik Taş en güçlüdür',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Bu seviyeli Runik Taş yetmiyor',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Yanlış Runik Taş slotu',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Bu slot artık meşgul',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Runik Taş slotu boş',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Arena koruyucusu seçilmez',
    'key.ServiceException.Cause.WRONG_SPELL': 'Yanlış büyü',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Büyü için daha çok Runik Taş gerek',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Şu an yeni görev verilmez',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Bu Obelisk az önce kullandınız',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Haritanın tüm parçaları gösterildi',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Altın Yumurta\'ya avlamaya katılmadınız',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Bu alanda Altın Yumurtayı daha önce bulmaya çalıştınız',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Yaratığınızı az önce yedirdiniz',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Yaratık az önce yakalandı',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Yaratık henüz dönüştürülmez',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Kütüphane henüz kapalı',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Servera ulaşılamıyor. Az sonra bir daha deneyin',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Savaş limiti az önce yükseltildi',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Savaş limitine ulaşıldı',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Büyücüler Savaşlarına katılmak için 10. seviyeye ulaşmanız gerek',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Büyücüler Savaşları için düşman bulunamadı. Az sonra bir daha deneyin',
    'key.ServiceException.Cause.MARKET_ERROR': 'Hata. Mağaza kullanılmaz',
    'key.ServiceException.Cause.NO_CHEST': 'Sandık bulunamadı',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Hata. Az sonra bir daha deneyin.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Ejderhalar Annesi\'ne daha çok yumurta vermek için Ejderha Kalbi veya Ejderha Artefakt Takımını giyinmek gerek',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Bu slotta yumurta var',
    'key.ServiceException.Cause.NO_CONNECTION': 'İnternet ile bağlantı yok',
    'key.ServiceException.Cause.SERVER_DOWN': 'Servera ulaşılamıyor. Biraz sonra bir daha deneyin.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Serverda şu an teknik işler yapılmaktadır. Az sonra bir daha deneyin.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Bu Runik Taşlar şu an kullanılıyor',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Çok hızlı yürüyorsunuz',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Ele geçirilen Arena sayısı limite ulaştı',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Ele geçirilen Kütüphane sayısı limite ulaştı',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Hata: GPS ulaşılmaz durumda',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Bu büyü Arkana Vadisi\'nde kullanılmaz',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Zaman tükendi',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Oyunun versiyonu eskidir. Onu yenilemek gerek.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Görüş alanında müttefik Arena yok',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Görüş alanında düşman Arena yok',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'küreler',
    'stop.personalized.HEALS': 'tedavi edici iksirler',
    'stop.personalized.RESURRECTIONS': 'canlandırıcı iksirler',
    'stop.personalized.EGGS': 'yaratık yumurtaları',
    'stop.personalized.FOODS': 'yem',
    'key.button.cancelPersonal': 'İptal',
    'key.error.needHigherLevelForSofaBattles': 'Büyücüler Savaşlarına katılmak için {0}.seviyeye ulaşmanız gerek',
    'fraction.text.youWilLGetBonus': 'Bu fraksiyona katıldıktan sonra {0} coin kazanacaksınız',
    'fraction.text.fractionUnavailable': 'Fraksiyon şu an müsait değil',
    'fraction.text.chooseYourAlliance': 'Savaşmak istediğiniz fraksiyonu seçin',
    'fraction.text.redFractionName': 'Kırmızı Nişan',
    'fraction.text.blueFractionName': 'Mavi Nişan',
    'key.error.chestTooFarAway': 'Sandık çok uzak bulunuyor',
    'key.button.openChest': 'Aç',
    'key.candy.MONSTER_WATER_1': 'Kurbağacık Taşları',
    'key.candy.MONSTER_WATER_2': 'Damlacık Taşları',
    'key.candy.MONSTER_WATER_3': 'Spiritus Taşları',
    'key.candy.MONSTER_WATER_4': 'Overaquian Taşları',
    'key.candy.MONSTER_WATER_8': 'Jöleşapkalı Taşları',
    'key.candy.MONSTER_WATER_9': 'Minor Taşları',
    'key.candy.MONSTER_WATER_10': 'Kunduzcuk Taşları',
    'key.candy.MONSTER_WATER_12': 'Dadachock Taşları',
    'key.candy.MONSTER_WATER_13': 'Tırpanacık Taşları',
    'key.candy.MONSTER_WATER_23': 'Kunduzcuk Taşları',
    'key.candy.MONSTER_WATER_24': 'Neptün Taşları',
    'key.candy.MONSTER_WATER_25': 'Leviathan Taşları',
    'key.candy.MONSTER_FIRE_1': 'Kazancık Taşları',
    'key.candy.MONSTER_FIRE_2': 'Kabakkafalı Mumyacık Taşları',
    'key.candy.MONSTER_FIRE_3': 'Buharcı Taşları',
    'key.candy.MONSTER_FIRE_4': 'Ejderha Yavrusu Taşları',
    'key.candy.MONSTER_FIRE_6': 'Alevcik Taşları',
    'key.candy.MONSTER_FIRE_7': 'Phoby Taşları',
    'key.candy.MONSTER_FIRE_11': 'Kıvılcım Taşları',
    'key.candy.MONSTER_FIRE_12': 'Hydra Taşları',
    'key.candy.MONSTER_FIRE_15': 'Sıcak İğne Taşları',
    'key.candy.MONSTER_FIRE_25': 'Dumancık Taşları',
    'key.candy.MONSTER_EARTH_1': 'Kirpicik Taşları',
    'key.candy.MONSTER_EARTH_2': 'Çiçek Ejderhası Taşları',
    'key.candy.MONSTER_EARTH_3': 'Orman Perisi Taşları',
    'key.candy.MONSTER_EARTH_4': 'Brownie Taşları',
    'key.candy.MONSTER_EARTH_8': 'Goblincik Taşları',
    'key.candy.MONSTER_EARTH_9': 'Çağanozcuk Taşları',
    'key.candy.MONSTER_EARTH_10': 'Palamutçuk Taşları',
    'key.candy.MONSTER_EARTH_11': 'Phylo Taşları',
    'key.candy.MONSTER_EARTH_13': 'Princie Taşları',
    'key.candy.MONSTER_EARTH_25': 'Scylla Taşları',
    'key.candy.MONSTER_DUNGEON_1': 'Rookie Taşları',
    'key.candy.MONSTER_DUNGEON_2': 'Aksolan Taşları',
    'key.candy.MONSTER_DUNGEON_3': 'Dikenli Taşları',
    'key.candy.MONSTER_DUNGEON_4': 'Salyangoz Taşları',
    'key.candy.MONSTER_DUNGEON_5': 'Şirin Kedi Taşları',
    'key.candy.MONSTER_DUNGEON_6': 'Fok Yavrusu Taşları',
    'key.candy.MONSTER_DUNGEON_12': 'Vampir Yarasa Taşları',
    'key.candy.MONSTER_DUNGEON_13': 'Yaşlı Kaz Taşları',
    'key.candy.MONSTER_DUNGEON_17': 'Inur Taşları',
    'key.candy.MONSTER_WIND_1': 'SunTzi Taşları',
    'key.candy.MONSTER_WIND_2': 'Yarasa Taşları',
    'key.candy.MONSTER_WIND_3': 'Shroomy Taşları',
    'key.candy.MONSTER_WIND_4': 'Tüylü Boynuzlu Taşları',
    'key.candy.MONSTER_WIND_6': 'Gamayun Taşları',
    'key.candy.MONSTER_WIND_7': 'Ürkütücü Taşları',
    'key.candy.MONSTER_WIND_11': 'Infird Taşları',
    'key.candy.MONSTER_WIND_12': 'Su Perisi Taşları',
    'key.candy.MONSTER_WIND_15': 'Cheshir Taşları',
    'key.candy.MONSTER_WIND_25': 'Charybdis Taşları',
    'key.button.leaveDungeon': 'Arkana Vadisi\'nden çık',
    'key.alias.enterNewAlias': 'Yaratık adını girin',
    'key.alias.enterText': 'Metin yazın...',
    'key.hut.hutName': 'Ejderhalar Annesi',
    'key.hut.hutDescr': 'Yumurtlanması için tüm antik yumurtaları Ejderhalar Annesi\'ne teslim edin',
    'key.text.noHutEggs': 'Sizde Antik yumurta yok',
    'key.text.noCapturedArenas': 'Ele geçirdiğiniz Arena yok',
    'key.text.noChosenPet': 'Yaratığı seçin',
    'key.text.noArtifacts': 'Sizde Artefakt yok',
    'key.text.noCreatures': 'Bir yaratık henüz yakalamadınız',
    'key.text.noLureItems': 'Yem yok',
    'key.descr.aboutWizardBattles': 'XP ve bonus kazanmak için diğer oyuncularla düello yapın ve savaşın',
    'key.text.writeToSupport': 'Teknik desteğe yaz',
    'key.text.regUsingFacebook': 'Facebook üzerinden kayıtlı ol',
    'key.text.regUsingGoogle': 'Google üzerinden kayıtlı ol',
    'key.text.logUsingFacebook': 'Facebook üzerinden giriş yap',
    'key.text.logUsingGoogle': 'Google üzerinden giriş yap',
    'key.text.logUsingDeviceIDCurrent': 'Cihaz ID üzerinden giriş yap',
    'key.text.logUsingDeviceIDNew': 'Cihaz ID üzerinden giriş yap (yeni hesap)',
    'key.text.createAccount': 'Oyna',
    'key.text.connectedToFacebook': 'Facebook ile bağlantılı',
    'key.text.connectedToGoogle': 'Google ile bağlantılı',
    'key.text.complainAboutPoint': 'Lokasyon için şikayet gönder',
    'key.text.copyCoordinates': 'Koordinatları kopyala',
    'key.text.complainEnterEmail': 'E-mail adresiniz',
    'key.text.complainEnterText': 'Probleminizi anlatın',
    'key.modal.doYouWantToCloseApp': 'Oyundan çıkmak istiyor musunuz?',
    'key.catchPopup.notBad': 'Fena değil!',
    'key.catchPopup.good': 'İyi!',
    'key.catchPopup.sumptuously': 'Çok iyi!',
    'key.catchPopup.twistedThrow': 'Bükülü atış!',
    'key.battlePopup.strongHit': 'Güçlü vuruş!',
    'key.battlePopup.weakHit': 'Zayıf vuruş',
    'key.battlePopup.dodge': 'Kaçış!',
    'key.battlePopup.chargedAttack': '{0} {1} kullanıyor',
    'auth.login.play': 'Oyna',
    'auth.login.nickname.placeholder': 'Adınızı girin',
    'auth.login.nickname.busy': 'Bu isim artık kullanılıyor',
    'auth.login.nickname.proposal': 'Bu adı kullanabilirsiniz:',
    'auth.login.nickname.deviceId': 'Kayıtlı hesabınız var',
    'auth.login.social.title': 'Sosyal ağ üzerinden giriş yapın',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': '{0}\'a bağlantılı',
    'auth.login.social.signOut': 'Hesaptan çık',
    'auth.login.signOut.confirmation': 'Hesaptan çıkmak istiyor musunuz?',
    'auth.login.social.userCancelledError': 'Bağlamayı iptal et',
    'auth.login.social.cantSignInError': '{0}\'ya bağlanamıyor',
    'licence.title': '«DRACONİUS GO: CATCH A DRAGON!» KULLANICI SÖZLEŞMESİ',
    'licence.checkbox': 'Benim e-mail adresime haber ve önerileri gönderin',
    'licence.accept': 'Kabul et',
    'licence.decline': 'Vazgeç',
    'key.error.wrongRoostIndex': 'Slot meşgul',
    'key.speed.passenger': 'Yolcuyum',
    'key.activeObjects.addUnit.question': '{0}\'yı bu yapının koruyucusu yapmak istiyor musunuz?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} saat',
    'key.confirm.selectAlliance': 'Bu fraksiyonu seçmek istiyor musunuz? Bundan sonra onu değiştiremezsiniz.',
    'key.confirm.giveUpEncounter': 'Vahşi canavarla savaşmaktan vazgeçmek istiyor musunuz?',
    'key.confirm.giveUpBattle': 'Teslim etmek ve savaşı bitirmek istiyor musunuz?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Yükleniyor...',
    'key.layerUp.title': 'Yeni Lig!',
};
