module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Áno',
    'key.button.cancel': 'ZRUŠIŤ',
    'key.button.apply': 'ОК',
    'key.button.use': 'Použiť',
    'key.button.buy': 'Kúpiť',
    'key.beCarefulMessage.text': 'Počas hry buďte opatrní. Obzerajte sa okolo seba.',
    'key.creature.details.attack': 'Sila',
    'key.creature.details.health': 'Zdravie',
    'key.creature.details.powerUp': 'Posilnenie',
    'key.creature.details.evolve': 'Transformácia',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'CP {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'UVOĽNIŤ',
    'key.creature.details.creadex': 'Beštiár',
    'key.creature.registration.creadex': 'Pridané k Beštiáru',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Dobyté budovy',
    'key.activeObjects.library': 'Preškolenie bytosti v Knižnici',
    'key.activeObjects.library.empty': 'Nie sú dobyté Knižnice',
    'key.activeObjects.arena': 'Vyberanie daní z Arén',
    'key.activeObjects.arena.collect': 'Vybrať',
    'key.activeObjects.arena.empty': 'Nie sú dobyté Arény',
    'key.activeObjects.error.timer': 'Vyberanie dani nie je dostupné. Je treba počkať',
    'key.activeObjects.error.noMoney': 'Najskôr je potrebné obsadiť Arénu',
    'key.activeObjects.error.cannotRemaster': 'Preškolenie nie je k dispozícii. Dobývajte nové Knižnice pre zrýchlenie časovača preškolenia.',
    'key.activeObjects.library.remaster': 'Preškoliť',
    'key.activeObjects.library.blocked': 'Knižnice nie sú k dispozícii',
    'key.activeObjects.remaster.confirmation.main': 'Naozaj chcete preškoliť {0}? Hlavné zručnosť {1} bude nahradená!',
    'key.activeObjects.remaster.confirmation.charged': 'Naozaj chcete preškoliť {0}? Dobíjacia zručnosť {1} bude nahradená.',
    'key.activeObjects.remaster.error': 'Chyba',
    'key.activeObjects.item.weaklyBonus': 'Týždenný bonus + {0} mince',
    'key.library.remaster.selectCreature': 'Vyberte bytosť, ktorú chcete preškoliť',
    'key.remasterPanel.title': 'Vyberte zručnosť pre nahradenie',
    'key.storage.creatues': 'Bytosti',
    'key.storage.eggs': 'Vajcia',
    'key.storage.eggs.simple': 'Obyčajné vajcia',
    'key.storage.eggs.super': 'Starobylé vajcia',
    'key.storage.eggs.missingAny': 'Nemáte vajcia bytostí',
    'key.startEgg.button': 'Umiestniť do kokónu',
    'key.startEgg.description': 'Použite dračí kokón, aby ste vysedeli toto vajce',
    'key.startEgg.incubator.title': 'Dračie kokóny',
    'key.startEgg.select.title': 'Vyberte vajce',
    'key.openEgg.button': 'Otvoriť vajce',
    'key.openEgg.description': 'Nová bytosť sa teraz vyliahne z vajca',
    'key.startEgg.description.roost.hatching': 'Matka Drakov vysedáva toto vajce. Musíme len počkať. Vysedávanie sa preruší, ak zmizne Zlom Arkany, v ktorom sa nachádza Matka Drakov',
    'key.startEgg.description.roost.notHatching': 'Dajte to vajce Matke Drakov, aby ho vysedela pre vás',
    'key.startEgg.description.simple.hatching': 'Toto vajce sa vysedáva v dračom kokóne. Ak sa mu chcete pomôcť vykľuť, nevypínajte hru',
    'key.startEgg.description.simple.notHatching': 'Umiestnite toto vajce do dračieho kokónu pre spustenie vysedávania. Vajce sa vykľuje, keď prejdete nutnú vzdialenosť',
    'key.mainMenu.wizardDuels': 'SÚBOJ MÁGOV',
    'key.mainMenu.quests': 'ÚLOHY',
    'key.mainMenu.activePoints': 'DOBYTÉ',
    'key.mainMenu.creadex': 'BEŠTIÁR',
    'key.mainMenu.magic': 'MÁGIA',
    'key.mainMenu.creatues': 'BYTOSTI',
    'key.mainMenu.shop': 'OBCHOD',
    'key.mainMenu.backpack': 'TAŠKA',
    'key.error.banned': 'Účet je blokovaný',
    'event.log.CREATURE_CAUGHT': '{0} je chytený!',
    'event.log.ITEM_BOUGHT': '{0} x{1} kúpený. Boli minuté {2} mince',
    'event.log.ARTIFACT_BOUGHT': 'Bol kúpený artefakt: {0}. Bola minutá {1} minca',
    'event.log.EGG_HATCHED': '{0} vykľul sa z {1} vajca!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'zlatého',
    'event.log.ROOST_EGG_HATCHED': 'Matka Drakov vysedela {1} vajce.{0} je teraz váš!',
    'event.log.CHEST_OPENED': 'V truhle sa našlo',
    'event.log.ARENA_LOST_CONTROL': '{1} bol vyhodený z budovy: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} bol vyhodený z budovy: {0}',
    'event.log.LEVEL_UP': 'Dosiahli ste úroveň {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Miláčik našiel {0}',
    'event.log.QUEST_COMPLETED': 'Odmena za úlohu {0}',
    'event.log.ENCOUNTER_LOOSE': 'Utiekli ste od divokého monštra',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Limit bitiek v Súboji Mágov bol zvýšený za {0} mince',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} mincí bolo nakúpených za {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Taška bola vylepšená za {0} mincí',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Skladisko bytostí bolo vylepšené za {0} mincí',
    'key.shop.accesories': 'PREDMETY',
    'key.shop.artifacts': 'ARTEFAKTY',
    'key.shop.donate': 'MINCE',
    'key.shop.upgrade': 'ZLEPŠENIA',
    'key.shop.donate.coins': '{0} mincí',
    'key.shop.upgrade.bag': 'Rozšírenie tašky',
    'key.shop.upgrade.bag.desc': 'Veľkosť tašky sa zvýši o 50',
    'key.shop.upgrade.storage': 'Rozšírenie skladiska bytostí',
    'key.shop.upgrade.storage.desc': 'Veľkosť skladiska bytostí sa zvýši o 50',
    'key.shop.donate.dialog.title': 'Chýbajú mince',
    'key.shop.donate.dialog.desc': 'Získajte je tu alebo navštívte Obchod, kde nájdete ďalšie možnosti',
    'key.potionUseMenu.title': 'Liečebné elixíry',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Vytvára Portál do sveta Arkany',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Všetci hráči okolo pocítia zúrivosť leprikónov',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Na 30 minút vytvára pole Stĺpov hojnosti',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Na 30 minút zdvojnásobuje množstvo odmien zo Stĺpov hojnosti',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Dlhými stlačeniami po teréne ho osvetlíš pri hľadní monštier',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Na 30 minút zväčšuje rádius objavenia monštier',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Na 7 dní zväčšuje rádius rozhľadu o 30%',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'Najbližšia zväzová Aréna nebude prístupná pre útok nepriateľmi počas 30 hodín',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Všetky nepriateľské Arény v rádiuse viditeľnosti sa stanú neutrálnymi. Odstraňuje Požehnanie obrany.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Vytvára magickú vežu, ktorá priťahuje bytosti ohnivého živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Vytvára magickú vežu, ktorá priťahuje bytosti vodného živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Vytvára magickú vežu, ktorá priťahuje bytosti vzdušného živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Vytvára magickú vežu, ktorá priťahuje bytosti zemského živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Vytvára magickú vežu, ktorá priťahuje bytosti živlu Arkany',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Zlom Arkany',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Hnev leprikónov',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Pole hojnosti',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Dar Zlatého draka',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astrálne videnie',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Dračí zrak',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Dlhé ruky',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Požehnanie obrany',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Očistenie ohňom',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Ohnivá veža',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Vodná veža',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Vzdušná veža',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Zemská veža',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Veža Arkany',
    'key.buff.ATTACKER_CP_BOOST': 'CP vašich bytostí bola dočasne zvýšená',
    'key.buff.BEST_BALL_LUCK': 'Len najlepšie sféry v Stĺpoch hojnosti počas 30 min',
    'key.buff.BEST_POTION_LUCK': 'Len najlepšie elixíry v Stĺpoch hojnosti počas 30 min',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 predmety zo Stĺpov hojnosti počas 30 min',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Čas do preškolení v Knižnici je znížený o {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Čas do výberu daní z Arény je znížený o {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Zvyšuje CP netvorov, ktorí nie sú obrancovia budov',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Zo Stĺpov Hodnosti získavate len najlepšie sféry, ktoré sú k dispozícii pre vašu úroveň',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Zo Stĺpov Hojnosti získavate len najlepšie elixíry, ktoré sú k dispozícii pre vašu úroveň',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Zo Stĺpov Hojnosti získavate na dva predmety viac',
    'key.loot.result.dust': 'Esencia',
    'key.loot.result.exp': 'Skúsenosť postavy',
    'key.loot.result.coin': 'Mince',
    'key.loot.result.candy': 'kamene',
    'key.item.MAGIC_BALL_SIMPLE': 'Sféra žiaka',
    'key.item.MAGIC_BALL_NORMAL': 'Sféra magistra',
    'key.item.MAGIC_BALL_GOOD': 'Sféra veliteľa',
    'key.item.LURE': 'Nástraha',
    'key.item.INCENSE': 'Feromóny',
    'key.item.EGG': 'Vajce',
    'key.item.SHOVEL': 'Lopata',
    'key.item.POTION_HEAL_1': 'Malý liečebný elixír',
    'key.item.POTION_HEAL_2': 'Stredný liečebný elixír',
    'key.item.POTION_HEAL_3': 'Veľký liečebný elixír',
    'key.item.POTION_HEAL_4': 'Elixír úplného uzdravenia',
    'key.item.POTION_RESURRECTION_1': 'Elixír oživenia',
    'key.item.POTION_RESURRECTION_2': 'Veľký elixír oživenia',
    'key.item.INCUBATOR_1': 'Dračí kokón',
    'key.item.INCUBATOR_3': 'Dračí kokón',
    'key.item.INCUBATOR_PERPETUAL': 'Večný dračí kokón',
    'key.item.SUPER_VISION': 'Dračí zrak',
    'key.item.RUNE_1': 'Rúna 1',
    'key.item.RUNE_2': 'Rúna 2',
    'key.item.RUNE_3': 'Rúna 3',
    'key.item.RUNE_4': 'Rúna 4',
    'key.item.RUNE_5': 'Rúna 5',
    'key.item.RUNE_6': 'Rúna 6',
    'key.item.FOOD_CATCH_CHANCE': 'Arkanický karamel',
    'key.item.FOOD_MORE_DUST': 'Magický papmúch',
    'key.item.FOOD_CALM_DOWN': 'Ovocný krém jednorožca',
    'key.item.FOOD_MORE_CANDIES': 'Zmrzlinka štyroch živlov',
    'key.item.EXPERIENCE_BOOSTER': 'Kryštál múdrosti',
    'key.item.EGG_KM_0': 'Zlaté Vajce',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sféra pre chytenie bytostí.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sféra pre chytenie bytostí. Trochu zvyšuje šancu na chytenie.',
    'key.item.MAGIC_BALL_GOOD.description': 'Sféra pre chytenie bytostí. Veľmi zvyšuje šancu na chytenie.',
    'key.item.LURE.description': 'Nástraha pre bytosti. Vložte do Stĺpov hojnosti aby ste k nim prilákali bytosti.',
    'key.item.INCENSE.description': 'Feromóny k Vám prilákajú bytosti určitého živlu podľa dňa týždňa.',
    'key.item.EGG.description': 'Používajte dračí kokón pre vysedenie bytosti z vajcia',
    'key.item.SHOVEL.description': 'Lopaty sú úplne nenahraditeľné pri hľadaní pokladov',
    'key.item.POTION_HEAL_1.description': 'Vylieči bytosť o 200 jednotiek zdravia',
    'key.item.POTION_HEAL_2.description': 'Vylieči bytosť o 500 jednotiek zdravia',
    'key.item.POTION_HEAL_3.description': 'Vylieči bytosť o 1000 jednotiek zdravia',
    'key.item.POTION_HEAL_4.description': 'Úplne vylieči bytosť',
    'key.item.POTION_RESURRECTION_1.description': 'Oživuje zvolenú bytosť. Po vskriesení bude bytosť poranená.',
    'key.item.POTION_RESURRECTION_2.description': 'Oživuje a úplne vylieči bytosť',
    'key.item.INCUBATOR_1.description': 'Dračie kokóny sú nutné pre vysedenie bytostí z vajec. Mizne po použití.',
    'key.item.INCUBATOR_3.description': 'Dračie kokóny sú nutné pre vysedenie bytostí z vajec. Mizne po 3. použití.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Dračie kokóny sú nutné pre vysedenie bytostí z vajec.',
    'key.item.SUPER_VISION.description': 'Ukazuje bytosti vo veľkej oblasti',
    'key.item.RUNE_1.description': 'Magická rúna 1. úrovne',
    'key.item.RUNE_2.description': 'Magická rúna 2. úrovne',
    'key.item.RUNE_3.description': 'Magická rúna 3. úrovne',
    'key.item.RUNE_4.description': 'Magická rúna 4. úrovne',
    'key.item.RUNE_5.description': 'Magická rúna 5. úrovne',
    'key.item.RUNE_6.description': 'Magická rúna 6. úrovne',
    'key.item.FOOD_CATCH_CHANCE.description': 'Maškrta pre chytenie bytostí. Zvyšuje šancu zachytiť bytosť magickou sférou',
    'key.item.FOOD_MORE_DUST.description': 'Maškrta pre chytenie bytostí. Zvyšuje množstvo esencí, ktoré dostaneme za chytenie',
    'key.item.FOOD_CALM_DOWN.description': 'Maškrta pre chytenie bytostí. Upokojuje bytosť. Prestáva skákať a útočiť',
    'key.item.FOOD_MORE_CANDIES.description': 'Maškrta pre chytenie bytostí. Zvyšuje množstvo kameňov duší, ktoré dostaneme za chytenie',
    'key.item.EXPERIENCE_BOOSTER.description': 'Na 30 minút zdvojnásobuje získanú skúsenosť',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Maska kúzelníka',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': 'Možnosť posadiť bytosť do Arény alebo Knižnice z diaľky jedenkrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Tento artefakt umožňuje posadiť z diaľky svoju bytosť na prázdne miesto do Arény alebo Knižnice viditeľnej na mape jedenkrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Tvár veštca',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': 'Možnosť posadiť bytosť do Arény alebo Knižnice z diaľky dvakrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Tento artefakt umožňuje posadiť z diaľky svoju bytosť na prázdne miesto do Arény alebo Knižnice viditeľnej na mape dvakrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Prilba dobyvateľa',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': 'Možnosť posadiť bytosť do Arény alebo Knižnice z diaľky trikrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Tento artefakt umožňuje posadiť z diaľky svoju bytosť na prázdne miesto do Arény alebo Knižnice viditeľnej na mape trikrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Prilba hrdinu',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': 'Možnosť posadiť bytosť do Arény alebo Knižnice z diaľky štyrikrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Tento artefakt umožňuje posadiť z diaľky svoju bytosť na prázdne miesto do Arény alebo Knižnice viditeľnej na mape štyrikrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Prilba bojovníka s drakmi',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': 'Možnosť posadiť bytosť do Arény alebo Knižnice z diaľky päťkrát za deň',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Tento artefakt umožňuje posadiť z diaľky svoju bytosť na prázdne miesto do Arény alebo Knižnice viditeľnej na mape päťkrát za deň',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Vlajka vladára',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Dovoľuje posadiť do Arény alebo Knižnice ešte jednu bytosť',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'S týmto artefaktom možno dať do ochrany Arény alebo Knižnice dve bytosti namiesto jednej.',
    'key.artifact.ARTIFACT_BANK_8': 'Vyrezaný artefakt',
    'key.artifact.ARTIFACT_BANK_8.description': 'Ako ste ho vôbec našli?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Uvideli ste artefakt, ktorý ste nemali vidieť. Teraz sa vás ako svedka musíme zbaviť.',
    'key.artifact.ARTIFACT_BANK_9': 'Vyrezaný artefakt',
    'key.artifact.ARTIFACT_BANK_9.description': 'Ako ste ho vôbec našli',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Uvideli ste artefakt, ktorý ste nemali vidieť. Teraz sa vás ako svedka musíme zbaviť.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Hodinky lenivého študenta',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 sekúnd k opätovnému nabíjaniu Stĺpov Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'S týmto artefaktom sa Stĺpy Hojnosti budú opätovne nabíjať o 20 sekúnd rýchlejšie a budete ich môcť používať častejšie',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Budík človeka, ktorý vždy chodí neskoro',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 sekúnd k opätovnému nabíjaniu Stĺpov Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'S týmto artefaktom sa Stĺpy Hojnosti budú opätovne nabíjať o 40 sekúnd rýchlejšie a budete ich môcť používať častejšie',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Priestorový urýchľovač',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 sekúnd k opätovnému nabíjaniu Stĺpov Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'S týmto artefaktom sa Stĺpy Hojnosti budú opätovne nabíjať o 60 sekúnd rýchlejšie a budete ich môcť používať častejšie',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Hodinky lenivého profesora',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 sekúnd k opätovnému nabíjaniu Stĺpov Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'S týmto artefaktom sa Stĺpy Hojnosti budú opätovne nabíjať o 80 sekúnd rýchlejšie a budete ich môcť používať častejšie',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Hodinky zebro-králika',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 sekúnd k opätovnému nabíjaniu Stĺpov Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'S týmto artefaktom sa Stĺpy hojnosti budú opätovne nabíjať o 100 sekúnd rýchlejšie a budete ich môcť používať častejšie',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Žezlo dobyvateľa',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 k úrovni Arény alebo Knižnice po obsadeniu',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Pokiaľ majiteľ toho artefaktu posadí bytosť na zajatú Arénu nebo Knižnicu ako prvý, bytosť ihneď dostane 5. úroveň miesto 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Prsteň vyberača daní',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 k maximálnej hodnote dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'S týmto artefaktom môžete vyberať daň z 11 Arén namiesto obyčajných 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Prsteň chamtivosti',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 k maximálnej hodnote dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'S týmto artefaktom môžete vyberať daň z 12 Arén namiesto obyčajných 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Dvojitý prsteň',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 k maximálnej hodnote dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'S týmto artefaktom môžete vyberať daň z 13 Arén namiesto obyčajných 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Pohár požierateľa koláčov',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% k sláve zväzových Arén a Knižníc počas tréningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'S týmto artefaktom dostávajú zväzové Arény a Knižnice o 20% viac slávy, keď ich trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Kalich na med',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% k sláve zväzových Arén a Knižnic počas tréningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'S týmto artefaktom dostávajú zväzové Arény a Knižnice o 30% viac slávy, keď ich trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Čaša hlbokých myšlienok',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% k sláve zväzových Arén a Knižnic počas tréningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'S týmto artefaktom dostávajú zväzové Arény a Knižnice o 40% viac slávy, keď ich trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Grál Lanselopa',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% k sláve zväzových Arén a Knižnic počas tréningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'S týmto artefaktom dostávajú zväzové Arény a knižnice o 50% viac slávy, keď ich trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Kalich dobyvateľa príšer',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% k sláve zväzových Arén a Knižnic počas tréningu',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'S týmto artefaktom dostávajú zväzové Arény a Knižnice o 80% viac slávy, keď ich trénujete',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem jasného videnia',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Odstraňuje slabé bytosti z radaru',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Tento artefakt odstraňuje slabšie bytosti z radaru, čo pomáha sústrediť sa na hľadanie silných exemplárov',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Rule book dobrodruha',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minút k vyberaniu daní z Arény po obsadení súperom',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'S tým artefaktom sú Arény prístupné pre vyberanie daní ešte počas 30 minút po ich obsadení, namiesto obyčajných 15 minút',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Hrubá solídna kniha',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minút k vyberaniu daní z Arény po obsadení súperom',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'S tým artefaktom sú Arény prístupné pre vyberanie daní ešte počas 45 minút po ich obsadení, namiesto obyčajných 15 minút',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Doska nárokov',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minút k vyberaniu daní z Arény po obsadení súperom',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'S tým artefaktom sú Arény prístupné pre vyberanie daní ešte počas 60 minút po ich obsadení, namiesto obyčajných 15 minút',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Traktát o vládnutí',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minút k vyberaniu daní z Arény po obsadení súperom',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'S tým artefaktom sú Arény prístupné pre vyberanie daní ešte počas 90 minút po ich obsadení, namiesto obyčajných 15 minút',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoár o moci',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minút k vyberaniu daní z arény po obsadení súperom',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'S tým artefaktom sú arény prístupné pre vyberanie daní ešte počas 120 minút po ich obsadení, namiesto obyčajných 15 minút',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Obojok s ostňami',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% urýchľovania k získaniu kameňov duší, ktoré dostaneme od miláčika',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'S týmto artefaktom budete môcť prekonávať o10% menšiu vzdialenosť s miláčikom, aby ste dostali kamene duší. Tiež vďaka nemu pôsobí miláčik o 17% strašnejšie',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Mrkva na paličke',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% urýchenie k získaniu kameňov duší, ktoré dostaneme od miláčika',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'S týmto artefaktom budete môcť prekonávať o 15% menšiu vzdialenosť s miláčikom, aby ste dostali kameň duší. To je dobrota!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Kefa na chrbátik',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% urýchlenie k získaniu kameňov duší, ktoré dostaneme od miláčika',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'S týmto artefaktom budete môcť prekonávať o 25% menšiu vzdialenosť s miláčikom, aby ste dostali kameň duší. Skloň sa pred mocou kefy na chrbátik!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Zvonček miláčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% urýchlenie k získaniu kameňov duší, ktoré dostaneme od miláčika',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'S týmto artefaktom budete môcť prekonávať o 30% menšiu vzdialenosť s miláčikom, aby ste dostali kameň duší. Kto je tento pekný chlapček?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Plyšový dráčik',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% urýchlenie k získaniu kameňov duší, ktoré dostaneme od miláčika',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'S týmto artefaktom budete môcť prekonávať o 40% menšiu vzdialenosť s miláčikom, aby ste dostali kameň duší. Najlepšia hračka na svete pre najlepšieho domáceho miláčika',
    'key.artifact.ARTIFACT_ROOST_1': 'Dračie srdce',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 dračí kokón u Matky Drakov',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Umožňuje použitie dodatočného dračieho kokónu pre vajcia u Matky Drakov',
    'dialog.artifact.select_artifact': 'VYBERTE ARTEFAKT',
    'dialog.artifact.confirm.remove': 'Naozaj chcete odstrániť artefakt?',
    'dialog.items.title': 'TAŠKA',
    'dialog.items.cannotUse': 'Ten predmet nie je možné použiť',
    'dialog.items.remove.header': 'Odstránenie predmetov',
    'dialog.encounter.header': 'Divoké monštrum útočí!',
    'dialog.encounter.button.leave': 'Utiecť',
    'dialog.encounter.button.fight': 'Bojovať',
    'dialog.encounter.result.outcome.win': 'Divoké monštrum je porazené',
    'dialog.encounter.result.outcome.lose': 'Vaša bytosť je porazená',
    'dialog.encounter.result.reward.dust': 'Esencia',
    'dialog.encounter.result.reward.exp': 'Skúsenosť',
    'error.nickname.validation.IS_EMPTY': 'Je treba zadať meno postavy',
    'error.nickname.validation.TOO_SHORT': 'Meno musí mať minimálne 3 až 16 znakov',
    'error.nickname.validation.TOO_LONG': 'Meno musí mať minimálne 3 až 16 znakov',
    'error.nickname.validation.INVALID_CHAR': 'Môžete použiť iba písmená, čísla a podčiarknutia.',
    'error.nickname.validation.DUPLICATE': 'Zvolené meno je už obsadené. Môžete si vybrať meno {0}',
    'creature.MONSTER_WATER_1': 'Ropuchus',
    'creature.MONSTER_WATER_2': 'Kvapka',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Akvin',
    'creature.MONSTER_WATER_5': 'Ropuchissimo',
    'creature.MONSTER_WATER_6': 'Potôčik',
    'creature.MONSTER_WATER_7': 'Vodník',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minori',
    'creature.MONSTER_WATER_10': 'Infalisk',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadačik',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisk',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Akvar',
    'creature.MONSTER_WATER_18': 'Dadačum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Bazilišok',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Kryštálum',
    'creature.MONSTER_WATER_23': 'Brnenius',
    'creature.MONSTER_WATER_24': 'Neptún',
    'creature.MONSTER_WATER_25': 'Leviatan',
    'creature.MONSTER_FIRE_1': 'Potti',
    'creature.MONSTER_FIRE_2': 'Mummyvin',
    'creature.MONSTER_FIRE_3': 'Steampal',
    'creature.MONSTER_FIRE_4': 'Inkumus',
    'creature.MONSTER_FIRE_5': 'Ohňotlap',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Foubi',
    'creature.MONSTER_FIRE_8': 'Dammivin',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Piecka',
    'creature.MONSTER_FIRE_11': 'Iskra',
    'creature.MONSTER_FIRE_12': 'Kydra',
    'creature.MONSTER_FIRE_13': 'Démonstar',
    'creature.MONSTER_FIRE_14': 'Fénix',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Železný chlap',
    'creature.MONSTER_FIRE_17': 'Svetluška',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Záblesk',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Salute',
    'creature.MONSTER_FIRE_24': 'Pikkarun',
    'creature.MONSTER_FIRE_25': 'Smaugr',
    'creature.MONSTER_EARTH_1': 'Bobulillo',
    'creature.MONSTER_EARTH_2': 'Kvetok',
    'creature.MONSTER_EARTH_3': 'Lístok',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Šamurf',
    'creature.MONSTER_EARTH_6': 'Dryáda',
    'creature.MONSTER_EARTH_7': 'Klíček',
    'creature.MONSTER_EARTH_8': 'Disguir',
    'creature.MONSTER_EARTH_9': 'Belflou',
    'creature.MONSTER_EARTH_10': 'Žaludeň',
    'creature.MONSTER_EARTH_11': 'Filo',
    'creature.MONSTER_EARTH_12': 'Brah',
    'creature.MONSTER_EARTH_13': 'Prinsi',
    'creature.MONSTER_EARTH_14': 'Šiškán',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dvant',
    'creature.MONSTER_EARTH_18': 'Čappian',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'Springa',
    'creature.MONSTER_EARTH_21': 'Zemevos',
    'creature.MONSTER_EARTH_22': 'Zvierakvet',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendeľ',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Uchomych',
    'creature.MONSTER_WIND_3': 'Hubi',
    'creature.MONSTER_WIND_4': 'Huňatoroh',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Hamajun',
    'creature.MONSTER_WIND_7': 'Strašan',
    'creature.MONSTER_WIND_8': 'Ucholot',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Vietrotanec',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Búrkoroh',
    'creature.MONSTER_WIND_14': 'Fantomo',
    'creature.MONSTER_WIND_15': 'Cheshire',
    'creature.MONSTER_WIND_16': 'Houbtopia',
    'creature.MONSTER_WIND_17': 'Harpya',
    'creature.MONSTER_WIND_18': 'Prízrakus',
    'creature.MONSTER_WIND_19': 'Puerogryph',
    'creature.MONSTER_WIND_20': 'Poduškocúr',
    'creature.MONSTER_WIND_21': 'Hippolet',
    'creature.MONSTER_WIND_22': 'Uragánna',
    'creature.MONSTER_WIND_23': 'Gryf',
    'creature.MONSTER_WIND_24': 'Bajun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Ostnechrbát',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Milokocúr',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Strašiak',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Džin',
    'creature.MONSTER_DUNGEON_12': 'Vampiro',
    'creature.MONSTER_DUNGEON_13': 'Húsen',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Chvostík',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tigermant',
    'creature.MONSTER_DUNGEON_21': 'Ostrochvost',
    'creature.MONSTER_DUNGEON_22': 'Púčik',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Mantikora',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Žraločie uhryznutie',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Hrôza z hĺbky',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Volanie Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Morské kladivo',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Vodná päsť',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Vlna',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Lejak',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Gejzír',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Kropaje',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Živý plameň',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Ohnivý prst',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Ohnivý korbáč',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Ohnivá guľa',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Spopoľňovač',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Hviezda',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Uhlie',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Plameňome',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Zastrelenie',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Vzdušný kosák',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'RoztrhávačL',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Dýchanie',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Elektrický šok',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Guľový blesk',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Šoková terapia',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Dračí vzdych',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Závan',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Zúrivosť vetra',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Jedovatý pľuvanec',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Hadí zubL',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Otrava',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Chrbátolom',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Skala',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Okružliak',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Lesný duch',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Prízrak stromu',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Tieň prírody',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Strela Аrkany',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Zhluk tmy',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Chápadlo zla',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Oko hrôzy',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sféra smrti',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Sféra smrti',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arkana Kadavra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarkus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Imperikanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Zľadovatenie',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Mrazenie',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Kryštalizácia',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Vodný vír',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Metelica',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Cunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Studená zúrivosť',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Ľadový výbuch',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Ľadová moc',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Čistenie',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Pozdvihnutie',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Vypálenie',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Láva',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Prúd ohňa',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteory',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armagedon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Blesk',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Hrom',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Búrka',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Preťaženie',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Elektrické pole',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Vlasy dupkom',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornádo',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Rev vetra',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Kolotoč',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Rachot',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Trasenie',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Zlom',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Stroskotanie',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Výbuch',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Kamenná víchrica',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Jazero smrti',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Jedovatá mláka',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Kyselina',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomizácia',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Dezintegrácia',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionizácia',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Vyhnanie',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Prekliatie',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Vylúčenie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Magická búrka',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Búrka many',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Hnev Arkany',
    'key.combined.first.1': 'Múdrych',
    'key.combined.first.2': 'Pekelných',
    'key.combined.first.3': 'Skvelých',
    'key.combined.first.4': 'Zlostných',
    'key.combined.first.5': 'Neutrálnych',
    'key.combined.first.6': 'Čestných',
    'key.combined.first.7': 'Svätých',
    'key.combined.first.8': 'Starobylých',
    'key.combined.first.9': 'Podzemných',
    'key.combined.first.10': 'Ohnivých',
    'key.combined.first.11': 'Šikovných',
    'key.combined.first.12': 'Ohromných',
    'key.combined.first.13': 'Modrých',
    'key.combined.first.14': 'Krutých',
    'key.combined.first.15': 'Dobrých',
    'key.combined.first.16': 'Vzdušných',
    'key.combined.first.17': 'Zemných',
    'key.combined.first.18': 'Červených',
    'key.combined.first.19': 'Nesmrteľných',
    'key.combined.first.20': 'Zahynutých',
    'key.combined.first.21': 'Vzdušných',
    'key.combined.first.22': 'Strašných',
    'key.combined.first.23': 'Vodných',
    'key.combined.first.24': 'Žartovných',
    'key.combined.first.25': 'Hlúpych',
    'key.combined.second.1': 'Hrdinov',
    'key.combined.second.2': 'Rýb',
    'key.combined.second.3': 'Sov',
    'key.combined.second.4': 'Zlodejov',
    'key.combined.second.5': 'Napomáhačov',
    'key.combined.second.6': 'Mágov',
    'key.combined.second.7': 'Starcov',
    'key.combined.second.8': 'Čarodejov',
    'key.combined.second.9': 'Vojakov',
    'key.combined.second.10': 'Súperov',
    'key.combined.second.11': 'Obchodníkov',
    'key.combined.second.12': 'Králikov',
    'key.combined.second.13': 'Jabĺk',
    'key.combined.second.14': 'Bojovníkov',
    'key.combined.second.15': 'Kúzelníkov',
    'key.combined.second.16': 'Rytierov',
    'key.combined.second.17': 'Barbarov',
    'key.combined.second.18': 'Chrobákov',
    'key.combined.second.19': 'Hadov',
    'key.combined.second.20': 'Drakov',
    'key.combined.second.21': 'Prízrakov',
    'key.combined.second.22': 'Kocúrikov',
    'key.combined.second.23': 'Vojakov',
    'key.combined.second.24': 'Šťastlivcov',
    'key.combined.second.25': 'Asasínov',
    'key.combined.second.26': 'Myší',
    'key.combined.second.27': 'Elementálov',
    'key.combined.second.28': 'Výskumníkov',
    'key.combined.second.29': 'Šamanov',
    'key.combined.second.30': 'Žrecov',
    'key.combined.second.31': 'Anjelov',
    'key.combined.second.32': 'Archontov',
    'key.combined.second.33': 'Katov',
    'key.combined.second.34': 'Hlupákov',
    'key.combined.second.35': 'Odvážlivcov',
    'key.combined.second.36': 'Dobrákov',
    'key.combined.second.37': 'Zbabelcov',
    'key.combined.second.38': 'Bardov',
    'key.combined.second.39': 'Krotiteľov',
    'key.combined.second.40': 'Obrancov',
    'key.combined.arena': 'Aréna {0} {1}',
    'key.combined.library': 'Knižnica {0} {1}',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Voda',
    'element.type.WIND': 'Vzduch',
    'element.type.FIRE': 'Oheň',
    'element.type.EARTH': 'Zem',
    'element.type.DUNGEON': 'Arkana',
    'spell.type.ACTIVATION_RADIUS': 'Rádius rozhľadu',
    'spell.type.VISION_RADIUS': 'Dračí zrak',
    'spell.type.STOP_FIELD': 'Pole Hojnosti',
    'spell.type.SCOUT': 'Prieskum',
    'spell.type.PROTECT_ARENA': 'Ochrana arény',
    'spell.type.CREATE_PORTAL': 'Vytvoriť Portál',
    'spell.type.ARMAGEDDON': 'Armagedon',
    'spell.type.DOUBLE_DROP': 'Dvojitý drop',
    'spell.type.SLUG_PLAYERS': 'Slizniaknuť hráčov',
    'quest.title.WIN_ARENA_MONSTER': 'Dominácia',
    'quest.title.OPEN_EGGS': 'Vaječná horúčka',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Kontrola územia',
    'quest.title.CAPTURE_LIBRARY': 'Hlad po poznaní',
    'quest.title.CAPTURE_WILD_MONSTER': 'Dračí park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Lov na živel',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Hľadanie Arkanozrodenej',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Záťah v zlome',
    'quest.title.OPEN_CHEST': 'Starodávne poklady',
    'quest.title.CHAIN_OF_STOP': 'Cesta hojnosti',
    'quest.desc.WIN_ARENA_MONSTER': 'Víťazte nad bytosťami na Aréne alebo v Knižnici. Nemožno poraziť bytosť toho istého druhu dvakrát',
    'quest.desc.OPEN_EGGS': 'Vysedávejte bytosti z vajec pomocou dračích kokónov alebo Matky drakov',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Vyberte daň z obsadených Arén',
    'quest.desc.CAPTURE_LIBRARY': 'Staňte sa majiteľom nutného počtu Knižníc',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Bytostí veľa nebýva. Cestujte a chytajte bytosti',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Cestujte a chytajte tvory vodného živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Cestujte a chytajte tvory vzdušného živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Cestujte a chytajte tvory ohnivého živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Cestujte a chytajte tvory zemského živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Cestujte a chytajte tvory živlu Arkany',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Prezrite si zlom Arkany, v ktorom je Matka drakov',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Prezrite si zlom Arkany a chyťte všetky bytosti, ktoré tam nájdete',
    'quest.desc.OPEN_CHEST': 'Najdite a otvorte truhly s pokladmi',
    'quest.desc.CHAIN_OF_STOP': 'Prejdite rad Stĺpov hojnosti a aktivujte je. Každý ďalší Stĺp bude prisvietený',
    'quest.dialog.completed.rewardtext': 'Vaša odmena:',
    'key.tab.altar.title': 'OLTÁR',
    'key.altar.remove': 'Odstrániť',
    'key.altar.put': 'Postaviť',
    'key.altar.convert': 'Pretvoriť',
    'key.altar.shared': 'Ukazovať iným',
    'key.altar.pass.placeholder': 'Tu môžete zadať heslo',
    'key.altar.pass.error': 'Heslo musí mať minimálne {0} znakov',
    'key.altar.level.error': 'Musíte dosiahnuť úroveň {0}, ak chcete používať Oltár',
    'key.altar.recipe.change': 'Naozaj chcete zmeniť recept? Runy budú vrátené majiteľom',
    'key.altar.row.title': 'Pokiaľ chcete vytvoriť zaklínadlo, je potrebné postaviť Oltár',
    'key.altar.rune.descr.RUNE_1': '3 sivé rúny = oranžová',
    'key.altar.rune.descr.RUNE_2': '3 oranžové rúny = modrá',
    'key.altar.rune.descr.RUNE_3': '3 modré rúny = smaragdová',
    'key.altar.rune.descr.RUNE_4': '3 smaragdové rúny = červená',
    'key.altar.rune.descr.RUNE_5': '3 červené rúny = fialová',
    'key.altar.rune.descr.RUNE_6': 'Fialové rúny sú najsilnejšie',
    'error.altar.cannotRemove': 'Oltár nemôže byť odstránený',
    'error.altar.cannotConvert': 'Nemáte dostatok rún',
    'key.tab.altar.recipes': 'RECEPTY',
    'key.altar.noRecipes': 'Nemáte recepty',
    'key.altar.header': 'Pre vytvorenie zaklínadla vyložte rúny na Oltár',
    'key.altar.castBtn': 'Vytvoriť',
    'key.altar.recipe.select': 'Vyberte potrebné zaklínadlo',
    'key.altar.castDone': 'Zaklínadlo bolo vytvorené',
    'key.arena.protected.ally': 'Obrana:',
    'key.avatarCustomization.title': 'Vyberte zovňajšok postavy:',
    'key.buddy.walkDescription': 'Prechádzajte sa s miláčikom, aby ste dostali {0}',
    'key.buddy.totalWalked': '{0} km prešlej dráhy',
    'key.account.balance': 'Zásoby:',
    'key.account.userLevel': '{0} úroveň',
    'key.account.totalDistance': 'Prejdená vzdialenosť: {0} kilometrov',
    'key.acount.registerDate': 'Začiatok hry: {0}',
    'key.storage.sort.name': 'MENO',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'ZELENÝ ZOZNAM',
    'key.storage.sort.group2': 'ŽLTÝ ZOZNAM',
    'key.storage.sort.group3': 'ČERVENÝ ZOZNAM',
    'key.storage.sort.date': 'DÁTUM',
    'key.account.options.jurnal': 'DENNÍK',
    'key.account.options.buddy': 'MAZNÁČIK',
    'key.account.options.artifacts': 'ARTEFAKTY',
    'key.account.options.style': 'ZOVŇAJŠOK',
    'key.error.gps.permission': 'GPS nie je k dispozícii. Zapnite prístup k systému GPS, aby ste mohli pokračovať v hre',
    'key.error.gps.disabled': 'GPS je vypnuté. Zapnite GPS, aby ste mohli pokračovať v hre',
    'key.error.gps.fakePosition': 'Nemôžete hrať bez GPS',
    'key.error.gps.signal.notFound': 'Chýba signál GPS',
    'key.error.gps.signal.bad': 'Hra nie je prístupná. Slabý signál GPS',
    'key.error.internet.notReachable': 'Pripojenie k internetu nie je k dispozícii',
    'key.journal.title': 'Denník',
    'key.journal.yesterday': 'Včera',
    'key.settings.title': 'Nastavenia',
    'key.settings.music': 'Hudba',
    'key.settings.deviceAuthError': 'Z bezpečnostných dôvodov pripojte svoj účet k Googlu alebo Facebooku',
    'key.settings.sounds': 'Zvuky',
    'key.settings.vibration': 'Vibrácia',
    'key.settings.batterySaver': 'Úspora energie',
    'key.settings.support': 'Kontaktovať technickú podporu',
    'key.settings.logout': 'Odhlásiť sa',
    'key.settings.auth.deviceid': 'ID prístroja',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Prepojiť',
    'key.settings.languageTitle': 'Jazyk',
    'key.settings.language': 'Slovenčina',
    'key.battle.result.win': 'Bitka je ukončená',
    'key.battle.result.lose': 'Bitka je ukončená',
    'key.wizardBattle.result.win': 'VÍŤAZSTVO!',
    'key.wizardBattle.result.lose': 'PORÁŽKA!',
    'key.battle.result.monster': 'Porazené bytosti',
    'key.battle.result.exp': 'Získané skúsenosti',
    'key.battle.result.prestige_strong_enemy': 'Bonus slávy za silných nepriateľov',
    'key.battle.result.exp_strong_enemy': 'Bonus skúsenosti za silných nepriateľov',
    'key.battle.result.prestige_killed_all': 'Bonus slávy za zabitie všetkých',
    'key.battle.result.exp_killed_all': 'Bonus skúsenosti za zabitie všetkých',
    'key.battle.result.dust': 'Esencia',
    'key.radar.title': 'Bytosti vedľa vás',
    'key.levelUp.title': 'Nová úroveň!',
    'key.wizardBattle.left': 'Limit bojov:',
    'key.wizardBattle.timer': 'Limit bude anulovaný za',
    'key.wizardBattle.enhance.title': 'ZVÝŠENIE LIMITU',
    'key.wizardBattle.enhance.desc': 'Limit bojov je možné zvýšiť na 7 za deň na jeden týždeň',
    'key.wizardBattle.enhance.btn': 'Zvýšiť',
    'key.wizardBattle.lookingForOpponent': 'Vyhľadávanie súpera na Duel...',
    'key.catch.result.expMonster': 'Skúsenosť za chytenie:',
    'key.catch.result.expMonsterNew': 'Novinka v Beštiáru:',
    'key.catch.result.expAccurate': 'Za presný hod:',
    'key.catch.result.expSpin': 'Za hod po zakrivenej trajektórii:',
    'key.catch.result.strike': 'Prvá bytosť za deň:',
    'key.catch.result.total': 'Celková skúsenosť:',
    'key.catch.fullStorage': 'Skladisko bytostí je zaplnené',
    'key.catch.noItems': 'Nemáte magické sféry',
    'key.creadex.title': 'BEŠTIÁR',
    'key.creadex.detail.caught': 'CHYTENÝ: {0}',
    'key.creadex.detail.evolution': 'VÝVOJ',
    'key.tab.doll': 'POSTAVA',
    'key.tab.artifacts': 'ARTEFAKTY',
    'key.activePoint.title': 'Stĺp hojnosti',
    'key.personalization.title': 'Začarovanie',
    'key.chest.title': 'Magická truhla',
    'key.quest.daily.title': 'ÚLOHA',
    'key.quest.weekly.title': 'LOV',
    'key.quest.get': 'DOSTAŤ ÚLOHU',
    'key.quest.change': 'VYMENIŤ ÚLOHU',
    'key.quest.progress': 'Pokrok v úlohe: {0} z {1}',
    'key.error.quest.weekly.level': 'Je potrebné dosiahnuť úroveň {0}, aby ste začali hon na Zlaté Vajce.',
    'key.error.quest.daily.level': 'Je potrebné dosiahnuť úroveň {0}, aby ste vzali úlohu.',
    'key.error.quest.tooFar': 'Obelisk je príliš ďaleko',
    'key.quest.daily.descr.noQuest.title': 'Nemáte žiadne úlohy',
    'key.quest.daily.descr.noQuest': 'Ak chcete dostať úlohu a zaslúžiť si odmenu, použite Obelisk.',
    'key.quest.daily.timer.descr': 'Úlohu môžete zmeniť za:',
    'key.quest.daily.waitForNew.descr': 'Nová úloha bude prístupná za:',
    'key.quest.weekly.getFragment': 'DOSTAŤ FRAGMENT',
    'key.quest.weekly.descr.noQuest.title': 'Nezúčastňujete sa lovu na Zlaté Vajce.',
    'key.quest.weekly.descr.noQuest': 'Použite Obelisk, aby ste dostali fragment tajnej mapy a začali lov.',
    'key.quest.weekly.descr.getFirstFragment': 'Dostaňte prvý fragment tajnej mapy, aby ste začali lov na Zlaté vajce',
    'key.quest.weekly.descr.top.notAllOpen': 'Použite obelisk, aby ste dostali fragment mapy. Ponáhľajte sa, lov sa končí za',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Použite lopatu na každom fragmente, aby ste našli Zlaté vajce',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Už ste dostali fragment mapy z toho obelisku',
    'key.quest.weekly.descr.top.allOpen': 'Všetky fragmenty mapy z obeliskov už boli obdržané. Ponáhľajte sa, lov sa skončí za',
    'key.quest.weekly.descr.bot.allOpen': 'Použite lopatu na každom fragmentu, aby ste našli Zlaté vajce',
    'key.quest.weekly.descr.top.completed': 'Už ste našli Zlaté vajce tento týždeň. Ďalší lov sa začne za',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}h',
    'key.timer.format.H_M': '{0}h {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}h',
    'key.creatureStorage.tab.creatures': 'BYTOSTI',
    'key.creatureStorage.tab.eggs': 'VAJCIA',
    'key.creatureStorage.multiTransferText': 'Vyberte, koho chcete pustiť',
    'key.storage.creature.transfer': 'Pustiť ({0})',
    'key.error.needHigherLevelForArena': 'Je potrebná úroveň {0} pre vstup do Arény',
    'key.error.needHigherLevelForLibrary': 'Je potrebná úroveň {0} pre vstup do Knižnice',
    'key.error.arenaUnderProtection': 'Aréna je pod ochranou Požehnania obrany',
    'key.error.buildingTooFar': 'Budova je príliš ďaleko',
    'key.error.noAliveCreaturesForAttack': 'Nemáte žiadné živé tvory',
    'key.error.noHealPotion': 'Nemáte liečebné elixíry',
    'key.error.noResurrectionPotion': 'Nemáte elixíry oživenia',
    'key.error.tryAgainLater': 'Chyba. Skúste to znova neskôr.',
    'key.error.alreadyHasLure': 'Nástraha je už postaven',
    'key.error.cannotUseLureInDungeon': 'Návnada nemôže byť použitá v Zlomu Arkany',
    'key.error.bagIsFull': 'V taške nie je miesto',
    'key.error.cantTransferCreature': 'Nie je možné pustiť túto bytosť',
    'key.notification.done': 'Hotovo!',
    'key.modal.doYouWantToTransfer': 'Naozaj chcete pustiť tieto bytosti?',
    'key.modal.youWillLoseBuddyProgress': 'Naozaj chcete vymeniť miláčika? Pokrok obdržaní kameňa duší bude stratený',
    'key.modal.doYouWantToLeaveDungeon': 'Chcete opustiť Zlom Arkany?',
    'key.modal.superVisionActive': 'Dračí zrak je už aktivovaný. Opätovné používanie presunie magickú zónu viditeľnosti. Naozaj ho chcete použiť ešte raz?',
    'key.modal.experienceBoosterActive': 'Kryštál múdrosti je už aktivovaný. Naozaj ho chcete použiť ešte raz?',
    'key.modal.youWillLooseQuestProgress': 'Pokrok tejto úlohy bude stratený. Ste si istí?',
    'key.modal.doYouWantToEnterDungeon': 'Chcete vstúpiť do Zlomu Arkany cez Portál?',
    'key.modal.doYouWantPersonalizePoint': 'Začarovaný stĺp bude dávať iba {0}. Chcete minúť {1} mincí na začarovanie?',
    'key.modal.doYouWantToDeletePersonalization': 'Naozaj chcete odstrániť kúzlo z tohto Stĺpu Hojnosti?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Chcete posilniť toto stvorenie?',
    'key.modal.doYouWantToEvolveThisCreature': 'Chcete premeniť toto stvorenie na silnejšie?',
    'key.modal.doYouWantToScoutHere': 'Naozaj chcete túto oblasť preskúmať?',
    'key.error.creatureHasMaxLevel': 'Bytosť už má maximálnu úroveň',
    'key.error.creatureHasMaxLevelForUser': 'Najskôr je potrebné zvýšiť úroveň postavy',
    'key.error.notEnoughResourcesForEnhance': 'Chýbajú zásoby',
    'key.error.creatureIsArenaDefender': 'Nie je možné vybrať bytosť, ktorá bráni budovu',
    'key.modal.incenseActive': 'Feromóny už boli aktivované. Naozaj ich chcete použiť ešte raz?',
    'key.error.cantHealHealthyCreature': 'Bytosť bola úplne vyliečená',
    'key.error.cantRessurectAliveCreature': 'Bytosť je už živá',
    'key.error.noTreasureHere': 'Na tomto fragmente mapy nie je žiadne Zlaté vajce. Pokračujte v hľadaní.',
    'key.error.levelTooSmall': 'Najskôr je potrebné zvýšiť úroveň postavy',
    'key.error.needHigherLevelForWizardBattles': 'Pre účasť v Súbojich mágov je potrebná úroveň {0}',
    'key.error.artifactBagIsFull': 'Skladisko artefaktov je zaplnené',
    'key.error.notEnoughCoins': 'Chýbajú mince',
    'key.error.allFragmentsAreOpen': 'Všetky fragmenty tajomnej mapy sú otvorené',
    'key.error.questAlreadyCompleted': 'Úloha je už ukončená',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Už ste dostali fragment mapy z tohto Obelisku',
    'key.error.portalTooFarAway': 'Portál je príliš ďaleko',
    'key.error.battleLimitAlreadyEnhanced': 'Limit bitiek už bol zvýšený',
    'key.error.youAreNotAltarOwner': 'Môže to robiť iba majiteľ Oltára',
    'key.error.youAlreadyHaveAltar': 'Oltár je už postavený',
    'key.error.cantTakeAnotherUsersRune': 'Nie je možné odobrať rúnu iného hráča',
    'key.error.libraryBlocked': 'Ak chcete používať knižnice, potrebujete počkať 3 dni po preškolení',
    'key.error.notAuthorized': 'Užívateľ nie je autorizovaný',
    'key.error.eggOnlyRoost': 'Toto vajce treba dať Matke drakov',
    'key.error.purchase': 'Chyba: {0}',
    'key.error.creatureIsDead': 'Najprv musíte vzkriesiť stvorenie',
    'key.error.no_connection': 'Nepodarilo sa pripojiť k serveru. Skúste neskôr.',
    'key.error.protocol_version_mismatch': 'Nepodarilo sa pripojiť k serveru. Skúste to znova neskôr.',
    'key.error.update_application': 'Verzia hry je zastaraná. Je potrebná aktualizácia.',
    'key.modal.doYouWantToTransferSingle': 'Naozaj chcete pustiť túto bytosť?',
    'key.notification.phoneNotSupportAR': 'Váš prístroj nepodporuje AR',
    'key.notification.turnOnARPermission': 'Hra nemá prístup ku kamere. Je potrebné povoliť prístup v nastaveniach zariadenia',
    'key.notification.dailyQuestFinished': 'Úloha je splnená!',
    'key.modal.yesBtn': 'Áno',
    'key.modal.noBtn': 'Nie',
    'event.log.DAILY_QUEST_COMPLETED': 'Každodenná úloha je ukončená. Odmeny boli obdržané:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Lov je ukončený! Vaša odmena:',
    'event.log.ENCOUNTER_VICTORY': 'Zvíťazili ste nad divokým monštrom!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Vaša verzia hry je zastaraná. Je potrebná aktualizácia.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Chyba autentifikace',
    'key.ServiceException.Cause.SESSION_GONE': 'Niekto sa prihlásil do vášho účtu z iného zariadenia',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'ID Užívateľa je prázdne',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Užívateľ nebol nájdený',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Účet bol zablokovaný za nekalú hru.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Účet bol zablokovaný za podvodné platby.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Účet bol zablokovaný za urážlivé používateľské meno.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Účet bol zablokovaný za agresívnu komunikáciu s ostatnými hráčmi.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Účet bol zablokovaný za nekalú hru.',
    'key.ServiceException.Cause.USER_BANNED': 'Účet bol zablokovaný.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'V taške nie je miesto',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maximálny počet vajec',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Chýbajú mince',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Chýbajú kamene duší',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Nedostatok esencií',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Skladisko bytostí je zaplnené',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Bytosť už má maximálnu úroveň',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Nie je možné pretvoriť túto bytosť',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Meno bytosti má mať maximálne 14 znakov',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Budova už má maximálny počet obrancov',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Nie je možné urobiť z miláčika obrancu budovy',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Vaša bytosť už bráni túto budovu',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Chyba',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Boj nebol nájdený',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Chyba',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Vaša bytosť už bráni túto budovu',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Aréna je pod ochranou Požehnania obrany',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Čas vyberania daní ešte nenadišiel',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Chybná sféra',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Chybná budova',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Prístup zamietnutý',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Neexistujúci predmet',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Neexistujúci recept',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Je možné postaviť iba jeden Oltár',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Najskôr je potrebné zvýšiť úroveň postavy',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Nepodarilo sa začať lov bytosti',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Neexistujúci tovar',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Neexistujúci tovar',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Neexistujúci budova',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Bytosť nebola nájdená',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Bytosť nebola nájdená',
    'key.ServiceException.Cause.TOO_FAR': 'Budova je príliš ďaleko',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Objekt je príliš ďaleko',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Budova je na opätovnom nabíjaní',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Budova v Zlome Arkany',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Budova sa nedá použiť',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Dračí kokón nebol nájdený',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Dračí kokón je prázdny',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Dračí kokón je obsadený',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Vajce nebolo vysedené',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Vajce nebolo nájdené',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Pre toto vajce je treba Matka Drakov',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Skončili sa nabíjania',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Nepodarilo sa postaviť budovu',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Došlo k chybe a tu je tajomná správa o nej',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Divoký netvor utiekol',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Divoké monštrum nebolo nájdené',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'V tomto Stĺpe Hojnosti už je návnada',
    'key.ServiceException.Cause.WRONG_ITEM': 'Nesprávny predmet',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Táto rúna je najsilnejšia',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Nedostatok rún tejto úrovne',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Nesprávny slot pre rúny',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Tento slot je už obsadený',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Slot pre rúnu je prázdny',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Nie je možné vybrať obranca budovy',
    'key.ServiceException.Cause.WRONG_SPELL': 'Nesprávne zaklínadlo',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Zaklínadlo vyžaduje viac rún',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Nová úloha ešte nie je k dispozícii',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Už ste použili tento Obelisk',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Všetky fragmenty tajomnej mapy sú už otvorené',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Nezúčastňujete sa lovu na Zlaté vajce',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Už ste skúšali hľadať Zlaté Vajce na tomto pozemku',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Už ste použili maškrtu',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Bytosť je už chytená',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Preškolenie bytosti zatiaľ nie je dostupné',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Knižnica je zatiaľ zablokovaná',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Server nereaguje. Skúste znova neskôr.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Limit bitiek už bol zvýšený',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Limit bitiek je vyčerpaný',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Pre účasť v Súboji Mágov je potrebná úroveň 9',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Nepodarilo sa nájsť súpera pre Súboj Mágov, skúste to znova neskôr',
    'key.ServiceException.Cause.MARKET_ERROR': 'Chyba obchodu',
    'key.ServiceException.Cause.NO_CHEST': 'Truhla nebola nájdená',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Chyba pri výdaji fragmentu. Skúste to znova neskôr.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Je potrebné obliecť na seba Dračie srdce alebo súbor Dračích artefaktov, ak chcete dať Matke Drakov viac vajec',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Táto bunka už obsahuje vajce',
    'key.ServiceException.Cause.NO_CONNECTION': 'Nie je k dispozícii pripojenie na internet',
    'key.ServiceException.Cause.SERVER_DOWN': 'Herný server je dočasne nedostupný. Skúste to prosím neskôr.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Práve prebieha údržba servera. Skúste to prosím neskôr.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Tieto runy sa teraz používajú',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Pohybujete sa príliš rýchlo',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Dosiahli ste maximálny počet obsadených arén',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Dosiahli ste maximálny počet obsadených knižníc',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Chyba: GPS nie je k dispozícii',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Toto kúzlo nemôžete použiť v Zlomu Arkany',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Čas vypršal',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Verzia hry je zastaraná. Je potrebná aktualizácia.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'V oblasti viditeľnosti nie sú zväzové Arény',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'V oblasti viditeľnosti nie sú nepriateľské Arény',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'sféry',
    'stop.personalized.HEALS': 'liečebné elixíry',
    'stop.personalized.RESURRECTIONS': 'elixíry oživenia',
    'stop.personalized.EGGS': 'vajcia bytostí',
    'stop.personalized.FOODS': 'dobrôty',
    'key.button.cancelPersonal': 'Zrušiť',
    'key.error.needHigherLevelForSofaBattles': 'Pre účasť v Súboji Mágov je potrebná úroveň {0}',
    'fraction.text.youWilLGetBonus': 'Dostanete {0} mincí za pripojenie k tejto frakcii',
    'fraction.text.fractionUnavailable': 'Frakcia je zatiaľ nedostupná',
    'fraction.text.chooseYourAlliance': 'Zvoľte frakciu, za ktorú budete bojovať',
    'fraction.text.redFractionName': 'Červený rad',
    'fraction.text.blueFractionName': 'Modrý rad',
    'key.error.chestTooFarAway': 'Truhla je príliš ďaleko',
    'key.button.openChest': 'Otvoriť',
    'key.candy.MONSTER_WATER_1': 'kamene Ropuchusa',
    'key.candy.MONSTER_WATER_2': 'kamene Kvapky',
    'key.candy.MONSTER_WATER_3': 'kamene Spiritusa',
    'key.candy.MONSTER_WATER_4': 'kamene Akvina',
    'key.candy.MONSTER_WATER_8': 'kamene Jellyhata',
    'key.candy.MONSTER_WATER_9': 'kamene Minori',
    'key.candy.MONSTER_WATER_10': 'kamene Infaliska',
    'key.candy.MONSTER_WATER_12': 'kamene Dadačka',
    'key.candy.MONSTER_WATER_13': 'kamene Batoida',
    'key.candy.MONSTER_WATER_23': 'kamene Brneniusa',
    'key.candy.MONSTER_WATER_24': 'kamene Neptúna',
    'key.candy.MONSTER_WATER_25': 'kamene Leviatana',
    'key.candy.MONSTER_FIRE_1': 'kamene Potti',
    'key.candy.MONSTER_FIRE_2': 'kamene Mummyvina',
    'key.candy.MONSTER_FIRE_3': 'kamene Steampala',
    'key.candy.MONSTER_FIRE_4': 'kamene Inkumusa',
    'key.candy.MONSTER_FIRE_6': 'kamene Flamy',
    'key.candy.MONSTER_FIRE_7': 'kamene Foubi',
    'key.candy.MONSTER_FIRE_11': 'kamene Iskry',
    'key.candy.MONSTER_FIRE_12': 'kamene Kydry',
    'key.candy.MONSTER_FIRE_15': 'kamene Needlehota',
    'key.candy.MONSTER_FIRE_25': 'kamene Smaugra',
    'key.candy.MONSTER_EARTH_1': 'kamene Bobulilla',
    'key.candy.MONSTER_EARTH_2': 'kamene Kvetka',
    'key.candy.MONSTER_EARTH_3': 'kamene Lístka',
    'key.candy.MONSTER_EARTH_4': 'kamene Brownie',
    'key.candy.MONSTER_EARTH_8': 'kamene Disguira',
    'key.candy.MONSTER_EARTH_9': 'kamene Belflou',
    'key.candy.MONSTER_EARTH_10': 'kamene Žaludňa',
    'key.candy.MONSTER_EARTH_11': 'kamene Filo',
    'key.candy.MONSTER_EARTH_13': 'kamene Prinsi',
    'key.candy.MONSTER_EARTH_25': 'kamene Scylly',
    'key.candy.MONSTER_DUNGEON_1': 'kamene Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'kamene Axolana',
    'key.candy.MONSTER_DUNGEON_3': 'kamene Ostnechrbáta',
    'key.candy.MONSTER_DUNGEON_4': 'kamene Magglada',
    'key.candy.MONSTER_DUNGEON_5': 'kamene Milokocúra',
    'key.candy.MONSTER_DUNGEON_6': 'kamene Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'kamene Vampiro',
    'key.candy.MONSTER_DUNGEON_13': 'kamene Húseňa',
    'key.candy.MONSTER_DUNGEON_17': 'kamene Inura',
    'key.candy.MONSTER_WIND_1': 'kamene SunTzi',
    'key.candy.MONSTER_WIND_2': 'kamene Uchomycha',
    'key.candy.MONSTER_WIND_3': 'kamene Hubi',
    'key.candy.MONSTER_WIND_4': 'kamene Huňatorohu',
    'key.candy.MONSTER_WIND_6': 'kamene Hamajuna',
    'key.candy.MONSTER_WIND_7': 'kamene Strašana',
    'key.candy.MONSTER_WIND_11': 'kamene Infirda',
    'key.candy.MONSTER_WIND_12': 'kamene Undine',
    'key.candy.MONSTER_WIND_15': 'kamene Cheshire',
    'key.candy.MONSTER_WIND_25': 'kamene Charybdisa',
    'key.button.leaveDungeon': 'Opustiť Zlom',
    'key.alias.enterNewAlias': 'Zadajte meno bytosti',
    'key.alias.enterText': 'Zadajte text...',
    'key.hut.hutName': 'Matka Drakov',
    'key.hut.hutDescr': 'Dajte Matke Drakov starobylé vajcia, aby ich vysedela pre vás',
    'key.text.noHutEggs': 'Nemáte žiadné starobylé vajcia',
    'key.text.noCapturedArenas': 'Nemáte žiadne dobyté Arény',
    'key.text.noChosenPet': 'Miláčik nebol zvolený',
    'key.text.noArtifacts': 'Nemáte artefakty',
    'key.text.noCreatures': 'Nemáte chytené bytosti',
    'key.text.noLureItems': 'Nemáte návnadu',
    'key.descr.aboutWizardBattles': 'Zúčastňujete sa Súbojov s inými hráčmi pre získanie skúsenosti a odmeny',
    'key.text.writeToSupport': 'Napísať na podporu',
    'key.text.regUsingFacebook': 'Registrovať sa pomocou Facebook',
    'key.text.regUsingGoogle': 'Registrovať sa pomocou Google',
    'key.text.logUsingFacebook': 'Prihlásiť sa pomocou Facebook',
    'key.text.logUsingGoogle': 'Prihlásiť sa pomocou Google',
    'key.text.logUsingDeviceIDCurrent': 'Prihlásiť sa pomocou Device ID',
    'key.text.logUsingDeviceIDNew': 'Prihlásiť sa pomocou Device ID (nový účet)',
    'key.text.createAccount': 'Hrať',
    'key.text.connectedToFacebook': 'Pripojené k Facebook',
    'key.text.connectedToGoogle': 'Pripojené k Google',
    'key.text.complainAboutPoint': 'Sťažovať sa na miesto',
    'key.text.copyCoordinates': 'Kopírovať súradnice',
    'key.text.complainEnterEmail': 'Váš e-mail',
    'key.text.complainEnterText': 'Povedzte o vašom probléme',
    'key.modal.doYouWantToCloseApp': 'Chcete zatvoriť aplikáciu?',
    'key.catchPopup.notBad': 'Dobre!',
    'key.catchPopup.good': 'Výborne!',
    'key.catchPopup.sumptuously': 'Báječne!',
    'key.catchPopup.twistedThrow': 'Hod po zakrivenej!',
    'key.battlePopup.strongHit': 'Silná rana!',
    'key.battlePopup.weakHit': 'Slabá rána',
    'key.battlePopup.dodge': 'Vyhnutie sa!',
    'key.battlePopup.chargedAttack': '{0} používa {1}',
    'auth.login.play': 'Hrať',
    'auth.login.nickname.placeholder': 'Zadajte meno',
    'auth.login.nickname.busy': 'Meno je obsadené',
    'auth.login.nickname.proposal': 'Môžete použiť toto meno:',
    'auth.login.nickname.deviceId': 'Už máte postavu',
    'auth.login.social.title': 'Prihlásenie cez sociálnu sieť',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Pripojené k {0}',
    'auth.login.social.signOut': 'Odhlásiť sa z účtu',
    'auth.login.signOut.confirmation': 'Naozaj sa chcete odhlásiť z účtu?',
    'auth.login.social.userCancelledError': 'Zrušenie pripojenia',
    'auth.login.social.cantSignInError': 'Nedá sa pripojiť k {0}',
    'licence.title': 'POUŽÍVATEĽSKÁ DOHODA HRY DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Posielajte mi správy a ponuky prostredníctvom e-mailu',
    'licence.accept': 'Prijať',
    'licence.decline': 'Odmietnuť',
    'key.error.wrongRoostIndex': 'Slot nie je k dispozícii',
    'key.speed.passenger': 'Som pasažier',
    'key.activeObjects.addUnit.question': 'Opravdu chcete udělat  {0} obráncem této budovy?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Naozaj chcete si vybrať túto frakciu? Túto voľbu nemožno zmeniť v budúcnosti',
    'key.confirm.giveUpEncounter': 'Naozaj sa chcete vzdať boja s divokým monštrom?',
    'key.confirm.giveUpBattle': 'Naozaj sa chcete vzdať boja?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nová liga!',
};
