module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Oui',
    'key.button.cancel': 'ANNULER',
    'key.button.apply': 'ОК',
    'key.button.use': 'Utiliser',
    'key.button.buy': 'Acheter',
    'key.beCarefulMessage.text': 'Soyez prudent en jouant. Regardez autour de vous.',
    'key.creature.details.attack': 'Force',
    'key.creature.details.health': 'Santé',
    'key.creature.details.powerUp': 'Renforcement',
    'key.creature.details.evolve': 'Évolution',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'СР {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'LIBERER',
    'key.creature.details.creadex': 'Bestiaire',
    'key.creature.registration.creadex': 'Ajouté au bestiaire',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Bâtiments capturés',
    'key.activeObjects.library': 'Réformation de la créature dans la Bibliothèque',
    'key.activeObjects.library.empty': 'Pas de Bibliothèques conquises',
    'key.activeObjects.arena': 'Collecte des impôts auprès des Arènes',
    'key.activeObjects.arena.collect': 'Collecter',
    'key.activeObjects.arena.empty': 'Pas d\'Arènes conquises',
    'key.activeObjects.error.timer': 'La collecte des impôts est impossible. Veuillez patienter !',
    'key.activeObjects.error.noMoney': 'Il vous faut d\'abord conquérir une Arène',
    'key.activeObjects.error.cannotRemaster': 'La réformation n\'est pas disponible. Emparez-vous de Bibliothèques pour accélérer le chronomètre.',
    'key.activeObjects.library.remaster': 'Réformer',
    'key.activeObjects.library.blocked': 'Les Bibliothèques ne sont pas disponible',
    'key.activeObjects.remaster.confirmation.main': 'Êtes-vous sûr de vouloir réformer {0} ? La compétence de base {1} sera remplacée.',
    'key.activeObjects.remaster.confirmation.charged': 'Êtes-vous sûr de vouloir réformer {0} ? La compétence {1} qui se recharge sera remplacée.',
    'key.activeObjects.remaster.error': 'Erreur',
    'key.activeObjects.item.weaklyBonus': 'Bonus hebdomadaire +{0} pièces',
    'key.library.remaster.selectCreature': 'Choisissez la créature à réformer',
    'key.remasterPanel.title': 'Choisissez la compétence à remplacer',
    'key.storage.creatues': 'Créatures',
    'key.storage.eggs': 'Œufs',
    'key.storage.eggs.simple': 'Œufs ordinaires',
    'key.storage.eggs.super': 'Œufs anciens',
    'key.storage.eggs.missingAny': 'Vous ne possédez pas d\'œufs de créatures',
    'key.startEgg.button': 'Mettre dans un cocon',
    'key.startEgg.description': 'Utilisez le cocon de dragon pour couver cet œuf',
    'key.startEgg.incubator.title': 'Cocons de dragon',
    'key.startEgg.select.title': 'Choisir un œuf',
    'key.openEgg.button': 'Ouvrir l\'œuf',
    'key.openEgg.description': 'Une nouvelle créature va bientôt sortir de son œuf',
    'key.startEgg.description.roost.hatching': 'La Mère des Dragons est en train de couver cet œuf. Il ne vous reste qu\'attendre. La couvaison sera interrompue si la Crevasse d\'Arcana, où la Mère des Dragons se trouve, disparaît.',
    'key.startEgg.description.roost.notHatching': 'Donnez cet œuf à la Mère des Dragons pour le couver.',
    'key.startEgg.description.simple.hatching': 'Lors de la couvaison, cet œuf est protégé par un cocon de dragon. Restez connecté au jeu pour aider le petit à sortir de l\'œuf.',
    'key.startEgg.description.simple.notHatching': 'Placez cet œuf dans un cocon pour le couver. L\'œuf éclora une fois que vous aurez parcouru la distance nécessaire.',
    'key.mainMenu.wizardDuels': 'DUEL DE MAGICIENS',
    'key.mainMenu.quests': 'QUÊTES',
    'key.mainMenu.activePoints': 'BUTIN',
    'key.mainMenu.creadex': 'BESTIAIRE',
    'key.mainMenu.magic': 'MAGIE',
    'key.mainMenu.creatues': 'CRÉATURES',
    'key.mainMenu.shop': 'BOUTIQUE',
    'key.mainMenu.backpack': 'SAC',
    'key.error.banned': 'Le compte est bloqué',
    'event.log.CREATURE_CAUGHT': '{0} a été capturé !',
    'event.log.ITEM_BOUGHT': '{0} x{1} acheté. {2} pièces dépensées',
    'event.log.ARTIFACT_BOUGHT': 'Artefact acheté: {0}. {1} pièces dépensées',
    'event.log.EGG_HATCHED': '{0} est sorti de {1} l\'œuf !',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'd’or',
    'event.log.ROOST_EGG_HATCHED': 'La Mère des Dragons a couvé {1} h œuf. {0} est à vous maintenant !',
    'event.log.CHEST_OPENED': 'Trouvé dans le coffre :',
    'event.log.ARENA_LOST_CONTROL': '{1} a été exclu du bâtiment :  {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} a été exclu du bâtiment :  {0}',
    'event.log.LEVEL_UP': 'Vous avez atteint le niveau {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Votre compagnon a trouvé {0}',
    'event.log.QUEST_COMPLETED': 'Récompense pour la quête {0}',
    'event.log.ENCOUNTER_LOOSE': 'Vous avez échappé à un monstre sauvage',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'La limite de combats dans le Duel des Magiciens a été augmentée pour {0} pièces',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} pièces achetées pour {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Vous avez amélioré le sac pour {0} pièces',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Vous avez amélioré le stockage de créatures pour {0} pièces',
    'key.shop.accesories': 'OBJETS',
    'key.shop.artifacts': 'ARTEFACTS',
    'key.shop.donate': 'PIÈCES',
    'key.shop.upgrade': 'AMÉLIORATIONS',
    'key.shop.donate.coins': '{0} pièces',
    'key.shop.upgrade.bag': 'Amélioration du sac',
    'key.shop.upgrade.bag.desc': 'La taille du sac sera augmentée de 50',
    'key.shop.upgrade.storage': 'Amélioration du stockage de créatures',
    'key.shop.upgrade.storage.desc': 'La taille du stockage de créatures sera augmentée de 50',
    'key.shop.donate.dialog.title': 'Pas assez de pièces !',
    'key.shop.donate.dialog.desc': 'Obtenez-les ici ou visitez le Boutique pour voir plus d\'options',
    'key.potionUseMenu.title': 'Potions curatives',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Crée un Portail vers le monde d\'Arcana.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Tous les joueurs aux alentours vont ressentir la colère des leprechauns',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Crée un champ de Colonnes d\'Abondance pour une durée de 30 minutes',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Dans les Colonnes d\'Abondances, vos récompenses seront doublées pendant 30 minutes.',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Cliquez et maintenez sur la parcelle pour la mettre en évidence lors de la recherche des créatures',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Augmente le rayon de détection des monstres pour une durée de 30 minutes',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Augmente le champ de vision de 30 % pour une durée de 7 jours',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'L\'Arène alliée la plus proche sera protégée des attaques ennemies pendant 30 heures',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Toutes les Arènes ennemies dans le champ de vision deviennent neutres. Enlève la Bénédiction de la Défense.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Crée une tour magique qui attire les créatures de l\'élément Feu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Crée une tour magique qui attire les créatures de l\'élément Eau',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Crée une tour magique qui attire les créatures de l\'élément Air',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Crée une tour magique qui attire les créatures de l\'élément Terre',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Crée une tour magique qui attire les créatures de l\'élément Arcana',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Crevasse d\'Arcana',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Colère des leprechauns',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Champ d\'Abondance',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Don du Dragon d\'Or',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Vision astrale',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Vision de dragon',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Bras longs',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Bénédiction de la Défense',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Purification par le feu',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'La Tour du Feu',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'La Tour de l\'Eau',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'La Tour de l\'Air',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'La Tour de la Terre',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'La Tour de l\'Arcana',
    'key.buff.ATTACKER_CP_BOOST': 'CP de vos créatures a été temporairement augmenté',
    'key.buff.BEST_BALL_LUCK': 'Uniquement les meilleures sphères dans les Colonnes d\'Abondance pour une durée de 30 minutes',
    'key.buff.BEST_POTION_LUCK': 'Uniquement les meilleures potions dans les Colonnes d\'Abondance pour une durée de 30 minutes',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 objets dans les Colonnes d\'Abondance pour une durée de 30 minutes',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Le temps avant le réformation dans la Bibliothèque est réduit de {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Le temps avant la collecte des impôts auprès des Arènes est réduit de {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Augmente CP des monstres qui ne protègent pas des bâtiments',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Auprès des Colonnes d\'Abondance vous ne recevez que les meilleures sphères disponibles pour votre niveau',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Auprès des Colonnes d\'Abondance vous ne recevez que les meilleures potions disponibles pour votre niveau',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Vous recevez deux objets de plus auprès des Colonnes d\'Abondance',
    'key.loot.result.dust': 'Essence',
    'key.loot.result.exp': 'Expérience du personnage',
    'key.loot.result.coin': 'Pièces',
    'key.loot.result.candy': 'pierres',
    'key.item.MAGIC_BALL_SIMPLE': 'Sphère d\'apprenti',
    'key.item.MAGIC_BALL_NORMAL': 'Sphère de maître',
    'key.item.MAGIC_BALL_GOOD': 'Sphère de seigneur',
    'key.item.LURE': 'Appât',
    'key.item.INCENSE': 'Phéromones',
    'key.item.EGG': 'Œuf',
    'key.item.SHOVEL': 'Pelle',
    'key.item.POTION_HEAL_1': 'Petite potion curative',
    'key.item.POTION_HEAL_2': 'Moyenne potion curative',
    'key.item.POTION_HEAL_3': 'Grande potion curative',
    'key.item.POTION_HEAL_4': 'Potion de guérison complète',
    'key.item.POTION_RESURRECTION_1': 'Potion de résurrection',
    'key.item.POTION_RESURRECTION_2': 'Grande potion de résurrection',
    'key.item.INCUBATOR_1': 'Cocon de dragon',
    'key.item.INCUBATOR_3': 'Cocon de dragon',
    'key.item.INCUBATOR_PERPETUAL': 'Cocon de dragon permanent',
    'key.item.SUPER_VISION': 'Vision de dragon',
    'key.item.RUNE_1': 'Rune I',
    'key.item.RUNE_2': 'Rune II',
    'key.item.RUNE_3': 'Rune III',
    'key.item.RUNE_4': 'Rune IV',
    'key.item.RUNE_5': 'Rune V',
    'key.item.RUNE_6': 'Rune VI',
    'key.item.FOOD_CATCH_CHANCE': 'Caramel d\'Arcana',
    'key.item.FOOD_MORE_DUST': 'Beignet magique',
    'key.item.FOOD_CALM_DOWN': 'Guimauve de licorne',
    'key.item.FOOD_MORE_CANDIES': 'Glace des quatre éléments',
    'key.item.EXPERIENCE_BOOSTER': 'Cristal de sagesse',
    'key.item.EGG_KM_0': 'Œuf d\'Or',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sphère pour capturer les créatures.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sphère pour capturer les créatures. Augmente légèrement les chances de les attraper.',
    'key.item.MAGIC_BALL_GOOD.description': 'Sphère pour capturer les créatures. Augmente considérablement les chances de les attraper.',
    'key.item.LURE.description': 'Appât pour les créatures. Insérez-le dans la Colonne d\'abondance pour attirer les créatures.',
    'key.item.INCENSE.description': 'En fonction du jour de la semaine, les phéromones vont attirer les créatures d’un des éléments.',
    'key.item.EGG.description': 'Le cocon de dragon vous aidera à couver vos œufs pour faire naître des créatures',
    'key.item.SHOVEL.description': 'Les pelles sont indispensables lors de la chasse aux trésors',
    'key.item.POTION_HEAL_1.description': 'Soigne la créature en augmentant sa jauge de santé de 200 points',
    'key.item.POTION_HEAL_2.description': 'Soigne la créature en augmentant sa jauge de santé de 500 points',
    'key.item.POTION_HEAL_3.description': 'Soigne la créature en augmentant sa jauge de santé de 1000 points',
    'key.item.POTION_HEAL_4.description': 'Soigne complètement la créature',
    'key.item.POTION_RESURRECTION_1.description': 'Ressuscite la créature. Après la résurrection la créature sera blessée.',
    'key.item.POTION_RESURRECTION_2.description': 'Ressuscite et soigne complètement la créature',
    'key.item.INCUBATOR_1.description': 'Les cocons de dragon vous aideront à couver vos œufs pour faire naître des créatures. Il disparaîtra après l\'utilisation.',
    'key.item.INCUBATOR_3.description': 'Les cocons de dragon vous aideront à couver vos œufs pour faire naître des créatures. Il disparaîtra après les 3 utilisations.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Les cocons de dragon vous aideront à couver vos œufs pour faire naître des créatures.',
    'key.item.SUPER_VISION.description': 'Détecte des créatures dans une large zone',
    'key.item.RUNE_1.description': 'Rune magique du niveau 1',
    'key.item.RUNE_2.description': 'Rune magique du niveau 2',
    'key.item.RUNE_3.description': 'Rune magique du niveau 3',
    'key.item.RUNE_4.description': 'Rune magique du niveau 4',
    'key.item.RUNE_5.description': 'Rune magique du niveau 5',
    'key.item.RUNE_6.description': 'Rune magique du niveau 6',
    'key.item.FOOD_CATCH_CHANCE.description': 'Une sucrerie pour attirer les créatures. Augmente les chances de les attraper à l\'aide d\'une sphère magique',
    'key.item.FOOD_MORE_DUST.description': 'Une sucrerie pour attirer les créatures. Augmente la quantité d’essence que vous recevez pour les créatures capturées',
    'key.item.FOOD_CALM_DOWN.description': 'Une sucrerie pour attirer les créatures. Elle permet de calmer la créature en l\'empêchant de sauter et d\'attaquer',
    'key.item.FOOD_MORE_CANDIES.description': 'Une sucrerie pour attirer les créatures. Augmente la quantité de pierres d\'âme que vous recevez pour les créatures capturées',
    'key.item.EXPERIENCE_BOOSTER.description': 'Votre expérience sera doublée pendant 30 minutes',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Masque du magicien',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': 'La possibilité d’assigner à distance une créature à une Arène ou à une Bibliothèque 1 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Cet artefact vous permet de placer à distance votre créature sur un espace libre dans l\'Arène ou dans la Bibliothèque visibles sur la carte 1 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Tête du voyant',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': 'La possibilité d’assigner à distance une créature à une Arène ou à une Bibliothèque 2 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Cet artefact vous permet de placer à distance votre créature sur un espace libre dans l\'Arène ou dans la Bibliothèque visibles sur la carte 2 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Casque du conquérant',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': 'La possibilité d’assigner à distance une créature à une Arène ou à une Bibliothèque 3 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Cet artefact vous permet de placer à distance votre créature sur un espace libre dans l\'Arène ou dans la Bibliothèque visibles sur la carte 3 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Casque du héros',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': 'La possibilité d’assigner à distance une créature à une Arène ou à une Bibliothèque 4 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Cet artefact vous permet de placer à distance votre créature sur un espace libre dans l\'Arène ou dans la Bibliothèque visibles sur la carte 4 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Casque du tueur de dragons',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': 'La possibilité d’assigner à distance une créature à une Arène ou à une Bibliothèque 5 fois par jour',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Cet artefact vous permet de placer à distance votre créature sur un espace libre dans l\'Arène ou dans la Bibliothèque visibles sur la carte 5 fois par jour',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Étendard du seigneur',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Permet d\'envoyer une créature supplémentaire sur l\'Arène ou dans la Bibliothèque',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Cet artefact vous permet d\'envoyer deux créatures au lieu d’une pour défendre une Arène ou une Bibliothèque',
    'key.artifact.ARTIFACT_BANK_8': 'Artefact coupé',
    'key.artifact.ARTIFACT_BANK_8.description': 'Comment l\'avez-vous trouvé ?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Vous avez découvert un artefact que vous n’auriez jamais dû voir. Maintenant nous devons nous débarrasser d\'un témoin.',
    'key.artifact.ARTIFACT_BANK_9': 'Artefact coupé',
    'key.artifact.ARTIFACT_BANK_9.description': 'Comment l\'avez-vous trouvé ?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Vous avez découvert un artefact que vous n’auriez jamais dû voir. Maintenant nous devons nous débarrasser d\'un témoin.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Montre de l\'étudiant paresseux',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': 'Le temps de rechargement des Colonnes d\'Abondance sera réduit de 20 secondes',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Cet artefact vous permettra de réduire le temps de rechargement des Colonnes d\'Abondance de 20 secondes et les utiliser plus souvent.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Le réveil du retardataire',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': 'Le temps de rechargement des Colonnes d\'Abondance sera réduit de 40 secondes',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Cet artefact vous permettra de réduire le temps de rechargement des Colonnes d\'Abondance de 40 secondes et les utiliser plus souvent.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Accélérateur spatial',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': 'Le temps de rechargement des Colonnes d\'Abondance sera réduit de 60 secondes',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Cet artefact vous permettra de réduire le temps de rechargement des Colonnes d\'Abondance de 60 secondes et les utiliser plus souvent.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Montre du professeur paresseux',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': 'Le temps de rechargement des Colonnes d\'Abondance sera réduit de 80 secondes',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Cet artefact vous permettra de réduire le temps de rechargement des Colonnes d\'Abondance de 80 secondes et les utiliser plus souvent.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Montre du lapin zèbre',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': 'Le temps de rechargement des Colonnes d\'Abondance sera réduit de 100 secondes',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Cet artefact vous permettra de réduire le temps de rechargement des Colonnes d\'Abondance de 100 secondes et les utiliser plus souvent.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Bâton d\'envahisseur',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 au niveau de l\'Arène ou de la Bibliothèque après l\'occupation',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Si le propriétaire de cet artefact est le premier à placer une créature sur l\'Arène ou dans la Bibliothèque occupées, cette dernière atteindra instantanément le niveau 5 au lieu du niveau 3',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Anneau de percepteur',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 au nombre maximum d\'Arènes occupées',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Cet artefact vous permet de percevoir les impôts de 11 Arènes, au lieu de 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Anneau d\'avidité',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 au nombre maximum d’Arènes occupées',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Cet artefact vous permet de percevoir les impôts de 12 Arènes, au lieu de 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Anneau double',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 au nombre total d’Arènes disponibles pour la collecte des impôts',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Cet artefact vous permet de percevoir les impôts de 13 Arènes, au lieu de 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Coupe du mangeur de gâteaux',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% à la gloire des Arènes et Bibliothèques alliées pendant l\'entraînement',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Avec cet artefact les Arènes et Bibliothèques alliées reçoivent 20% de gloire en plus lorsque vous les entraînez',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Coupe de miel',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% à la gloire des Arènes et Bibliothèques alliées pendant l\'entraînement',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Avec cet artefact les Arènes et Bibliothèques alliées reçoivent 30% de gloire en plus lorsque vous les entraînez',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Calice de pensées profondes',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% à la gloire des Arènes et Bibliothèques alliées pendant l\'entraînement',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Avec cet artefact les Arènes et Bibliothèques alliées reçoivent 40% de gloire en plus lorsque vous les entraînez',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Graal de Lancelope',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% à la gloire des Arènes et Bibliothèques alliées pendant l\'entraînement',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Avec cet artefact les Arènes et Bibliothèques alliées reçoivent 50% de gloire en plus lorsque vous les entraînez',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Coupe du conquérant des monstres',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% à la gloire des Arènes et Bibliothèques alliées pendant l\'entraînement',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Avec cet artefact les Arènes et Bibliothèques alliées reçoivent 80% de gloire en plus lorsque vous les entraînez',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem de vision nette',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Enlève les créatures faibles du radar',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Cet artefact enlève les créatures les plus faibles du radar pour que vous puissiez vous concentrer sur les créatures les plus fortes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Livre de règles d\'aventurier',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minutes à la durée de la collecte des impôts auprès d’une Arène après l\'occupation de celle-ci par l’adversaire',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Avec cet artefact les Arènes sont disponibles à la collecte des impôts pendant 30 minutes après l’occupation, au lieu de 15 minutes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Épais livre',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minutes à la durée de la collecte des impôts auprès d’une Arène après l\'occupation de celle-ci par l’adversaire',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Avec cet artefact les Arènes sont disponibles à la collecte des impôts pendant 45 minutes après l’occupation, au lieu de 15 minutes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tablette de possession',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minutes à la durée de la collecte des impôts auprès d’une Arène après l\'occupation de celle-ci par l’adversaire',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Avec cet artefact les Arènes sont disponibles à la collecte des impôts pendant 60 minutes après l’occupation, au lieu de 15 minutes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Traité sur la gouvernance',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minutes à la durée de la collecte des impôts auprès d’une Arène après l\'occupation de celle-ci par l’adversaire',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Avec cet artefact les Arènes sont disponibles à la collecte des impôts pendant 90 minutes après l’occupation, au lieu de 15 minutes',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoire du pouvoir',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minutes à la durée de la collecte des impôts auprès d’une Arène après l\'occupation de celle-ci par l’adversaire',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Avec cet artefact les Arènes sont disponibles à la collecte des impôts pendant 120 minutes après l’occupation, au lieu de 15 minutes',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Collier clouté',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% de réduction du temps nécessaire pour l\'obtention de pierres d\'âme de votre compagnon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Avec cet artefact, la distance que vous devez surmonter avec votre compagnon pour obtenir votre pierre d\'âme sera réduite de 10%. Le niveau de sévérité de votre compagnon sera élevé de 17%',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Carotte sur un bâtonnet',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% de réduction du temps nécessaire pour l\'obtention de pierres d\'âme de votre compagnon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Avec cet artefact, la distance que vous devez surmonter avec votre compagnon pour obtenir votre pierre d\'âme sera réduite de 15 %. Miam miam',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Gratte-dos',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% de réduction du temps nécessaire pour l\'obtention de pierres d\'âme de votre compagnon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Avec cet artefact, la distance que vous devez surmonter avec votre compagnon pour obtenir votre pierre d\'âme sera réduite de 25%. Inclinez-vous devant le pouvoir du gratte-dos !',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Grelot du chouchou',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% de réduction du temps nécessaire pour l\'obtention de pierres d\'âme de votre compagnon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Avec cet artefact, la distance que vous devez surmonter avec votre compagnon pour obtenir votre pierre d\'âme sera réduite de 30%. C\'est qui, le bon toutou ?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Dragon en peluche',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% de réduction du temps nécessaire pour l\'obtention de pierres d\'âme de votre compagnon',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Avec cet artefact, la distance que vous devez surmonter avec votre compagnon pour obtenir votre pierre d\'âme sera réduite de 40%. Le meilleur joueut pour le meilleur compagnon du monde',
    'key.artifact.ARTIFACT_ROOST_1': 'Cœur du Dragon',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 cocon de dragon chez la Mère des Dragons',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Permet d\'utiliser le cocon de dragon supplémentaire pour les œufs chez la Mère des Dragons',
    'dialog.artifact.select_artifact': 'CHOISISSEZ UN ARTEFACT',
    'dialog.artifact.confirm.remove': 'Êtes-vous sûr de vouloir supprimer l\'artefact ?',
    'dialog.items.title': 'SAC',
    'dialog.items.cannotUse': 'Cet objet ne peut pas être utilisé',
    'dialog.items.remove.header': 'Supprimer les objets',
    'dialog.encounter.header': 'Attaque d\'un monstre sauvage !',
    'dialog.encounter.button.leave': 'S\'enfuir',
    'dialog.encounter.button.fight': 'Combattre',
    'dialog.encounter.result.outcome.win': 'Le monstre sauvage a subi une défaite',
    'dialog.encounter.result.outcome.lose': 'Votre créature a subi une défaite',
    'dialog.encounter.result.reward.dust': 'Essence',
    'dialog.encounter.result.reward.exp': 'Expérience',
    'error.nickname.validation.IS_EMPTY': 'Saisissez le nom du personnage',
    'error.nickname.validation.TOO_SHORT': 'Le nom doit contenir de 3 à 16 caractères',
    'error.nickname.validation.TOO_LONG': 'Le nom doit contenir de 3 à 16 caractères',
    'error.nickname.validation.INVALID_CHAR': 'Vous pouvez utiliser des lettres latines, des chiffres et des tirets bas.',
    'error.nickname.validation.DUPLICATE': 'Ce nom est déjà pris. Le nom disponible {0}',
    'creature.MONSTER_WATER_1': 'Crapaudius',
    'creature.MONSTER_WATER_2': 'Guth',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Aquin',
    'creature.MONSTER_WATER_5': 'Crapaudissimo',
    'creature.MONSTER_WATER_6': 'Ruisseau',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minori',
    'creature.MONSTER_WATER_10': 'Inphalisque',
    'creature.MONSTER_WATER_11': 'Médiaquin',
    'creature.MONSTER_WATER_12': 'Dadachoc',
    'creature.MONSTER_WATER_13': 'Batoїde',
    'creature.MONSTER_WATER_14': 'Poirolisque',
    'creature.MONSTER_WATER_15': 'Phalkhore',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Aquarh',
    'creature.MONSTER_WATER_18': 'Dadatchum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilic',
    'creature.MONSTER_WATER_21': 'Melkhore',
    'creature.MONSTER_WATER_22': 'Cristalo',
    'creature.MONSTER_WATER_23': 'Blinderius',
    'creature.MONSTER_WATER_24': 'Neptune',
    'creature.MONSTER_WATER_25': 'Léviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mommiewin',
    'creature.MONSTER_FIRE_3': 'Vaporino',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Patteaufeu',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Phoby',
    'creature.MONSTER_FIRE_8': 'Dammiewin',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Helsailor',
    'creature.MONSTER_FIRE_11': 'Etincelle',
    'creature.MONSTER_FIRE_12': 'Khydra',
    'creature.MONSTER_FIRE_13': 'Démonstar',
    'creature.MONSTER_FIRE_14': 'Phénix',
    'creature.MONSTER_FIRE_15': 'Pikhot',
    'creature.MONSTER_FIRE_16': 'Toutanfer',
    'creature.MONSTER_FIRE_17': 'Luciole',
    'creature.MONSTER_FIRE_18': 'César',
    'creature.MONSTER_FIRE_19': 'Flashy',
    'creature.MONSTER_FIRE_20': 'Fliboustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydre',
    'creature.MONSTER_FIRE_23': 'Artifix',
    'creature.MONSTER_FIRE_24': 'Pikaroune',
    'creature.MONSTER_FIRE_25': 'Smaugre',
    'creature.MONSTER_EARTH_1': 'Fruidzilla',
    'creature.MONSTER_EARTH_2': 'Fleurette',
    'creature.MONSTER_EARTH_3': 'Feuillux',
    'creature.MONSTER_EARTH_4': 'Browny',
    'creature.MONSTER_EARTH_5': 'Chamurf',
    'creature.MONSTER_EARTH_6': 'Dryade',
    'creature.MONSTER_EARTH_7': 'Pouxi',
    'creature.MONSTER_EARTH_8': 'Disghuir',
    'creature.MONSTER_EARTH_9': 'Belflow',
    'creature.MONSTER_EARTH_10': 'Glandoux',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Pignours',
    'creature.MONSTER_EARTH_15': 'Dhao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Guardrag',
    'creature.MONSTER_EARTH_20': 'Springua',
    'creature.MONSTER_EARTH_21': 'Terraborna',
    'creature.MONSTER_EARTH_22': 'Methafleur',
    'creature.MONSTER_EARTH_23': 'Yogui',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Оreyor',
    'creature.MONSTER_WIND_3': 'Gribbie',
    'creature.MONSTER_WIND_4': 'Fluffycorne',
    'creature.MONSTER_WIND_5': 'Aїrvert',
    'creature.MONSTER_WIND_6': 'Gamaïoun',
    'creature.MONSTER_WIND_7': 'Horrificus',
    'creature.MONSTER_WIND_8': 'Oreillot',
    'creature.MONSTER_WIND_9': 'Esquimau',
    'creature.MONSTER_WIND_10': 'Vendanse',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Ondine',
    'creature.MONSTER_WIND_13': 'Aerocorne',
    'creature.MONSTER_WIND_14': 'Phantomo',
    'creature.MONSTER_WIND_15': 'Cheshire',
    'creature.MONSTER_WIND_16': 'Chamtopie',
    'creature.MONSTER_WIND_17': 'Harpie',
    'creature.MONSTER_WIND_18': 'Ghostus',
    'creature.MONSTER_WIND_19': 'Pérogriffe',
    'creature.MONSTER_WIND_20': 'Pillowcha',
    'creature.MONSTER_WIND_21': 'Hippomouche',
    'creature.MONSTER_WIND_22': 'Cyclonia',
    'creature.MONSTER_WIND_23': 'Griffon',
    'creature.MONSTER_WIND_24': 'Bayoune',
    'creature.MONSTER_WIND_25': 'Charybde',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Crampondo',
    'creature.MONSTER_DUNGEON_4': 'Maglad',
    'creature.MONSTER_DUNGEON_5': 'Chatmix',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Maride',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Épouvantail',
    'creature.MONSTER_DUNGEON_10': 'Sneylin',
    'creature.MONSTER_DUNGEON_11': 'Djinno',
    'creature.MONSTER_DUNGEON_12': 'Vampiro',
    'creature.MONSTER_DUNGEON_13': 'Chenillou',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twisty',
    'creature.MONSTER_DUNGEON_16': 'Kedoux',
    'creature.MONSTER_DUNGEON_17': 'Aynur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Regalus',
    'creature.MONSTER_DUNGEON_20': 'Tigromanus',
    'creature.MONSTER_DUNGEON_21': 'Khefine',
    'creature.MONSTER_DUNGEON_22': 'Butonius',
    'creature.MONSTER_DUNGEON_23': 'Phrizeux',
    'creature.MONSTER_DUNGEON_24': 'Manthycore',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Morsure de requin',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Terreur des profondeurs',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Appel de Khatoulou',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Marteau marin',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Poing aqueux',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Vague',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Averse',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Geyser',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Éclaboussures',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Flamme vivante',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Doigt de feu',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Fouet de feu',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Boule de feu',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Incinérateur',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Étoile',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Charbon',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Lance-flammes',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Fusillade',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Faucille aérienne',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Fouilleur',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Respiration',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Électrochoc',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Eclairs de plasma',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Sismothérapie',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Soupir de dragon',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Souffle',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Fureur du vent',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Crachat de poison',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Croc de serpent',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Empoisonnement',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Brise-échine',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Rocher',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Caillou',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Esprit de la forêt',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Fantôme de l\'arbre',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Ombre de la nature',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Flèche d\'Arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Caillot des ténèbres',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentacules de mal',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Œil de  terreur',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sphère de  mort',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Boule des ténèbres',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arcana Kadavra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarcus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Impericanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Givrage',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Congélation',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Cristallisation',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Tourbillon',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Tempête',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Сolère froide',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Explosion glacée',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Puissance de glace',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Purification',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Ascension',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Brûlure',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lave',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Fontaine de feu',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Météores',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocide',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Éclair',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Tonnerre',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Orage',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Redémarrage',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Champ magnétique',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Chair de poule',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornade',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Hurlement du vent',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Carrousel',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Tintamarre',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Tremblement',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Crevasse',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Destruction',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Explosion',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Tourbillon de pierres',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Lac de mort',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Flaque empoisonnée',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Acide',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomisation',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Désintégration',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionisation',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Expulsion',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Malédiction',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Exclusion',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Tempête de magie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Tempête de mana',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Colère d\'Arcana',
    'key.combined.first.1': 'Sages',
    'key.combined.first.2': 'Sacrés',
    'key.combined.first.3': 'Magnifiques',
    'key.combined.first.4': 'Virulents',
    'key.combined.first.5': 'Neutres',
    'key.combined.first.6': 'Sincères',
    'key.combined.first.7': 'Saints',
    'key.combined.first.8': 'Anciens',
    'key.combined.first.9': 'Souterrains',
    'key.combined.first.10': 'Enflammés',
    'key.combined.first.11': 'Adroits',
    'key.combined.first.12': 'Gigantesques',
    'key.combined.first.13': 'Bleus',
    'key.combined.first.14': 'Cruels',
    'key.combined.first.15': 'Gentils',
    'key.combined.first.16': 'Aériens',
    'key.combined.first.17': 'Terrestres',
    'key.combined.first.18': 'Rouges',
    'key.combined.first.19': 'Immortels',
    'key.combined.first.20': 'Morts',
    'key.combined.first.21': 'Aériens',
    'key.combined.first.22': 'Epouvantables',
    'key.combined.first.23': 'Aquatiques',
    'key.combined.first.24': 'Amusants',
    'key.combined.first.25': 'Bêtes',
    'key.combined.second.1': 'Héros',
    'key.combined.second.2': 'Poissons',
    'key.combined.second.3': 'Hiboux',
    'key.combined.second.4': 'Malfaiteurs',
    'key.combined.second.5': 'Lieutenants',
    'key.combined.second.6': 'Magiciens',
    'key.combined.second.7': 'Vieux',
    'key.combined.second.8': 'Conjurateurs',
    'key.combined.second.9': 'Guerriers',
    'key.combined.second.10': 'Duellistes',
    'key.combined.second.11': 'Marchands',
    'key.combined.second.12': 'Lapins',
    'key.combined.second.13': 'Pommiers',
    'key.combined.second.14': 'Combattants',
    'key.combined.second.15': 'Illusionnistes',
    'key.combined.second.16': 'Chevaliers',
    'key.combined.second.17': 'Barbares',
    'key.combined.second.18': 'Coléoptères',
    'key.combined.second.19': 'Serpents',
    'key.combined.second.20': 'Dragons',
    'key.combined.second.21': 'Fantômes',
    'key.combined.second.22': 'Chats',
    'key.combined.second.23': 'Soldats',
    'key.combined.second.24': 'Chanceux',
    'key.combined.second.25': 'Assassins',
    'key.combined.second.26': 'Rats',
    'key.combined.second.27': 'Élémentaires',
    'key.combined.second.28': 'Explorateurs',
    'key.combined.second.29': 'Chamans',
    'key.combined.second.30': 'Prêtres',
    'key.combined.second.31': 'Anges',
    'key.combined.second.32': 'Archontes',
    'key.combined.second.33': 'Exécuteurs',
    'key.combined.second.34': 'Imbéciles',
    'key.combined.second.35': 'Courageux',
    'key.combined.second.36': 'Braves',
    'key.combined.second.37': 'Froussards',
    'key.combined.second.38': 'Bardes',
    'key.combined.second.39': 'Dompteurs',
    'key.combined.second.40': 'Défenseurs',
    'key.combined.arena': 'Arène de {1} {0}',
    'key.combined.library': 'Bibliothèque de {1} {0}',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Eau',
    'element.type.WIND': 'Air',
    'element.type.FIRE': 'Feu',
    'element.type.EARTH': 'Terre',
    'element.type.DUNGEON': 'Arcana',
    'spell.type.ACTIVATION_RADIUS': 'Champ de vision',
    'spell.type.VISION_RADIUS': 'Vision de dragon',
    'spell.type.STOP_FIELD': 'Champ d\'Abondance',
    'spell.type.SCOUT': 'Explorer',
    'spell.type.PROTECT_ARENA': 'Défense de l\'Arène',
    'spell.type.CREATE_PORTAL': 'Créer un Portail',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Double-drop',
    'spell.type.SLUG_PLAYERS': 'Слизнякнуть игроков',
    'quest.title.WIN_ARENA_MONSTER': 'Dominance',
    'quest.title.OPEN_EGGS': 'Ruée vers l\'œuf',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Contrôle du territoire',
    'quest.title.CAPTURE_LIBRARY': 'Soif de connaissance',
    'quest.title.CAPTURE_WILD_MONSTER': 'Parc des dragons',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Chasse à l\'élément',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Recherche de natifs arcaniens',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Nettoyage de la Crevasse',
    'quest.title.OPEN_CHEST': 'Vieux trésors',
    'quest.title.CHAIN_OF_STOP': 'Chemin d\'Abondance',
    'quest.desc.WIN_ARENA_MONSTER': 'Vainquez les créatures sur l\'Arène ou dans la Bibliothèque. Il est impossible de vaincre la créature du même type deux fois.',
    'quest.desc.OPEN_EGGS': 'Les cocons de dragon ainsi que la Mère des Dragons vous aideront à couver vos œufs pour faire naître des créatures.',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Collectez les impôts auprès des Arènes occupées',
    'quest.desc.CAPTURE_LIBRARY': 'Possédez le nombre nécessaire de Bibliothèques',
    'quest.desc.CAPTURE_WILD_MONSTER': 'On n’a jamais assez de créatures. Voyagez et capturez de nouvelles créatures',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Voyagez et capturez les créatures d\'Eau',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Voyagez et capturez les créatures d\'Air',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Voyagez et capturez les créatures de Feu.',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Voyagez et capturez les créatures de Terre.',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Voyagez et capturez les créatures d\'Arcana',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Visitez la Crevasse d\'Arcana pour trouver la Mère des Dragons',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Visitez la Crevasse d\'Arcana pour capturer toutes les créatures qu\'elle abrite',
    'quest.desc.OPEN_CHEST': 'Trouvez les coffres aux trésors et ouvrez-les',
    'quest.desc.CHAIN_OF_STOP': 'Passez par la chaîne des Colonnes d\'Abondance et activez-les. Chaque Colonne suivante s\'éclairera.',
    'quest.dialog.completed.rewardtext': 'Votre récompense : ',
    'key.tab.altar.title': 'AUTEL',
    'key.altar.remove': 'Supprimer',
    'key.altar.put': 'Installer',
    'key.altar.convert': 'Transformer',
    'key.altar.shared': 'Partager',
    'key.altar.pass.placeholder': 'Vous pouvez saisir votre mot de passe ici',
    'key.altar.pass.error': 'Le mot de passe doit contenir au moins {0} caractères',
    'key.altar.level.error': 'Vous devez atteindre le niveau {0}, pour avoir accès à l\'Autel',
    'key.altar.recipe.change': 'Êtes-vous sûr de vouloir modifier la recette ? Les runes seront retournées à leurs propriétaires.',
    'key.altar.row.title': 'Pour faire ce sort il faut installer l\'Autel',
    'key.altar.rune.descr.RUNE_1': '3 runes vertes = une rune orange',
    'key.altar.rune.descr.RUNE_2': '3 runes orange = une rune bleue',
    'key.altar.rune.descr.RUNE_3': '3 runes bleues = une rune émeraude',
    'key.altar.rune.descr.RUNE_4': '3 runes émeraude = une rune rouge',
    'key.altar.rune.descr.RUNE_5': '3 runes rouges = une rune mauve',
    'key.altar.rune.descr.RUNE_6': 'Les runes mauves sont les plus fortes',
    'error.altar.cannotRemove': 'Impossible de supprimer l\'Autel',
    'error.altar.cannotConvert': 'Vous n\'avez pas assez de runes',
    'key.tab.altar.recipes': 'RECETTES',
    'key.altar.noRecipes': 'Vous n\'avez pas de recettes',
    'key.altar.header': 'Placez les runes sur l\'Autel pour créer une incantation',
    'key.altar.castBtn': 'Créer',
    'key.altar.recipe.select': 'Choisissez une incantation',
    'key.altar.castDone': 'L\'incantation a été créée',
    'key.arena.protected.ally': 'Défense',
    'key.avatarCustomization.title': 'Sélectionnez votre personnage :',
    'key.buddy.walkDescription': 'Marchez avec votre compagnon pour recevoir {0}',
    'key.buddy.totalWalked': 'Vous avez déjà fait {0} km',
    'key.account.balance': 'Ressources :',
    'key.account.userLevel': '{0} niveau',
    'key.account.totalDistance': 'Distance totale parcourue : {0} kilomètre(s)',
    'key.acount.registerDate': 'Début du jeu : {0}',
    'key.storage.sort.name': 'NOM',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'LISTE VERTE',
    'key.storage.sort.group2': 'LISTE JAUNE',
    'key.storage.sort.group3': 'LISTE ROUGE',
    'key.storage.sort.date': 'DATE',
    'key.account.options.jurnal': 'CARNET',
    'key.account.options.buddy': 'COMPAGNON',
    'key.account.options.artifacts': 'ARTEFACTS',
    'key.account.options.style': 'APPARENCE',
    'key.error.gps.permission': 'Le GPS n\'est pas disponible. Activez l\'accès au GPS pour continuer le jeu.',
    'key.error.gps.disabled': 'GPS désactivé. Activez le GPS pour continuer le jeu.',
    'key.error.gps.fakePosition': 'Vous ne pouvez pas jouer sans GPS',
    'key.error.gps.signal.notFound': 'Signal GPS introuvable',
    'key.error.gps.signal.bad': 'Le jeu n\'est pas disponible. Le signal GPS est faible.',
    'key.error.internet.notReachable': 'Aucune connexion Internet',
    'key.journal.title': 'Carnet',
    'key.journal.yesterday': 'Hier',
    'key.settings.title': 'Paramètres',
    'key.settings.music': 'Musique',
    'key.settings.sounds': 'Sons',
    'key.settings.vibration': 'Vibrations',
    'key.settings.batterySaver': 'Économie d\'énergie',
    'key.settings.support': 'Contacter l\'assistance',
    'key.settings.logout': 'Se déconnecter',
    'key.settings.auth.deviceid': 'ID de l\'appareil',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Associer',
    'key.settings.languageTitle': 'Langue',
    'key.settings.language': 'Français',
    'key.battle.result.win': 'Fin du combat',
    'key.battle.result.lose': 'Fin du combat',
    'key.wizardBattle.result.win': 'VICTOIRE !',
    'key.wizardBattle.result.lose': 'DÉFAITE!',
    'key.battle.result.monster': 'Créatures vaincues',
    'key.battle.result.exp': 'L\'expérience aquise',
    'key.battle.result.prestige_strong_enemy': 'Bonus de gloire pour avoir vaincu un ennemi puissant',
    'key.battle.result.exp_strong_enemy': 'Bonus d\'expérience pour avoir vaincu un ennemi puissant',
    'key.battle.result.prestige_killed_all': 'Bonus de gloire pour avoir éliminé tous les ennemis',
    'key.battle.result.exp_killed_all': 'Bonus d\'expérience pour avoir éliminé tous les ennemis',
    'key.battle.result.dust': 'Essence',
    'key.radar.title': 'Créatures à proximité',
    'key.levelUp.title': 'Nouveau niveau !',
    'key.wizardBattle.left': 'Limite de combats :',
    'key.wizardBattle.timer': 'La limite sera remise à zéro dans ',
    'key.wizardBattle.enhance.title': 'AUGMENTER LA LIMITE',
    'key.wizardBattle.enhance.desc': 'Il est possible d\'augmenter la limite des combats jusqu\'au 7 par jour pour une semaine.',
    'key.wizardBattle.enhance.btn': 'Augmenter',
    'key.wizardBattle.lookingForOpponent': 'Recherche d’un adversaire pour le Duel...',
    'key.catch.result.expMonster': 'Expérience pour la capture :',
    'key.catch.result.expMonsterNew': 'Nouveauté dans le Bestiaire :',
    'key.catch.result.expAccurate': 'Pour un tir précis :',
    'key.catch.result.expSpin': 'Pour un tir courbé :',
    'key.catch.result.strike': 'La première créature aujourd’hui :',
    'key.catch.result.total': 'Total d\'expérience :',
    'key.catch.fullStorage': 'Le stockage de créatures est plein',
    'key.catch.noItems': 'Vous n\'avez pas de sphères magiques',
    'key.creadex.title': 'Bestiaire',
    'key.creadex.detail.caught': 'Capturé : {0}',
    'key.creadex.detail.evolution': 'Evolution',
    'key.tab.doll': 'PERSONNAGE',
    'key.tab.artifacts': 'ARTEFACTS',
    'key.activePoint.title': 'Colonne d\'Abondance',
    'key.personalization.title': 'Enchantement',
    'key.chest.title': 'Coffre magique',
    'key.quest.daily.title': 'MISSION',
    'key.quest.weekly.title': 'CHASSE',
    'key.quest.get': 'RECEVOIR UNE MISSIONЕ',
    'key.quest.change': 'CHANGER LA MISSION',
    'key.quest.progress': 'Progrès de la mission : {0} de {1}',
    'key.error.quest.weekly.level': 'Il faut atteindre le niveau {0} pour commencer la chasse à l\'Œuf d\'Or',
    'key.error.quest.daily.level': 'Il faut atteindre le niveau {0} pour recevoir une mission',
    'key.error.quest.tooFar': 'L’Obélisque est trop loin',
    'key.quest.daily.descr.noQuest.title': 'Vous n\'avez pas de missions.',
    'key.quest.daily.descr.noQuest': 'Utilisez l\'Obélisque pour recevoir une mission et obtenir votre récompense.',
    'key.quest.daily.timer.descr': 'Le changement de la quête sera disponible dans :',
    'key.quest.daily.waitForNew.descr': 'La nouvelle quête sera disponible dans : ',
    'key.quest.weekly.getFragment': 'RECEVOIR UN FRAGMENT',
    'key.quest.weekly.descr.noQuest.title': 'Vous ne participez pas à la chasse à l\'Œuf d\'Or.',
    'key.quest.weekly.descr.noQuest': 'Utilisez l\'Obélisque pour recevoir un fragment d\'une carte mystérieuse et commencer la chasse.',
    'key.quest.weekly.descr.getFirstFragment': 'Obtenez le premier fragment d\'une carte mystérieuse pour commencer la chasse à l\'Œuf d\'Or.',
    'key.quest.weekly.descr.top.notAllOpen': 'Utilisez les Obélisques pour recevoir les fragments de la carte. Dépêchez-vous, la chasse sera terminée dans ',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Utilisez la pelle sur chaque fragment pour trouver l\'Œuf d\'Or',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Vous avez déjà reçu un fragment de la carte de cet Obélisque',
    'key.quest.weekly.descr.top.allOpen': 'Vous avez déjà reçu tous les fragments de la carte des Obélisques. Dépêchez-vous, la chasse sera terminée dans ',
    'key.quest.weekly.descr.bot.allOpen': 'Utilisez la pelle sur chaque fragment pour trouver l\'Œuf d\'Or',
    'key.quest.weekly.descr.top.completed': 'Vous avez déjà trouvé un Œuf d\'Or cette semaine. La prochaine chasse commence dans ',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}h',
    'key.timer.format.H_M': '{0}h {1}m',
    'key.timer.format.D': '{0}j',
    'key.timer.format.D_H': '{0}j {1}h',
    'key.creatureStorage.tab.creatures': 'CRÉATURES',
    'key.creatureStorage.tab.eggs': 'ŒUFS',
    'key.creatureStorage.multiTransferText': 'Choisissez la créature que vous voulez libérer',
    'key.storage.creature.transfer': 'Libérer ({0})',
    'key.error.needHigherLevelForArena': 'Le niveau {0} est requis pour entrer dans l\'Arène',
    'key.error.needHigherLevelForLibrary': 'Le niveau {0} est requis pour entrer dans la Bibliothèque',
    'key.error.arenaUnderProtection': 'L\'Arène est sous la protection de la Bénédiction de la Défense',
    'key.error.buildingTooFar': 'Le bâtiment est trop loin',
    'key.error.noAliveCreaturesForAttack': 'Vous n\'avez pas de créatures vivantes disponibles',
    'key.error.noHealPotion': 'Vous n\'avez pas de potions curatives',
    'key.error.noResurrectionPotion': 'Vous n\'avez pas de potions de résurrection',
    'key.error.tryAgainLater': 'Une erreur s\'est produite. Veuillez réessayer plus tard.',
    'key.error.alreadyHasLure': 'L’appât a été posé',
    'key.error.cannotUseLureInDungeon': 'L\'appât ne peut pas être utilisé dans la Crevasse d\'Arcana',
    'key.error.bagIsFull': 'Le sac est plein',
    'key.error.cantTransferCreature': 'Impossible de libérer cette créature',
    'key.notification.done': 'C\'est fait !',
    'key.modal.doYouWantToTransfer': 'Êtes-vous sûr de vouloir libérer ces créatures ?',
    'key.modal.youWillLoseBuddyProgress': 'Êtes-vous sûr de vouloir changer votre compagnon ? Le progrès de la réception des pierres d\'âmes sera remis à zéro.',
    'key.modal.doYouWantToLeaveDungeon': 'Vous voulez quitter la Crevasse d\'Arcana ?',
    'key.modal.superVisionActive': 'La vision de dragon a déjà été activée. La réutilisation déplacera la zone de visibilité magique. Êtes-vous sûr de vouloir l\'utiliser à nouveau ?',
    'key.modal.experienceBoosterActive': 'Le cristal de sagesse est déjà activé. Êtes-vous sûr de vouloir l\'utiliser encore une fois ?',
    'key.modal.youWillLooseQuestProgress': 'Le progrès de la quête en cours sera perdu. Êtes-vous sûr ?',
    'key.modal.doYouWantToEnterDungeon': 'Voulez-vous utiliser le Portail pour accéder à la Crevasse d\'Arcana ?',
    'key.modal.doYouWantPersonalizePoint': 'La Colonne d\'Abondance vous n\'offrira que {0}. Voulez-vous dépenser {1} pièce(s) pour l\'enchantement ?',
    'key.modal.doYouWantToDeletePersonalization': 'Êtes-vous sûr de vouloir retirer l\'enchantement de cette Colonne d\'Abondance ?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Voulez-vous renforcer cette créature ?',
    'key.modal.doYouWantToEvolveThisCreature': 'Voulez-vous faire évoluer cette créature ?',
    'key.modal.doYouWantToScoutHere': 'Êtes-vous sûr de vouloir explorer ce terrain ?',
    'key.error.creatureHasMaxLevel': 'Cette créature a atteint le niveau maximal',
    'key.error.creatureHasMaxLevelForUser': 'Vous devez d\'abord améliorer votre personnage',
    'key.error.notEnoughResourcesForEnhance': 'Vous n\'avez pas assez de ressources',
    'key.error.creatureIsArenaDefender': 'Impossible de choisir la créature qui est assignée à la défense d\'un bâtiment',
    'key.modal.incenseActive': 'Les phéromones sont déjà activées. Êtes-vous sûr de vouloir les réutiliser ?',
    'key.error.cantHealHealthyCreature': 'La créature est complètement guérie',
    'key.error.cantRessurectAliveCreature': 'La créature est vivante',
    'key.error.noTreasureHere': 'Ce fragment de la carte ne contient pas d\'Œuf d\'Or. Continuez vos recherches.',
    'key.error.levelTooSmall': 'Vous devez d\'abord améliorer votre personnage',
    'key.error.needHigherLevelForWizardBattles': 'Le niveau {0} est requis pour participer dans les Duels des Magiciens',
    'key.error.artifactBagIsFull': 'Le stockage de artefacts est plein',
    'key.error.notEnoughCoins': 'Vous n\'avez pas assez de pièces',
    'key.error.allFragmentsAreOpen': 'Tous les fragments de la carte mystérieuse sont ouverts',
    'key.error.questAlreadyCompleted': 'La mission est accomplie',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Vous avez déjà reçu un fragment de la carte de cet Obélisque',
    'key.error.portalTooFarAway': 'Le Portail est trop loin',
    'key.error.battleLimitAlreadyEnhanced': 'La limite des combats a déjà été augmentée',
    'key.error.youAreNotAltarOwner': 'Seul le propriétaire de l\'Autel peut le faire',
    'key.error.youAlreadyHaveAltar': 'L\'Autel a déjà été installé',
    'key.error.cantTakeAnotherUsersRune': 'Impossible de récupérer une rune appartenant à un autre joueur',
    'key.error.libraryBlocked': 'Une fois que la réformation sera effectuée, il faudra attendre 3 jours pour utiliser les Bibliothèques.',
    'key.error.notAuthorized': 'L\'utilisateur n\'est pas identifié',
    'key.error.eggOnlyRoost': 'Vous devez donner cet œuf à la Mère des Dragons',
    'key.error.purchase': 'Erreur: {0}',
    'key.error.creatureIsDead': 'D\'abord, vous devez ressusciter la créature',
    'key.error.no_connection': 'Impossible de vous connecter au serveur. Réessayez plus tard.',
    'key.error.protocol_version_mismatch': 'La version du jeu est obsolète, une mise à jour est nécessaire.',
    'key.error.update_application': 'La version du jeu est obsolète, une mise à jour est nécessaire.',
    'key.modal.doYouWantToTransferSingle': 'Êtes-vous sûr de vouloir libérer cette créature ?',
    'key.notification.phoneNotSupportAR': 'Votre appareil n\'est pas compatible avec le régime RA',
    'key.notification.turnOnARPermission': 'Le jeu demande l\'autorisation d\'utiliser la caméra. Autoriser le jeu à accéder à votre caméra dans les réglages.',
    'key.notification.dailyQuestFinished': 'La mission est accomplie !',
    'key.modal.yesBtn': 'Oui',
    'key.modal.noBtn': 'Non',
    'event.log.DAILY_QUEST_COMPLETED': 'Vous avez terminé la mission quotidienne. Votre récompense :',
    'event.log.WEEKLY_QUEST_COMPLETED': 'La chasse est terminée. Votre récompense :',
    'event.log.ENCOUNTER_VICTORY': 'Vous avez vaincu un monstre sauvage !',
    'key.ServiceException.Cause.OLD_CLIENT': 'Votre version du jeu est obsolète, une mise à jour est nécessaire.',
    'key.ServiceException.Cause.AUTH_ERROR': 'L\'authentification a échouée',
    'key.ServiceException.Cause.SESSION_GONE': 'Quelqu\'un s’est connecté à votre compte à partir d\'un autre appareil',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'Le champs avec ID de l\'utilisateur est vide',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Utilisateur introuvable',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Compte suspendu pour jeu malhonnête.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Compte suspendu pour fraudes.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Compte suspendu pour un nom d\'utilisateur inapproprié.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Compte suspendu pour communication agressive avec d\'autres joueurs. ',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Compte suspendu pour jeu malhonnête.',
    'key.ServiceException.Cause.USER_BANNED': 'Le compte est bloqué',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Le sac est plein',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Nombre maximal d’œufs',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Vous n\'avez pas assez de pièces',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Vous n\'avez pas assez de pierres d\'âme',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Vous n\'avez pas assez d\'essence',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Le stockage de créatures est plein',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Cette créature a atteint le niveau maximal',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Impossible de faire évoluer cette créature',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Le nom de votre créature ne doit pas dépasser 14 caractères',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Le nombre maximal de défenseurs pour ce bâtiment est atteint',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Le défenseur du bâtiment ne peut pas devenir votre compagnon',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Votre créature a déjà été assignée à la défense de ce bâtiment',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Erreur',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Combat introuvable',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Erreur',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Votre créature a déjà été assignée à la défense de ce bâtiment',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'L\'Arène est sous la protection de la Bénédiction de la Défense',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Il est encore trop tôt pour collecter les impôts',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Sphère incorrecte',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Bâtiment incorrect',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Accès interdit',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Objet inexistant',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Recette inexistante',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Il n\'est possible d\'installer qu\'un seul Autel',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Il faut d\'abord améliorer votre personnage',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Impossible de commencer la chasse à la créature',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Article inexistant',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Article inexistant',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Bâtiment inexistant',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Créature introuvable',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Créature introuvable',
    'key.ServiceException.Cause.TOO_FAR': 'Le bâtiment est trop loin',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'L\'objet est trop loin',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Le bâtiment est en cours de rechargement',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Le bâtiment est dans la Crevasse d\'Arcana',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Impossible d\'utiliser le bâtiment',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Cocon de dragon introuvable',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Le cocon de dragon est vide',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Le cocon de dragon est occupé',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'L\'œuf n\'a pas été couvé',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'L\'œuf introuvable',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Il vous faut la Mère des Dragons pour couver cet oeuf',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Il n\'y a plus de charges',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Impossible d\'installer le bâtiment',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Vous avez reçu ce mystérieux message car une erreur est survenue',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Le monstre sauvage a échappé',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Aucun monstre sauvage n’a été trouvé',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'L\'appât a déjà été installé sur cette Colonne d\'Abondance',
    'key.ServiceException.Cause.WRONG_ITEM': 'Objet incorrect',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Cette rune est la plus puissante',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Vous n\'avez pas assez de runes de ce niveau',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Cellule incorrecte pour la rune',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Cette cellule est occupée',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'La cellule pour la rune est vide',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Impossible de choisir un défenseur du bâtiment',
    'key.ServiceException.Cause.WRONG_SPELL': 'Incantation incorrecte',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'L\'incantation nécessite plus de runes',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'La nouvelle mission n\'est pas encore disponible',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Vous avez déjà utilisé cet Obélisque',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Tous les fragments de la carte sont déjà ouverts',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Vous ne participez pas à la chasse aux Œufs d\'Or',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Vous avez déjà fouillé ce secteur pour trouver un Œuf d\'Or',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Vous avez déjà utilisé une sucrerie',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'La créature a déjà été capturée',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'La réformation de la créature n\'est pas disponible pour le moment',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'La Bibliothèque n\'est pas disponible pour le moment',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Le serveur ne répond pas. Essayez plus tard.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'La limite des combats a déjà été augmentée',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'La limite des combats a été épuisée.',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Il faut atteindre le niveau 9 pour participer au Duel des Magiciens',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Aucun adversaire trouvé pour le Duel des Magiciens. Réessayez plus tard.',
    'key.ServiceException.Cause.MARKET_ERROR': 'Erreur de la boutique',
    'key.ServiceException.Cause.NO_CHEST': 'Coffre introuvable',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Erreur de délivrance du fragment. Réessayez plus tard.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Vous devez mettre le Cœur du Dragon, ou une collection d’Artefacts de Dragon pour donner plus d\'œufs à Mère des Dragons',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Il y a déjà un œuf dans cette cellule',
    'key.ServiceException.Cause.NO_CONNECTION': 'Aucune connexion Internet',
    'key.ServiceException.Cause.SERVER_DOWN': 'Le serveur du jeu est temporairement indisponible. Veuillez réessayer plus tard.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Le serveur de jeu est en maintenance. Veuillez essayez plus tard.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Vous utilisez déjà ces runes',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Vous vous déplacez trop vite',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Vous avez atteint la limite des Arènes conquises',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Vous avez atteint la limite des Bibliothèques conquises',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Erreur: GPS est indisponible',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Cette incantation ne peut pas être utilisée dans la Crevasse d\'Arcana',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Le temps est écoulé',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'La version du jeu est obsolète. Une mise à jour est nécessaire.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Pas d\'Arènes alliées à portée de vue',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Pas d\'Arènes ennemies à portée de vue',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'sphères',
    'stop.personalized.HEALS': 'potions curatives',
    'stop.personalized.RESURRECTIONS': 'potions de résurrection',
    'stop.personalized.EGGS': 'œufs des créatures',
    'stop.personalized.FOODS': 'sucreries',
    'key.button.cancelPersonal': 'Annuler',
    'key.error.needHigherLevelForSofaBattles': 'Il faut atteindre le niveau {0} pour particier au Duel des Magiciens',
    'fraction.text.youWilLGetBonus': 'Vous bénéficierez de {0} pièces si vous adhérez cette faction',
    'fraction.text.fractionUnavailable': 'La faction n\'est pas disponible pour le moment',
    'fraction.text.chooseYourAlliance': 'Choisissez la faction, aux côtés de laquelle vous allez combattre',
    'fraction.text.redFractionName': 'Ordre rouge',
    'fraction.text.blueFractionName': 'Ordre bleu',
    'key.error.chestTooFarAway': 'Le coffre est trop loin',
    'key.button.openChest': 'Ouvrir',
    'key.candy.MONSTER_WATER_1': 'pierres de Crapaudius',
    'key.candy.MONSTER_WATER_2': 'pierres de Guth',
    'key.candy.MONSTER_WATER_3': 'pierres de Spiritus',
    'key.candy.MONSTER_WATER_4': 'pierres d\'Aquin',
    'key.candy.MONSTER_WATER_8': 'pierres de Jellyhat',
    'key.candy.MONSTER_WATER_9': 'pierres de Minori',
    'key.candy.MONSTER_WATER_10': 'pierres d\'Inphalisque',
    'key.candy.MONSTER_WATER_12': 'pierres de Dadachoc',
    'key.candy.MONSTER_WATER_13': 'pierres de Batoїde',
    'key.candy.MONSTER_WATER_23': 'pierres de Blinderius',
    'key.candy.MONSTER_WATER_24': 'pierres de Neptune',
    'key.candy.MONSTER_WATER_25': 'pierres de Léviathan',
    'key.candy.MONSTER_FIRE_1': 'pierres de Potty',
    'key.candy.MONSTER_FIRE_2': 'pierres de Mommiewin',
    'key.candy.MONSTER_FIRE_3': 'pierres de Vaporino',
    'key.candy.MONSTER_FIRE_4': 'pierres d\'Incumus',
    'key.candy.MONSTER_FIRE_6': 'pierres de Flamy',
    'key.candy.MONSTER_FIRE_7': 'pierres de Phoby',
    'key.candy.MONSTER_FIRE_11': 'pierres d\'Etincelle',
    'key.candy.MONSTER_FIRE_12': 'pierres de Khydra',
    'key.candy.MONSTER_FIRE_15': 'pierres de Pikhot',
    'key.candy.MONSTER_FIRE_25': 'pierres de Smaugre',
    'key.candy.MONSTER_EARTH_1': 'pierres de Fruidzilla',
    'key.candy.MONSTER_EARTH_2': 'pierres de Fleurette',
    'key.candy.MONSTER_EARTH_3': 'pierres de Feuillux',
    'key.candy.MONSTER_EARTH_4': 'pierres de Browny',
    'key.candy.MONSTER_EARTH_8': 'pierres de Disghuir',
    'key.candy.MONSTER_EARTH_9': 'pierres de Belflow',
    'key.candy.MONSTER_EARTH_10': 'pierres de Glandoux',
    'key.candy.MONSTER_EARTH_11': 'pierres de Phylo',
    'key.candy.MONSTER_EARTH_13': 'pierres de Princie',
    'key.candy.MONSTER_EARTH_25': 'pierres de Scylla',
    'key.candy.MONSTER_DUNGEON_1': 'pierres de Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'pierres d\'Axolan',
    'key.candy.MONSTER_DUNGEON_3': 'pierres de Crampondo',
    'key.candy.MONSTER_DUNGEON_4': 'pierres de Maglad',
    'key.candy.MONSTER_DUNGEON_5': 'pierres de Chatmix',
    'key.candy.MONSTER_DUNGEON_6': 'pierres de Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'pierres de Vampiro',
    'key.candy.MONSTER_DUNGEON_13': 'pierres de Chenillou',
    'key.candy.MONSTER_DUNGEON_17': 'pierres d\'Aynur',
    'key.candy.MONSTER_WIND_1': 'pierres de SunTzi',
    'key.candy.MONSTER_WIND_2': 'pierres d\'Оreyor',
    'key.candy.MONSTER_WIND_3': 'pierres de Gribbie',
    'key.candy.MONSTER_WIND_4': 'pierres de Fluffycorne',
    'key.candy.MONSTER_WIND_6': 'pierres de Gamaïoun',
    'key.candy.MONSTER_WIND_7': 'pierres d\'Horrificus',
    'key.candy.MONSTER_WIND_11': 'pierres d\'Infird',
    'key.candy.MONSTER_WIND_12': 'pierres d\'Ondine',
    'key.candy.MONSTER_WIND_15': 'pierres de Cheshire',
    'key.candy.MONSTER_WIND_25': 'pierres de Charybde',
    'key.button.leaveDungeon': 'Quitter la Crevasse',
    'key.alias.enterNewAlias': 'Saisissez le nom de la créature',
    'key.alias.enterText': 'Saisissez le texte...',
    'key.hut.hutName': 'Mère des Dragons',
    'key.hut.hutDescr': 'Donnez les œufs anciens à la Mère des Dragons pour les couver',
    'key.text.noHutEggs': 'Vous n\'avez pas d\'œufs anciens',
    'key.text.noCapturedArenas': 'Vous n\'avez pas d\'Arènes conquises',
    'key.text.noChosenPet': 'Vous n\'avez pas choisi votre compagnon',
    'key.text.noArtifacts': 'Vous n\'avez pas d\'artefacts',
    'key.text.noCreatures': 'Vous n\'avez pas de créatures',
    'key.text.noLureItems': 'Vous n\'avez pas d\'appât',
    'key.descr.aboutWizardBattles': 'Participez aux Duels contre les autres joueurs pour recevoir l\'expérience et la récompense',
    'key.text.writeToSupport': 'Contacter l\'assistance',
    'key.text.regUsingFacebook': 'S\'inscrire via Facebook',
    'key.text.regUsingGoogle': 'S\'inscrire via Google',
    'key.text.logUsingFacebook': 'S\'identifier via Facebook',
    'key.text.logUsingGoogle': 'S\'identifier via Google',
    'key.text.logUsingDeviceIDCurrent': 'S\'identifier via Device ID',
    'key.text.logUsingDeviceIDNew': 'S\'identifier via Device ID (nouveau compte)',
    'key.text.createAccount': 'Jouer',
    'key.text.connectedToFacebook': 'Connecté à Facebook',
    'key.text.connectedToGoogle': 'Connecté à Google',
    'key.text.complainAboutPoint': 'Signaler ce point',
    'key.text.copyCoordinates': 'Copier les coordonnées',
    'key.text.complainEnterEmail': 'Votre e-mail',
    'key.text.complainEnterText': 'Spécifiez votre problème',
    'key.modal.doYouWantToCloseApp': 'Voulez-vous fermer l\'application ?',
    'key.catchPopup.notBad': 'Bien !',
    'key.catchPopup.good': 'Très bien !',
    'key.catchPopup.sumptuously': 'Génial !',
    'key.catchPopup.twistedThrow': 'Tir courbé !',
    'key.battlePopup.strongHit': 'Bon tir !',
    'key.battlePopup.weakHit': 'Coup faible',
    'key.battlePopup.dodge': 'Esquive !',
    'key.battlePopup.chargedAttack': '{0} utilise {1}',
    'auth.login.play': 'Jouer',
    'auth.login.nickname.placeholder': 'Saisissez le nom',
    'auth.login.nickname.busy': 'Ce nom est déjà pris',
    'auth.login.nickname.proposal': 'Vous pouvez utiliser le nom suivant :',
    'auth.login.nickname.deviceId': 'Vous avez déjà créé un personnage',
    'auth.login.social.title': 'Se connecter via une réseau social',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Connecté à {0}',
    'auth.login.social.signOut': 'Quitter',
    'auth.login.signOut.confirmation': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'auth.login.social.userCancelledError': 'Annuler la connexion',
    'auth.login.social.cantSignInError': 'Impossible de se connecter à {0}',
    'licence.title': 'CONDITIONS D\'UTILISATION DU JEU DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Envoyez-moi des actualités et des offres par e-mail',
    'licence.accept': 'Accepter',
    'licence.decline': 'Refuser',
    'key.error.wrongRoostIndex': 'La cellule n\'est pas disponible',
    'key.speed.toMachSpeed': 'Vous vous déplacez trop vite. Ne jouez pas à Draconius GO: Catch a Dragon! en conduisant - c\'est dangereux.',
    'key.speed.passenger': 'Je suis passager',
    'key.activeObjects.addUnit.question': 'Êtes-vous sûr de vouloir désigner {0} comme protecteur de ce bâtiment ?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Êtes-vous sûr de vouloir choisir cette faction ? Ce choix ne peut pas être modifié à l\'avenir.',
    'key.confirm.giveUpEncounter': 'Êtes-vous sûr de vouloir refuser de vous battre contre un monstre sauvage ?',
    'key.confirm.giveUpBattle': 'Êtes-vous sûr de vouloir vous rendre et finir le combat ?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nouvelle Ligue !',
};
