module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Ano',
    'key.button.cancel': 'ZRUŠIT',
    'key.button.apply': 'ОК',
    'key.button.use': 'Použít',
    'key.button.buy': 'Koupit',
    'key.beCarefulMessage.text': 'Buďte opatrní při hraní. Dívejte se kolem sebe.',
    'key.creature.details.attack': 'Síla',
    'key.creature.details.health': 'Zdraví',
    'key.creature.details.powerUp': 'Posílení',
    'key.creature.details.evolve': 'Přeměna',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'CP {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'UVOLNIT',
    'key.creature.details.creadex': 'Bestiář',
    'key.creature.registration.creadex': 'Přidáno do Bestiáře',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Dobyté budovy',
    'key.activeObjects.library': 'Přeškolení bytosti v Knihovně',
    'key.activeObjects.library.empty': 'Nejsou dobyté Knihovny',
    'key.activeObjects.arena': 'Vybírání daní z Arén',
    'key.activeObjects.arena.collect': 'Vybrat',
    'key.activeObjects.arena.empty': 'Nejsou dobyté Arény',
    'key.activeObjects.error.timer': 'Vybírání dani je nedostupné. Je třeba počkat',
    'key.activeObjects.error.noMoney': 'Nejdříve je zapotřebí obsadit Arénu',
    'key.activeObjects.error.cannotRemaster': 'Přeškolení není možné. Pro zrychlení časovače přeškolení dobývejte Knihovny.',
    'key.activeObjects.library.remaster': 'Přeškolit',
    'key.activeObjects.library.blocked': 'Knihovny nejsou k dispozici',
    'key.activeObjects.remaster.confirmation.main': 'Opravdu chcete přeškolit {0}? Hlavní dovednost {1} bude nahrazena!',
    'key.activeObjects.remaster.confirmation.charged': 'Opravdu chcete přeškolit {0}? Dobíjecí dovednost {1} bude nahrazena.',
    'key.activeObjects.remaster.error': 'Chyba',
    'key.activeObjects.item.weaklyBonus': 'Týdenní bonus + {0} mince',
    'key.library.remaster.selectCreature': 'Vyberte bytost, kterou chcete přeškolit',
    'key.remasterPanel.title': 'Vyberte dovednost pro nahrazení',
    'key.storage.creatues': 'Bytosti',
    'key.storage.eggs': 'Vejce',
    'key.storage.eggs.simple': 'Obyčejné vejce',
    'key.storage.eggs.super': 'Starobylé vejce',
    'key.storage.eggs.missingAny': 'Nemáte vejce bytostí',
    'key.startEgg.button': 'Umístit do kokonu',
    'key.startEgg.description': 'Použijte dračí kokon, abyste vyseděli toto vejce',
    'key.startEgg.incubator.title': 'Dračí kokony',
    'key.startEgg.select.title': 'Vyberte si vejce',
    'key.openEgg.button': 'Vylíhnout vejce',
    'key.openEgg.description': 'Nová bytost se nyní vylíhne z vejce',
    'key.startEgg.description.roost.hatching': 'Matka Draků vysedává toto vejce. Musíme jen počkat. Vysedávání se přeruší, pokud zmizí Zlom Arkany, ve kterém se nacházela Matka Draků.',
    'key.startEgg.description.roost.notHatching': 'Dejte to vejce Matce Draků, aby ho vyseděla pro vás.',
    'key.startEgg.description.simple.hatching': 'Toto vejce je ve dračím kokonu. Pokud chcete pomoct mu se vyklubat, nevypínejte hru.',
    'key.startEgg.description.simple.notHatching': 'Umístěte toto vejce do dračího kokonu pro spuštění vysedávání. Vejce se vyklube, až projdete nutnou vzdálenost.',
    'key.mainMenu.wizardDuels': 'SOUBOJ MÁGŮ',
    'key.mainMenu.quests': 'ÚKOLY',
    'key.mainMenu.activePoints': 'DOBYTÉ',
    'key.mainMenu.creadex': 'BESTIÁŘ',
    'key.mainMenu.magic': 'MAGIE',
    'key.mainMenu.creatues': 'BYTOSTI',
    'key.mainMenu.shop': 'KRÁMEK',
    'key.mainMenu.backpack': 'TAŠKA',
    'key.error.banned': 'Účet je zablokovaný',
    'event.log.CREATURE_CAUGHT': '{0} je chycen!',
    'event.log.ITEM_BOUGHT': '{0} x{1} byl koupen. Utraceno {2} mincí',
    'event.log.ARTIFACT_BOUGHT': 'Byl koupen artefakt: {0}. Utraceno {1} mincí',
    'event.log.EGG_HATCHED': '{0} vyklubal se z {1} vejce!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'zlatého',
    'event.log.ROOST_EGG_HATCHED': 'Matka Draků vyseděla {1} vejce. {0} je teď váš!',
    'event.log.CHEST_OPENED': 'V truhle bylo nalezeno:',
    'event.log.ARENA_LOST_CONTROL': '{1} byl vyhozen z budovy: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} byl vyhozen z budovy: {0}',
    'event.log.LEVEL_UP': 'Dosáhli jste úrovně {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Domácí mazlíček objevil {0}',
    'event.log.QUEST_COMPLETED': 'Odměna za quest {0}',
    'event.log.ENCOUNTER_LOOSE': 'Utekli jste od divokého monstra',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Limit bitev v Souboji Mágů byl zvýšený o {0} mincí',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} mincí bylo nakoupeno za {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Taška byla vylepšena za {0} mincí',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Skladiště bytostí bylo vylepšeno za {0} mincí',
    'key.shop.accesories': 'PŘEDMĚTY',
    'key.shop.artifacts': 'ARTEFAKTY',
    'key.shop.donate': 'MINCE',
    'key.shop.upgrade': 'VYLEPŠENÍ',
    'key.shop.donate.coins': '{0} mincí',
    'key.shop.upgrade.bag': 'Rozšíření tašky',
    'key.shop.upgrade.bag.desc': 'Velikost tašky se zvýší o 50',
    'key.shop.upgrade.storage': 'Rozšíření skladiště bytostí',
    'key.shop.upgrade.storage.desc': 'Velikost skladiště bytostí se zvýší o 50',
    'key.shop.donate.dialog.title': 'Chybějí mince',
    'key.shop.donate.dialog.desc': 'Získejte je zde nebo navštivte Krámek, kde naleznete další možnosti',
    'key.potionUseMenu.title': 'Léčebné lektvary',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Vytváří Portál do světa Arkany.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Všichni hráči kolem pocítí zuřivost leprikónů',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Na 30 minut vytváří pole Sloupů Hojnosti',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Na 30 minut zdvojnásobuje množství odměn ze Sloupů Hojnosti',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Dlouhým kliknutím na terén ho prosvítíš při vyhledávání bytostí',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Na 30 minut zvětšuje dosah objevení bytostí',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Na 7 dnů zvětšuje poloměr výhledu o 30%',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'Nejbližší spojenecká Aréna nebude přístupná pro útok nepřáteli během 30 hodin',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Všechny nepřátelské Arény v dosahu viditelnosti se stanou neutrálními. Odstraňuje Požehnání obrany.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Vytváří magickou věž, která přitahuje bytosti ohnivého živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Vytváří magickou věž, která přitahuje bytosti vodního živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Vytváří magickou věž, která přitahuje bytosti vzdušného živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Vytváří magickou věž, která přitahuje bytosti zemského živlu',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Vytváří magickou věž, která přitahuje bytosti živlu Arkany',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Zlom Arkany',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Zuřivost leprikónů',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Pole Hojnosti',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Dar Zlatého Draka',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astrální vidění',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Dračí zrak',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Dlouhé ruce',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Požehnání obrany',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Očištění ohněm',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Ohnivá věž',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Vodní věž',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Vzdušná věž',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Zěmská věž',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Věž Arkany',
    'key.buff.ATTACKER_CP_BOOST': 'CP vašich bytostí bylo dočasně zvýšeno',
    'key.buff.BEST_BALL_LUCK': 'Jenom nejlepší sféry v Sloupech Hojnosti během 30 min',
    'key.buff.BEST_POTION_LUCK': 'Jenom nejlepší lektvary v Sloupech Hojnosti během 30 min',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 předměta ze Sloupů Hojnosti během 30 min',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Čas do přeškolení v Knihovně je snížen o {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Čas do vybírání daní z Arény je snížen o {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Zvyšuje CP netvorů, kteří nejsou obránci budov',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Ze Sloupů Hojnosti získáváte jenom nejlepší sféry, které jsou k dispozici pro vaši úroveň',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Ze Sloupů Hojnosti získáváte jenom nejlepší lektvary, které jsou k dispozici pro vaši úroveň',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Dostanete dva předměty navíc ze Sloupů Hojnosti',
    'key.loot.result.dust': 'Esence',
    'key.loot.result.exp': 'Zkušenost postavy',
    'key.loot.result.coin': 'Mince',
    'key.loot.result.candy': 'kameny',
    'key.item.MAGIC_BALL_SIMPLE': 'Sféra učně',
    'key.item.MAGIC_BALL_NORMAL': 'Sféra magistra',
    'key.item.MAGIC_BALL_GOOD': 'Sféra vládce',
    'key.item.LURE': 'Návnada',
    'key.item.INCENSE': 'Feromony',
    'key.item.EGG': 'Vejce',
    'key.item.SHOVEL': 'Lopata',
    'key.item.POTION_HEAL_1': 'Malý léčebný lektvar',
    'key.item.POTION_HEAL_2': 'Střední léčebný lektva',
    'key.item.POTION_HEAL_3': 'Velký léčebný lektvar',
    'key.item.POTION_HEAL_4': 'Lektvar úplného uzdravení',
    'key.item.POTION_RESURRECTION_1': 'Lektvar oživení',
    'key.item.POTION_RESURRECTION_2': 'Velký lektvar oživení',
    'key.item.INCUBATOR_1': 'Dračí kokon',
    'key.item.INCUBATOR_3': 'Dračí kokon',
    'key.item.INCUBATOR_PERPETUAL': 'Věčný dračí kokon',
    'key.item.SUPER_VISION': 'Dračí zrak',
    'key.item.RUNE_1': 'Runa I',
    'key.item.RUNE_2': 'Runa II',
    'key.item.RUNE_3': 'Runa III',
    'key.item.RUNE_4': 'Runa IV',
    'key.item.RUNE_5': 'Runa V',
    'key.item.RUNE_6': 'Runa VI',
    'key.item.FOOD_CATCH_CHANCE': 'Arkanický karamel',
    'key.item.FOOD_MORE_DUST': 'Magická kobliha',
    'key.item.FOOD_CALM_DOWN': 'Marshmallow jednorožce',
    'key.item.FOOD_MORE_CANDIES': 'Zmrzlina čtyř živlů',
    'key.item.EXPERIENCE_BOOSTER': 'Krystal moudrosti',
    'key.item.EGG_KM_0': 'Zlaté Vejce',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sféra pro chycení bytostí.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sféra pro chycení bytostí. Trochu zvyšuje šanci na chycení.',
    'key.item.MAGIC_BALL_GOOD.description': 'Sféra pro chycení bytostí. Hodně zvyšuje šanci na chycení.',
    'key.item.LURE.description': 'Nástraha pro bytosti. Vložte do Sloupu Hojnosti pro přilákání bytostí k němu.',
    'key.item.INCENSE.description': 'Feromony k Vám přilákají bytosti určitého živlu podle dne v týdnu.',
    'key.item.EGG.description': 'Používejte dračí kokon pro vysezení bytosti z vejce',
    'key.item.SHOVEL.description': 'Lopaty jsou naprosto nenahraditelné při hledání pokladů',
    'key.item.POTION_HEAL_1.description': 'Vyléčí bytost o 200 jednotek zdraví',
    'key.item.POTION_HEAL_2.description': 'Vyléčí bytost o 500 jednotek zdraví',
    'key.item.POTION_HEAL_3.description': 'Vyléčí bytost o 1000 jednotek zdraví',
    'key.item.POTION_HEAL_4.description': 'Úplně vyléčí bytost',
    'key.item.POTION_RESURRECTION_1.description': 'Oživí zvolenou bytost. Po vzkříšení bytost bude poraněná.',
    'key.item.POTION_RESURRECTION_2.description': 'Oživí a úplně vyléčí bytost',
    'key.item.INCUBATOR_1.description': 'Dračí kokony jsou nutné pro vysezení bytostí z vajec. Mizí po použití.',
    'key.item.INCUBATOR_3.description': 'Dračí kokony jsou nutné pro vysezení bytostí z vajec. Mizí po 3 použití',
    'key.item.INCUBATOR_PERPETUAL.description': 'Dračí kokony jsou nutné pro vysezení bytostí z vajec.',
    'key.item.SUPER_VISION.description': 'Ukazuje bytosti ve velké oblasti',
    'key.item.RUNE_1.description': 'Magická runa 1. úrovně',
    'key.item.RUNE_2.description': 'Magická runa 2. úrovně',
    'key.item.RUNE_3.description': 'Magická runa 3. úrovně',
    'key.item.RUNE_4.description': 'Magická runa 4. úrovně',
    'key.item.RUNE_5.description': 'Magická runa 5. úrovně',
    'key.item.RUNE_6.description': 'Magická runa 6. úrovně',
    'key.item.FOOD_CATCH_CHANCE.description': 'Lahůdka pro chycení bytostí. Zvyšuje šanci zachytit bytost magickou sférou',
    'key.item.FOOD_MORE_DUST.description': 'Lahůdka pro chycení bytostí. Zvyšuje množství esencí, které dostaneme za chycení',
    'key.item.FOOD_CALM_DOWN.description': 'Lahůdka pro chycení bytostí. Uklidňuje bytost a ta přestává skákat a útočit',
    'key.item.FOOD_MORE_CANDIES.description': 'Lahůdka pro chycení bytostí. Zvyšuje množství kamenů duší, které dostaneme za chycení',
    'key.item.EXPERIENCE_BOOSTER.description': 'Na 30 minut zdvojnásobuje získanou zkušenost',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Maska kouzelníka',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': 'Možnost posadit bytost do Arény nebo Knihovny na dálku 1krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Tento artefakt umožňuje posadit svou bytost na volné místo do Arény nebo Knihovny viditelné na mapě 1krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Tvář věštce',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': 'Možnost posadit bytost do Arény nebo Knihovny na dálku 2krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Tento artefakt umožňuje posadit svou bytost na volné místo do Arény nebo Knihovny viditelné na mapě 2krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Přilba dobyvatele',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': 'Možnost posadit bytost do Arény nebo Knihovny na dálku 3krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Tento artefakt umožňuje posadit svou bytost na volné místo do Arény nebo Knihovny viditelné na mapě 3krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Přilba hrdiny',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': 'Možnost posadit bytost do Arény nebo Knihovny na dálku 4krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Tento artefakt umožňuje posadit svou bytost na volné místo do Arény nebo Knihovny viditelné na mapě 4krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Přilba bojovníka s draky',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': 'Možnost posadit bytost do Arény nebo Knihovny na dálku 5krát během dne',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Tento artefakt umožňuje posadit svou bytost na volné místo do Arény nebo Knihovny viditelné na mapě 5krát během dne',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Prapor vládce',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Dovoluje posadit do Arény nebo Knihovny ještě jednu bytost',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'S tímto artefaktem lze dát do ochrany Arény nebo Knihovny dvě bytosti místo jedné',
    'key.artifact.ARTIFACT_BANK_8': 'Vyříznutý artefakt',
    'key.artifact.ARTIFACT_BANK_8.description': 'Jak jste ho vůbec našli?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Uviděli jste artefakt, který byste neměli vidět. Nyní se vás musíme zbavit jako svědka.',
    'key.artifact.ARTIFACT_BANK_9': 'Vyříznutý artefakt',
    'key.artifact.ARTIFACT_BANK_9.description': 'Jak jste ho vůbec našli?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Uviděli jste artefakt, který byste neměli vidět. Nyní se vás musíme zbavit jako svědka.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Hodinky líného studenta',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 sekund k znovunabití Sloupů Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'S tímto artefaktem Sloupy Hojnosti se budou znovu nabíjet o 20 sekund rychleji a budete moci je používat častěji.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Budík člověka, který vždy chodí pozdě',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 sekund k znovunabití Sloupů Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'S tímto artefaktem Sloupy Hojnosti se budou znovu nabíjet o 40 sekund rychleji a budete moci je používat častěji.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Prostorový urychlovač',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 sekund k znovunabití Sloupů Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'S tímto artefaktem Sloupy Hojnosti se budou znovu nabíjet o 60 sekund rychleji a budete moci je používat častěji.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Hodinky líného profesora',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 sekund k znovunabití Sloupů Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'S tímto artefaktem Sloupy Hojnosti se budou znovu nabíjet o 80 sekund rychleji a budete moci je používat častěji.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Hodinky zebro-králíka',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 sekund k znovunabití Sloupů Hojnosti',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'S tímto artefaktem Sloupy Hojnosti se budou znovu nabíjet o 100 sekund rychleji a budete moci je používat častěji.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Žezlo dobyvatele',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 k úrovni Arény nebo Knihovny po dobytí',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Pokud majitel toho artefaktu posadí bytost do dobyté Arény nebo Knihovny jako první, ona ihned dostane 5. úroveň místo 3.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Prsten výběrčího daní',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 k maximálnímu počtu dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'S tímto artefaktem můžete vybírat daň z 11 Arén místo obyčejných 10.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Prsten lakoty',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 k maximálnímu počtu dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'S tímto artefaktem můžete vybírat daň z 12 Arén místo obyčejných 10.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Dvojitý prsten',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 k maximálnímu počtu dobytých Arén',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'S tímto artefaktem můžete vybírat daň z 13 Arén místo obyčejných 10.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Pohár hltouna koláčů',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% k slávě svazových Arén a Knihoven při výcviku',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'S tímto artefaktem svazové Arény a Knihovny dostávají o 20% více slávy, když je trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Kalich na med',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% k slávě svazových Arén a Knihoven při výcviku',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'S tímto artefaktem svazové Arény a Knihovny dostávají o 30% více slávy, když je trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Číše hlubokých myšlenek',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% k slávě svazových Arén a Knihoven při výcviku',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'S tímto artefaktem svazové Arény a Knihovny dostávají o 40% více slávy, když je trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Grál Lanselopa',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% k slávě svazových Arén a Knihoven při výcviku',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'S tímto artefaktem svazové Arény a Knihovny dostávají o 50% více slávy, když je trénujete',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Pohár dobyvatele příšer',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% k slávě svazových Arén a Knihoven při výcviku',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'S tímto artefaktem svazové Arény a Knihovny dostávají o 80% více slávy, když je trénujete',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem jasného vidění',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Odstraňuje slabé bytosti z radaru',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Tento artefakt odstraňuje slabší bytosti z radaru, což pomáhá se soustředit na hledání silných exemplářů',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Kniha pravidel dobrodruha',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minut k vybírání daní z Arény po jejím dobytí nepřítelem',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'S tím artefaktem Arény jsou přístupné pro vybírání daní ještě během 30 minut po jejich dobytí, místo obyčejných 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Tlustá solidní kniha',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minut k vybírání daní z Arény po jejím dobytí nepřítelem',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'S tím artefaktem Arény jsou přístupné pro vybírání daní ještě během 45 minut po jejich dobytí, místo obyčejných 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Deska nároků',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minut k vybírání daní z Arény po jejím dobytí nepřítelem',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'S tím artefaktem Arény jsou přístupné pro vybírání daní ještě během 60 minut po jejich dobytí, místo obyčejných 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Traktát o vládnutí',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minut k vybírání daní z Arény po jejím dobytí nepřítelem',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'S tím artefaktem Arény jsou přístupné pro vybírání daní ještě během 90 minut po jejich dobytí, místo obyčejných 15 minut',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoár autority',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minut k vybírání daní z Arény po jejím dobytí nepřítelem',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'S tím artefaktem Arény jsou přístupné pro vybírání daní ještě během 120 minut po jejich dobytí, místo obyčejných 15 minut',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Obojek s ostny',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% zrychlení dobytí kamenů duší od domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'S tímto artefaktem budete moci překonávat o 10% menší vzdálenost s domácím mazlíčkem, abyste dostali kamene duší. Také dělá domácího mazlíčka o 17% hroznější',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Mrkev na hůlce',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% zrychlení dobytí kamenů duší od domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'S tímto artefaktem budete moci překonávat o 15% menší vzdálenost s domácím mazlíčkem, abyste dostali kamen duší. To je dobrota!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Kartáč na zádíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% zrychlení dobytí kamenů duší od domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'S tímto artefaktem budete moci překonávat o 25% menší vzdálenost s domácím mazlíčkem, abyste dostali kamen duší. Skloň se před mocí kartáče na zádíčka!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Rolnička domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% zrychlení dobytí kamenů duší od domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'S tímto artefaktem budete moci překonávat o 30% menší vzdálenost s domácím mazlíčkem, abyste dostali kamen duší. Kdopak je náš pěkný chlapeček?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Plyšový dráček',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% zrychlení dobytí kamenů duší od domácího mazlíčka',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'S tímto artefaktem budete moci překonávat o 40% menší vzdálenost s domácím mazlíčkem, abyste dostali kamen duší. Nejlepší hračka na světě pro nejlepší domácí zvířátko',
    'key.artifact.ARTIFACT_ROOST_1': 'Dračí srdce',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 dračí kokon u Matky Draků',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Umožňuje použití dodatečného dračího kokonu na vejce u Matky Draků',
    'dialog.artifact.select_artifact': 'VYBERTE ARTEFAKT',
    'dialog.artifact.confirm.remove': 'Opravdu chcete odstranit artefakt?',
    'dialog.items.title': 'TAŠKA',
    'dialog.items.cannotUse': 'Tento předmět se nedá používat',
    'dialog.items.remove.header': 'Odstranění předmětů',
    'dialog.encounter.header': 'Divoká příšera útočí!',
    'dialog.encounter.button.leave': 'Utéct',
    'dialog.encounter.button.fight': 'Bojovat',
    'dialog.encounter.result.outcome.win': 'Divoká příšera je poražena',
    'dialog.encounter.result.outcome.lose': 'Vaše bytost je poražena',
    'dialog.encounter.result.reward.dust': 'Esence',
    'dialog.encounter.result.reward.exp': 'Zkušenost',
    'error.nickname.validation.IS_EMPTY': 'Je třeba zadat jméno postavy',
    'error.nickname.validation.TOO_SHORT': 'Jméno musí být minimálně 3 až 16 znaků',
    'error.nickname.validation.TOO_LONG': 'Jméno musí být minimálně 3 až 16 znaků',
    'error.nickname.validation.INVALID_CHAR': 'Lze používat pouze písmena, číslice a podtržítka.',
    'error.nickname.validation.DUPLICATE': 'Zvolené jméno už je obsazené. Můžete si vzít jméno {0}',
    'creature.MONSTER_WATER_1': 'Ropuchus',
    'creature.MONSTER_WATER_2': 'Kapka',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Akvin',
    'creature.MONSTER_WATER_5': 'Ropuchissimo',
    'creature.MONSTER_WATER_6': 'Potůček',
    'creature.MONSTER_WATER_7': 'Vodník',
    'creature.MONSTER_WATER_8': 'Jellyhat',
    'creature.MONSTER_WATER_9': 'Minori',
    'creature.MONSTER_WATER_10': 'Infalisk',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadačik',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisk',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahat',
    'creature.MONSTER_WATER_17': 'Akvar',
    'creature.MONSTER_WATER_18': 'Dadačum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Bazilišek',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Krystalium',
    'creature.MONSTER_WATER_23': 'Brněnius',
    'creature.MONSTER_WATER_24': 'Neptun',
    'creature.MONSTER_WATER_25': 'Leviatan',
    'creature.MONSTER_FIRE_1': 'Potti',
    'creature.MONSTER_FIRE_2': 'Mummyvin',
    'creature.MONSTER_FIRE_3': 'Steampal',
    'creature.MONSTER_FIRE_4': 'Inkumus',
    'creature.MONSTER_FIRE_5': 'Ohnitlap',
    'creature.MONSTER_FIRE_6': 'Flamy',
    'creature.MONSTER_FIRE_7': 'Foubi',
    'creature.MONSTER_FIRE_8': 'Dammivin',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Kamna',
    'creature.MONSTER_FIRE_11': 'Jiskra',
    'creature.MONSTER_FIRE_12': 'Kydra',
    'creature.MONSTER_FIRE_13': 'Démonstar',
    'creature.MONSTER_FIRE_14': 'Ohnivák',
    'creature.MONSTER_FIRE_15': 'Needlehot',
    'creature.MONSTER_FIRE_16': 'Železný chlap',
    'creature.MONSTER_FIRE_17': 'Světluška',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Záblesk',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Salute',
    'creature.MONSTER_FIRE_24': 'Pikkarun',
    'creature.MONSTER_FIRE_25': 'Smaugr',
    'creature.MONSTER_EARTH_1': 'Bobulillo',
    'creature.MONSTER_EARTH_2': 'Květek',
    'creature.MONSTER_EARTH_3': 'Lístek',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Šamurf',
    'creature.MONSTER_EARTH_6': 'Dryáda',
    'creature.MONSTER_EARTH_7': 'Klíček',
    'creature.MONSTER_EARTH_8': 'Disguir',
    'creature.MONSTER_EARTH_9': 'Belflou',
    'creature.MONSTER_EARTH_10': 'Žaluden',
    'creature.MONSTER_EARTH_11': 'Filo',
    'creature.MONSTER_EARTH_12': 'Brah',
    'creature.MONSTER_EARTH_13': 'Prinsi',
    'creature.MONSTER_EARTH_14': 'Šiškán',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Troll',
    'creature.MONSTER_EARTH_17': 'Dvant',
    'creature.MONSTER_EARTH_18': 'Čappian',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'Springa',
    'creature.MONSTER_EARTH_21': 'Zeměvos',
    'creature.MONSTER_EARTH_22': 'Zvěrokvět',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Uchomych',
    'creature.MONSTER_WIND_3': 'Houbi',
    'creature.MONSTER_WIND_4': 'Chlupatoroh',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Hamajun',
    'creature.MONSTER_WIND_7': 'Strašan',
    'creature.MONSTER_WIND_8': 'Ucholot',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Vítrotanec',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Bouřkoroh',
    'creature.MONSTER_WIND_14': 'Fantomo',
    'creature.MONSTER_WIND_15': 'Cheshire',
    'creature.MONSTER_WIND_16': 'Houbtopia',
    'creature.MONSTER_WIND_17': 'Harpyje',
    'creature.MONSTER_WIND_18': 'Přízrakus',
    'creature.MONSTER_WIND_19': 'Puerogryph',
    'creature.MONSTER_WIND_20': 'Polštářkocour',
    'creature.MONSTER_WIND_21': 'Hippolet',
    'creature.MONSTER_WIND_22': 'Uragánna',
    'creature.MONSTER_WIND_23': 'Gryf',
    'creature.MONSTER_WIND_24': 'Bajun',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Rookie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Ostenzád',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Milokocour',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Strašák',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Džin',
    'creature.MONSTER_DUNGEON_12': 'Vampiro',
    'creature.MONSTER_DUNGEON_13': 'Housen',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Ocásek',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Dracool',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tygromant',
    'creature.MONSTER_DUNGEON_21': 'Ostrocas',
    'creature.MONSTER_DUNGEON_22': 'Poupě',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Mantikora',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Žraločí uštknutí',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Hrůza z hloubky',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Volání Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Mořské kladivo',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Vodní pěst',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Vlna',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Liják',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Gejzír',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Spršky',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Živý plamen',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Ohnivý prst',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Ohnivý prst',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Ohnivá koule',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Spalovač na popel',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Hvězda',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Uhlí',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Plamenomet',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Zastřelení',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Vzdušný srp',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Roztrhávač',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Dýchání',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Elektrický šok',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Kulový blesk',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Šoková terapie',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Dračí vzdech',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Závan',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Zuřivost větru',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Jedovaté plivnutí',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Hadí špičák',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Otrava',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Hřbetolom',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Skála',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Valoun',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Lesní duch',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Přízrak stromu',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Stín přírody',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Šíp Arkany',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Shluk tmy',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Chapadlo zla',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Oko hrůzy',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sféra smrti',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Koule tmy',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arkana Kadavra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarkus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Imperikanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Zalednění',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Zamražení',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Krystalizace',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Vír',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Sněhová bouře',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Studená zuřivost',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Ledový výbuch',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Ledová moc',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Vyčištění',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Pozvednutí',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Vypálení',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Láva',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Proud ohně',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteory',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocid',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armagedon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Blesk',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Hrom',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Bouřka',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Přetížení',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Elektrické pole',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Vlasy se ježí',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornádo',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Řev větru',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Kolotoč',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Hřmot',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Třesení',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Zlom',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Ztroskotání',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Výbuch',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Kamenná vichřice',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Jezero smrti',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Jedovatá louže',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Kyselina',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomizace',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Dezintegrace',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ionizace',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Vyhnání',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Prokletí',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Vyloučení',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Magická bouřka',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Bouřka many',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Hněv Arkany',
    'key.combined.first.1': 'Moudrých',
    'key.combined.first.2': 'Pekelných',
    'key.combined.first.3': 'Skvělých',
    'key.combined.first.4': 'Zlostných',
    'key.combined.first.5': 'Neutrálních',
    'key.combined.first.6': 'Čestných',
    'key.combined.first.7': 'Svatých',
    'key.combined.first.8': 'Starobylých',
    'key.combined.first.9': 'Podzemních',
    'key.combined.first.10': 'Ohnivých',
    'key.combined.first.11': 'Šikovných',
    'key.combined.first.12': 'Obrovských',
    'key.combined.first.13': 'Modrých',
    'key.combined.first.14': 'Krutých',
    'key.combined.first.15': 'Dobrých',
    'key.combined.first.16': 'Vzdušných',
    'key.combined.first.17': 'Zemních',
    'key.combined.first.18': 'Červených',
    'key.combined.first.19': 'Nesmrtelných',
    'key.combined.first.20': 'Zahynulých',
    'key.combined.first.21': 'Vzdušných',
    'key.combined.first.22': 'Strašných',
    'key.combined.first.23': 'Vodních',
    'key.combined.first.24': 'Legračních',
    'key.combined.first.25': 'Hloupých',
    'key.combined.second.1': 'Hrdinů',
    'key.combined.second.2': 'Ryb',
    'key.combined.second.3': 'Sov',
    'key.combined.second.4': 'Zločinců',
    'key.combined.second.5': 'Přisluhovačů',
    'key.combined.second.6': 'Mágů',
    'key.combined.second.7': 'Kmetů',
    'key.combined.second.8': 'Zaklínačů',
    'key.combined.second.9': 'Válečníků',
    'key.combined.second.10': 'Soupeřů',
    'key.combined.second.11': 'Obchodníků',
    'key.combined.second.12': 'Králíků',
    'key.combined.second.13': 'Jablek',
    'key.combined.second.14': 'Vojáků',
    'key.combined.second.15': 'Kouzelníků',
    'key.combined.second.16': 'Rytířů',
    'key.combined.second.17': 'Barbarů',
    'key.combined.second.18': 'Brouků',
    'key.combined.second.19': 'Hadů',
    'key.combined.second.20': 'Draků',
    'key.combined.second.21': 'Přízraků',
    'key.combined.second.22': 'Kocourků',
    'key.combined.second.23': 'Vojínů',
    'key.combined.second.24': 'Klikařů',
    'key.combined.second.25': 'Asasínů',
    'key.combined.second.26': 'Myší',
    'key.combined.second.27': 'Elementálů',
    'key.combined.second.28': 'Výzkumníků',
    'key.combined.second.29': 'Šamanů',
    'key.combined.second.30': 'Žreců',
    'key.combined.second.31': 'Andělů',
    'key.combined.second.32': 'Archónů',
    'key.combined.second.33': 'Katů',
    'key.combined.second.34': 'Hlupáků',
    'key.combined.second.35': 'Odvážlivců',
    'key.combined.second.36': 'Dobráků',
    'key.combined.second.37': 'Zbabělců',
    'key.combined.second.38': 'Bardů',
    'key.combined.second.39': 'Krotitelů',
    'key.combined.second.40': 'Obránců',
    'key.combined.arena': 'Aréna {0} {1}',
    'key.combined.library': 'Knihovna {0} {1}',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Voda',
    'element.type.WIND': 'Vzduch',
    'element.type.FIRE': 'Oheň',
    'element.type.EARTH': 'Země',
    'element.type.DUNGEON': 'Arkana',
    'spell.type.ACTIVATION_RADIUS': 'Poloměr výhledu',
    'spell.type.VISION_RADIUS': 'Dračí zrak',
    'spell.type.STOP_FIELD': 'Pole Hojnosti',
    'spell.type.SCOUT': 'Průzkum',
    'spell.type.PROTECT_ARENA': 'Obrana Arény',
    'spell.type.CREATE_PORTAL': 'Vytvořit Portál',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Dvojnásobný drop',
    'spell.type.SLUG_PLAYERS': 'Slimáknout hráče',
    'quest.title.WIN_ARENA_MONSTER': 'Dominance',
    'quest.title.OPEN_EGGS': 'Vaječná horečka',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Kontrola území',
    'quest.title.CAPTURE_LIBRARY': 'Touha po vědění',
    'quest.title.CAPTURE_WILD_MONSTER': 'Dračí park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Lov na živel',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Hledání Arkanorozené',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Zátah v zlomu',
    'quest.title.OPEN_CHEST': 'Starodávné poklady',
    'quest.title.CHAIN_OF_STOP': 'Cesta Hojnosti',
    'quest.desc.WIN_ARENA_MONSTER': 'Vítězte nad bytostmi na Aréně nebo v Knihovně. Nelze porazit bytost toho samého druhu  dvakrát.',
    'quest.desc.OPEN_EGGS': 'Vysedávejte bytosti z vajec pomocí dračích kokonů nebo Matky Draků',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Vyberte daň z dobytých Arén',
    'quest.desc.CAPTURE_LIBRARY': 'Staňte se majitelem nutného počtu Knihoven',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Nikdy není dost bytostí. Cestujte a chytejte tvory',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Cestujte a chytejte bytosti vodního živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Cestujte a chytejte bytosti vzdušného živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Cestujte a chytejte bytosti ohnivého živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Cestujte a chytejte bytosti zemského živlu',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Cestujte a chytejte bytosti živlu Arkany',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Prohlédněte si Zlom Arkany, ve kterém je Matka Draků',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Prohlédněte si Zlom Arkany a chyťte všechny bytosti, které tam najdete',
    'quest.desc.OPEN_CHEST': 'Najděte a otevřete truhly s poklady',
    'quest.desc.CHAIN_OF_STOP': 'Projděte řadu Sloupů Hojnosti a aktuvujte je. Každý další Sloup bude nasvícený.',
    'quest.dialog.completed.rewardtext': 'Vaše odměna:',
    'key.tab.altar.title': 'OLTÁŘ',
    'key.altar.remove': 'Odstranit',
    'key.altar.put': 'Postavit',
    'key.altar.convert': 'Přetvořit',
    'key.altar.shared': 'Ukazovat jiným',
    'key.altar.pass.placeholder': 'Zde můžete zadat heslo',
    'key.altar.pass.error': 'Heslo musí mít minimálně {0} znaků',
    'key.altar.level.error': 'Musíte dosáhnout úrovně {0}, pokud chcete používat Oltář',
    'key.altar.recipe.change': 'Opravdu chcete změnit recept? Runy budou navráceny majitelům',
    'key.altar.row.title': 'Chcete-li vytvořit zaklínadlo, postavte Oltář',
    'key.altar.rune.descr.RUNE_1': '3 šedé runy = oranžová',
    'key.altar.rune.descr.RUNE_2': '3 oranžové runy = modrá',
    'key.altar.rune.descr.RUNE_3': '3 modré runy = smaragdová',
    'key.altar.rune.descr.RUNE_4': '3 smaragdové runy = červená',
    'key.altar.rune.descr.RUNE_5': '3 červené runy = fialová',
    'key.altar.rune.descr.RUNE_6': 'Fialové runy jsou nejsilnější',
    'error.altar.cannotRemove': 'Oltář nemůže být odstraněn',
    'error.altar.cannotConvert': 'Nemáte dostatečný počet run',
    'key.tab.altar.recipes': 'RECEPTY',
    'key.altar.noRecipes': 'Nemáte recepty',
    'key.altar.header': 'Pro vytvoření zaklínadla položte runy na Oltář',
    'key.altar.castBtn': 'Vytvořit',
    'key.altar.recipe.select': 'Vyberte nutné zaklínadlo',
    'key.altar.castDone': 'Zaklínadlo bylo vytvořené',
    'key.arena.protected.ally': 'Obrana:',
    'key.avatarCustomization.title': 'Zvolte zevnějšek postavy:',
    'key.buddy.walkDescription': 'Procházejte se s mazlíčkem, abyste dostali {0}',
    'key.buddy.totalWalked': '{0} km cesty, která byla absolvována',
    'key.account.balance': 'Zásoby:',
    'key.account.userLevel': '{0} úroveň',
    'key.account.totalDistance': 'Překonána vzdálenost: {0} kilometrů',
    'key.acount.registerDate': 'Začátek hraní: {0}',
    'key.storage.sort.name': 'JMÉNO',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'ZELENÝ SEZNAM',
    'key.storage.sort.group2': 'ŽLUTÝ SEZNAM',
    'key.storage.sort.group3': 'ČERVENÝ SEZNAM',
    'key.storage.sort.date': 'DATUM',
    'key.account.options.jurnal': 'DENÍK',
    'key.account.options.buddy': 'MAZLÍČEK',
    'key.account.options.artifacts': 'ARTEFAKTY',
    'key.account.options.style': 'ZEVNĚJŠEK',
    'key.error.gps.permission': 'GPS není k dispozici. Zapněte přístup k systému GPS pro pokračování ve hře',
    'key.error.gps.disabled': 'GPS je vypnut. Zapněte GPS pro pokračování ve hře',
    'key.error.gps.fakePosition': 'Nemůžete hrát bez GPS',
    'key.error.gps.signal.notFound': 'Chybí signál GPS',
    'key.error.gps.signal.bad': 'Hra není přístupná. Slabý signál GPS',
    'key.error.internet.notReachable': 'Připojení k internetu není k dispozici',
    'key.journal.title': 'Deník',
    'key.journal.yesterday': 'Včera',
    'key.settings.title': 'Nastavení',
    'key.settings.music': 'Hudba',
    'key.settings.deviceAuthError': 'Z bezpečnostních důvodů připojte svůj účet k Googlu nebo Facebooku',
    'key.settings.sounds': 'Zvukys',
    'key.settings.vibration': 'Vibrace',
    'key.settings.batterySaver': 'Zachování energie',
    'key.settings.support': 'Kontaktovat technickou podporu',
    'key.settings.logout': 'Odhlásit se',
    'key.settings.auth.deviceid': 'ID přístroje',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Propojit',
    'key.settings.languageTitle': 'Jazyk',
    'key.settings.language': 'Čeština',
    'key.battle.result.win': 'Bitva je ukončena',
    'key.battle.result.lose': 'Bitva je ukončena',
    'key.wizardBattle.result.win': 'VÍTĚZSTVÍ!',
    'key.wizardBattle.result.lose': 'PORÁŽKA!',
    'key.battle.result.monster': 'Poražené bytosti',
    'key.battle.result.exp': 'Získána zkušenost',
    'key.battle.result.prestige_strong_enemy': 'Bonus slávy za zabití silných nepřátel',
    'key.battle.result.exp_strong_enemy': 'Bonus zkušenosti za silných nepřátel',
    'key.battle.result.prestige_killed_all': 'Bonus slávy za zabití všech',
    'key.battle.result.exp_killed_all': 'Bonus zkušenosti za zabití všech',
    'key.battle.result.dust': 'Esence',
    'key.radar.title': 'Bytosti vedle vás',
    'key.levelUp.title': 'Nová úroveň',
    'key.wizardBattle.left': 'Limit bojů',
    'key.wizardBattle.timer': 'Limit bude anulován za ',
    'key.wizardBattle.enhance.title': 'ZVÝŠENÍ LIMITU',
    'key.wizardBattle.enhance.desc': 'Limit bojů lze zvýšit do 7 za den na jeden týden',
    'key.wizardBattle.enhance.btn': 'Zvýšit',
    'key.wizardBattle.lookingForOpponent': 'Prochází hledání soupeře pro Souboj…',
    'key.catch.result.expMonster': 'Zkušenost za chycení:',
    'key.catch.result.expMonsterNew': 'Novinka v Bestiáři:',
    'key.catch.result.expAccurate': 'Za přesný hod:',
    'key.catch.result.expSpin': 'Za hod po zakřivené trajektorii:',
    'key.catch.result.strike': 'První bytost za den:',
    'key.catch.result.total': 'Celková zkušenost:',
    'key.catch.fullStorage': 'Skladiště bytostí je zaplněné',
    'key.catch.noItems': 'Nemáte magické sféry',
    'key.creadex.title': 'BESTIÁŘ',
    'key.creadex.detail.caught': 'CHYCEN: {0}',
    'key.creadex.detail.evolution': 'VÝVOJ',
    'key.tab.doll': 'POSTAVA',
    'key.tab.artifacts': 'ARTEFAKTY',
    'key.activePoint.title': 'Sloup Hojnosti',
    'key.personalization.title': 'Začarování',
    'key.chest.title': 'Magická truhla',
    'key.quest.daily.title': 'ÚKOL',
    'key.quest.weekly.title': 'LOV',
    'key.quest.get': 'DOSTAT ÚKOL',
    'key.quest.change': 'VYMĚNIT ÚKOL',
    'key.quest.progress': 'Pokrok v úkolu: {0} z {1}',
    'key.error.quest.weekly.level': 'Je třeba dosáhnout úrovně {0}, abyste začali hon na Zlaté Vejce',
    'key.error.quest.daily.level': 'Je třeba dosáhnout úrovně {0}, abyste vzali úkol',
    'key.error.quest.tooFar': 'Obelisk je příliš daleko',
    'key.quest.daily.descr.noQuest.title': 'Úkoly nejsou',
    'key.quest.daily.descr.noQuest': 'Chcete-li dostat úkoly a zasloužit odměnu, použijte Obelisk.',
    'key.quest.daily.timer.descr': 'Úkol lze změnit za:',
    'key.quest.daily.waitForNew.descr': 'Nový úkol bude přístupný za:',
    'key.quest.weekly.getFragment': 'DOSTAT FRAGMENT',
    'key.quest.weekly.descr.noQuest.title': 'Neúčastníte se lovu na Zlaté Vejce',
    'key.quest.weekly.descr.noQuest': 'Chcete-li dostat fragment tajemné mapy a začít lov, použijte Obelisk.',
    'key.quest.weekly.descr.getFirstFragment': 'Dostaňte první fragment tajemné mapy, abyste začali lov na Zlaté Vejce',
    'key.quest.weekly.descr.top.notAllOpen': 'Použijte Obelisk, abyste dostali fragment mapy. Spěchejte, lov skončí za',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Použijte lopatu na každém fragmentu, abyste našli Zlaté Vejce',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Už jste dostali fragment mapy z toho Obelisku',
    'key.quest.weekly.descr.top.allOpen': 'Všechny fragmenty mapy z Obelisků už byly obdrženy. Spěchejte, lov skončí za',
    'key.quest.weekly.descr.bot.allOpen': 'Použijte lopatu na každém fragmentu, abyste našli Zlaté Vejce',
    'key.quest.weekly.descr.top.completed': 'Našli jste už Zlaté Vejce tento týden. Další lov začne za',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}h',
    'key.timer.format.H_M': '{0}h {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}h',
    'key.creatureStorage.tab.creatures': 'BYTOSTI',
    'key.creatureStorage.tab.eggs': 'VEJCE',
    'key.creatureStorage.multiTransferText': 'Vyberte si, koho chcete pustit',
    'key.storage.creature.transfer': 'Pustit ({0})',
    'key.error.needHigherLevelForArena': 'Je zapotřebí úroveň {0} pro vstup do Arény',
    'key.error.needHigherLevelForLibrary': 'Je zapotřebí úroveň {0} pro vstup do Knihovny',
    'key.error.arenaUnderProtection': 'Aréna je pod ochranou Požehnání obrany',
    'key.error.buildingTooFar': 'Budova je příliš daleko',
    'key.error.noAliveCreaturesForAttack': 'Nemáte žádné živé bytosti',
    'key.error.noHealPotion': 'Nemáte léčebné lektvary',
    'key.error.noResurrectionPotion': 'Nemáte lektvary oživení',
    'key.error.tryAgainLater': 'Chyba. Zkuste to znovu později.',
    'key.error.alreadyHasLure': 'Návnada je již použita',
    'key.error.cannotUseLureInDungeon': 'Návnada nemůže být použita ve Zlomu Arkany',
    'key.error.bagIsFull': 'V tašce není místo',
    'key.error.cantTransferCreature': 'Nelze pustit tuto bytost',
    'key.notification.done': 'Hotovo!',
    'key.modal.doYouWantToTransfer': 'Opravdu chcete pustit tyto bytosti?',
    'key.modal.youWillLoseBuddyProgress': 'Opravdu chcete vyměnit mazlíčka? Pokrok k obdržení kamene duší bude ztracený.',
    'key.modal.doYouWantToLeaveDungeon': 'Chcete opustit Zlom Arkany',
    'key.modal.superVisionActive': 'Dračí zrak byl už aktivovaný. Opakované použití přemístí magickou zónu viditelnosti. Opravdu ho chcete použít ještě jednou?',
    'key.modal.experienceBoosterActive': 'Krystal moudrosti byl už aktivovaný. Opravdu ho chcete použít ještě jednou?',
    'key.modal.youWillLooseQuestProgress': 'Pokrok v tomto úkolu bude ztracený. Jste si jisti?',
    'key.modal.doYouWantToEnterDungeon': 'Chcete vstoupit do Zlomu Arkany přes Portál?',
    'key.modal.doYouWantPersonalizePoint': 'Začarovaný sloup bude dávat pouze {0}. Chcete utratit {1} mincí na začarování?',
    'key.modal.doYouWantToDeletePersonalization': 'Opravdu chcete odstranit kouzlo z toho Sloupu Hojnosti?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Opravdu chcete posílit tuto bytost?',
    'key.modal.doYouWantToEvolveThisCreature': 'Opravdu chcete přeměnit tuto bytost v silnější?',
    'key.modal.doYouWantToScoutHere': 'Opravdu chcete zkontrolovat tuto zónu?',
    'key.error.creatureHasMaxLevel': 'Bytost už má maximální úroveň',
    'key.error.creatureHasMaxLevelForUser': 'Zprvu je třeba zvýšit úroveň postavy',
    'key.error.notEnoughResourcesForEnhance': 'Chybějí zásoby',
    'key.error.creatureIsArenaDefender': 'Nelze vybrat bytost, která brání budovu',
    'key.modal.incenseActive': 'Feromony už byly aktivované. Opravdu je chcete použít ještě jednou?',
    'key.error.cantHealHealthyCreature': 'Bytost byla úplně vyléčena',
    'key.error.cantRessurectAliveCreature': 'Bytost je už živá',
    'key.error.noTreasureHere': 'Na tomto fragmentu mapy není žádné Zlaté Vejce. Pokračujte v hledání.',
    'key.error.levelTooSmall': 'Zprvu je třeba zvýšit úroveň postavy',
    'key.error.needHigherLevelForWizardBattles': 'Pro účast na Soubojích Mágů je zapotřebí úroveň {0}',
    'key.error.artifactBagIsFull': 'Skladiště artefaktů je zaplněné',
    'key.error.notEnoughCoins': 'Chybějí mince',
    'key.error.allFragmentsAreOpen': 'Všechny fragmenty tajemné mapy jsou otevřeny',
    'key.error.questAlreadyCompleted': 'Úkol je už ukončený',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Už jste dostali fragment mapy z toho Obelisku',
    'key.error.portalTooFarAway': 'Portál je příliš daleko',
    'key.error.battleLimitAlreadyEnhanced': 'Limit bitev už byl zvýšený',
    'key.error.youAreNotAltarOwner': 'Toto může dělat pouze majitel Oltáře',
    'key.error.youAlreadyHaveAltar': 'Oltář je už postaven',
    'key.error.cantTakeAnotherUsersRune': 'Nelze odebrat runu jiného hráče',
    'key.error.libraryBlocked': 'Aby šly používat Knihovny, je třeba počkat 3 dny po přeškolení',
    'key.error.notAuthorized': 'Uživatel není autorizovaný',
    'key.error.eggOnlyRoost': 'Tato vejce je třeba dát Matce Draků',
    'key.error.purchase': 'Chyba: {0}',
    'key.error.creatureIsDead': 'Nejdřív je třeba oživit bytost',
    'key.error.no_connection': 'Nepodařilo se připojit k serveru. Zkuste později.',
    'key.error.protocol_version_mismatch': 'Verze hry je zastaralá. Je nutná aktualizace.',
    'key.error.update_application': 'Verze hry je zastaralá. Je nutná aktualizace.',
    'key.modal.doYouWantToTransferSingle': 'Opravdu chcete uvolnit tuto bytost?',
    'key.notification.phoneNotSupportAR': 'Váš přístroj nepodporuje AR',
    'key.notification.turnOnARPermission': 'Hra nemá přístup ke kameře. Je nutné umožnit přístup v nastaveních přístroje',
    'key.notification.dailyQuestFinished': 'Úkol je splněný!',
    'key.modal.yesBtn': 'Ano',
    'key.modal.noBtn': 'Ne',
    'event.log.DAILY_QUEST_COMPLETED': 'Každodenní úkol je ukončený. Odměny byly obdrženy:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Lov je ukončen! Vaše odměna:',
    'event.log.ENCOUNTER_VICTORY': 'Zvítězili jste nad divokou příšerou!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Vaše verze hry je zastaralá. Je nutná aktualizace.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Chyba autentifikace',
    'key.ServiceException.Cause.SESSION_GONE': 'Někdo se přihlásil do vašeho účtu z jiného zařízení',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'ID Uživatele je prázdné',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Uživatel nebyl nalezen',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Účet byl zablokován pro nepoctivou hru',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Účet byl zablokován pro podvodné platby.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Účet byl zablokován pro urážlivé uživatelské jméno.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Účet byl zablokován pro agresivní komunikaci s jinými hráči.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Účet byl zablokován pro nepoctivou hru.',
    'key.ServiceException.Cause.USER_BANNED': 'Účet byl zablokován.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'V tašce není místo',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maximální počet vajec',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Chybějí mince',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Chybějí kameny duší',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Chybí esence',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Skladiště bytostí je zaplněné',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Bytost už má maximální úroveň',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Nelze přetvořit tuto bytost',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Jméno bytosti má mít maximálně 14 znaků',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Budova už má maximální počet obránců',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Nelze udělat mazlíčkem obránce budovy',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Vaše bytost už brání tuto budovu',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Chyba',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Žádný boj nebyl nalezen',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Chyba',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Vaše bytost už brání tuto budovu',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Aréna je pod ochranou Požehnání obrany',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Čas výběru daní ještě nepřišel',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Špatná sféra',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Špatná budova',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Přístup odepřen',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Neexistující předmět',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Neexistující recept',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Lze postavit pouze jeden Oltář',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Zprvu je třeba zvýšit úroveň postavy',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Nepodařilo se začít lov bytosti',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Neexistující zboží',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Neexistující zboží',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Neexistující budova',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Bytost nebyla nalezena',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Bytost nebyla nalezena',
    'key.ServiceException.Cause.TOO_FAR': 'Budova je příliš daleko',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Objekt je příliš daleko',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Budova je na znovunabíjení',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Budova v Zlomu Arkany',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Nelze použít budovu',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Dračí kokon nebyl nalezen',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Dračí kokon je prázdný',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Dračí kokon je obsazený',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Vejce nebylo vysezeno',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Vejce nebylo nalezeno',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Pro to vejce je nutná Matka Draků',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Skončila se nabíjení',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Nepodařilo se postavit budovu',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Došlo k chybě a to je tajemná zpráva o ní',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Divoké monstrum uteklo',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Divoké monstrum nebylo nalezeno',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'V tomto Sloupě Hojnosti už je návnada',
    'key.ServiceException.Cause.WRONG_ITEM': 'Špatný předmět',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Tato runa je nejsilnějš',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Nedostatek run této úrovně',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Špatný slot pro runy',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Tento slot je už obsazený',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Slot pro runu je prázdný',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Nelze si vybrat obránce budovy',
    'key.ServiceException.Cause.WRONG_SPELL': 'Nesprávné zaklínadlo',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Zaklínadlo vyžaduje více run',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Nový úkol ještě není k dispozici',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Již jste použili tento Obelisk',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Všechny fragmenty tajemné mapy jsou už otevřeny',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Neúčastníte se lovu na Zlaté Vejce',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Už jste zkoušeli hledat Zlaté Vejce na tomto pozemku',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Již jste použili lahůdku',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Bytost je už chycena',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Přeškolení bytosti zatím není dostupné',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Knihovna je zatím zablokován',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Server neodpovídá. Zkuste to znovu později.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Limit bitev už byl zvýšený',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Limit bitev je vyčerpán',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Pro účast na Souboji Mágů je zapotřebí úroveň 9',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Soupeř pro Souboj Mágů nebyl nalezen, zkuste to znovu později',
    'key.ServiceException.Cause.MARKET_ERROR': 'Chyba obchodu',
    'key.ServiceException.Cause.NO_CHEST': 'Truhla nebyla nalezena',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Chyba výdeje fragmentu. Zkuste to znovu později.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Pokud chcete předat Matce Draků více vajec, dejte na sebe Dračí Srdce nebo komplet Dračích Artefaktů',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'V této buňce už je vejce',
    'key.ServiceException.Cause.NO_CONNECTION': 'Připojení k internetu není k dispozici',
    'key.ServiceException.Cause.SERVER_DOWN': 'Herní server je dočasně nedostupný. Zkuste to prosím později.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Právě probíhá technická údržba serveru. Zkuste to prosím později.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Tyto runy se nyní používají',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Pohybujete se příliš rychle',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Limit dobytých Arén byl dosažen',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Limit dobytých Knihoven byl dosažen',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Chyba: GPS není k dispozici',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Toto zaklínadlo nelze použít ve Zlomu Arkany',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Čas vypršel',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Verze hry je zastaralá. Je nutná aktualizace.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'V oblasti viditelnosti nejsou svazové Arény',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'V oblasti viditelnosti nejsou nepřátelské Arény',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'This account is already in use',
    'stop.personalized.BALLS': 'sféry',
    'stop.personalized.HEALS': 'léčebné lektvary',
    'stop.personalized.RESURRECTIONS': 'lektvary oživení',
    'stop.personalized.EGGS': 'vejce bytostí',
    'stop.personalized.FOODS': 'dobrůtky',
    'key.button.cancelPersonal': 'Zrušit',
    'key.error.needHigherLevelForSofaBattles': 'Pro účast na Souboji Mágů je zapotřebí úroveň {0}',
    'fraction.text.youWilLGetBonus': 'Dostanete {0} mincí za připojení k této frakci',
    'fraction.text.fractionUnavailable': 'Frakce je zatím nedostupná',
    'fraction.text.chooseYourAlliance': 'Zvolte frakci, za kterou budete bojovat',
    'fraction.text.redFractionName': 'Červený řád',
    'fraction.text.blueFractionName': 'Modrý řád',
    'key.error.chestTooFarAway': 'Truhla je příliš daleko',
    'key.button.openChest': 'Otevřít',
    'key.candy.MONSTER_WATER_1': 'kameny Ropuchusa',
    'key.candy.MONSTER_WATER_2': 'kameny Kapky',
    'key.candy.MONSTER_WATER_3': 'kameny Spiritusa',
    'key.candy.MONSTER_WATER_4': 'kameny Akvina',
    'key.candy.MONSTER_WATER_8': 'kameny Jellyhata',
    'key.candy.MONSTER_WATER_9': 'kameny Minori',
    'key.candy.MONSTER_WATER_10': 'kameny Infaliska',
    'key.candy.MONSTER_WATER_12': 'kameny Dadačka',
    'key.candy.MONSTER_WATER_13': 'kameny Batoida',
    'key.candy.MONSTER_WATER_23': 'kameny Brněniusa',
    'key.candy.MONSTER_WATER_24': 'kameny Neptuna',
    'key.candy.MONSTER_WATER_25': 'kameny Leviatana',
    'key.candy.MONSTER_FIRE_1': 'kameny Potti',
    'key.candy.MONSTER_FIRE_2': 'kameny Mummyvina',
    'key.candy.MONSTER_FIRE_3': 'kameny Steampala',
    'key.candy.MONSTER_FIRE_4': 'kameny Inkumusa',
    'key.candy.MONSTER_FIRE_6': 'kameny Flamy',
    'key.candy.MONSTER_FIRE_7': 'kameny Foubi',
    'key.candy.MONSTER_FIRE_11': 'kameny Jiskry',
    'key.candy.MONSTER_FIRE_12': 'kameny Kydry',
    'key.candy.MONSTER_FIRE_15': 'kameny Needlehota',
    'key.candy.MONSTER_FIRE_25': 'kameny Smaugra',
    'key.candy.MONSTER_EARTH_1': 'kameny Bobulilla',
    'key.candy.MONSTER_EARTH_2': 'kameny Květka',
    'key.candy.MONSTER_EARTH_3': 'kameny Lístka',
    'key.candy.MONSTER_EARTH_4': 'kameny Brownie',
    'key.candy.MONSTER_EARTH_8': 'kameny Disguira',
    'key.candy.MONSTER_EARTH_9': 'kameny Belflou',
    'key.candy.MONSTER_EARTH_10': 'kameny Žaludne',
    'key.candy.MONSTER_EARTH_11': 'kameny Filo',
    'key.candy.MONSTER_EARTH_13': 'kameny Prinsi',
    'key.candy.MONSTER_EARTH_25': 'kameny Scylly',
    'key.candy.MONSTER_DUNGEON_1': 'kameny Rookie',
    'key.candy.MONSTER_DUNGEON_2': 'kameny Axolana',
    'key.candy.MONSTER_DUNGEON_3': 'kameny Ostenzáda',
    'key.candy.MONSTER_DUNGEON_4': 'kameny Magglada',
    'key.candy.MONSTER_DUNGEON_5': 'kameny Milokocoura',
    'key.candy.MONSTER_DUNGEON_6': 'kameny Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'kameny Vampiro',
    'key.candy.MONSTER_DUNGEON_13': 'kameny Housene',
    'key.candy.MONSTER_DUNGEON_17': 'kameny Inura',
    'key.candy.MONSTER_WIND_1': 'kameny SunTzi',
    'key.candy.MONSTER_WIND_2': 'kameny Uchomychu',
    'key.candy.MONSTER_WIND_3': 'kameny Houbi',
    'key.candy.MONSTER_WIND_4': 'kameny Chlupatorohu',
    'key.candy.MONSTER_WIND_6': 'kameny Hamajuny',
    'key.candy.MONSTER_WIND_7': 'kameny Strašana',
    'key.candy.MONSTER_WIND_11': 'kameny Infirda',
    'key.candy.MONSTER_WIND_12': 'kameny Undine',
    'key.candy.MONSTER_WIND_15': 'kameny Cheshire',
    'key.candy.MONSTER_WIND_25': 'kameny Cheshire',
    'key.button.leaveDungeon': 'Opustit Zlom',
    'key.alias.enterNewAlias': 'Zadejte jméno bytosti',
    'key.alias.enterText': 'Zadejte text…',
    'key.hut.hutName': 'Matka Draků',
    'key.hut.hutDescr': 'Předejte Matce Draků starobylé vejce, aby je vyseděla pro vás',
    'key.text.noHutEggs': 'Nemáte žádné starobylé vejce',
    'key.text.noCapturedArenas': 'Nemáte žádné dobyté Arény',
    'key.text.noChosenPet': 'Mazlíček nebyl zvolen',
    'key.text.noArtifacts': 'Nemáte artefakty',
    'key.text.noCreatures': 'Nemáte chycené bytosti',
    'key.text.noLureItems': 'Nemáte návnadu',
    'key.descr.aboutWizardBattles': 'Účastníte se Soubojů s jinými hráči pro obdržení zkušenosti a odměny',
    'key.text.writeToSupport': 'Kontaktovat podporu',
    'key.text.regUsingFacebook': 'Registrovat se pomocí Facebook',
    'key.text.regUsingGoogle': 'Registrovat se pomocí Google',
    'key.text.logUsingFacebook': 'Přihlásit se pomocí Facebook',
    'key.text.logUsingGoogle': 'Přihlásit se pomocí Google',
    'key.text.logUsingDeviceIDCurrent': 'Přihlásit se pomocí Device ID',
    'key.text.logUsingDeviceIDNew': 'Přihlásit se pomocí Device ID (nový účet)',
    'key.text.createAccount': 'Hrát',
    'key.text.connectedToFacebook': 'Připojené k Facebook',
    'key.text.connectedToGoogle': 'Připojené k Google',
    'key.text.complainAboutPoint': 'Nahlásit místo',
    'key.text.copyCoordinates': 'Kopírovat souřadnice',
    'key.text.complainEnterEmail': 'Váš e-mail',
    'key.text.complainEnterText': 'Popište Váš problém',
    'key.modal.doYouWantToCloseApp': 'Opravdu chcete zavřít aplikaci?',
    'key.catchPopup.notBad': 'Dobře!',
    'key.catchPopup.good': 'Výborně!',
    'key.catchPopup.sumptuously': 'Skvěle!',
    'key.catchPopup.twistedThrow': 'Křivý hod!',
    'key.battlePopup.strongHit': 'Silný úder!',
    'key.battlePopup.weakHit': 'Slabý úder',
    'key.battlePopup.dodge': 'Uhnout!',
    'key.battlePopup.chargedAttack': '{0} používá {1}',
    'auth.login.play': 'Hrát',
    'auth.login.nickname.placeholder': 'Zadejte jméno',
    'auth.login.nickname.busy': 'Jméno je obsazené',
    'auth.login.nickname.proposal': 'Můžete použít toto jméno:',
    'auth.login.nickname.deviceId': 'Už máte postavu',
    'auth.login.social.title': 'Přihlásit se přes sociální síť',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Připojeno k {0}',
    'auth.login.social.signOut': 'Odhlásit se z účtu',
    'auth.login.signOut.confirmation': 'Opravdu se chcete odhlásit z účtu?',
    'auth.login.social.userCancelledError': 'Zrušení připojení',
    'auth.login.social.cantSignInError': 'Nedaří se připojit k  {0}',
    'licence.title': 'UŽIVATELSKÁ SMLOUVA HRY DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Posílejte mi novinky a nabídky na e-mail',
    'licence.accept': 'Přijmout',
    'licence.decline': 'Odmítnout',
    'key.error.wrongRoostIndex': 'Slot není k dispozici',
    'key.speed.passenger': 'Jsem pasažér',
    'key.activeObjects.addUnit.question': 'Opravdu chcete udělat {0} obráncem této budovy?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Opravdu chcete si vybrat tuto frakci? Tuto volbu nelze změnit v budoucnu.',
    'key.confirm.giveUpEncounter': 'Opravdu se chcete vzdát boje s divokou příšerou?',
    'key.confirm.giveUpBattle': 'Opravdu se chcete vzdát boje?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nová liga!',
};
