module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'JA',
    'key.button.cancel': 'ANNULEREN',
    'key.button.apply': 'TOEPASSEN',
    'key.button.use': 'Gebruiken',
    'key.button.buy': 'Kopen',
    'key.beCarefulMessage.text': 'Vergeet niet om te allen tijde alert te zijn. Blijf op de hoogte van jouw omgeving.',
    'key.creature.details.attack': 'Kracht',
    'key.creature.details.health': 'Gezondheid',
    'key.creature.details.powerUp': 'Versterking',
    'key.creature.details.evolve': 'Evolutie',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'СР {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'WEGGEVEN',
    'key.creature.details.creadex': 'Beestiarium',
    'key.creature.registration.creadex': 'Geregistreerd in beestiarium',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Veroverde objecten',
    'key.activeObjects.library': 'Monster training in de Bibliotheek',
    'key.activeObjects.library.empty': 'Geen veroverde Bibliotheken',
    'key.activeObjects.arena': 'Belastinginzameling vanuit Arena\'s',
    'key.activeObjects.arena.collect': 'Verzamelen',
    'key.activeObjects.arena.empty': 'Je hebt geen Arena\'s',
    'key.activeObjects.error.timer': 'Belastinginzameling is niet beschikbaar. Even wachten astjeblieft',
    'key.activeObjects.error.noMoney': 'De Arena moet eerst veroverd worden',
    'key.activeObjects.error.cannotRemaster': 'Omscholing is niet beschikbaar. Verover Bibliotheken, om de timer van omscholing te versnellen.',
    'key.activeObjects.library.remaster': 'Omscholen',
    'key.activeObjects.library.blocked': 'Omscholing is niet beschikbaar. Verover Bibliotheken, om de timer van omscholing te resetten.',
    'key.activeObjects.remaster.confirmation.main': 'Weet je zeker dat je het wezen {0} wilt omscholen? Hoofdvaardigheid {1} wordt veranderd!',
    'key.activeObjects.remaster.confirmation.charged': 'Weet je zeker dat je het wezen {0} wilt omscholen? Geladen vaardigheid {1} wordt veranderd!',
    'key.activeObjects.remaster.error': 'Fout',
    'key.activeObjects.item.weaklyBonus': '+{0} munten voor de eerste belasting van deze week',
    'key.library.remaster.selectCreature': 'Kies wezen voor omscholing',
    'key.remasterPanel.title': 'Kies vaardigheid',
    'key.storage.creatues': 'Wezens',
    'key.storage.eggs': 'Eieren',
    'key.storage.eggs.simple': 'Gewone eieren',
    'key.storage.eggs.super': 'Oeroude eieren',
    'key.storage.eggs.missingAny': 'Je hebt geen monster eieren',
    'key.startEgg.button': 'In een cocon plaatsen',
    'key.startEgg.description': 'Gebruik de drakencocon om dit ei uit te broeden',
    'key.startEgg.incubator.title': 'Drakencocons',
    'key.startEgg.select.title': 'Kies een ei',
    'key.openEgg.button': 'Ei openbreken',
    'key.openEgg.description': 'Een nieuw wezen staat op het punt om uit het ei te komen',
    'key.startEgg.description.roost.hatching': 'De Moeder der Draken broedt dit ei uit. Je moet gewoon wachten. Het uitbroeden zal stoppen, wanneer de Breuk van de Arcana, waar de Moeder der Draken zich bevindt, verdwijnt.',
    'key.startEgg.description.roost.notHatching': 'Geef dit ei aan de Moeder der Draken, zodat ze het voor jou uitbroedt.',
    'key.startEgg.description.simple.hatching': 'Dit ei wordt uitgebroed in een drakencocon. Loop rond, met het spel actief,  om het te helpen uitkomen. ',
    'key.startEgg.description.simple.notHatching': 'Plaats dit ei in een drakencocon om het uitbroeden te laten beginnen. Het ei zal uitkomen, nadat je de benodigde afstand hebt gelopen.',
    'key.mainMenu.wizardDuels': 'DUEL VAN MAGIERS',
    'key.mainMenu.quests': 'OPDRACHTEN',
    'key.mainMenu.activePoints': 'VEROVERDE',
    'key.mainMenu.creadex': 'BEESTIARIUM',
    'key.mainMenu.magic': 'MAGIE',
    'key.mainMenu.creatues': 'WEZENS',
    'key.mainMenu.shop': 'WINKEL',
    'key.mainMenu.backpack': 'TAS',
    'key.error.banned': 'Dit account is geblokkeerd',
    'event.log.CREATURE_CAUGHT': '{0} is gevangen!',
    'event.log.ITEM_BOUGHT': '{0} x{1} is gekocht. Je hebt {2} munten uitgegeven',
    'event.log.ARTIFACT_BOUGHT': 'Artefact {0} gekocht. {1} munten zijn uitgegeven',
    'event.log.EGG_HATCHED': '{0} is uitgekomen uit {1} ei!',
    'event.log.EGG_HATCHED.distance': '{0} km',
    'event.log.EGG_HATCHED.gold': 'gouden',
    'event.log.ROOST_EGG_HATCHED': 'De Moeder der Draken heeft {1} ei uitgebroed. {0} is nu van jou!',
    'event.log.CHEST_OPENED': 'Gevonden in de kist:',
    'event.log.ARENA_LOST_CONTROL': '{1} is uit het gebouw: {0} geslagen',
    'event.log.LIBRARY_LIST_CONTROL': '{1} is uit het gebouw: {0} geslagen',
    'event.log.LEVEL_UP': 'Je hebt niveau {0} bereikt',
    'event.log.BUDDY_FOUND_CANDY': 'Het huisdier heeft {0} gevonden}',
    'event.log.QUEST_COMPLETED': 'Beloning voor de opdracht: {0}',
    'event.log.ENCOUNTER_LOOSE': 'Je bent ontsnapt van een Wilde Monster',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Het limiet van de strijden, in de Duel tussen Magiërs, is vergroot voor {0} munten',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} munten gekocht voor {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Deze tas is geupgrade voor {0} munten',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Wezensbergplaats is geupgrade voor {0} munten',
    'key.shop.accesories': 'ITEMS',
    'key.shop.artifacts': 'ARTEFACTEN',
    'key.shop.donate': 'MUNTEN',
    'key.shop.upgrade': 'UPGRADES',
    'key.shop.donate.coins': '{0} munten',
    'key.shop.upgrade.bag': 'Tas upgrade',
    'key.shop.upgrade.bag.desc': 'Maat van de tas wordt tot 50 vergroot',
    'key.shop.upgrade.storage': 'Wezensbergplaats upgrade',
    'key.shop.upgrade.storage.desc': 'Maat van de wezensbergplaats wordt tot 50 vergroot',
    'key.shop.donate.dialog.title': 'Niet genoeg munten!',
    'key.shop.donate.dialog.desc': 'Verkrijg ze hier of bezoek een winkel om meer varianten te zien',
    'key.potionUseMenu.title': 'Geneesdrankje',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Creëert een Portaal naar de wereld van Arcana.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Alle omringende spelers zullen de toorn van de leprechauns voelen',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'Creëert een veld van Pilaren van Overvloed voor 30 minuten',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Verdubbelt het aantal beloningen uit de Pilaren van Overvloed voor 30 minuten',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Tik op de landstreek en houd deze vast om het te markeren, terwijl je naar wezens zoekt',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'Vergroot het bereik voor het vinden van wezens voor 30 minuten',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Vergroot het bereik voor objectactivering met 30% voor 7 dagen',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'De dichtstbijzijnde geallieerde Arena zal de komende 30 uur veilig zijn tegen vijandelijke aanvallen',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Alle vijandelijke Arena\'s binnen het bereik van N kilometer worden neutraal. Haalt Zegen voor bescherming weg',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Creëert een elementaire toren van vuur',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Creëert een elementaire toren van water',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Creëert een elementaire toren van wind',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Creëert een elementaire toren van aarde',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Creëert een elementaire toren van kerker',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Breuk van Arcana',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Toorn van Leprechauns',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Veld van Overvloed',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Geschenk van de Gouden Draak',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Astrale visie',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Drakenzicht',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Lange handen',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Zegen voor bescherming',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Zuivering door vuur',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Toren van vuur',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Toren van water',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Toren van wind',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Toren van aarde',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Toren van kerker',
    'key.buff.ATTACKER_CP_BOOST': 'CP van jouw wezens is tijdelijk verhoogd',
    'key.buff.BEST_BALL_LUCK': 'Alleen de beste sferen in de Pilaren van Overvloed voor 30 min',
    'key.buff.BEST_POTION_LUCK': 'Alleen de beste toverdrankjes in de Pilaren van Overvloed voor 30 min',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 items van de Pilaren van Overvloed voor 30 min',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Cooldown van Bibliotheek verhoogd met {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Tijd van belastinginzameling van Arena\'s verhoogd met {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Verhoogt de CP van wezens die gebouwen huidig niet verdedigen',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Je krijgt alleen de beste sferen voor jouw niveau van de Pilaren van Overvloed',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Je krijgt alleen de beste toverdrankjes voor jouw niveau van de Pilaren van Overvloed',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Aantal items die je van Pilaren van Overvloed krijgt vergroot met 2',
    'key.loot.result.dust': 'Essentie',
    'key.loot.result.exp': 'Ervaring van karakter',
    'key.loot.result.coin': 'Munten',
    'key.loot.result.candy': 'Stenen',
    'key.item.MAGIC_BALL_SIMPLE': 'Sfeer van leerling',
    'key.item.MAGIC_BALL_NORMAL': 'Sfeer van meester',
    'key.item.MAGIC_BALL_GOOD': 'Sfeer van beheerser',
    'key.item.LURE': 'Lokken',
    'key.item.INCENSE': 'Feromonen',
    'key.item.EGG': 'Ei',
    'key.item.SHOVEL': 'Schop',
    'key.item.POTION_HEAL_1': 'Klein drankje voor genezing',
    'key.item.POTION_HEAL_2': 'Medium drankje voor genezing',
    'key.item.POTION_HEAL_3': 'Groot drankje voor genezing',
    'key.item.POTION_HEAL_4': 'Drankje voor complete genezing',
    'key.item.POTION_RESURRECTION_1': 'Drankje voor herrijzenis',
    'key.item.POTION_RESURRECTION_2': 'Groot drankje voor herrijzenis',
    'key.item.INCUBATOR_1': 'Drakencocon',
    'key.item.INCUBATOR_3': 'Drakencocon',
    'key.item.INCUBATOR_PERPETUAL': 'Eeuwige drakencocon',
    'key.item.SUPER_VISION': 'Drakenzicht',
    'key.item.RUNE_1': 'Rune I',
    'key.item.RUNE_2': 'Rune II',
    'key.item.RUNE_3': 'Rune III',
    'key.item.RUNE_4': 'Rune IV',
    'key.item.RUNE_5': 'Rune V',
    'key.item.RUNE_6': 'Rune VI',
    'key.item.FOOD_CATCH_CHANCE': 'Stok van arcanische karamel',
    'key.item.FOOD_MORE_DUST': 'Donut met magische poeder',
    'key.item.FOOD_CALM_DOWN': 'Eenhoorn spekjes',
    'key.item.FOOD_MORE_CANDIES': 'Ijsje van vier elementen',
    'key.item.EXPERIENCE_BOOSTER': 'Kristal van wijsheid',
    'key.item.EGG_KM_0': 'Gouden Ei',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Sfeer voor het vangen van wezens.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Sfeer voor het vangen van wezens. Vergroot enigszins de kans op een succesvolle vangst.',
    'key.item.MAGIC_BALL_GOOD.description': 'Sfeer voor het vangen van wezens. Vergroot de kans op een succesvolle vangst enorm.',
    'key.item.LURE.description': 'Het lokken van wezens. Plaats het in de Pilaar van Overvloed om wezens aan te trekken.',
    'key.item.INCENSE.description': 'De feromonen zullen wezens aantrekken van een bepaald element, afhankelijk van de dag van de week.',
    'key.item.EGG.description': 'Gebruik de drakencocon om het wezen uit het ei te laten komen',
    'key.item.SHOVEL.description': 'De schoppen zijn essentieel tijdens de jacht naar schatten',
    'key.item.POTION_HEAL_1.description': 'Geneest het gekozen wezen met 200 gezondheidspunten',
    'key.item.POTION_HEAL_2.description': 'Geneest het gekozen wezen met 500 gezondheidspunten',
    'key.item.POTION_HEAL_3.description': 'Geneest het gekozen wezen met 1000 gezondheidspunten',
    'key.item.POTION_HEAL_4.description': 'Geneest het gekozen wezen volledig',
    'key.item.POTION_RESURRECTION_1.description': 'Herrijst het gekozen wezen. Na de herrijzing zal het wezen gewond zijn.',
    'key.item.POTION_RESURRECTION_2.description': 'Herrijst en geneest volledig het gekozen wezen',
    'key.item.INCUBATOR_1.description': 'Drakencocons zijn nodig om wezens uit eieren te broeden. Ze verdwijnen na gebruik.',
    'key.item.INCUBATOR_3.description': 'Drakencocons zijn nodig om wezens uit eieren te broeden. Ze verdwijnen na 3 gebruiken.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Drakencocons zijn nodig om wezens uit eieren te broeden.',
    'key.item.SUPER_VISION.description': 'Verbetert het bereik van zichtbaarheid van wezens aanzienlijk',
    'key.item.RUNE_1.description': 'Magische rune met de sterkte van niveau 1',
    'key.item.RUNE_2.description': 'Magische rune met de sterkte van niveau 2',
    'key.item.RUNE_3.description': 'Magische rune met de sterkte van niveau 3',
    'key.item.RUNE_4.description': 'Magische rune met de sterkte van niveau 4',
    'key.item.RUNE_5.description': 'Magische rune met de sterkte van niveau 5',
    'key.item.RUNE_6.description': 'Magische rune met de sterkte van niveau 6',
    'key.item.FOOD_CATCH_CHANCE.description': 'Snoep voor de vangst van wezens. Verhoogt de kans om een wezen met een magische sfeer te vangen.',
    'key.item.FOOD_MORE_DUST.description': 'Snoep voor de vangst van wezens. Verhoogt de hoeveelheid essentie die je krijgt voor het vangen van een wezen',
    'key.item.FOOD_CALM_DOWN.description': 'Snoep voor de vangst van wezens. Kalmeert het wezen, waardoor het stopt met springen en aanvallen',
    'key.item.FOOD_MORE_CANDIES.description': 'Snoep voor de wezens. Verhoogt het aantal zielstenen dat je ontvangt voor het vangen van een wezen',
    'key.item.EXPERIENCE_BOOSTER.description': 'Verdubbelt de hoeveelheid ervaring dat je krijgt gedurende 30 minuten',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Masker van de goochelaar',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '1 afgelegen plaatsing van een wezen op Arena per dag',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Dit artefact staat je toe om jouw wezen, 1 keer per dag, te plaatsen op een vrije plaats in de zichtbare op de kaart Arena of Bibliotheek op afstand.',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Gezicht van de ziener',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '2 afgelegen plaatsingen van een wezen op Arena per dag',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Dit artefact staat je toe om jouw wezen, 2 keer per dag, te plaatsen op een vrije plaats in de zichtbare op de kaart Arena of Bibliotheek op afstand.',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Helm van de veroveraar',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '3 afgelegen plaatsingen van een wezen op Arena per dag',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Dit artefact staat je toe om jouw wezen, 3 keer per dag, te plaatsen op een vrije plaats in de zichtbare op de kaart Arena of Bibliotheek op afstand.',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Helm van de held',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '4 afgelegen plaatsingen van een wezen op Arena per dag',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Dit artefact staat je toe om jouw wezen, 4 keer per dag, te plaatsen op een vrije plaats in de zichtbare op de kaart Arena of Bibliotheek op afstand.',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Helm van de drakenvechter',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '5 afgelegen plaatsingen van een wezen op Arena per dag',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Dit artefact staat je toe om jouw wezen, 5 keer per dag, te plaatsen op een vrije plaats in de zichtbare op de kaart Arena of Bibliotheek op afstand.',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Vaandel van de beheerser van Arena\'s',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Staat je toe om nog één wezen in de Arena te plaatsen',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'Met dit artefact kun je twee wezens plaatsen, in plaats van één, om de Arena of de Bibliotheek te verdedigen',
    'key.artifact.ARTIFACT_BANK_8': 'Uitgeknipt artefact',
    'key.artifact.ARTIFACT_BANK_8.description': 'Hoe heb je het allemaal gevonden?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Je hebt een artefact gezien, die je niet had moeten zien. We moeten nu van jou, de ongewenste getuige, zien af te komen.',
    'key.artifact.ARTIFACT_BANK_9': 'Uitgeknipt artefact',
    'key.artifact.ARTIFACT_BANK_9.description': 'Hoe heb je het allemaal gevonden?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Je hebt een artefact gezien, die je niet had moeten zien. We moeten nu van jou, de ongewenste getuige, zien af te komen.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Klok van de luie student',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 seconden naar de herlading van de Pilaren van Overvloed',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'Met dit artefact zullen de Pilaren van Overvloed met 40 seconden sneller herladen worden, waardoor je ze vaker kunt gebruiken.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Wekker van de gewoonlijke laatkomer',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 seconden naar de herlading van de Pilaren van Overvloed',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'Met dit artefact zullen de Pilaren van Overvloed met 60 seconden sneller herladen worden, waardoor je ze vaker kunt gebruiken.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Ruimte versneller',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 seconden naar de herlading van de Pilaren van Overvloed',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'Met dit artefact zullen de Pilaren van Overvloed met 60 seconden sneller herladen worden, waardoor je ze vaker kunt gebruiken.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Horloge van de luie professor',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 seconden naar de herlading van de Pilaren van Overvloed',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'Met dit artefact zullen de Pilaren van Overvloed met 80 seconden sneller herladen worden, waardoor je ze vaker kunt gebruiken.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Horloge van het zebra-konijn',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 seconden naar de herlading van de Pilaren van Overvloed',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'Met dit artefact zullen de Pilaren van Overvloed met 100 seconden sneller herladen worden, waardoor je ze vaker kunt gebruiken.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'De vlag van de verovenaar',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 naar het niveau van de Arena, na de verovering',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Als de eigenaar van dit artefact de eerste is die zijn wezen in de veroverde Arena plaatst, bereikt de Arena onmiddellijk niveau 5 in plaats van niveau 3.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Ring van de belastingverzamelaar',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 naar het maximum van de veroverde Arena\'s',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'Met dit artefact kun je belastingen inzamelen van 11 arena\'s in plaats van gewone 10.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Ring van gierigheid',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 naar het maximum van de veroverde Arena\'s',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'Met dit artefact kun je belastingen inzamelen van 12 arena\'s in plaats van gewone 10.',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Dubbelring',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 naar het maximum van de Arena\'s van welke je belastingen kunt inzamelen',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'Met dit artefact kun je belastingen inzamelen van 13 arena\'s in plaats van gewone 10.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Beker van de taart eter',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% naar de ervaring van de geallieerde Arena\'s en Bibliotheken gedurende de training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'Dit artefact geeft geallieerde Arena\'s en Bibliotheken 20% meer ervaring wanneer je ze aanvalt.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Beker voor de honing',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% naar de ervaring van de geallieerde Arena\'s en Bibliotheken gedurende de training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'Dit artefact geeft geallieerde Arena\'s en Bibliotheken 30% meer ervaring wanneer je ze aanvalt.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Kelk van diepe gedachten',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% naar de ervaring van de geallieerde Arena\'s en Bibliotheken gedurende de training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'Dit artefact geeft geallieerde Arena\'s en Bibliotheken 40% meer ervaring wanneer je ze aanvalt.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Lancelot-Graal',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% naar de ervaring van de geallieerde Arena\'s en Bibliotheken gedurende de training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'Dit artefact geeft geallieerde Arena\'s en Bibliotheken 50% meer ervaring wanneer je ze aanvalt.',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Beker van de wezen veroveraar',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% naar de ervaring van de geallieerde Arena\'s en Bibliotheken gedurende de training',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'Dit artefact geeft geallieerde Arena\'s en Bibliotheken 80% meer ervaring wanneer je ze aanvalt.',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Totem van tweede visie',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Haalt de zwakke wezens van de radar',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Dit artefact haalt de zwakste wezens van de radar, zodat je alleen zoekt naar de sterke exemplaren',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Handleiding van de avonturier',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 minuten aan de belastinginzameling van de Arena nadat het door een tegenstander is veroverd.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'Dit artefact maakt Arena\'s beschikbaar voor belastinginzameling voor nog eens 30 minuten in plaats van de gewoonlijke 15 minuten, nadat ze waren veroverd',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Dik massief boek',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 minuten aan de belastinginzameling van de Arena nadat het door een tegenstander is veroverd.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'Dit artefact maakt Arena\'s beschikbaar voor belastinginzameling voor nog eens 45 minuten in plaats van de gewoonlijke 15 minuten, nadat ze waren veroverd',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Tablet van bezit',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 minuten aan de belastinginzameling van de Arena nadat het door een tegenstander is veroverd.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'Dit artefact maakt Arena\'s beschikbaar voor belastinginzameling voor nog eens 60 minuten in plaats van de gewoonlijke 15 minuten, nadat ze waren veroverd',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Verhandeling over het bestuur',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 minuten aan de belastinginzameling van de Arena nadat het door een tegenstander is veroverd.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'Dit artefact maakt arena\'s beschikbaar voor belastinginzameling voor nog eens 90 minuten in plaats van de gewoonlijke 15 minuten, nadat ze waren veroverd',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Grimoire van de autoriteit',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 minuten aan de belastinginzameling van de Arena nadat het door een tegenstander is veroverd.',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'Dit artefact maakt Arena\'s beschikbaar voor belastinginzameling voor nog eens 120 minuten in plaats van de gewoonlijke 15 minuten, nadat ze waren veroverd',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Puntige halsband',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% toename in de snelheid van het ontvangen van zielenstenen van uw huisdier',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'Met dit artefact hoef je 10% minder te lopen met je huisdier om zielenstenen te ontvangen. Het maakt jouw huisdier ook met 17% meer formidabel',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Wortel op een stokje',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% toename in de snelheid van het ontvangen van zielenstenen van uw huisdier',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'Met dit artefact hoef je 15% minder te lopen met je huisdier om zielenstenen te ontvangen. Lekker ding.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Rugkrabber',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% toename in de snelheid van het ontvangen van zielenstenen van uw huisdier',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'Met dit artefact hoef je 25% minder te lopen met je huisdier om zielenstenen te ontvangen. Buig voor de kracht van de rugkrabber!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Favoriete deuntje',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% toename in de snelheid van het ontvangen van zielenstenen van uw huisdier',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'Met dit artefact hoef je 30% minder te lopen met je huisdier om zielenstenen te ontvangen. Wie is zo\'n mooie jongen?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Rubberen draak',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% toename in de snelheid van het ontvangen van zielenstenen van uw huisdier',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'Met dit artefact hoef je 40% minder te lopen met je huisdier om zielenstenen te ontvangen. Werelds best spelletje voor het werelds beste huisdier',
    'key.artifact.ARTIFACT_ROOST_1': 'Hart van de draak',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 drakencocon voor de Moeder der Draken',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Staat je toe om een extra drakencocon te gebruiken voor de eieren van de Moeder der Draken',
    'dialog.artifact.select_artifact': 'KIES ARTEFACT',
    'dialog.artifact.confirm.remove': 'Ben je zeker dat je deze artefact wilt verwijderen?',
    'dialog.items.title': 'Tas',
    'dialog.items.cannotUse': 'Dit item kan niet gebruikt worden',
    'dialog.items.remove.header': 'Items verwijderen',
    'dialog.encounter.header': 'Een wilde monster valt aan!',
    'dialog.encounter.button.leave': 'Wegrennen',
    'dialog.encounter.button.fight': 'Vechten',
    'dialog.encounter.result.outcome.win': 'Het wilde monster is verslagen',
    'dialog.encounter.result.outcome.lose': 'Jouw wezen is verslagen',
    'dialog.encounter.result.reward.dust': 'Essentie',
    'dialog.encounter.result.reward.exp': 'XP',
    'error.nickname.validation.IS_EMPTY': 'Voer de naam van het karakter in',
    'error.nickname.validation.TOO_SHORT': 'De naam moet tussen 6 en 12 tekens lang zijn',
    'error.nickname.validation.TOO_LONG': 'De naam moet tussen 3 en 6 tekens lang zijn',
    'error.nickname.validation.INVALID_CHAR': 'Je kan alleen Latijnse letters en cijfers en het laag streepje gebruiken.',
    'error.nickname.validation.DUPLICATE': 'Deze naam is al bezet. Je kunt naam {0} nemen',
    'creature.MONSTER_WATER_1': 'Kikkerus',
    'creature.MONSTER_WATER_2': 'Druppel',
    'creature.MONSTER_WATER_3': 'Spiritus',
    'creature.MONSTER_WATER_4': 'Overaquian',
    'creature.MONSTER_WATER_5': 'Kikkerissimo',
    'creature.MONSTER_WATER_6': 'Beekje',
    'creature.MONSTER_WATER_7': 'Kelpie',
    'creature.MONSTER_WATER_8': 'Kwallehoed',
    'creature.MONSTER_WATER_9': 'Minor',
    'creature.MONSTER_WATER_10': 'Infalisk',
    'creature.MONSTER_WATER_11': 'Mediaquian',
    'creature.MONSTER_WATER_12': 'Dadachock',
    'creature.MONSTER_WATER_13': 'Batoid',
    'creature.MONSTER_WATER_14': 'Puerolisk',
    'creature.MONSTER_WATER_15': 'Falhor',
    'creature.MONSTER_WATER_16': 'Tentahoed',
    'creature.MONSTER_WATER_17': 'Onderaquian',
    'creature.MONSTER_WATER_18': 'Dadachum',
    'creature.MONSTER_WATER_19': 'Mantari',
    'creature.MONSTER_WATER_20': 'Basilisk',
    'creature.MONSTER_WATER_21': 'Melhor',
    'creature.MONSTER_WATER_22': 'Kristalhoed',
    'creature.MONSTER_WATER_23': 'Pantserank',
    'creature.MONSTER_WATER_24': 'Neptunus',
    'creature.MONSTER_WATER_25': 'Leviathan',
    'creature.MONSTER_FIRE_1': 'Potty',
    'creature.MONSTER_FIRE_2': 'Mummiekeen',
    'creature.MONSTER_FIRE_3': 'Dampes',
    'creature.MONSTER_FIRE_4': 'Incumus',
    'creature.MONSTER_FIRE_5': 'Vurepoot',
    'creature.MONSTER_FIRE_6': 'Vlammetje',
    'creature.MONSTER_FIRE_7': 'Fobia',
    'creature.MONSTER_FIRE_8': 'Dompiekeen',
    'creature.MONSTER_FIRE_9': 'Lavion',
    'creature.MONSTER_FIRE_10': 'Helzeeman',
    'creature.MONSTER_FIRE_11': 'Sprank',
    'creature.MONSTER_FIRE_12': 'Kindra',
    'creature.MONSTER_FIRE_13': 'Demonster',
    'creature.MONSTER_FIRE_14': 'Feniks',
    'creature.MONSTER_FIRE_15': 'Naaldeheet',
    'creature.MONSTER_FIRE_16': 'Ijzervent',
    'creature.MONSTER_FIRE_17': 'Vuurvlieg',
    'creature.MONSTER_FIRE_18': 'Caesar',
    'creature.MONSTER_FIRE_19': 'Flits',
    'creature.MONSTER_FIRE_20': 'Flibustus',
    'creature.MONSTER_FIRE_21': 'Tempter',
    'creature.MONSTER_FIRE_22': 'Hydra',
    'creature.MONSTER_FIRE_23': 'Saluut',
    'creature.MONSTER_FIRE_24': 'Picaroon',
    'creature.MONSTER_FIRE_25': 'Smoargh',
    'creature.MONSTER_EARTH_1': 'Bessedillo',
    'creature.MONSTER_EARTH_2': 'Bloemie',
    'creature.MONSTER_EARTH_3': 'Blaadje',
    'creature.MONSTER_EARTH_4': 'Brownie',
    'creature.MONSTER_EARTH_5': 'Shamurf',
    'creature.MONSTER_EARTH_6': 'Dryade',
    'creature.MONSTER_EARTH_7': 'Plantic',
    'creature.MONSTER_EARTH_8': 'Disguir',
    'creature.MONSTER_EARTH_9': 'Bellflow',
    'creature.MONSTER_EARTH_10': 'Eikeling',
    'creature.MONSTER_EARTH_11': 'Phylo',
    'creature.MONSTER_EARTH_12': 'Brag',
    'creature.MONSTER_EARTH_13': 'Princie',
    'creature.MONSTER_EARTH_14': 'Dennenbeer',
    'creature.MONSTER_EARTH_15': 'Dao',
    'creature.MONSTER_EARTH_16': 'Trol',
    'creature.MONSTER_EARTH_17': 'Dwantflow',
    'creature.MONSTER_EARTH_18': 'Chappian',
    'creature.MONSTER_EARTH_19': 'Gardrag',
    'creature.MONSTER_EARTH_20': 'Springan',
    'creature.MONSTER_EARTH_21': 'Aardgeboren',
    'creature.MONSTER_EARTH_22': 'Parabeest',
    'creature.MONSTER_EARTH_23': 'Yogi',
    'creature.MONSTER_EARTH_24': 'Grendel',
    'creature.MONSTER_EARTH_25': 'Scylla',
    'creature.MONSTER_WIND_1': 'SunTzi',
    'creature.MONSTER_WIND_2': 'Oormuizel',
    'creature.MONSTER_WIND_3': 'Zwammie',
    'creature.MONSTER_WIND_4': 'Donzihoorn',
    'creature.MONSTER_WIND_5': 'Airver',
    'creature.MONSTER_WIND_6': 'Gamayun',
    'creature.MONSTER_WIND_7': 'Spookje',
    'creature.MONSTER_WIND_8': 'Oorett',
    'creature.MONSTER_WIND_9': 'Eskimo',
    'creature.MONSTER_WIND_10': 'Windans',
    'creature.MONSTER_WIND_11': 'Infird',
    'creature.MONSTER_WIND_12': 'Undine',
    'creature.MONSTER_WIND_13': 'Stormhoorn',
    'creature.MONSTER_WIND_14': 'Phantomo',
    'creature.MONSTER_WIND_15': 'Cheshir',
    'creature.MONSTER_WIND_16': 'Paddetopie',
    'creature.MONSTER_WIND_17': 'Harpij',
    'creature.MONSTER_WIND_18': 'Geestus',
    'creature.MONSTER_WIND_19': 'Puerogryph',
    'creature.MONSTER_WIND_20': 'Kussenkat',
    'creature.MONSTER_WIND_21': 'Hippofly',
    'creature.MONSTER_WIND_22': 'Stormdina',
    'creature.MONSTER_WIND_23': 'Griffioen',
    'creature.MONSTER_WIND_24': 'Dodijner',
    'creature.MONSTER_WIND_25': 'Charybdis',
    'creature.MONSTER_DUNGEON_1': 'Roekie',
    'creature.MONSTER_DUNGEON_2': 'Axolan',
    'creature.MONSTER_DUNGEON_3': 'Spijkerug',
    'creature.MONSTER_DUNGEON_4': 'Magglad',
    'creature.MONSTER_DUNGEON_5': 'Lievekat',
    'creature.MONSTER_DUNGEON_6': 'Rosie',
    'creature.MONSTER_DUNGEON_7': 'Marid',
    'creature.MONSTER_DUNGEON_8': 'Grandalotl',
    'creature.MONSTER_DUNGEON_9': 'Vogelschrik',
    'creature.MONSTER_DUNGEON_10': 'Snailyn',
    'creature.MONSTER_DUNGEON_11': 'Genie',
    'creature.MONSTER_DUNGEON_12': 'Vampiero',
    'creature.MONSTER_DUNGEON_13': 'Rups',
    'creature.MONSTER_DUNGEON_14': 'Mantikid',
    'creature.MONSTER_DUNGEON_15': 'Twist',
    'creature.MONSTER_DUNGEON_16': 'Zachtestaart',
    'creature.MONSTER_DUNGEON_17': 'Inur',
    'creature.MONSTER_DUNGEON_18': 'Stoeracula',
    'creature.MONSTER_DUNGEON_19': 'Absolerm',
    'creature.MONSTER_DUNGEON_20': 'Tijgermant',
    'creature.MONSTER_DUNGEON_21': 'Scherpestaart',
    'creature.MONSTER_DUNGEON_22': 'Rozenknop',
    'creature.MONSTER_DUNGEON_23': 'Curly',
    'creature.MONSTER_DUNGEON_24': 'Manticore',
    'creature.MONSTER_DUNGEON_25': 'Morgoroth',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Haaienbeet',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Griezel uit de diepte',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Roep van Katulu',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Zeehamer',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Watervuist',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Golf',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Wolkbreuk',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Geiser',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Spatten',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Levende vlam',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Vuurvinger',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Vuurzweep',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Vuurbal',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Afbrander',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Ster',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Kolen',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Vlammenwerper',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Fusillade',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Luchtsikkel',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Verbreker',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Adem',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Elektrische shock',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Bolbliksem',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Schoktherapie',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Drakenzucht',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Vleugje',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Woede van de wind',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Giftige spuug',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Slangentand',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Vergiftiging',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Ruggengraat breker',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Rots',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Kiezelsteen',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Bosgeest',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Boomspook',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Schaduw van de natuur',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Pijl van Arcana',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Klont van duister',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Tentakel van kwaad',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Oog van gruwel',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Sfeer van gevaar',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Bol van duister',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Arcana Kadavra',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Cruciarcus',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Impericanus',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Glaciaal',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Bevriezing',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Kristallisatie',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Wervelstorm',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Sneeuwstorm',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Tsunami',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Koude woede',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Ijzige ontploffing',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Macht van het ijs',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Zuivering',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Hemelvaart',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Verschroeiing',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Napalm',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Lava',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Vuurfontein',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Meteoren',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Dinocide',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Armageddon',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Bliksem',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Donder',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Storm',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Herlading',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Röntgen',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Kippenvel',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Tornado',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Brul van de wind',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Carrousel',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Gedonder',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Beving',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Breuk',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Ineenstorting',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Explosie',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Werveling van stenen',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Meer van de dood',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Giftige plas',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Zuur',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Atomisatie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Desintegratie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Splitsing',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Verbanning',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Vloek',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Uitzondering',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Storm van magie',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Manastorm',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Furie van Arcana',
    'key.combined.first.1': 'Wijze',
    'key.combined.first.2': 'Hels',
    'key.combined.first.3': 'Prachtige',
    'key.combined.first.4': 'Boosaardige',
    'key.combined.first.5': 'Neutrale',
    'key.combined.first.6': 'Eerlijke',
    'key.combined.first.7': 'Engelachtige',
    'key.combined.first.8': 'Oeroude',
    'key.combined.first.9': 'Ondergrondse',
    'key.combined.first.10': 'Vurige',
    'key.combined.first.11': 'Behendige',
    'key.combined.first.12': 'Gigantische',
    'key.combined.first.13': 'Blauwe',
    'key.combined.first.14': 'Wrede',
    'key.combined.first.15': 'Aardige',
    'key.combined.first.16': 'Luchtige',
    'key.combined.first.17': 'Aarde',
    'key.combined.first.18': 'Rode',
    'key.combined.first.19': 'Onsterfelijke',
    'key.combined.first.20': 'Omgekomen',
    'key.combined.first.21': 'Luchtige',
    'key.combined.first.22': 'Griezelige',
    'key.combined.first.23': 'Water',
    'key.combined.first.24': 'Vermakelijke',
    'key.combined.first.25': 'Stomme',
    'key.combined.second.1': 'Helden',
    'key.combined.second.2': 'Vissen',
    'key.combined.second.3': 'Uilen',
    'key.combined.second.4': 'Schurken',
    'key.combined.second.5': 'Knechten',
    'key.combined.second.6': 'Magiërs',
    'key.combined.second.7': 'Ouderlingen',
    'key.combined.second.8': 'Bezweerders',
    'key.combined.second.9': 'Strijders',
    'key.combined.second.10': 'Duelers',
    'key.combined.second.11': 'Handelaren',
    'key.combined.second.12': 'Konijnen',
    'key.combined.second.13': 'Appels',
    'key.combined.second.14': 'Vechters',
    'key.combined.second.15': 'Goochelaars',
    'key.combined.second.16': 'Ridders',
    'key.combined.second.17': 'Barbaren',
    'key.combined.second.18': 'Kevers',
    'key.combined.second.19': 'Slangen',
    'key.combined.second.20': 'Draken',
    'key.combined.second.21': 'Geesten',
    'key.combined.second.22': 'Katjes',
    'key.combined.second.23': 'Soldaten',
    'key.combined.second.24': 'Bofkonten',
    'key.combined.second.25': 'Moordenaars',
    'key.combined.second.26': 'Muizen',
    'key.combined.second.27': 'Elementair',
    'key.combined.second.28': 'Onderzoekers',
    'key.combined.second.29': 'Sjamanen',
    'key.combined.second.30': 'Priesters',
    'key.combined.second.31': 'Engelen',
    'key.combined.second.32': 'Archonten',
    'key.combined.second.33': 'Beulen',
    'key.combined.second.34': 'Dwaashoofden',
    'key.combined.second.35': 'Dappere personen',
    'key.combined.second.36': 'Vriendelijke zielen',
    'key.combined.second.37': 'Lafaards',
    'key.combined.second.38': 'Troubadours',
    'key.combined.second.39': 'Temmers',
    'key.combined.second.40': 'Verdedigers',
    'key.combined.arena': 'Arena van {0} {1}',
    'key.combined.library': 'Bibliotheek van {0} {1}',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Water',
    'element.type.WIND': 'Wind',
    'element.type.FIRE': 'Vuur',
    'element.type.EARTH': 'Aarde',
    'element.type.DUNGEON': 'Arcana',
    'spell.type.ACTIVATION_RADIUS': 'Bereik van activatie',
    'spell.type.VISION_RADIUS': 'Drakenzicht',
    'spell.type.STOP_FIELD': 'Veld van Overvloed',
    'spell.type.SCOUT': 'Verkenning',
    'spell.type.PROTECT_ARENA': 'Verdediging van Arena',
    'spell.type.CREATE_PORTAL': 'Portaal creëren',
    'spell.type.ARMAGEDDON': 'Armageddon',
    'spell.type.DOUBLE_DROP': 'Dubbele daling',
    'spell.type.SLUG_PLAYERS': 'Слизнякнуть игроков',
    'quest.title.WIN_ARENA_MONSTER': 'Overheersing',
    'quest.title.OPEN_EGGS': 'Eierkoorts',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Territoriale controle',
    'quest.title.CAPTURE_LIBRARY': 'Zucht naar kennis',
    'quest.title.CAPTURE_WILD_MONSTER': 'Drakonic Park',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Jacht op element',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Zoektocht naar de Arcanageboren',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Breukopschoning',
    'quest.title.OPEN_CHEST': 'Oude schatten',
    'quest.title.CHAIN_OF_STOP': 'Weg van Overvloed',
    'quest.desc.WIN_ARENA_MONSTER': 'Versla wezens in de Arena of in de Bibliotheek. Je kan niet wezen van hetzelfde type twee keer verslaan. ',
    'quest.desc.OPEN_EGGS': 'Broed monsters uit eieren, met behulp van de drakencocons of de Moeder der Draken',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Zamel belastingen in van de door jou veroverde Arena\'s',
    'quest.desc.CAPTURE_LIBRARY': 'Maak van jouw wezen een verdediger van elke nieuwe Bibliotheek.',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Je kunt nooit teveel wezens hebben. Reis en vang ze.',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Reis en vang wezens van het element Water',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Reis en vang wezens van het element Wind',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Reis en vang wezens van het element Vuur',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Reis en vang wezens van het element Aarde',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Reis en vang wezens van het element Arcana',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Bezoek de Breuk van Arcana, om de Moeder der Draken te vinden',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Bezoek de Breuk van Arcana en vang alle wezens die je daar vindt',
    'quest.desc.OPEN_CHEST': 'Vind en open kisten met schatten',
    'quest.desc.CHAIN_OF_STOP': 'Loop langs de reeks van Pilaren van Overvloed en activeer ze. Elke volgende Pilaar zal gemarkeerd zijn.',
    'quest.dialog.completed.rewardtext': 'Je krijgt beloning voor het volooien van deze opdracht:',
    'key.tab.altar.title': 'ALTAAR',
    'key.altar.remove': 'Verwijderen',
    'key.altar.put': 'Installeren',
    'key.altar.convert': 'Omzetten',
    'key.altar.shared': 'Deel met anderen',
    'key.altar.pass.placeholder': 'Hier kun je je wachtwoord invoeren',
    'key.altar.pass.error': 'Het wachtwoord moet minimaal {0} tekens bevatten',
    'key.altar.level.error': 'Je moet eerst niveau {0} bereiken om het Altaar te kunnen gebruiken',
    'key.altar.recipe.change': 'Weet je zeker dat je het recept wilt veranderen? De runen worden teruggegeven aan hun eigenaren',
    'key.altar.row.title': 'Om toverspreuk te creëren, heb je een Altaar nodig',
    'key.altar.rune.descr.RUNE_1': '3 groene runen = oranje',
    'key.altar.rune.descr.RUNE_2': '3 oranje runen = blauwe',
    'key.altar.rune.descr.RUNE_3': '3 blauwe runen = smaragd',
    'key.altar.rune.descr.RUNE_4': '3 smaragd runen = rode',
    'key.altar.rune.descr.RUNE_5': '3 rode runen = paarse',
    'key.altar.rune.descr.RUNE_6': 'De paarse runes zijn het meest krachtig',
    'error.altar.cannotRemove': 'Het Altaar kan niet verwijderd worden',
    'error.altar.cannotConvert': 'Je hebt niet genoeg runen',
    'key.tab.altar.recipes': 'RECEPTEN',
    'key.altar.noRecipes': 'Je hebt geen recepten',
    'key.altar.header': 'Plaats runen op het Altaar om een toverspreuk uit te spreken',
    'key.altar.castBtn': 'Uitspreken',
    'key.altar.recipe.select': 'Kies de nodige toverspreuk',
    'key.altar.castDone': 'Toverspreuk is uitgesproken',
    'key.arena.protected.ally': 'Verdedigd:',
    'key.avatarCustomization.title': 'Kies het uiterlijk van je karakter:',
    'key.buddy.walkDescription': 'Wandel met jouw huisdier om {0} te ontvangen',
    'key.buddy.totalWalked': 'Je hebt {0} km gelopen',
    'key.account.balance': 'Grondstoffen:',
    'key.account.userLevel': '{0} niveau',
    'key.account.totalDistance': 'Gelopen afstand: {0} kilometers',
    'key.acount.registerDate': 'Startdatum: {0}',
    'key.storage.sort.name': 'NAAM',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'GROENE LIJST',
    'key.storage.sort.group2': 'GELE LIJST',
    'key.storage.sort.group3': 'RODE LIJST',
    'key.storage.sort.date': 'DATUM',
    'key.account.options.jurnal': 'JOURNAAL',
    'key.account.options.buddy': 'HUISDIER',
    'key.account.options.artifacts': 'ARTEFACTEN',
    'key.account.options.style': 'STIJL',
    'key.error.gps.permission': 'GPS is niet beschikbaar. Activeer je GPS om verder te spelen',
    'key.error.gps.disabled': 'GPS is uitgeschakeld. Schakel de GPS in om verder te gaan met het spel',
    'key.error.gps.fakePosition': 'Je kan niet spelen zonder GPS',
    'key.error.gps.signal.notFound': 'Geen GPS signaal',
    'key.error.gps.signal.bad': 'Het spel is niet beschikbaar. GPS signaal is te zwak',
    'key.error.internet.notReachable': 'Geen Internet verbinding',
    'key.journal.title': 'Journaal',
    'key.journal.yesterday': 'Gisteren',
    'key.settings.title': 'Instellingen',
    'key.settings.music': 'Muziek',
    'key.settings.deviceAuthError': 'For safety reasons, please link your account to Google or Facebook',
    'key.settings.sounds': 'Geluiden',
    'key.settings.vibration': 'Trilling',
    'key.settings.batterySaver': 'Batterij besparing',
    'key.settings.support': 'Contact opnemen met klantendienst',
    'key.settings.logout': 'Uitloggen',
    'key.settings.auth.deviceid': 'ID van het toestel',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Koppelen',
    'key.settings.languageTitle': 'Taal',
    'key.settings.language': 'Nederlands',
    'key.battle.result.win': 'De strijd is voorbij',
    'key.battle.result.lose': 'De strijd is voorbij',
    'key.wizardBattle.result.win': 'OVERWINNING!',
    'key.wizardBattle.result.lose': 'VERLIES!',
    'key.battle.result.monster': 'Verslagen wezens',
    'key.battle.result.exp': 'Bonus ervaring',
    'key.battle.result.prestige_strong_enemy': 'Prestige bonus voor de sterke vijanden',
    'key.battle.result.exp_strong_enemy': 'Ervaringsbonus voor de sterke vijanden',
    'key.battle.result.prestige_killed_all': 'Prestige bonus voor het vermoorden van iedereen',
    'key.battle.result.exp_killed_all': 'Ervaringsbonus voor het vermoorden van iedereen',
    'key.battle.result.dust': 'Essentie',
    'key.radar.title': 'Wezens in de buurt',
    'key.levelUp.title': 'Nieuw niveau!',
    'key.wizardBattle.left': 'Limiet van strijden:',
    'key.wizardBattle.timer': 'Limiet wordt opnieuw ingesteld over',
    'key.wizardBattle.enhance.title': 'VERGROTEN VAN HET LIMIET',
    'key.wizardBattle.enhance.desc': 'Je kunt je strijdlimiet tot 7 keer per week voor een week verhogen',
    'key.wizardBattle.enhance.btn': 'Vergroten',
    'key.wizardBattle.lookingForOpponent': 'Zoekt naar een tegenstander voor een duel...',
    'key.catch.result.expMonster': 'Ervaring voor de vangst:',
    'key.catch.result.expMonsterNew': 'Nieuw in het Beestiarium:',
    'key.catch.result.expAccurate': 'Voor het nauwkeurige gooi:',
    'key.catch.result.expSpin': 'Voor een gedraaide gooi:',
    'key.catch.result.strike': 'Jouw eerste wezen van vandaag:',
    'key.catch.result.total': 'Totale ervaring:',
    'key.catch.fullStorage': 'Wezensbergplaats is vol',
    'key.catch.noItems': 'Je hebt geen magische sferen',
    'key.creadex.title': 'Bibiliotheek van wezens',
    'key.creadex.detail.caught': 'GEVANGEN: {0}',
    'key.creadex.detail.evolution': 'Evolutie',
    'key.tab.doll': 'KARAKTER',
    'key.tab.artifacts': 'ARTEFACTEN',
    'key.activePoint.title': 'Pilaar van Overvloed',
    'key.personalization.title': 'Betovering',
    'key.chest.title': 'Magische kist',
    'key.quest.daily.title': 'OPDRACHT',
    'key.quest.weekly.title': 'JACHT',
    'key.quest.get': 'OPDRACHT KRIJGEN',
    'key.quest.change': 'OPDRACHT VERANDEREN',
    'key.quest.progress': 'Vooruitgang van de opdracht: {0} van {1}',
    'key.error.quest.weekly.level': 'Je moet eerst niveau {0} bereiken om de jacht naar het Gouden Ei te beginnen',
    'key.error.quest.daily.level': 'Je moet eerst niveau {0} bereiken om een opdracht te ontvangen',
    'key.error.quest.tooFar': 'Obelisk is te ver weg',
    'key.quest.daily.descr.noQuest.title': 'Je hebt geen opdrachten',
    'key.quest.daily.descr.noQuest': 'Je hebt geen opdrachten. Gebruik de Obelisk om een opdracht te krijgen en beloning te verdienen.',
    'key.quest.daily.timer.descr': 'Je kunt deze opdracht veranderen over:',
    'key.quest.daily.waitForNew.descr': 'Je kunt een nieuwe opdracht krijgen over: ',
    'key.quest.weekly.getFragment': 'FRAGMENT KRIJGEN',
    'key.quest.weekly.descr.noQuest.title': 'Je neemt geen deel aan de jacht naar het Gouden Ei',
    'key.quest.weekly.descr.noQuest': 'Je doet niet mee met de jacht naar het Gouden Ei. Gebruik de Obelisk om een fragment van de mysterieuze kaart te ontvangen en te beginnen met de jacht.',
    'key.quest.weekly.descr.getFirstFragment': 'Krijg het eerste fragment van de mysterieuze kaart om de jacht naar het Gouden Ei te beginnen',
    'key.quest.weekly.descr.top.notAllOpen': 'Gebruik Obelisken om de kaartfragmenten te krijgen. Schiet op, de jacht zal stoppen over',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Gebruik de schop op elk fragment om het Gouden Ei te vinden',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Je hebt het kaartfragment van deze Obelisk al ontvangen',
    'key.quest.weekly.descr.top.allOpen': 'Alle kaartfragmenten van de Obelisken zijn al ontvangen. Schiet op, de jacht zal stoppen over',
    'key.quest.weekly.descr.bot.allOpen': 'Gebruik de schop op elk fragment om het Gouden Ei te vinden',
    'key.quest.weekly.descr.top.completed': 'Deze week heb je het Gouden Ei al gevonden. Volgende jacht begint over',
    'key.timer.format.S': '{0}s',
    'key.timer.format.M': '{0}m',
    'key.timer.format.M_S': '{0}m {1}s',
    'key.timer.format.H': '{0}u',
    'key.timer.format.H_M': '{0}u {1}m',
    'key.timer.format.D': '{0}d',
    'key.timer.format.D_H': '{0}d {1}u',
    'key.creatureStorage.tab.creatures': 'WEZENS',
    'key.creatureStorage.tab.eggs': 'EIEREN',
    'key.creatureStorage.multiTransferText': 'Kies welk wezen je wilt weggeven',
    'key.storage.creature.transfer': 'Weggeven ({0})',
    'key.error.needHigherLevelForArena': 'Je hebt niveau {0} nodig om toegang te krijgen tot Arena',
    'key.error.needHigherLevelForLibrary': ' Je hebt niveau {0} nodig om toegang te krijgen tot Bibliotheek',
    'key.error.arenaUnderProtection': 'De Arena wordt beveiligd door de Zegening van Bescherming',
    'key.error.buildingTooFar': 'Het gebouw is te ver weg',
    'key.error.noAliveCreaturesForAttack': 'Je hebt geen levende wezens',
    'key.error.noHealPotion': 'Je hebt geen genezende drankjes',
    'key.error.noResurrectionPotion': 'Je hebt geen herrijzende drankjes',
    'key.error.tryAgainLater': 'Fout. Probeer het later opnieuw.',
    'key.error.alreadyHasLure': 'Het lokmiddel is ingesteld',
    'key.error.cannotUseLureInDungeon': 'De lok kan niet in de Breuk van Arcana gebruikt worden',
    'key.error.bagIsFull': 'Er is geen plaats in de tas',
    'key.error.cantTransferCreature': 'Het is onmogelijk om dit wezen weg te geven',
    'key.notification.done': 'Klaar!',
    'key.modal.doYouWantToTransfer': 'Weet je zeker dat je deze wezens weg wilt geven?',
    'key.modal.youWillLoseBuddyProgress': 'Weet je zeker dat je je huisdier wilt veranderen? De voortgang van het ontvangen van een zielsteen wordt geannuleerd.',
    'key.modal.doYouWantToLeaveDungeon': 'Wil je de Breuk van Arcana verlaten?',
    'key.modal.superVisionActive': 'Drakenzicht is al geactiveerd. Als je het nogmaals toepast dan wordt de magische zone van de zichtbaarheid verplaatst. Weet je zeker dat je het nogmaals wilt gebruiken?',
    'key.modal.experienceBoosterActive': 'Kristal van wijsheid is al geactiveerd. Weet je zeker dat je het nogmaals wilt gebruiken?',
    'key.modal.youWillLooseQuestProgress': 'De voortgang van uw huidige opdracht zal verloren gaan. Weet je het zeker?',
    'key.modal.doYouWantToEnterDungeon': 'Wil je via het Portaal de Breuk van Arcana binnengaan?',
    'key.modal.doYouWantPersonalizePoint': 'Weet je zeker dat je de Pilaar van Overvloed wilt betoveren, zodat het {0} voor {1} munten geeft?',
    'key.modal.doYouWantToDeletePersonalization': 'Weet je het zeker dat je de betovering van deze Pilaar van Overvloed wilt annuleren?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Wil je dit wezen versterken?',
    'key.modal.doYouWantToEvolveThisCreature': 'Wil je dit wezen sterker maken?',
    'key.modal.doYouWantToScoutHere': 'Weet je zeker dat je deze locatie wilt verlichten?',
    'key.error.creatureHasMaxLevel': 'Het wezen heeft al het maximale niveau bereikt',
    'key.error.creatureHasMaxLevelForUser': 'Verhoog eerst het niveau van je karakter',
    'key.error.notEnoughResourcesForEnhance': 'Niet genoeg grondstoffen',
    'key.error.creatureIsArenaDefender': 'Je kan niet een wezen kiezen die het gebouw verdedigt',
    'key.modal.incenseActive': 'De feromonen zijn al geactiveerd. Weet je het zeker dat je ze nogmaals wilt gebruiken?',
    'key.error.cantHealHealthyCreature': 'Het wezen is volledig genezen',
    'key.error.cantRessurectAliveCreature': 'Het wezen leeft al',
    'key.error.noTreasureHere': 'Er is geen Gouden Ei op dit fragment van de kaart. Blijf zoeken.',
    'key.error.levelTooSmall': 'Verhoog eerst het niveau van je karakter',
    'key.error.needHigherLevelForWizardBattles': 'Niveau {0} is vereist voor de deelneming aan het Duel van Magiërs',
    'key.error.artifactBagIsFull': 'Artefactenopslag is vol',
    'key.error.notEnoughCoins': 'Niet genoeg muntenт',
    'key.error.allFragmentsAreOpen': 'Alle fragmenten van de mysterieuze kaart zijn geopend',
    'key.error.questAlreadyCompleted': 'De opdracht is al voltooid',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Van deze Obelisk heb je al een kaartfragment gekregen',
    'key.error.portalTooFarAway': 'Portaal is te ver weg',
    'key.error.battleLimitAlreadyEnhanced': 'Het limiet van strijden is al verhoogd',
    'key.error.youAreNotAltarOwner': 'Alleen de eigenaar van het Altaar kan dit doen',
    'key.error.youAlreadyHaveAltar': 'Het Altaar is al geinstalleerd',
    'key.error.cantTakeAnotherUsersRune': 'Je kan niet de rune van een andere speler nemen',
    'key.error.libraryBlocked': 'Je dient 3 dagen na de omscholing te wachten om Bibliotheken te kunen gebruiken',
    'key.error.notAuthorized': 'Gebruiker is niet geautoriseerd',
    'key.error.eggOnlyRoost': 'Dit ei moet je aan de Moeder der Draken geven',
    'key.error.purchase': 'Fout: {0}',
    'key.error.creatureIsDead': 'Eerst moet je het wezen herrijzen',
    'key.error.no_connection': 'Verbinding met de server is mislukt. Probeer het later nogmaals.',
    'key.error.protocol_version_mismatch': 'Versie van het spel is verouderd. Update is vereist.',
    'key.error.update_application': 'Versie van het spel is verouderd. Update is vereist.',
    'key.modal.doYouWantToTransferSingle': 'Weet je het zeker dat je dit wezen wilt weggeven?',
    'key.notification.phoneNotSupportAR': 'Jouw toestel ondersteunt AR niet',
    'key.notification.turnOnARPermission': 'Het spel heeft geen toegang tot de camera. Verleen toegang in de instellingen',
    'key.notification.dailyQuestFinished': 'De opdracht is voltooid!',
    'key.modal.yesBtn': 'Ja',
    'key.modal.noBtn': 'Nee',
    'event.log.DAILY_QUEST_COMPLETED': 'Dagelijkse opdracht is voltooid. Je hebt beloningen ontvangen:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Jacht is beeindigd! Jouw beloning:',
    'event.log.ENCOUNTER_VICTORY': 'Je hebt een wilde monster verslagen!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Versie van het spel is verouderd. Update is nodig.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Authenticatie is mislukt.',
    'key.ServiceException.Cause.SESSION_GONE': 'Iemand is ingelogd op jouw account vanaf een ander apparaat',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'De gebruikersnaam is leeg',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Gebruiker is niet gevonden',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Account werd vanwege oneerlijk spelen geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Account werd vanwege fraude geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Account werd vanwege een beledigende gebruikersnaam  geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Account werd vanwege intimidatie geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Account werd vanwege oneerlijk spelen geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.USER_BANNED': 'Account werd geblokkeerd. Datum van deblokkering: [unban_date_dont_translate]',
    'key.ServiceException.Cause.BAG_IS_FULL': 'Er is geen plaats in de tas',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Maximale hoeveelheid van eieren',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Niet genoeg munten',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Niet genoeg zielstenen',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Niet genoeg essentie',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'Wezensbergplaats is vol',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Het wezen heeft al het maximale niveau bereikt',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Je kunt dit wezen niet evolueren',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'De naam van het wezen mag niet meer dan 14 tekens bevatten',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'Het gebouw heeft al het maximale aantal verdedigers bereikt',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'De verdediger van het gebouw mag niet een huisdier worden',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Jouw wezen verdedigt al dit gebouw',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Fout',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Strijd is niet gevonden',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Fout',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Jouw wezen verdedigt al deze Arena',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'De Arena is onder de beveiliging van de Zegening van Bescherming',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'De tijd voor belastinginzameling is nog niet gekomen',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Verkeerde sfeer',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Verkeerd gebouw',
    'key.ServiceException.Cause.ACCESS_DENIED': 'De toegang is geweigerd',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Geen dergelijk item',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Geen dergelijk recept',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Je kunt slechts één Altaar installeren',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Eerst dien je het niveau van je karakter te verhogen',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Het is niet gelukt om de wezenvangst te beginnen',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Geen dergelijk product',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Geen dergelijk product',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': ' Geen dergelijk gebouw',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Geen dergelijk wezen',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Geen dergelijk wezen',
    'key.ServiceException.Cause.TOO_FAR': 'Het gebouw is te ver weg',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'De object is te ver weg',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Het gebouw wordt herladen',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Het gebouw is in de Breuk van Arcana',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Het gebouw kan niet worden gebruikt',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Drakencocon is niet gevonden',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Drakencocon is leeg',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Drakencocon is bezet',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Ei is niet uitgebroed',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Geen ei gevonden',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Je hebt Moeder der Draken nodig voor dit ei',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Geen opladingen meer',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Het plaatsen van het gebouw is mislukt',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Er is een fout opgetreden en dit is een geheimzinnige boodschap erover',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Het wilde monster is weggerend',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Het wilde monster is niet gevonden',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'Deze Pilaar van Overvloed heeft al een lokmiddel',
    'key.ServiceException.Cause.WRONG_ITEM': 'Verkeerd item',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Deze rune is de krachtigste',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Niet genoeg runen van dit niveau',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Verkeerde plaats voor de rune',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Deze plaats is al bezet',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'De rune plaats is leeg',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'De verdediger van gebouw kan niet gekozen worden',
    'key.ServiceException.Cause.WRONG_SPELL': 'Verkeerde toverspreuk',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'De toverspreuk vereist meer runen',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Nieuwe opdrachten zijn nog niet beschikbaar',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Je hebt deze Obelisk al gebruikt',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Alle kaartfragmenten zijn geopend',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Je neemt geen deel aan de jacht op het Gouden Ei',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Je hebt al geprobeerd het Gouden Ei op dit terrein te vinden',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Je hebt het snoep al gebruikt',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Het wezen is al gevangen',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Omscholing van het wezen is nog niet beschikbaar',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'De Bibliotheek is op dit moment niet toegankelijk',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Wacht alsjeblieft',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Limiet van strijden is al verhoogd',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Limiet van strijden is bereikt',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Je moet level 9 bereiken om deel te nemen aan het Duel van Magiërs',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Geen tegenstander voor het Duel van Magiërs, probeer het later nogmaals',
    'key.ServiceException.Cause.MARKET_ERROR': 'Fout van de markt',
    'key.ServiceException.Cause.NO_CHEST': 'Kist is niet gevonden',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Fout bij het verkrijgen van het fragment. Probeer het later nogmaals',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Je moet het Hart van de Draak of de set van Drakenartefacten aandoen, om meer eieren aan Moeder der Draken te kunnen geven',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'Er is al een ei in deze ruimte',
    'key.ServiceException.Cause.NO_CONNECTION': 'Geen internetverbinding',
    'key.ServiceException.Cause.SERVER_DOWN': 'Spelserver is tijdelijk niet beschikbaar. Probeer later opnieuw aub.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'Spelserver is gesloten voor onderhoud. Probeer later opnieuw aub.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Deze runen worden nu gebruikt',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Je gaat te snel',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'De limiet van veroverde Arena\'s is bereikt',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'De limiet van veroverde Bibliotheek is bereikt',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Fout: GPS is niet beschikbaar',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Je kan niet deze toverspreuk in de kerker uitspreken',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Deze strijd is verstreken',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Wanverhouding van protocol. Update is vereist.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Geen geallieerde Arena\'s in de zicht',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Geen vijandelijke Arena\'s in de zicht',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'Deze account is al in gebruik',
    'stop.personalized.BALLS': 'sferen voor de wezenvangst',
    'stop.personalized.HEALS': 'drankjes voor genezing',
    'stop.personalized.RESURRECTIONS': 'drankjes voor herrijzenis',
    'stop.personalized.EGGS': 'eieren van wezens',
    'stop.personalized.FOODS': 'snoepjes voor de wezens',
    'key.button.cancelPersonal': 'Annuleren',
    'key.error.needHigherLevelForSofaBattles': 'Je dient niveau {0} te bereiken om te kunnen deelnemen aan Duel tussen Magiërs',
    'fraction.text.youWilLGetBonus': 'Je krijgt {0} munten voor het toetreden tot deze fractie',
    'fraction.text.fractionUnavailable': 'De fractie is niet beschikbaar',
    'fraction.text.chooseYourAlliance': 'Kies fractie voor welke je gaat vechten',
    'fraction.text.redFractionName': 'Rode orde',
    'fraction.text.blueFractionName': 'Blauwe orde',
    'key.error.chestTooFarAway': 'De kist is te ver weg',
    'key.button.openChest': 'Openen',
    'key.candy.MONSTER_WATER_1': 'stenen van Kikkerus',
    'key.candy.MONSTER_WATER_2': 'stenen van Druppel',
    'key.candy.MONSTER_WATER_3': 'stenen van Spiritus',
    'key.candy.MONSTER_WATER_4': 'stenen van Overaquian',
    'key.candy.MONSTER_WATER_8': 'stenen van Kwallehoed',
    'key.candy.MONSTER_WATER_9': 'stenen van Minor',
    'key.candy.MONSTER_WATER_10': 'stenen van Infalisk',
    'key.candy.MONSTER_WATER_12': 'stenen van Dadachock',
    'key.candy.MONSTER_WATER_13': 'stenen van Batoid',
    'key.candy.MONSTER_WATER_23': 'stenen van Pantserank',
    'key.candy.MONSTER_WATER_24': 'stenen van Neptunus',
    'key.candy.MONSTER_WATER_25': 'stenen van Leviathan',
    'key.candy.MONSTER_FIRE_1': 'stenen van Potty',
    'key.candy.MONSTER_FIRE_2': 'stenen van Mummiekeen',
    'key.candy.MONSTER_FIRE_3': 'stenen van Dampes',
    'key.candy.MONSTER_FIRE_4': 'stenen van Incumus',
    'key.candy.MONSTER_FIRE_6': 'stenen van Vlammetje',
    'key.candy.MONSTER_FIRE_7': 'stenen van Fobia',
    'key.candy.MONSTER_FIRE_11': 'stenen van Sprank',
    'key.candy.MONSTER_FIRE_12': 'stenen van Kindra',
    'key.candy.MONSTER_FIRE_15': 'stenen van Naaldeheet',
    'key.candy.MONSTER_FIRE_25': 'stenen van Smoargh',
    'key.candy.MONSTER_EARTH_1': 'stenen van Bessedillo',
    'key.candy.MONSTER_EARTH_2': 'stenen van Bloemie',
    'key.candy.MONSTER_EARTH_3': 'stenen van Blaadje',
    'key.candy.MONSTER_EARTH_4': 'stenen van Brownie',
    'key.candy.MONSTER_EARTH_8': 'stenen van Disguir',
    'key.candy.MONSTER_EARTH_9': 'stenen van Bellflow',
    'key.candy.MONSTER_EARTH_10': 'stenen van Eikeling',
    'key.candy.MONSTER_EARTH_11': 'stenen van Phylo',
    'key.candy.MONSTER_EARTH_13': 'stenen van Princie',
    'key.candy.MONSTER_EARTH_25': 'stenen van Scylla',
    'key.candy.MONSTER_DUNGEON_1': 'stenen van Roekie',
    'key.candy.MONSTER_DUNGEON_2': 'stenen van Axolan',
    'key.candy.MONSTER_DUNGEON_3': 'stenen van Spijkerug',
    'key.candy.MONSTER_DUNGEON_4': 'stenen van Magglad',
    'key.candy.MONSTER_DUNGEON_5': 'stenen van Lievekat',
    'key.candy.MONSTER_DUNGEON_6': 'stenen van Rosie',
    'key.candy.MONSTER_DUNGEON_12': 'stenen van Vampiero',
    'key.candy.MONSTER_DUNGEON_13': 'stenen van Rups',
    'key.candy.MONSTER_DUNGEON_17': 'stenen van Inur',
    'key.candy.MONSTER_WIND_1': 'stenen van SunTzi',
    'key.candy.MONSTER_WIND_2': 'stenen van Oormuizel',
    'key.candy.MONSTER_WIND_3': 'stenen van Zwammie',
    'key.candy.MONSTER_WIND_4': 'stenen van Donzihoorn',
    'key.candy.MONSTER_WIND_6': 'stenen van Gamayun',
    'key.candy.MONSTER_WIND_7': 'stenen van Spookje',
    'key.candy.MONSTER_WIND_11': 'stenen van Infird',
    'key.candy.MONSTER_WIND_12': 'stenen van Undine',
    'key.candy.MONSTER_WIND_15': 'stenen van Cheshir',
    'key.candy.MONSTER_WIND_25': 'stenen van Charybdis',
    'key.button.leaveDungeon': 'Breuk verlaten',
    'key.alias.enterNewAlias': 'Voer de naam van het wezen in',
    'key.alias.enterText': 'Voer de tekst in....',
    'key.hut.hutName': 'Moeder der Draken',
    'key.hut.hutDescr': 'Geef de oeroude eieren aan de Moeder der Draken, zodat zij ze voor jou uitbroedt',
    'key.text.noHutEggs': 'Je hebt geen oeroude eieren',
    'key.text.noCapturedArenas': 'Je hebt geen veroverde Arena\'s',
    'key.text.noChosenPet': 'Je hebt je huisdier niet gekozen',
    'key.text.noArtifacts': 'Je hebt geen artefacten',
    'key.text.noCreatures': 'Je hebt geen gevangen wezens',
    'key.text.noLureItems': 'Je hebt geen lokmiddel',
    'key.descr.aboutWizardBattles': 'Neem deel aan duels tegen andere spelers om ervaring en beloningen te verdienen',
    'key.text.writeToSupport': 'Contact met de klantenservice opnemen',
    'key.text.regUsingFacebook': 'Aanmelden via Facebook',
    'key.text.regUsingGoogle': 'Aanmelden via Google',
    'key.text.logUsingFacebook': 'Inloggen via Facebook',
    'key.text.logUsingGoogle': 'Inloggen via Google',
    'key.text.logUsingDeviceIDCurrent': 'Inloggen via Device ID',
    'key.text.logUsingDeviceIDNew': 'Inloggen via Device ID (nieuwe account)',
    'key.text.createAccount': 'Spelen',
    'key.text.connectedToFacebook': 'Gekoppeld aan Facebook',
    'key.text.connectedToGoogle': 'Gekoppeld aan Google',
    'key.text.complainAboutPoint': 'Klacht indienen over punt',
    'key.text.copyCoordinates': 'Coördinaten kopiëren',
    'key.text.complainEnterEmail': 'Jouw e-mail',
    'key.text.complainEnterText': 'Beschrijf jouw probleem',
    'key.modal.doYouWantToCloseApp': 'Wil je de toepassing sluiten?',
    'key.catchPopup.notBad': 'Niet slecht!!',
    'key.catchPopup.good': 'Goed!',
    'key.catchPopup.sumptuously': 'Prachtig!',
    'key.catchPopup.twistedThrow': 'Curveball',
    'key.battlePopup.strongHit': 'Sterk slag!',
    'key.battlePopup.weakHit': 'Zwak slag',
    'key.battlePopup.dodge': 'Ontwijking!',
    'key.battlePopup.chargedAttack': '{0} gebruikte {1}',
    'auth.login.play': 'Spelen',
    'auth.login.nickname.placeholder': 'Voer jouw bijnaam in',
    'auth.login.nickname.busy': 'Deze bijnaam is al bezet',
    'auth.login.nickname.proposal': 'Je kunt deze bijnaam gebruiken:',
    'auth.login.nickname.deviceId': 'Je hebt al een karakter',
    'auth.login.social.title': 'Inloggen via sociaal netwerk',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Verbonden met {0}',
    'auth.login.social.signOut': 'Uitloggen',
    'auth.login.signOut.confirmation': 'Weet je zeker dat je wilt uitloggen?',
    'auth.login.social.userCancelledError': 'Verbinding is geannuleerd',
    'auth.login.social.cantSignInError': 'Kan niet verbinden met {0}',
    'licence.title': 'LICENTIEOVEREENKOMST DRACONIUS GO: CATCH A DRAGON!',
    'licence.checkbox': 'Email mij nieuws en aanbiedingen',
    'licence.accept': 'Accepteren',
    'licence.decline': 'Weigeren',
    'key.error.wrongRoostIndex': 'De plaats is niet beschikbaar',
    'key.speed.toMachSpeed': 'Je gaat te snel. Je mag niet Draconius GO: Catch a Dragon! tijdens rijden spelen - het is levensgevaarlijk',
    'key.speed.passenger': 'Ik ben een passagier',
    'key.activeObjects.addUnit.question': 'Ben je zeker dat je {0} een verdediger van dit gebouw wilt maken?',
    'key.egg.passedDistance.simple': '{0} / {1} km',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} h',
    'key.confirm.selectAlliance': 'Ben je zeker in de keuze van bondgenootschap?',
    'key.confirm.giveUpEncounter': 'Ben je zeker dat je confrontatie wilt ontwijken?',
    'key.confirm.giveUpBattle': 'Ben je zeker dat je wilt overgeven en strijd beeindigen?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Nieuwe Liga!',
};
