module.exports = {
    'key.system.application.name': 'Draconius GO: Catch a Dragon!',
    'key.button.ok': 'OK',
    'key.button.yes': 'Да',
    'key.button.cancel': 'ОТМЕНИТЬ',
    'key.button.apply': 'ОК',
    'key.button.use': 'Использовать',
    'key.button.buy': 'Обменять',
    'key.beCarefulMessage.text': 'Будьте осторожны во время игры. Смотрите по сторонам.',
    'key.creature.details.attack': 'Сила',
    'key.creature.details.health': 'Здоровье',
    'key.creature.details.powerUp': 'Усиление',
    'key.creature.details.evolve': 'Превращение',
    'key.creature.details.cp': 'CP',
    'key.creature.details.cpValue': 'СР {0}',
    'key.creature.details.hp': 'HP',
    'key.creature.details.transfer': 'ОТПУСТИТЬ',
    'key.creature.details.creadex': 'Бестиарий',
    'key.creature.registration.creadex': 'Добавлено в бестиарий',
    'key.creature.details.dps': 'DPS',
    'key.creature.details.eps': 'EPS',
    'key.activeObjects.title': 'Захваченные здания',
    'key.activeObjects.library': 'Переобучение существа в Библиотеке',
    'key.activeObjects.library.empty': 'Нет захваченных Библиотек',
    'key.activeObjects.arena': 'Сбор дани с Арен',
    'key.activeObjects.arena.collect': 'Собрать',
    'key.activeObjects.arena.empty': 'Нет захваченных Арен',
    'key.activeObjects.error.timer': 'Сбор дани недоступен. Нужно подождать',
    'key.activeObjects.error.noMoney': 'Сначала нужно захватить Арену',
    'key.activeObjects.error.cannotRemaster': 'Переучивание недоступно. Захватывайте Библиотеки, чтобы ускорить таймер переучивания.',
    'key.activeObjects.library.remaster': 'Переучить',
    'key.activeObjects.library.blocked': 'Библиотеки недоступны',
    'key.activeObjects.remaster.confirmation.main': 'Вы уверены, что хотите переучить {0}? Основной навык {1} будет заменен.',
    'key.activeObjects.remaster.confirmation.charged': 'Вы уверены, что хотите переучить {0}? Заряжаемый навык {1} будет заменен.',
    'key.activeObjects.remaster.error': 'Ошибка',
    'key.activeObjects.item.weaklyBonus': 'Еженедельный бонус +{0} монеты',
    'key.library.remaster.selectCreature': 'Выберите существо для переучивания',
    'key.remasterPanel.title': 'Выберите навык для замены',
    'key.storage.creatues': 'Существа',
    'key.storage.eggs': 'Яйца',
    'key.storage.eggs.simple': 'Обычные яйца',
    'key.storage.eggs.super': 'Древние яйца',
    'key.storage.eggs.missingAny': 'У Вас нет яиц существ',
    'key.startEgg.button': 'Поместить в кокон',
    'key.startEgg.description': 'Используйте драконий кокон, чтобы высидеть это яйцо',
    'key.startEgg.incubator.title': 'Драконьи коконы',
    'key.startEgg.select.title': 'Выберите яйцо',
    'key.openEgg.button': 'Открыть яйцо',
    'key.openEgg.description': 'Новое существо сейчас вылупится из яйца',
    'key.startEgg.description.roost.hatching': 'Матерь Драконов высиживает это яйцо. Нужно лишь подождать. Высиживание прекратится, если исчезнет Разлом Арканы, в котором находится Матерь Драконов.',
    'key.startEgg.description.roost.notHatching': 'Отдайте это яйцо Матери Драконов, чтобы она высидела его для Вас.',
    'key.startEgg.description.simple.hatching': 'Это яйцо высиживается в драконьем коконе. Ходите с включенной игрой, чтобы помочь ему вылупиться. ',
    'key.startEgg.description.simple.notHatching': 'Поместите это яйцо в драконий кокон, чтобы начать высиживать его. Яйцо вылупится, когда Вы пройдете нужное расстояние.',
    'key.mainMenu.wizardDuels': 'ДУЭЛЬ МАГОВ',
    'key.mainMenu.quests': 'ЗАДАНИЯ',
    'key.mainMenu.activePoints': 'ЗАХВАЧЕННОЕ',
    'key.mainMenu.creadex': 'БЕСТИАРИЙ',
    'key.mainMenu.magic': 'МАГИЯ',
    'key.mainMenu.creatues': 'СУЩЕСТВА',
    'key.mainMenu.shop': 'ЛАВКА',
    'key.mainMenu.backpack': 'СУМКА',
    'key.error.banned': 'Аккаунт заблокирован',
    'event.log.CREATURE_CAUGHT': '{0} пойман!',
    'event.log.ITEM_BOUGHT': '{0} x{1} куплен. Потрачено {2} монет',
    'event.log.ARTIFACT_BOUGHT': 'Куплен артефакт: {0}. Потрачено {1} монет',
    'event.log.EGG_HATCHED': '{0} вылупился из {1} яйца!',
    'event.log.EGG_HATCHED.distance': '{0} км',
    'event.log.EGG_HATCHED.gold': 'золотого',
    'event.log.ROOST_EGG_HATCHED': 'Матерь драконов высидела {1} ч яйцо. {0} теперь Ваш!',
    'event.log.CHEST_OPENED': 'Найдено в сундуке:',
    'event.log.ARENA_LOST_CONTROL': '{1} был выбит из здания: {0}',
    'event.log.LIBRARY_LIST_CONTROL': '{1} был выбит из здания: {0}',
    'event.log.LEVEL_UP': 'Вы достигли уровня {0}',
    'event.log.BUDDY_FOUND_CANDY': 'Питомец нашел {0}',
    'event.log.QUEST_COMPLETED': 'Награда за задание {0}',
    'event.log.ENCOUNTER_LOOSE': 'Вы убежали от дикого монстра',
    'event.log.WIZARD_BATTLE_LIMIT_ENHANCED': 'Лимит битв в Дуэли Магов увеличен за {0} монет',
    'event.log.HARD_CURRENCY_BOUGHT': '{0} монет куплено за {1}',
    'event.log.UPGRADE_BAG_BOUGHT': 'Сумка улучшена за {0} монет',
    'event.log.UPGRADE_STORAGE_BOUGHT': 'Хранилище существ улучшено за {0} монет',
    'key.shop.accesories': 'ПРЕДМЕТЫ',
    'key.shop.artifacts': 'АРТЕФАКТЫ',
    'key.shop.donate': 'МОНЕТЫ',
    'key.shop.upgrade': 'УЛУЧШЕНИЯ',
    'key.shop.donate.coins': '{0} монет',
    'key.shop.upgrade.bag': 'Расширение сумки',
    'key.shop.upgrade.bag.desc': 'Размер сумки будет увеличен на 50',
    'key.shop.upgrade.storage': 'Расширение хранилища существ',
    'key.shop.upgrade.storage.desc': 'Размер хранилища существ будет увеличен на 50',
    'key.shop.donate.dialog.title': 'Не хватает монет!',
    'key.shop.donate.dialog.desc': 'Получите их тут, или посетите Лавку, чтобы увидеть больше вариантов',
    'key.potionUseMenu.title': 'Зелья лечения',
    'key.recipe.descr.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Создает Портал в мир Арканы.',
    'key.recipe.descr.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Все игроки вокруг почувствуют ярость лепреконов',
    'key.recipe.descr.RECIPE_PERSONAL_STOP_FIELD_1': 'На 30 минут создает поле Столпов Изобилия',
    'key.recipe.descr.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'На 30 минут удваивает количество наград из Столпов Изобилия ',
    'key.recipe.descr.RECIPE_MONSTERS_HIGHLIGHT_1': 'Делай длинные тапы по местности, чтобы просветить ее в поисках монстров',
    'key.recipe.descr.RECIPE_SUPER_VISION_1': 'На 30 минут увеличивает радиус обнаружения монстров',
    'key.recipe.descr.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'На 7 дней увеличивает радиус обзора на 30%',
    'key.recipe.descr.RECIPE_PROTECT_ALLY_ARENA_1': 'Ближайшая союзная Арена будет недоступной для атаки врагами на 30 часов',
    'key.recipe.descr.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Все вражеские Арены в радиусе видимости станут нейтральными. Снимает Благословление защиты.',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_FIRE': 'Создает магическую башню, которая привлекает существ стихии огня',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WATER': 'Создает магическую башню, которая привлекает существ стихии воды',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_WIND': 'Создает магическую башню, которая привлекает существ стихии воздуха',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_EARTH': 'Создает магическую башню, которая привлекает существ стихии земли',
    'key.recipe.descr.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Создает магическую башню, которая привлекает существ стихии арканы',
    'key.recipe.RECIPE_CREATE_DUNGEON_PORTAL_1': 'Разлом Арканы',
    'key.recipe.RECIPE_TURN_PLAYERS_TO_SLUGS_1': 'Гнев лепреконов',
    'key.recipe.RECIPE_PERSONAL_STOP_FIELD_1': 'Поле Изобилия',
    'key.recipe.RECIPE_DOUBLE_DROP_FROM_STOPS_1': 'Дар Золотого Дракона',
    'key.recipe.RECIPE_MONSTERS_HIGHLIGHT_1': 'Астральное видение',
    'key.recipe.RECIPE_SUPER_VISION_1': 'Драконье зрение',
    'key.recipe.RECIPE_ACTIVATION_RADIUS_IMPROVE_1': 'Длинные руки',
    'key.recipe.RECIPE_PROTECT_ALLY_ARENA_1': 'Благословление защиты',
    'key.recipe.RECIPE_RECAPTURE_ENEMY_PLACES_1': 'Очищение огнем',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_FIRE': 'Башня Огня',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WATER': 'Башня Воды',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_WIND': 'Башня Воздуха',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_EARTH': 'Башня Земли',
    'key.recipe.RECIPE_TOWER_ELEMENTAL_DUNGEON': 'Башня Арканы',
    'key.buff.ATTACKER_CP_BOOST': 'СР Ваших существ временно увеличено',
    'key.buff.BEST_BALL_LUCK': 'Только лучшие сферы в Столпах Изобилия на 30 мин',
    'key.buff.BEST_POTION_LUCK': 'Только лучшие зелья в Столпах Изобилия на 30 мин',
    'key.buff.TWO_EXTRA_ITEMS_IN_STOP_LOOT': '+2 предмета из Столпов Изобилия на 30 мин',
    'key.instantuseitem.LIBRARY_COOLDOWN_REDUCE': 'Время до переучивания в Библиотеке уменьшено на {0}',
    'key.instantuseitem.ARENA_TRIBUTE_COOLDOWN_REDUCE': 'Время до сбора дани с Арен уменьшено на {0}',
    'key.buff.tooltip.ATTACKER_CP_BOOST': 'Увеличивает СР существ, которые не являются защитниками зданий',
    'key.buff.tooltip.BEST_BALL_LUCK': 'Вы получаете из Столпов только лучшие сферы, доступные для Вашего уровня',
    'key.buff.tooltip.BEST_POTION_LUCK': 'Вы получаете из Столпов только лучшие зелья, доступные для Вашего уровня',
    'key.buff.tooltip.TWO_EXTRA_ITEMS_IN_STOP_LOOT': 'Вы получаете на два предмета больше из Столпов Изобилия',
    'key.loot.result.dust': 'Эссенция',
    'key.loot.result.exp': 'Опыт персонажа',
    'key.loot.result.coin': 'Монеты',
    'key.loot.result.candy': 'камни',
    'key.item.MAGIC_BALL_SIMPLE': 'Сфера ученика',
    'key.item.MAGIC_BALL_NORMAL': 'Сфера магистра',
    'key.item.MAGIC_BALL_GOOD': 'Сфера повелителя',
    'key.item.LURE': 'Приманка',
    'key.item.INCENSE': 'Феромоны',
    'key.item.EGG': 'Яйцо',
    'key.item.SHOVEL': 'Лопата',
    'key.item.POTION_HEAL_1': 'Малое зелье лечения',
    'key.item.POTION_HEAL_2': 'Среднее зелье лечения',
    'key.item.POTION_HEAL_3': 'Великое зелье лечения',
    'key.item.POTION_HEAL_4': 'Зелье полного исцеления',
    'key.item.POTION_RESURRECTION_1': 'Зелье воскрешения',
    'key.item.POTION_RESURRECTION_2': 'Великое зелье воскрешения',
    'key.item.INCUBATOR_1': 'Драконий кокон',
    'key.item.INCUBATOR_3': 'Драконий кокон',
    'key.item.INCUBATOR_PERPETUAL': 'Вечный драконий кокон',
    'key.item.SUPER_VISION': 'Драконье зрение',
    'key.item.RUNE_1': 'Руна I',
    'key.item.RUNE_2': 'Руна II',
    'key.item.RUNE_3': 'Руна III',
    'key.item.RUNE_4': 'Руна IV',
    'key.item.RUNE_5': 'Руна V',
    'key.item.RUNE_6': 'Руна VI',
    'key.item.FOOD_CATCH_CHANCE': 'Арканическая карамель',
    'key.item.FOOD_MORE_DUST': 'Магический пончик',
    'key.item.FOOD_CALM_DOWN': 'Единорожий зефир',
    'key.item.FOOD_MORE_CANDIES': 'Мороженка четырех стихий',
    'key.item.EXPERIENCE_BOOSTER': 'Кристалл мудрости',
    'key.item.EGG_KM_0': 'Золотое Яйцо',
    'key.item.MAGIC_BALL_SIMPLE.description': 'Сфера для поимки существ.',
    'key.item.MAGIC_BALL_NORMAL.description': 'Сфера для поимки существ. Немного увеличивает шанс на поимку.',
    'key.item.MAGIC_BALL_GOOD.description': 'Сфера для поимки существ. Сильно увеличивает шанс на поимку.',
    'key.item.LURE.description': 'Приманка для существ. Вставьте в Столп Изобилия, чтобы привлечь к нему существ.',
    'key.item.INCENSE.description': 'Феромоны привлекут к Вам существ определенной стихии, в зависимости от дня недели.',
    'key.item.EGG.description': 'Используйте драконий кокон, чтобы высидеть из яйца существо',
    'key.item.SHOVEL.description': 'Лопаты совершенно незаменимы при поиске кладов',
    'key.item.POTION_HEAL_1.description': 'Исцеляет существо на 200 единиц здоровья',
    'key.item.POTION_HEAL_2.description': 'Исцеляет существо на 500 единиц здоровья',
    'key.item.POTION_HEAL_3.description': 'Исцеляет существо на 1000 единиц здоровья',
    'key.item.POTION_HEAL_4.description': 'Полностью исцеляет существо',
    'key.item.POTION_RESURRECTION_1.description': 'Воскрешает выбранное существо. После воскрешения существо будет ранено.',
    'key.item.POTION_RESURRECTION_2.description': 'Воскрешает и полностью исцеляет существо',
    'key.item.INCUBATOR_1.description': 'Драконьи коконы нужны, чтобы высиживать существ из яиц. Пропадает после использования.',
    'key.item.INCUBATOR_3.description': 'Драконьи коконы нужны, чтобы высиживать существ из яиц. Пропадает после 3-х использований.',
    'key.item.INCUBATOR_PERPETUAL.description': 'Драконьи коконы нужны, чтобы высиживать существ из яиц. ',
    'key.item.SUPER_VISION.description': 'Показывает существ в большой области',
    'key.item.RUNE_1.description': 'Магическая руна 1 уровня',
    'key.item.RUNE_2.description': 'Магическая руна 2 уровня',
    'key.item.RUNE_3.description': 'Магическая руна 3 уровня',
    'key.item.RUNE_4.description': 'Магическая руна 4 уровня',
    'key.item.RUNE_5.description': 'Магическая руна 5 уровня',
    'key.item.RUNE_6.description': 'Магическая руна 6 уровня',
    'key.item.FOOD_CATCH_CHANCE.description': 'Лакомство для поимки существ. Увеличивает шанс захватить монстра магической сферой',
    'key.item.FOOD_MORE_DUST.description': 'Лакомство для поимки существ. Увеличивает количество эссенции, получаемой за поимку',
    'key.item.FOOD_CALM_DOWN.description': 'Лакомство для поимки существ. Успокаивает существо. Оно перестает прыгать и атаковать',
    'key.item.FOOD_MORE_CANDIES.description': 'Лакомство для поимки существ. Увеличивает количество камней душ, получаемых за поимку',
    'key.item.EXPERIENCE_BOOSTER.description': 'На 30 минут увеличивает получение опыта вдвое',
    'key.artifact.ARTIFACT_TELEPATHY_1': 'Маска фокусника',
    'key.artifact.ARTIFACT_TELEPATHY_1.description': '1 удаленная подсадка существа на Арену или Библиотеку в сутки',
    'key.artifact.ARTIFACT_TELEPATHY_1.description.long': 'Этот артефакт позволяет 1 раз в сутки удаленно посадить свое существо на свободное место в видимую на карте Арену или Библиотеку',
    'key.artifact.ARTIFACT_TELEPATHY_2': 'Лицо провидца',
    'key.artifact.ARTIFACT_TELEPATHY_2.description': '2 удаленные подсадки существа на Арену или Библиотеку в сутки',
    'key.artifact.ARTIFACT_TELEPATHY_2.description.long': 'Этот артефакт позволяет 2 раза в сутки удаленно посадить свое существо на свободное место в видимую на карте Арену или Библиотеку',
    'key.artifact.ARTIFACT_TELEPATHY_3': 'Шлем покорителя',
    'key.artifact.ARTIFACT_TELEPATHY_3.description': '3 удаленные подсадки существа на Арену или Библиотеку в сутки',
    'key.artifact.ARTIFACT_TELEPATHY_3.description.long': 'Этот артефакт позволяет 3 раза в сутки удаленно посадить свое существо на свободное место в видимую на карте Арену или Библиотеку',
    'key.artifact.ARTIFACT_TELEPATHY_4': 'Шлем героя',
    'key.artifact.ARTIFACT_TELEPATHY_4.description': '4 удаленные подсадки существа на Арену или Библиотеку в сутки',
    'key.artifact.ARTIFACT_TELEPATHY_4.description.long': 'Этот артефакт позволяет 4 раза в сутки удаленно посадить свое существо на свободное место в видимую на карте Арену или Библиотеку',
    'key.artifact.ARTIFACT_TELEPATHY_5': 'Шлем драконоборца',
    'key.artifact.ARTIFACT_TELEPATHY_5.description': '5 удаленных подсадок существа на Арену или Библиотеку в сутки',
    'key.artifact.ARTIFACT_TELEPATHY_5.description.long': 'Этот артефакт позволяет 5 раз в сутки удаленно посадить свое существо на свободное место в видимую на карте Арену или Библиотеку',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1': 'Знамя владыки',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description': 'Позволяет сажать на Арену или Библиотеку еще одно существо',
    'key.artifact.ARTIFACT_ADDITIONAL_MONSTER_1.description.long': 'С этим артефактом можно посадить на защиту Арены или Библиотеки двух существ вместо одного',
    'key.artifact.ARTIFACT_BANK_8': 'Вырезанный артефакт',
    'key.artifact.ARTIFACT_BANK_8.description': 'Как Вы вобще его нашли?',
    'key.artifact.ARTIFACT_BANK_8.description.long': 'Вы увидели артефакт, который не должны были видеть. Теперь нам придется избавиться от Вас, как от свидетеля.',
    'key.artifact.ARTIFACT_BANK_9': 'Вырезанный артефакт',
    'key.artifact.ARTIFACT_BANK_9.description': 'Как Вы вобще его нашли?',
    'key.artifact.ARTIFACT_BANK_9.description.long': 'Вы увидели артефакт, который не должны были видеть. Теперь нам придется избавиться от Вас, как от свидетеля.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1': 'Часы ленивого студента',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description': '-20 секунд к перезарядке Столпов Изобилия',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_1.description.long': 'С этим артефактом, после использования Столпы Изобилия будут перезаряжаться на 20 секунд быстрее, и их можно будет использовать чаще.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2': 'Будильник вечно опаздывающего',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description': '-40 секунд к перезарядке Столпов Изобилия',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_2.description.long': 'С этим артефактом, после использования Столпы Изобилия будут перезаряжаться на 40 секунд быстрее, и их можно будет использовать чаще.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3': 'Пространственный ускоритель',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description': '-60 секунд к перезарядке Столпов Изобилия',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_3.description.long': 'С этим артефактом, после использования Столпы Изобилия будут перезаряжаться на 60 секунд быстрее, и их можно будет использовать чаще.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4': 'Часы ленивого профессора',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description': '-80 секунд к перезарядке Столпов Изобилия',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_4.description.long': 'С этим артефактом, после использования Столпы Изобилия будут перезаряжаться на 80 секунд быстрее, и их можно будет использовать чаще.',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5': 'Часы зебро-кролика',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description': '-100 секунд к перезарядке Столпов Изобилия',
    'key.artifact.ARTIFACT_STOP_CD_REDUCE_5.description.long': 'С этим артефактом, после использования Столпы Изобилия будут перезаряжаться на 100 секунд быстрее, и их можно будет использовать чаще.',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1': 'Жезл завоевателя',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description': '+2 к уровню Арены или Библиотеки после ее захвата',
    'key.artifact.ARTIFACT_ARENA_POWERUP_AFTER_CAPTURE_1.description.long': 'Если владелец этого артефакта первым сажает существо в захваченную Арену или Библиотеку, она получает сразу 5й уровень, вместо 3-го',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1': 'Кольцо сборщика податей',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description': '+1 к максимуму захваченных Арен',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_1.description.long': 'С этим артефактом Вы можете собирать дань с 11 Арен, вместо обычных 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2': 'Кольцо жадности',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description': '+2 к максимуму захваченных Арен',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_2.description.long': 'С этим артефактом Вы можете собирать дань с 12 Арен, вместо обычных 10',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3': 'Двойное Кольцо',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description': '+3 к максимуму Арен с которых можно собрать дань',
    'key.artifact.ARTIFACT_ARENA_LIMIT_INCREASE_3.description.long': 'С этим артефактом Вы можете собирать дань с 13 Арен, вместо обычных 10',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1': 'Кубок пожирателя пирогов',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description': '+20% к славе союзных Арен и Библиотек при тренировке',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_1.description.long': 'С этим артефактом, союзные Арены и Библиотеки получают на 20% больше славы, когда Вы их тренируете',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2': 'Кубок для меда',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description': '+30% к славе союзных Арен и Библиотек при тренировке',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_2.description.long': 'С этим артефактом, союзные Арены и Библиотеки получают на 30% больше славы, когда Вы их тренируете',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3': 'Чаша глубоких мыслей',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description': '+40% к славе союзных Арен и Библиотек при тренировке',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_3.description.long': 'С этим артефактом, союзные Арены и Библиотеки получают на 40% больше славы, когда Вы их тренируете',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4': 'Грааль Ланселопа',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description': '+50% к славе союзных Арен и Библиотек при тренировке',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_4.description.long': 'С этим артефактом, союзные Арены и Библиотеки получают на 50% больше славы, когда Вы их тренируете',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5': 'Кубок покорителя чудовищ',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description': '+80% к славе союзных Арен и Библиотек при тренировке',
    'key.artifact.ARTIFACT_ARENA_XP_FOR_TRAINING_INCREASE_5.description.long': 'С этим артефактом, союзные Арены и Библиотеки получают на 80% больше славы, когда Вы их тренируете',
    'key.artifact.ARTIFACT_RADAR_IMPROVE': 'Тотем ясного видения',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description': 'Убирает слабых существ с радара',
    'key.artifact.ARTIFACT_RADAR_IMPROVE.description.long': 'Этот артефакт убирает с радара слабейших существ, что помогает сосредоточиться на поиске сильных экземпляров',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1': 'Рулбук приключенца',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description': '+15 минут к сбору дани с Арены после захвата противником',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_1.description.long': 'С этим артефактом Арены доступны для сбора дани еще 30 минут после их захвата, вместо обычных 15 минут',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2': 'Толстая солидная книга',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description': '+30 минут к сбору дани с Арены после захвата противником',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_2.description.long': 'С этим артефактом Арены доступны для сбора дани еще 45 минут после их захвата, вместо обычных 15 минут',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3': 'Скрижаль притязания',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description': '+45 минут к сбору дани с Арены после захвата противником',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_3.description.long': 'С этим артефактом Арены доступны для сбора дани еще 60 минут после их захвата, вместо обычных 15 минут',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4': 'Трактат о правлении',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description': '+75 минут к сбору дани с Арены после захвата противником',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_4.description.long': 'С этим артефактом Арены доступны для сбора дани еще 90 минут после их захвата, вместо обычных 15 минут',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5': 'Гримуар власти',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description': '+105 минут к сбору дани с Арены после захвата противником',
    'key.artifact.ARTIFACT_TRIBUTE_TIME_LIMIT_INCREASE_5.description.long': 'С этим артефактом Арены доступны для сбора дани еще 120 минут после их захвата, вместо обычных 15 минут',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1': 'Шипастый ошейник',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description': '10% ускорение получения камней душ от питомца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_1.description.long': 'С этим артефактом Вам нужно будет пройти на 10% меньшее расстояние с питомцем, чтобы получить камень душ. Так же делает питомца на 17% грознее',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2': 'Морковка на палочке',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description': '15% ускорение получения камней душ от питомца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_2.description.long': 'С этим артефактом Вам нужно будет пройти на 15% меньшее расстояние с питомцем, чтобы получить камень душ. Вкуснятинка.',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3': 'Спинко-чесалка',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description': '25% ускорение получения камней душ от питомца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_3.description.long': 'С этим артефактом Вам нужно будет пройти на 25% меньшее расстояние с питомцем, чтобы получить камень душ. Склонись перед мощью спинко-чесалки!',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4': 'Бубенчик любимца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description': '30% ускорение получения камней душ от питомца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_4.description.long': 'С этим артефактом Вам нужно будет пройти на 30% меньшее расстояние с питомцем, чтобы получить камень душ. Кто тут у нас такой красивый мальчик?',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5': 'Плюшевый дракоша',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description': '40% ускорение получения камней душ от питомца',
    'key.artifact.ARTIFACT_BUDDY_DISTANCE_REDUCE_5.description.long': 'С этим артефактом Вам нужно будет пройти на 40% меньшее расстояние с питомцем, чтобы получить камень душ. Лучшая игрушка для лучшего в мире питомца',
    'key.artifact.ARTIFACT_ROOST_1': 'Сердце дракона',
    'key.artifact.ARTIFACT_ROOST_1.description': '+1 драконий кокон у Матери Драконов',
    'key.artifact.ARTIFACT_ROOST_1.description.long': 'Позволяет использовать дополнительный драконий кокон для яиц у Матери Драконов',
    'dialog.artifact.select_artifact': 'ВЫБЕРИТЕ АРТЕФАКТ',
    'dialog.artifact.confirm.remove': 'Вы уверены, что хотите удалить артефакт?',
    'dialog.items.title': 'СУМКА',
    'dialog.items.cannotUse': 'Этот предмет нельзя использовать',
    'dialog.items.remove.header': 'Удаление предметов',
    'dialog.encounter.header': 'Дикий монстр атакует!',
    'dialog.encounter.button.leave': 'Убежать',
    'dialog.encounter.button.fight': 'Сражаться',
    'dialog.encounter.result.outcome.win': 'Дикий монстр побежден',
    'dialog.encounter.result.outcome.lose': 'Ваше существо побеждено',
    'dialog.encounter.result.reward.dust': 'Эссенция',
    'dialog.encounter.result.reward.exp': 'Опыт',
    'error.nickname.validation.IS_EMPTY': 'Нужно ввести имя персонажа',
    'error.nickname.validation.TOO_SHORT': 'Имя должно содержать не менее 3 и не более 16 символов',
    'error.nickname.validation.TOO_LONG': 'Имя должно содержать не менее 3 и не более 16 символов',
    'error.nickname.validation.INVALID_CHAR': 'Можно использовать латинские буквы, цифры и подчеркивание.',
    'error.nickname.validation.DUPLICATE': 'Выбранное имя уже занято. Вы можете взять имя {0}',
    'creature.MONSTER_WATER_1': 'Жабус',
    'creature.MONSTER_WATER_2': 'Капля',
    'creature.MONSTER_WATER_3': 'Спиритус',
    'creature.MONSTER_WATER_4': 'Аквин',
    'creature.MONSTER_WATER_5': 'Жабиссимо',
    'creature.MONSTER_WATER_6': 'Ручеек',
    'creature.MONSTER_WATER_7': 'Келпи',
    'creature.MONSTER_WATER_8': 'Джеллихат',
    'creature.MONSTER_WATER_9': 'Минори',
    'creature.MONSTER_WATER_10': 'Инфалиск',
    'creature.MONSTER_WATER_11': 'Медиаквин',
    'creature.MONSTER_WATER_12': 'Дадачок',
    'creature.MONSTER_WATER_13': 'Батоид',
    'creature.MONSTER_WATER_14': 'Пуэролиск',
    'creature.MONSTER_WATER_15': 'Фальхор',
    'creature.MONSTER_WATER_16': 'Тентахат',
    'creature.MONSTER_WATER_17': 'Аквар',
    'creature.MONSTER_WATER_18': 'Дадачум',
    'creature.MONSTER_WATER_19': 'Мантари',
    'creature.MONSTER_WATER_20': 'Василиск',
    'creature.MONSTER_WATER_21': 'Мельхор',
    'creature.MONSTER_WATER_22': 'Кристалий',
    'creature.MONSTER_WATER_23': 'Брониус',
    'creature.MONSTER_WATER_24': 'Нептун',
    'creature.MONSTER_WATER_25': 'Левиафан',
    'creature.MONSTER_FIRE_1': 'Потти',
    'creature.MONSTER_FIRE_2': 'Муммивин',
    'creature.MONSTER_FIRE_3': 'Паровик',
    'creature.MONSTER_FIRE_4': 'Инкумус',
    'creature.MONSTER_FIRE_5': 'Огнелап',
    'creature.MONSTER_FIRE_6': 'Флейми',
    'creature.MONSTER_FIRE_7': 'Фоуби',
    'creature.MONSTER_FIRE_8': 'Даммивин',
    'creature.MONSTER_FIRE_9': 'Лавион',
    'creature.MONSTER_FIRE_10': 'Печка',
    'creature.MONSTER_FIRE_11': 'Искра',
    'creature.MONSTER_FIRE_12': 'Кидра',
    'creature.MONSTER_FIRE_13': 'Демонстар',
    'creature.MONSTER_FIRE_14': 'Феникс',
    'creature.MONSTER_FIRE_15': 'Нидлхот',
    'creature.MONSTER_FIRE_16': 'Железный мужик',
    'creature.MONSTER_FIRE_17': 'Светлячок',
    'creature.MONSTER_FIRE_18': 'Цезарь',
    'creature.MONSTER_FIRE_19': 'Вспышка',
    'creature.MONSTER_FIRE_20': 'Флибустус',
    'creature.MONSTER_FIRE_21': 'Темптер',
    'creature.MONSTER_FIRE_22': 'Гидра',
    'creature.MONSTER_FIRE_23': 'Салют',
    'creature.MONSTER_FIRE_24': 'Пиккарун',
    'creature.MONSTER_FIRE_25': 'Смаугр',
    'creature.MONSTER_EARTH_1': 'Ягодилло',
    'creature.MONSTER_EARTH_2': 'Цветик',
    'creature.MONSTER_EARTH_3': 'Листок',
    'creature.MONSTER_EARTH_4': 'Брауни',
    'creature.MONSTER_EARTH_5': 'Шамурф',
    'creature.MONSTER_EARTH_6': 'Дриада',
    'creature.MONSTER_EARTH_7': 'Росток',
    'creature.MONSTER_EARTH_8': 'Гоблик',
    'creature.MONSTER_EARTH_9': 'Белфлоу',
    'creature.MONSTER_EARTH_10': 'Желудень',
    'creature.MONSTER_EARTH_11': 'Фило',
    'creature.MONSTER_EARTH_12': 'Браг',
    'creature.MONSTER_EARTH_13': 'Принси',
    'creature.MONSTER_EARTH_14': 'Шишун',
    'creature.MONSTER_EARTH_15': 'Дао',
    'creature.MONSTER_EARTH_16': 'Тролль',
    'creature.MONSTER_EARTH_17': 'Двант',
    'creature.MONSTER_EARTH_18': 'Чаппиан',
    'creature.MONSTER_EARTH_19': 'Гардраг',
    'creature.MONSTER_EARTH_20': 'Спринга',
    'creature.MONSTER_EARTH_21': 'Землеос',
    'creature.MONSTER_EARTH_22': 'Звероцвет',
    'creature.MONSTER_EARTH_23': 'Йоги',
    'creature.MONSTER_EARTH_24': 'Грендель',
    'creature.MONSTER_EARTH_25': 'Сцилла',
    'creature.MONSTER_WIND_1': 'СунТзы',
    'creature.MONSTER_WIND_2': 'Ухомых',
    'creature.MONSTER_WIND_3': 'Грибби',
    'creature.MONSTER_WIND_4': 'Пушисторог',
    'creature.MONSTER_WIND_5': 'Аирвер',
    'creature.MONSTER_WIND_6': 'Гамаюн',
    'creature.MONSTER_WIND_7': 'Страшуль',
    'creature.MONSTER_WIND_8': 'Ухолот',
    'creature.MONSTER_WIND_9': 'Эскимо',
    'creature.MONSTER_WIND_10': 'Ветропляс',
    'creature.MONSTER_WIND_11': 'Инфирд',
    'creature.MONSTER_WIND_12': 'Ундина',
    'creature.MONSTER_WIND_13': 'Шторморог',
    'creature.MONSTER_WIND_14': 'Фантомо',
    'creature.MONSTER_WIND_15': 'Чешир',
    'creature.MONSTER_WIND_16': 'Грибтопия',
    'creature.MONSTER_WIND_17': 'Гарпия',
    'creature.MONSTER_WIND_18': 'Гостус',
    'creature.MONSTER_WIND_19': 'Пэрогриф',
    'creature.MONSTER_WIND_20': 'Подушкот',
    'creature.MONSTER_WIND_21': 'Хипполет',
    'creature.MONSTER_WIND_22': 'Ураганна',
    'creature.MONSTER_WIND_23': 'Грифон',
    'creature.MONSTER_WIND_24': 'Баюн',
    'creature.MONSTER_WIND_25': 'Харибда',
    'creature.MONSTER_DUNGEON_1': 'Рууки',
    'creature.MONSTER_DUNGEON_2': 'Аксолан',
    'creature.MONSTER_DUNGEON_3': 'Шипоспин',
    'creature.MONSTER_DUNGEON_4': 'Магглад',
    'creature.MONSTER_DUNGEON_5': 'Милокот',
    'creature.MONSTER_DUNGEON_6': 'Рози',
    'creature.MONSTER_DUNGEON_7': 'Марид',
    'creature.MONSTER_DUNGEON_8': 'Агролотль',
    'creature.MONSTER_DUNGEON_9': 'Чучело',
    'creature.MONSTER_DUNGEON_10': 'Снэйлин',
    'creature.MONSTER_DUNGEON_11': 'Джин',
    'creature.MONSTER_DUNGEON_12': 'Вампиро',
    'creature.MONSTER_DUNGEON_13': 'Гусень',
    'creature.MONSTER_DUNGEON_14': 'Мантик',
    'creature.MONSTER_DUNGEON_15': 'Твист',
    'creature.MONSTER_DUNGEON_16': 'Хвостик',
    'creature.MONSTER_DUNGEON_17': 'Инур',
    'creature.MONSTER_DUNGEON_18': 'Крутакула',
    'creature.MONSTER_DUNGEON_19': 'Регулум',
    'creature.MONSTER_DUNGEON_20': 'Тигромант',
    'creature.MONSTER_DUNGEON_21': 'Острохвост',
    'creature.MONSTER_DUNGEON_22': 'Бутон',
    'creature.MONSTER_DUNGEON_23': 'Керли',
    'creature.MONSTER_DUNGEON_24': 'Мантикора',
    'creature.MONSTER_DUNGEON_25': 'Моргорот',
    'skill.main.SKILL_WATER_MAIN_BAD_SLOW': 'Укус акулы',
    'skill.main.SKILL_WATER_MAIN_BAD_NORMAL': 'Ужас из глубин',
    'skill.main.SKILL_WATER_MAIN_BAD_FAST': 'Зов Катулу',
    'skill.main.SKILL_WATER_MAIN_GOOD_SLOW': 'Морской молот',
    'skill.main.SKILL_WATER_MAIN_GOOD_NORMAL': 'Водный кулак',
    'skill.main.SKILL_WATER_MAIN_GOOD_FAST': 'Волна',
    'skill.main.SKILL_WATER_MAIN_BEST_SLOW': 'Ливень',
    'skill.main.SKILL_WATER_MAIN_BEST_NORMAL': 'Гейзер',
    'skill.main.SKILL_WATER_MAIN_BEST_FAST': 'Брызги',
    'skill.main.SKILL_FIRE_MAIN_BAD_SLOW': 'Живое пламя',
    'skill.main.SKILL_FIRE_MAIN_BAD_NORMAL': 'Перст огня',
    'skill.main.SKILL_FIRE_MAIN_BAD_FAST': 'Огнеплеть',
    'skill.main.SKILL_FIRE_MAIN_GOOD_SLOW': 'Огненный шар',
    'skill.main.SKILL_FIRE_MAIN_GOOD_NORMAL': 'Испепелитель',
    'skill.main.SKILL_FIRE_MAIN_GOOD_FAST': 'Звезда',
    'skill.main.SKILL_FIRE_MAIN_BEST_SLOW': 'Угли',
    'skill.main.SKILL_FIRE_MAIN_BEST_NORMAL': 'Огнемет',
    'skill.main.SKILL_FIRE_MAIN_BEST_FAST': 'Расстрел',
    'skill.main.SKILL_WIND_MAIN_BAD_SLOW': 'Воздушный серп',
    'skill.main.SKILL_WIND_MAIN_BAD_NORMAL': 'Разрыватель',
    'skill.main.SKILL_WIND_MAIN_BAD_FAST': 'Дыхание',
    'skill.main.SKILL_WIND_MAIN_GOOD_SLOW': 'Электрошок',
    'skill.main.SKILL_WIND_MAIN_GOOD_NORMAL': 'Шаровая молния',
    'skill.main.SKILL_WIND_MAIN_GOOD_FAST': 'Шокотерапия',
    'skill.main.SKILL_WIND_MAIN_BEST_SLOW': 'Вздох дракона',
    'skill.main.SKILL_WIND_MAIN_BEST_NORMAL': 'Дуновение',
    'skill.main.SKILL_WIND_MAIN_BEST_FAST': 'Ярость ветра',
    'skill.main.SKILL_EARTH_MAIN_BAD_SLOW': 'Плевок ядом',
    'skill.main.SKILL_EARTH_MAIN_BAD_NORMAL': 'Змеиный клык',
    'skill.main.SKILL_EARTH_MAIN_BAD_FAST': 'Отравление',
    'skill.main.SKILL_EARTH_MAIN_GOOD_SLOW': 'Хребтолом',
    'skill.main.SKILL_EARTH_MAIN_GOOD_NORMAL': 'Скала',
    'skill.main.SKILL_EARTH_MAIN_GOOD_FAST': 'Булыжник',
    'skill.main.SKILL_EARTH_MAIN_BEST_SLOW': 'Дух леса',
    'skill.main.SKILL_EARTH_MAIN_BEST_NORMAL': 'Призрак дерева',
    'skill.main.SKILL_EARTH_MAIN_BEST_FAST': 'Тень природы',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_SLOW': 'Стрела Арканы',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_NORMAL': 'Сгусток тьмы',
    'skill.main.SKILL_DUNGEON_MAIN_BAD_FAST': 'Щупальце зла',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_SLOW': 'Око ужаса',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_NORMAL': 'Сфера гибели',
    'skill.main.SKILL_DUNGEON_MAIN_GOOD_FAST': 'Шар тьмы',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_SLOW': 'Аркана Кадавра',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_NORMAL': 'Круциаркус',
    'skill.main.SKILL_DUNGEON_MAIN_BEST_FAST': 'Империканус',
    'skill.charge.SKILL_WATER_CHARGED_BAD_SHORT': 'Заледенение',
    'skill.charge.SKILL_WATER_CHARGED_BAD_MIDDLE': 'Заморозка',
    'skill.charge.SKILL_WATER_CHARGED_BAD_LONG': 'Кристаллизация',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_SHORT': 'Водоворот',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_MIDDLE': 'Буран',
    'skill.charge.SKILL_WATER_CHARGED_GOOD_LONG': 'Цунами',
    'skill.charge.SKILL_WATER_CHARGED_BEST_SHORT': 'Холодная ярость',
    'skill.charge.SKILL_WATER_CHARGED_BEST_MIDDLE': 'Ледяной взрыв',
    'skill.charge.SKILL_WATER_CHARGED_BEST_LONG': 'Власть льда',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_SHORT': 'Очищение',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_MIDDLE': 'Вознесение',
    'skill.charge.SKILL_FIRE_CHARGED_BAD_LONG': 'Выжигание',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_SHORT': 'Напалм',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_MIDDLE': 'Лава',
    'skill.charge.SKILL_FIRE_CHARGED_GOOD_LONG': 'Фонтан огня',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_SHORT': 'Метеоры',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_MIDDLE': 'Диноцид',
    'skill.charge.SKILL_FIRE_CHARGED_BEST_LONG': 'Армагеддон',
    'skill.charge.SKILL_WIND_CHARGED_BAD_SHORT': 'Молния',
    'skill.charge.SKILL_WIND_CHARGED_BAD_MIDDLE': 'Гром',
    'skill.charge.SKILL_WIND_CHARGED_BAD_LONG': 'Гроза',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_SHORT': 'Перегрузка',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_MIDDLE': 'Электрополе',
    'skill.charge.SKILL_WIND_CHARGED_GOOD_LONG': 'Волосы дыбом',
    'skill.charge.SKILL_WIND_CHARGED_BEST_SHORT': 'Торнадо',
    'skill.charge.SKILL_WIND_CHARGED_BEST_MIDDLE': 'Рев ветра',
    'skill.charge.SKILL_WIND_CHARGED_BEST_LONG': 'Карусель',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_SHORT': 'Грохот',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_MIDDLE': 'Тряска',
    'skill.charge.SKILL_EARTH_CHARGED_BAD_LONG': 'Разлом',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_SHORT': 'Крушение',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_MIDDLE': 'Подрыв',
    'skill.charge.SKILL_EARTH_CHARGED_GOOD_LONG': 'Вихрь камней',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_SHORT': 'Озеро смерти',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_MIDDLE': 'Ядовитая лужа',
    'skill.charge.SKILL_EARTH_CHARGED_BEST_LONG': 'Кислота',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_SHORT': 'Атомизация',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_MIDDLE': 'Дезинтеграция',
    'skill.charge.SKILL_DUNGEON_CHARGED_BAD_LONG': 'Ионизация',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_SHORT': 'Изгнание',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_MIDDLE': 'Проклятие',
    'skill.charge.SKILL_DUNGEON_CHARGED_GOOD_LONG': 'Отлучение',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_SHORT': 'Магическая буря',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_MIDDLE': 'Манашторм',
    'skill.charge.SKILL_DUNGEON_CHARGED_BEST_LONG': 'Гнев Арканы',
    'key.combined.first.1': 'Мудрых',
    'key.combined.first.2': 'Адских',
    'key.combined.first.3': 'Прекрасных',
    'key.combined.first.4': 'Злобных',
    'key.combined.first.5': 'Нейтральных',
    'key.combined.first.6': 'Честных',
    'key.combined.first.7': 'Святых',
    'key.combined.first.8': 'Древних',
    'key.combined.first.9': 'Подземных',
    'key.combined.first.10': 'Огненных',
    'key.combined.first.11': 'Ловких',
    'key.combined.first.12': 'Огромных',
    'key.combined.first.13': 'Синих',
    'key.combined.first.14': 'Жестоких',
    'key.combined.first.15': 'Добрых',
    'key.combined.first.16': 'Воздушных',
    'key.combined.first.17': 'Земляных',
    'key.combined.first.18': 'Красных',
    'key.combined.first.19': 'Бессмертных',
    'key.combined.first.20': 'Погибших',
    'key.combined.first.21': 'Воздушных',
    'key.combined.first.22': 'Страшных',
    'key.combined.first.23': 'Водных',
    'key.combined.first.24': 'Забавных',
    'key.combined.first.25': 'Глупых',
    'key.combined.second.1': 'Героев',
    'key.combined.second.2': 'Рыб',
    'key.combined.second.3': 'Сов',
    'key.combined.second.4': 'Злодеев',
    'key.combined.second.5': 'Приспешников',
    'key.combined.second.6': 'Магов',
    'key.combined.second.7': 'Старцев',
    'key.combined.second.8': 'Заклинателей',
    'key.combined.second.9': 'Воителей',
    'key.combined.second.10': 'Дуэлянтов',
    'key.combined.second.11': 'Торговцев',
    'key.combined.second.12': 'Кроликов',
    'key.combined.second.13': 'Яблок',
    'key.combined.second.14': 'Бойцов',
    'key.combined.second.15': 'Фокусников',
    'key.combined.second.16': 'Рыцарей',
    'key.combined.second.17': 'Варваров',
    'key.combined.second.18': 'Жуков',
    'key.combined.second.19': 'Змей',
    'key.combined.second.20': 'Драконов',
    'key.combined.second.21': 'Призраков',
    'key.combined.second.22': 'Котиков',
    'key.combined.second.23': 'Солдат',
    'key.combined.second.24': 'Везунчиков',
    'key.combined.second.25': 'Ассасинов',
    'key.combined.second.26': 'Мышей',
    'key.combined.second.27': 'Элементалей',
    'key.combined.second.28': 'Исследователей',
    'key.combined.second.29': 'Шаманов',
    'key.combined.second.30': 'Жрецов',
    'key.combined.second.31': 'Ангелов',
    'key.combined.second.32': 'Архонтов',
    'key.combined.second.33': 'Палачей',
    'key.combined.second.34': 'Глупцов',
    'key.combined.second.35': 'Храбрецов',
    'key.combined.second.36': 'Добряков',
    'key.combined.second.37': 'Трусов',
    'key.combined.second.38': 'Бардов',
    'key.combined.second.39': 'Укротителей',
    'key.combined.second.40': 'Защитников',
    'key.combined.arena': 'Арена {0} {1} ',
    'key.combined.library': 'Библиотека {0} {1} ',
    'key.combined.common': '{0} {1} {2}',
    'element.type.WATER': 'Вода',
    'element.type.WIND': 'Воздух',
    'element.type.FIRE': 'Огонь',
    'element.type.EARTH': 'Земля',
    'element.type.DUNGEON': 'Аркана',
    'spell.type.ACTIVATION_RADIUS': 'Радиус обзора',
    'spell.type.VISION_RADIUS': 'Драконье зрение',
    'spell.type.STOP_FIELD': 'Поле Изобилия',
    'spell.type.SCOUT': 'Разведка',
    'spell.type.PROTECT_ARENA': 'Защита Арены',
    'spell.type.CREATE_PORTAL': 'Создать Портал',
    'spell.type.ARMAGEDDON': 'Армагеддон',
    'spell.type.DOUBLE_DROP': 'Двойной дроп',
    'spell.type.SLUG_PLAYERS': 'Слизнякнуть игроков',
    'quest.title.WIN_ARENA_MONSTER': 'Доминация',
    'quest.title.OPEN_EGGS': 'Яичная лихорадка',
    'quest.title.COLLECT_ARENA_TRIBUTE': 'Контроль территории',
    'quest.title.CAPTURE_LIBRARY': 'Жажда знаний',
    'quest.title.CAPTURE_WILD_MONSTER': 'Парк драконьего периода',
    'quest.title.CAPTURE_WILD_MONSTER_ELEMENT': 'Охота за стихией',
    'quest.title.FIND_DUNGEON_WITH_ROOST': 'Поиск Арканорожденной',
    'quest.title.CAPTURE_ALL_IN_DUNGEON': 'Зачистка Разлома',
    'quest.title.OPEN_CHEST': 'Старинные сокровища',
    'quest.title.CHAIN_OF_STOP': 'Путь Изобилия',
    'quest.desc.WIN_ARENA_MONSTER': 'Побеждайте существ на Арене или в Библиотеке. Нельзя побеждать существо одного и того же типа дважды. ',
    'quest.desc.OPEN_EGGS': 'Высиживайте существ из яиц, с помощью драконьих коконов, или Матери Драконов',
    'quest.desc.COLLECT_ARENA_TRIBUTE': 'Соберите дань с захваченных Арен',
    'quest.desc.CAPTURE_LIBRARY': 'Владейте нужным количеством Библиотек',
    'quest.desc.CAPTURE_WILD_MONSTER': 'Существ много не бывает. Путешествуйте и ловите существ',
    'quest.desc.CAPTURE_WILD_MONSTER_WATER': 'Путешествуйте и ловите существ стихии Воды',
    'quest.desc.CAPTURE_WILD_MONSTER_WIND': 'Путешествуйте и ловите существ стихии Воздуха',
    'quest.desc.CAPTURE_WILD_MONSTER_FIRE': 'Путешествуйте и ловите существ стихии Огня',
    'quest.desc.CAPTURE_WILD_MONSTER_EARTH': 'Путешествуйте и ловите существ стихии Земли',
    'quest.desc.CAPTURE_WILD_MONSTER_DUNGEON': 'Путешествуйте и ловите существ стихии Арканы',
    'quest.desc.FIND_DUNGEON_WITH_ROOST': 'Посетите Разлом Арканы, в котором есть Матерь Драконов',
    'quest.desc.CAPTURE_ALL_IN_DUNGEON': 'Посетите Разлом Арканы, и поймайте всех существ, которых найдете там',
    'quest.desc.OPEN_CHEST': 'Найдите и откройте сундуки с сокровищами',
    'quest.desc.CHAIN_OF_STOP': 'Пройдите по цепочке Столпов Изобилия и активируйте их. Каждый следующий Столп будет подсвечен.',
    'quest.dialog.completed.rewardtext': 'Ваша награда:',
    'key.tab.altar.title': 'АЛТАРЬ',
    'key.altar.remove': 'Убрать',
    'key.altar.put': 'Установить',
    'key.altar.convert': 'Превратить',
    'key.altar.shared': 'Показывать другим',
    'key.altar.pass.placeholder': 'Вы можете ввести здесь пароль',
    'key.altar.pass.error': 'Пароль должен содержать не меньше {0} символов',
    'key.altar.level.error': 'Вам нужно достичь уровня {0}, чтобы использовать Алтарь',
    'key.altar.recipe.change': 'Вы уверены, что хотите сменить рецепт? Руны будут возвращены владельцам',
    'key.altar.row.title': 'Чтобы сотворить заклинание, нужно установить Алтарь',
    'key.altar.rune.descr.RUNE_1': '3 серые руны = оранжевая',
    'key.altar.rune.descr.RUNE_2': '3 оранжевые руны = синяя',
    'key.altar.rune.descr.RUNE_3': '3 синие руны = изумрудная',
    'key.altar.rune.descr.RUNE_4': '3 изумрудные руны = красная',
    'key.altar.rune.descr.RUNE_5': '3 красные руны = фиолетовая',
    'key.altar.rune.descr.RUNE_6': 'Фиолетовые руны самые сильные',
    'error.altar.cannotRemove': 'Нельзя убрать Алтарь',
    'error.altar.cannotConvert': 'У Вас недостаточно рун',
    'key.tab.altar.recipes': 'РЕЦЕПТЫ',
    'key.altar.noRecipes': 'У Вас нет рецептов',
    'key.altar.header': 'Выкладывайте руны на Алтарь, чтобы сотворить заклинание',
    'key.altar.castBtn': 'Сотворить',
    'key.altar.recipe.select': 'Выбери нужное заклинание',
    'key.altar.castDone': 'Заклинание сотворено',
    'key.arena.protected.ally': 'Защита',
    'key.avatarCustomization.title': 'Выберите внешность персонажа:',
    'key.buddy.walkDescription': 'Гуляйте с питомцем, чтобы получить {0}',
    'key.buddy.totalWalked': '{0} км уже пройдено',
    'key.account.balance': 'Ресурсы:',
    'key.account.userLevel': '{0} уровень',
    'key.account.totalDistance': 'Пройденное расстояние: {0} километров',
    'key.acount.registerDate': 'Начало игры: {0}',
    'key.storage.sort.name': 'ИМЯ',
    'key.storage.sort.cp': 'CP',
    'key.storage.sort.group1': 'ЗЕЛЕНЫЙ СПИСОК',
    'key.storage.sort.group2': 'ЖЕЛТЫЙ СПИСОК',
    'key.storage.sort.group3': 'КРАСНЫЙ СПИСОК',
    'key.storage.sort.date': 'ДАТА',
    'key.account.options.jurnal': 'ЖУРНАЛ',
    'key.account.options.buddy': 'ПИТОМЕЦ',
    'key.account.options.artifacts': 'АРТЕФАКТЫ',
    'key.account.options.style': 'ВНЕШНОСТЬ',
    'key.error.gps.permission': 'GPS недоступен. Пожалуйста, включите доступ к GPS в настройках приложения, чтобы продолжить игру.',
    'key.error.gps.disabled': 'GPS отключен. Включите GPS, чтобы продолжить игру',
    'key.error.gps.fakePosition': 'Нельзя играть без GPS',
    'key.error.gps.signal.notFound': 'Отсутствует сигнал GPS',
    'key.error.gps.signal.bad': 'Игра недоступна. Слабый сигнал GPS',
    'key.error.internet.notReachable': 'Отсутствует интернет-соединение',
    'key.journal.title': 'Журнал',
    'key.journal.yesterday': 'Вчера',
    'key.settings.title': 'Настройки',
    'key.settings.music': 'Музыка',
    'key.settings.sounds': 'Звуки',
    'key.settings.vibration': 'Вибрация',
    'key.settings.batterySaver': 'Сохранение энергии',
    'key.settings.support': 'Написать в поддержку',
    'key.settings.logout': 'Выйти из аккаунта',
    'key.settings.auth.deviceid': 'ID устройства',
    'key.settings.auth.google': 'Google',
    'key.settings.auth.facebook': 'Facebook',
    'key.settings.auth.link': 'Привязать',
    'key.settings.languageTitle': 'Язык',
    'key.settings.language': 'Русский',
    'key.battle.result.win': 'Битва окончена',
    'key.battle.result.lose': 'Битва окончена',
    'key.wizardBattle.result.win': 'ПОБЕДА!',
    'key.wizardBattle.result.lose': 'ПОРАЖЕНИЕ',
    'key.battle.result.monster': 'Побеждено существ',
    'key.battle.result.exp': 'Получено опыта',
    'key.battle.result.prestige_strong_enemy': 'Бонус славы за сильных врагов',
    'key.battle.result.exp_strong_enemy': 'Бонус опыта за сильных врагов',
    'key.battle.result.prestige_killed_all': 'Бонус славы за убийство всех',
    'key.battle.result.exp_killed_all': 'Бонус опыта за убийство всех',
    'key.battle.result.dust': 'Эссенция',
    'key.radar.title': 'Существа рядом',
    'key.levelUp.title': 'Новый уровень!',
    'key.wizardBattle.left': 'Лимит сражений:',
    'key.wizardBattle.timer': 'Лимит будет сброшен через',
    'key.wizardBattle.enhance.title': 'УВЕЛИЧЕНИЕ ЛИМИТА',
    'key.wizardBattle.enhance.desc': 'Лимит сражений можно увеличить до 7 в день на одну неделю',
    'key.wizardBattle.enhance.btn': 'Увеличить',
    'key.wizardBattle.lookingForOpponent': 'Поиск соперника для Дуэли...',
    'key.catch.result.expMonster': 'Опыт за поимку:',
    'key.catch.result.expMonsterNew': 'Новинка в Бестиарии:',
    'key.catch.result.expAccurate': 'За точный бросок:',
    'key.catch.result.expSpin': 'За крученый бросок:',
    'key.catch.result.strike': 'Первое существо за день:',
    'key.catch.result.total': 'Всего опыта:',
    'key.catch.fullStorage': 'Хранилище существ заполнено',
    'key.catch.noItems': 'У Вас нет магических сфер',
    'key.creadex.title': 'БЕСТИАРИЙ',
    'key.creadex.detail.caught': 'ПОЙМАННЫЙ: {0}',
    'key.creadex.detail.evolution': 'ЭВОЛЮЦИЯ',
    'key.tab.doll': 'ПЕРСОНАЖ',
    'key.tab.artifacts': 'АРТЕФАКТЫ',
    'key.activePoint.title': 'Столп Изобилия',
    'key.personalization.title': 'Зачарование',
    'key.chest.title': 'Магический сундук',
    'key.quest.daily.title': 'ЗАДАНИЕ',
    'key.quest.weekly.title': 'ОХОТА',
    'key.quest.get': 'ПОЛУЧИТЬ ЗАДАНИЕ',
    'key.quest.change': 'СМЕНИТЬ ЗАДАНИЕ',
    'key.quest.progress': 'Прогресс задания: {0} из {1}',
    'key.error.quest.weekly.level': 'Нужно достичь уровня {0}, чтобы начать охоту на Золотое Яйцо',
    'key.error.quest.daily.level': 'Нужно достичь уровня {0}, чтобы взять задание',
    'key.error.quest.tooFar': 'Обелиск слишком далеко',
    'key.quest.daily.descr.noQuest.title': 'У Вас нет заданий.',
    'key.quest.daily.descr.noQuest': 'Используйте Обелиск, чтобы получить задание, и заслужить награду.',
    'key.quest.daily.timer.descr': 'Вы сможете поменять задание через:',
    'key.quest.daily.waitForNew.descr': 'Новое задание будет доступно через:',
    'key.quest.weekly.getFragment': 'ПОЛУЧИТЬ ФРАГМЕНТ',
    'key.quest.weekly.descr.noQuest.title': 'Вы не участвуете в охоте на Золотое Яйцо.',
    'key.quest.weekly.descr.noQuest': 'Используйте Обелиск, чтобы получить фрагмент таинственной карты и начать охоту.',
    'key.quest.weekly.descr.getFirstFragment': 'Получите первый фрагмент таинственной карты, чтобы начать охоту на Золотое Яйцо',
    'key.quest.weekly.descr.top.notAllOpen': 'Используйте Обелиски для получения фрагментов карты. Торопись, охота закончится через ',
    'key.quest.weekly.descr.bot.notAllOpen.menu': 'Используйте лопату на каждом фрагменте чтобы найти Золотое Яйцо',
    'key.quest.weekly.descr.bot.notAllOpen.obelisk': 'Вы уже получили фрагмент карты с этого Обелиска',
    'key.quest.weekly.descr.top.allOpen': 'Все фрагменты карты с Обелисков уже получены. Торопись, охота закончится через ',
    'key.quest.weekly.descr.bot.allOpen': 'Используйте лопату на каждом фрагменте, чтобы найти Золотое Яйцо',
    'key.quest.weekly.descr.top.completed': 'Вы уже нашли Золотое Яйцо на этой неделе. Следующая охота начнется через',
    'key.timer.format.S': '{0}с',
    'key.timer.format.M': '{0}м',
    'key.timer.format.M_S': '{0}м {1}с',
    'key.timer.format.H': '{0}ч',
    'key.timer.format.H_M': '{0}ч {1}м',
    'key.timer.format.D': '{0}д',
    'key.timer.format.D_H': '{0}д {1}ч',
    'key.creatureStorage.tab.creatures': 'СУЩЕСТВА',
    'key.creatureStorage.tab.eggs': 'ЯЙЦА',
    'key.creatureStorage.multiTransferText': 'Выберите, кого Вы хотите отпустить',
    'key.storage.creature.transfer': 'Отпустить ({0})',
    'key.error.needHigherLevelForArena': 'Нужен уровень {0} для входа на Арену',
    'key.error.needHigherLevelForLibrary': 'Нужен уровень {0} для входа в Библиотеку',
    'key.error.arenaUnderProtection': 'Арена под охраной Благословления Защиты',
    'key.error.buildingTooFar': 'Здание слишком далеко',
    'key.error.noAliveCreaturesForAttack': 'У Вас нет доступных живых существ',
    'key.error.noHealPotion': 'У Вас нет зелий лечения',
    'key.error.noResurrectionPotion': 'У Вас нет зелий воскрешения',
    'key.error.tryAgainLater': 'Ошибка. Попробуйте позже.',
    'key.error.alreadyHasLure': 'Приманка уже установлена',
    'key.error.cannotUseLureInDungeon': 'Приманку нельзя использовать в Разломе Арканы',
    'key.error.bagIsFull': 'В сумке нет места',
    'key.error.cantTransferCreature': 'Нельзя отпустить это существо',
    'key.notification.done': 'Готово!',
    'key.modal.doYouWantToTransfer': 'Вы уверены, что хотите отпустить этих существ?',
    'key.modal.youWillLoseBuddyProgress': 'Вы уверены, что хотите сменить питомца? Прогресс получения камня душ будет утерян.',
    'key.modal.doYouWantToLeaveDungeon': 'Вы хотите покинуть Разлом Арканы?',
    'key.modal.superVisionActive': 'Драконье зрение уже активировано. Повторное применение переместит магическую зону видимости. Вы уверены, что хотите использовать его еще раз?',
    'key.modal.experienceBoosterActive': 'Кристалл мудрости уже активирован. Вы уверены, что хотите использовать его еще раз?',
    'key.modal.youWillLooseQuestProgress': 'Прогресс текущего квеста будет утерян. Вы уверены?',
    'key.modal.doYouWantToEnterDungeon': 'Вы хотите войти в Разлом Арканы через Портал?',
    'key.modal.doYouWantPersonalizePoint': 'Зачарованный столп будет выдавать только {0}. Вы хотите потратить {1} монет на зачарование?',
    'key.modal.doYouWantToDeletePersonalization': 'Вы уверены, что хотите убрать зачарование с этого Столпа Изобилия?',
    'key.modal.doYouWantToPowerUpThisCreature': 'Вы хотите усилить это существо?',
    'key.modal.doYouWantToEvolveThisCreature': 'Вы хотите превратить это существо в более сильное?',
    'key.modal.doYouWantToScoutHere': 'Вы уверены, что хотите просветить эту зону?',
    'key.error.creatureHasMaxLevel': 'Существо уже максимального уровня',
    'key.error.creatureHasMaxLevelForUser': 'Вначале  нужно повысить уровень персонажа',
    'key.error.notEnoughResourcesForEnhance': 'Не хватает ресурсов',
    'key.error.creatureIsArenaDefender': 'Нельзя выбрать существо, которое защищает здание',
    'key.modal.incenseActive': 'Феромоны уже активированы. Вы уверены, что хотите использовать их еще раз?',
    'key.error.cantHealHealthyCreature': 'Существо полностью вылечено',
    'key.error.cantRessurectAliveCreature': 'Существо уже живое',
    'key.error.noTreasureHere': 'На этом фрагменте карты нет Золотого Яйца. Продолжайте искать.',
    'key.error.levelTooSmall': 'Вначале нужно повысить уровень персонажа',
    'key.error.needHigherLevelForWizardBattles': 'Нужен уровень {0}, чтобы участвовать в Дуэлях Магов',
    'key.error.artifactBagIsFull': 'В хранилище артефактов нет места',
    'key.error.notEnoughCoins': 'Не хватает монет',
    'key.error.allFragmentsAreOpen': 'Все фрагменты таинственной карты открыты',
    'key.error.questAlreadyCompleted': 'Задание уже завершено',
    'key.error.alreadyGotFragmentFromThisObelisk': 'Вы уже получили фрагмент карты с этого Обелиска',
    'key.error.portalTooFarAway': 'Портал слишком далеко',
    'key.error.battleLimitAlreadyEnhanced': 'Лимит битв уже увеличен',
    'key.error.youAreNotAltarOwner': 'Это может делать только владелец Алтаря',
    'key.error.youAlreadyHaveAltar': 'Алтарь уже установлен',
    'key.error.cantTakeAnotherUsersRune': 'Нельзя забрать руну другого игрока',
    'key.error.libraryBlocked': 'Нужно подождать 3 дня после переучивания, чтобы использовать Библиотеки',
    'key.error.notAuthorized': 'Пользователь не авторизован',
    'key.error.eggOnlyRoost': 'Это яйцо нужно отдать Матери Драконов',
    'key.error.purchase': 'Ошибка: {0}',
    'key.error.creatureIsDead': 'Сначала нужно воскресить существо',
    'key.error.no_connection': 'Не удалось подключиться к серверу. Попробуйте позже.',
    'key.error.protocol_version_mismatch': 'Версия игры устарела. Требуется обновление.',
    'key.error.update_application': 'Версия игры устарела. Требуется обновление.',
    'key.modal.doYouWantToTransferSingle': 'Вы уверены, что хотите отпустить это существо?',
    'key.notification.phoneNotSupportAR': 'Ваше устройство не поддерживает AR',
    'key.notification.turnOnARPermission': 'У игры нет доступа к камере. Нужно разрешить доступ в настройках устройства',
    'key.notification.dailyQuestFinished': 'Задание выполнено!',
    'key.modal.yesBtn': 'Да',
    'key.modal.noBtn': 'Нет',
    'event.log.DAILY_QUEST_COMPLETED': 'Ежедневное задание завершено. Получены награды:',
    'event.log.WEEKLY_QUEST_COMPLETED': 'Охота завершена! Ваша награда:',
    'event.log.ENCOUNTER_VICTORY': 'Вы победили дикого монстра!',
    'key.ServiceException.Cause.OLD_CLIENT': 'Ваша версия игры устарела. Нужно обновление.',
    'key.ServiceException.Cause.AUTH_ERROR': 'Ошибка аутентификации',
    'key.ServiceException.Cause.SESSION_GONE': 'В Ваш аккаунт зашли с другого устройства',
    'key.ServiceException.Cause.USER_ID_IS_EMPTY': 'ID Пользователя пуст',
    'key.ServiceException.Cause.USER_NOT_FOUND': 'Пользователь не найден',
    'key.ServiceException.Cause.USER_BANNED.AutoBySuspicion': 'Аккаунт заблокирован за нечестную игру.',
    'key.ServiceException.Cause.USER_BANNED.FraudPayment': 'Аккаунт заблокирован за мошеннические платежи.',
    'key.ServiceException.Cause.USER_BANNED.ObsceneNickname': 'Аккаунт заблокирован за оскорбительное имя пользователя.',
    'key.ServiceException.Cause.USER_BANNED.Harrasment': 'Аккаунт заблокирован за агрессивное общение с другими игроками.',
    'key.ServiceException.Cause.USER_BANNED.Cheating': 'Аккаунт заблокирован за нечестную игру.',
    'key.ServiceException.Cause.USER_BANNED': 'Аккаунт заблокирован.',
    'key.ServiceException.Cause.BAG_IS_FULL': 'В сумке нет места',
    'key.ServiceException.Cause.EGGS_BAG_IS_FULL': 'Максимальное количество яиц',
    'key.ServiceException.Cause.NOT_ENOUGH_COINS': 'Не хватает монет',
    'key.ServiceException.Cause.NOT_ENOUGH_CANDIES': 'Не хватает камней душ',
    'key.ServiceException.Cause.NOT_ENOUGH_DUST': 'Не хватает эссенции',
    'key.ServiceException.Cause.CREATURE_STORAGE_IS_FULL': 'В хранилище существ нет места',
    'key.ServiceException.Cause.CREATURE_MAX_LEVEL_REACHED': 'Существо уже максимального уровня',
    'key.ServiceException.Cause.CREATURE_FULLY_EVOLVED': 'Нельзя превратить это существо',
    'key.ServiceException.Cause.CREATURE_ALIAS_TOO_LONG': 'Имя существа должно быть не более 14 символов',
    'key.ServiceException.Cause.ARENA_DEFENDERS_LIMIT_REACHED': 'У здания уже максимум защитников',
    'key.ServiceException.Cause.ARENA_DEFENDER_CANNOT_BE_BUDDY': 'Нельзя сделать защитника здания питомцем',
    'key.ServiceException.Cause.ARENA_CREATURE_ALREADY_ASSIGNED': 'Ваше существо уже защищает это здание',
    'key.ServiceException.Cause.ARENA_RESTRICTED_FOR_ALLIANCE': 'Ошибка',
    'key.ServiceException.Cause.ARENA_BATTLE_NOT_FOUND': 'Бой не найден',
    'key.ServiceException.Cause.ARENA_WRONG_ALLIANCE': 'Ошибка',
    'key.ServiceException.Cause.ARENA_CANT_ASSIGN_MORE_USER_CREATURES': 'Ваше существо уже защищает это здание',
    'key.ServiceException.Cause.ARENA_PROTECTED': 'Арена под охраной Благословления Защиты',
    'key.ServiceException.Cause.TRIBUTE_COLLECTION_NOT_READY_YET': 'Время сбора дани еще не пришло',
    'key.ServiceException.Cause.WRONG_BALL_TYPE': 'Неправильная сфера',
    'key.ServiceException.Cause.WRONG_BUILDING': 'Неправильное здание',
    'key.ServiceException.Cause.ACCESS_DENIED': 'Доступ запрещен',
    'key.ServiceException.Cause.NO_SUCH_ITEM': 'Несуществующий предмет',
    'key.ServiceException.Cause.NO_SUCH_RECIPE': 'Несуществующий рецепт',
    'key.ServiceException.Cause.MAX_ALTARS_REACHED': 'Можно установить только один Алтарь',
    'key.ServiceException.Cause.NOT_ENOUGH_USER_LEVEL': 'Вначале нужно повысить уровень персонажа',
    'key.ServiceException.Cause.CATCHING_NOT_STARTED': 'Не удалось начать ловлю существа',
    'key.ServiceException.Cause.SHOP_NO_SUCH_PRODUCT': 'Несуществующий товар',
    'key.ServiceException.Cause.SHOP_NO_SUCH_LOT_FOR_PRODUCT': 'Несуществующий товар',
    'key.ServiceException.Cause.NO_SUCH_BUILDING': 'Несуществующее здание',
    'key.ServiceException.Cause.NO_SUCH_CREATURE': 'Существо не найдено',
    'key.ServiceException.Cause.WRONG_CREATURE': 'Существо не найдено',
    'key.ServiceException.Cause.TOO_FAR': 'Здание слишком далеко',
    'key.ServiceException.Cause.OBJECT_TOO_FAR': 'Объект слишком далеко',
    'key.ServiceException.Cause.BUILDING_COOLDOWN': 'Здание на перезарядке',
    'key.ServiceException.Cause.BUILDING_IN_DUNGEON': 'Здание в Разломе Арканы',
    'key.ServiceException.Cause.BUILDING_NOT_USABLE': 'Нельзя использовать здание',
    'key.ServiceException.Cause.INCUBATOR_NOT_FOUND': 'Драконий конон не найден',
    'key.ServiceException.Cause.INCUBATOR_IS_EMPTY': 'Драконий кокон пуст',
    'key.ServiceException.Cause.INCUBATOR_NOT_EMPTY': 'Драконий кокон занят',
    'key.ServiceException.Cause.EGG_NOT_HATCHED': 'Яйцо не было высижено',
    'key.ServiceException.Cause.EGG_NOT_FOUND': 'Яйцо не найдено',
    'key.ServiceException.Cause.EGG_NOT_FOR_INCUBATOR': 'Для этого яйца нужна Матерь Драконов',
    'key.ServiceException.Cause.NO_CHARGES_LEFT': 'Закончились заряды',
    'key.ServiceException.Cause.NO_PLACE_FOR_BUILDING': 'Не удалось разместить здание',
    'key.ServiceException.Cause.NO_BANK_ARTIFACT_FOR_DEPOSIT': 'Произошла ошибка, а это таинственное сообщение о ней',
    'key.ServiceException.Cause.ENCOUNTER_CREATURE_RAN_AWAY': 'Дикий монстр убежал',
    'key.ServiceException.Cause.ENCOUNTER_NOT_FOUND': 'Не найден дикий монстр',
    'key.ServiceException.Cause.LURE_IS_ALREADY_INSERTED': 'В этом Столпе Изобилия уже есть приманка',
    'key.ServiceException.Cause.WRONG_ITEM': 'Неправильный предмет',
    'key.ServiceException.Cause.RUNE_MAX_LEVEL_REACHED': 'Эта руна самая сильная',
    'key.ServiceException.Cause.NOT_ENOUGH_RUNES': 'Не хватает рун этого уровня',
    'key.ServiceException.Cause.WRONG_RUNE_SLOT': 'Неправильный слот для руны',
    'key.ServiceException.Cause.RUNE_SLOT_TAKEN': 'Этот слот уже занят',
    'key.ServiceException.Cause.RUNE_SLOT_EMPTY': 'Слот для руны пуст',
    'key.ServiceException.Cause.CREATURE_IS_ARENA_DEFENDER': 'Нельзя выбрать защитника здания',
    'key.ServiceException.Cause.WRONG_SPELL': 'Неправильное заклинание',
    'key.ServiceException.Cause.NEED_MORE_RUNES': 'Заклинание требует больше рун',
    'key.ServiceException.Cause.QUEST_COOLDOWN': 'Новое задание еще недоступно',
    'key.ServiceException.Cause.OBELISK_ALREADY_USED': 'Вы уже использовали этот Обелиск',
    'key.ServiceException.Cause.WEEKLY_QUEST_ALL_OPEN': 'Все фрагменты карты уже открыты',
    'key.ServiceException.Cause.NO_ACTIVE_WEEKLY_QUEST': 'Вы не участвуете в охоте на Золотое Яйцо',
    'key.ServiceException.Cause.WEEKLY_QUEST_SECOND_TIME_DIG': 'Вы уже пытались искать Золотое Яйцо на этом участке',
    'key.ServiceException.Cause.CREATURE_FED_ALREADY': 'Вы уже использовали лакомство',
    'key.ServiceException.Cause.CREATURE_CATCH_ALREADY': 'Существо уже поймано',
    'key.ServiceException.Cause.LIBRARY_NOT_READY_TO_REMASTER': 'Переобучение существа пока недоступно',
    'key.ServiceException.Cause.LIBRARY_USAGE_BLOCKED': 'Библиотека пока заблокирована',
    'key.ServiceException.Cause.TRY_AGAIN_LATER': 'Сервер не отвечает. Попробуйте позже.',
    'key.ServiceException.Cause.WIZARD_CANNOT_ENHANCE_LIMIT': 'Лимит битв уже увеличен',
    'key.ServiceException.Cause.WIZARD_BATTLES_LIMIT_REACHED': 'Лимит битв исчерпан',
    'key.ServiceException.Cause.WIZARD_LEVEL_TOO_SMALL': 'Нужно достичь уровня 9, чтобы участвовать в Дуэли Магов',
    'key.ServiceException.Cause.WIZARD_OPPONENT_NOT_FOUND': 'Оппонент для Дуэли Магов не найден, попробуйте позже',
    'key.ServiceException.Cause.MARKET_ERROR': 'Ошибка магазина',
    'key.ServiceException.Cause.NO_CHEST': 'Сундук не найден',
    'key.ServiceException.Cause.QUEST_MAP_ERROR_TRY_LATER': 'Ошибка выдачи фрагмента. Попробуйте пожалуйста позже.',
    'key.ServiceException.Cause.TOO_MANY_ROOST_EGGS': 'Нужно надеть Сердце Дракона или комплект Драконьих Артефактов, чтобы дать Матери Драконов больше яиц',
    'key.ServiceException.Cause.WRONG_ROOST_SLOT': 'В этой ячейке уже есть яйцо',
    'key.ServiceException.Cause.NO_CONNECTION': 'Отсутствует интернет-соединение',
    'key.ServiceException.Cause.SERVER_DOWN': 'Игровой сервер временно недоступен. Пожалуйста, попробуйте позже.',
    'key.ServiceException.Cause.SERVER_MAINTENANCE': 'В настоящий момент проводится техническое обслуживание игрового сервера. Пожалуйста, попробуйте позже.',
    'key.ServiceException.Cause.RUNE_IS_LOCKED': 'Эти руны сейчас используются',
    'key.ServiceException.Cause.TOO_HIGH_SPEED_FOR_USE': 'Вы двигаетесь слишком быстро',
    'key.ServiceException.Cause.CAPTURED_ARENAS_LIMIT_REACHED': 'Вы достигли лимита захваченных Арен',
    'key.ServiceException.Cause.CAPTURED_LIBRARIES_LIMIT_REACHED': 'Вы достигли лимита захваченных Библиотек',
    'key.ServiceException.Cause.LOCATION_MANAGER_NOT_VALID_STATE': 'Ошибка: GPS недоступен',
    'key.ServiceException.Cause.CANNOT_CAST_IN_DUNGEON': 'Нельзя использовать это заклинание в Разломе Арканы',
    'key.ServiceException.Cause.BATTLE_EXPIRED': 'Время истекло',
    'key.ServiceException.Cause.PROTOCOL_MISMATCH': 'Версия игры устарела. Требуется обновление.',
    'key.ServiceException.Cause.ALLY_AREANA_NOT_FOUND': 'Нет союзных Арен в зоне видимости',
    'key.ServiceException.Cause.ENEMY_AREANA_NOT_FOUND': 'Нет вражеских Арен в зоне видимости',
    'key.ServiceException.Cause.ACCOUNT_ALREADY_USED': 'Данный аккаунт уже используется',
    'stop.personalized.BALLS': 'сферы',
    'stop.personalized.HEALS': 'зелья лечения',
    'stop.personalized.RESURRECTIONS': 'зелья воскрешения',
    'stop.personalized.EGGS': 'яйца существ',
    'stop.personalized.FOODS': 'лакомства',
    'key.button.cancelPersonal': 'Отменить',
    'key.error.needHigherLevelForSofaBattles': 'Нужно достичь уровня {0}, чтобы участвовать в Дуэли Магов',
    'fraction.text.youWilLGetBonus': 'Вы получите {0} монет за присоединение к этой фракции',
    'fraction.text.fractionUnavailable': 'Фракция сейчас недоступна',
    'fraction.text.chooseYourAlliance': 'Выберите фракцию, за которую будете сражаться',
    'fraction.text.redFractionName': 'Красный Орден',
    'fraction.text.blueFractionName': 'Синий Орден',
    'key.error.chestTooFarAway': 'Сундук слишком далеко',
    'key.button.openChest': 'Открыть',
    'key.candy.MONSTER_WATER_1': 'камни Жабуса',
    'key.candy.MONSTER_WATER_2': 'камни Капли',
    'key.candy.MONSTER_WATER_3': 'камни Спиритуса',
    'key.candy.MONSTER_WATER_4': 'камни Аквина',
    'key.candy.MONSTER_WATER_8': 'камни Джеллихата',
    'key.candy.MONSTER_WATER_9': 'камни Минори',
    'key.candy.MONSTER_WATER_10': 'камни Инфалиска',
    'key.candy.MONSTER_WATER_12': 'камни Дадачока',
    'key.candy.MONSTER_WATER_13': 'камни Батоида',
    'key.candy.MONSTER_WATER_23': 'камни Брониуса',
    'key.candy.MONSTER_WATER_24': 'камни Нептуна',
    'key.candy.MONSTER_WATER_25': 'камни Левиафана',
    'key.candy.MONSTER_FIRE_1': 'камни Потти',
    'key.candy.MONSTER_FIRE_2': 'камни Муммивина',
    'key.candy.MONSTER_FIRE_3': 'камни Паровика',
    'key.candy.MONSTER_FIRE_4': 'камни Инкумуса',
    'key.candy.MONSTER_FIRE_6': 'камни Флейми',
    'key.candy.MONSTER_FIRE_7': 'камни Фоуби',
    'key.candy.MONSTER_FIRE_11': 'камни Искры',
    'key.candy.MONSTER_FIRE_12': 'камни Кидры',
    'key.candy.MONSTER_FIRE_15': 'камни Нидлхота',
    'key.candy.MONSTER_FIRE_25': 'камни Смаугра',
    'key.candy.MONSTER_EARTH_1': 'камни Ягодилло',
    'key.candy.MONSTER_EARTH_2': 'камни Цветика',
    'key.candy.MONSTER_EARTH_3': 'камни Листка',
    'key.candy.MONSTER_EARTH_4': 'камни Брауни',
    'key.candy.MONSTER_EARTH_8': 'камни Гоблика',
    'key.candy.MONSTER_EARTH_9': 'камни Белфлоу',
    'key.candy.MONSTER_EARTH_10': 'камни Желудня',
    'key.candy.MONSTER_EARTH_11': 'камни Фило',
    'key.candy.MONSTER_EARTH_13': 'камни Принси',
    'key.candy.MONSTER_EARTH_25': 'камни Сциллы',
    'key.candy.MONSTER_DUNGEON_1': 'камни Рууки',
    'key.candy.MONSTER_DUNGEON_2': 'камни Аксолана',
    'key.candy.MONSTER_DUNGEON_3': 'камни Шипоспина',
    'key.candy.MONSTER_DUNGEON_4': 'камни Магглада',
    'key.candy.MONSTER_DUNGEON_5': 'камни Милокота',
    'key.candy.MONSTER_DUNGEON_6': 'камни Рози',
    'key.candy.MONSTER_DUNGEON_12': 'камни Вампиро',
    'key.candy.MONSTER_DUNGEON_13': 'камни Гусеня',
    'key.candy.MONSTER_DUNGEON_17': 'камни Инура',
    'key.candy.MONSTER_WIND_1': 'камни СунТзы',
    'key.candy.MONSTER_WIND_2': 'камни Ухомыха',
    'key.candy.MONSTER_WIND_3': 'камни Грибби',
    'key.candy.MONSTER_WIND_4': 'камни Пушисторога',
    'key.candy.MONSTER_WIND_6': 'камни Гамаюн',
    'key.candy.MONSTER_WIND_7': 'камни Страшуля',
    'key.candy.MONSTER_WIND_11': 'камни Инфирда',
    'key.candy.MONSTER_WIND_12': 'камни Ундины',
    'key.candy.MONSTER_WIND_15': 'камни Чешира',
    'key.candy.MONSTER_WIND_25': 'камни Харибды',
    'key.button.leaveDungeon': 'Покинуть Разлом',
    'key.alias.enterNewAlias': 'Введите имя существа',
    'key.alias.enterText': 'Введите текст...',
    'key.hut.hutName': 'Матерь Драконов',
    'key.hut.hutDescr': 'Отдайте Матери Драконов древние яйца, чтобы она высидела их для Вас',
    'key.text.noHutEggs': 'У Вас нет древних яиц',
    'key.text.noCapturedArenas': 'У Вас нет захваченных Арен',
    'key.text.noChosenPet': 'У Вас не выбран питомец',
    'key.text.noArtifacts': 'У Вас нет артефактов',
    'key.text.noCreatures': 'У Вас нет пойманных существ',
    'key.text.noLureItems': 'У Вас нет приманки',
    'key.descr.aboutWizardBattles': 'Участвуйте в Дуэлях против других игроков, чтобы получить опыт и награды',
    'key.text.writeToSupport': 'Написать в поддержку',
    'key.text.regUsingFacebook': 'Зарегистрироваться через Facebook',
    'key.text.regUsingGoogle': 'Зарегистрироваться через Google',
    'key.text.logUsingFacebook': 'Войти через Facebook',
    'key.text.logUsingGoogle': 'Войти через Google',
    'key.text.logUsingDeviceIDCurrent': 'Войти через Device ID',
    'key.text.logUsingDeviceIDNew': 'Войти через Device ID (новый аккаунт)',
    'key.text.createAccount': 'Играть',
    'key.text.connectedToFacebook': 'Подключено к Facebook',
    'key.text.connectedToGoogle': 'Подключено к Google',
    'key.text.complainAboutPoint': 'Пожаловаться на точку',
    'key.text.copyCoordinates': 'Копировать координаты',
    'key.text.complainEnterEmail': 'Ваш e-mail',
    'key.text.complainEnterText': 'Расскажите о Вашей проблеме',
    'key.modal.doYouWantToCloseApp': 'Вы хотите закрыть приложение?',
    'key.catchPopup.notBad': 'Хорошо!',
    'key.catchPopup.good': 'Отлично!',
    'key.catchPopup.sumptuously': 'Великолепно!',
    'key.catchPopup.twistedThrow': 'Крученый бросок!',
    'key.battlePopup.strongHit': 'Сильный удар!',
    'key.battlePopup.weakHit': 'Слабый удар',
    'key.battlePopup.dodge': 'Уворот!',
    'key.battlePopup.chargedAttack': '{0} использует {1}',
    'auth.login.play': 'Играть',
    'auth.login.nickname.placeholder': 'Введите имя',
    'auth.login.nickname.busy': 'Имя занято',
    'auth.login.nickname.proposal': 'Вы можете использовать это имя:',
    'auth.login.nickname.deviceId': 'У Вас уже есть персонаж',
    'auth.login.social.title': 'Зайти через соц.сеть',
    'auth.login.social.facebook': 'Facebook',
    'auth.login.social.google': 'Google',
    'auth.login.social.connected': 'Подключено к {0}',
    'auth.login.social.signOut': 'Выйти из аккаунта',
    'auth.login.signOut.confirmation': 'Вы уверены, что хотите выйти из аккаунта?',
    'auth.login.social.userCancelledError': 'Отмена подключения',
    'auth.login.social.cantSignInError': 'Не удается подключиться к {0}',
    'licence.title': 'ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ ИГРЫ «DRACONIUS GO: CATCH A DRAGON!»',
    'licence.checkbox': 'Присылайте мне новости и предложения на e-mail',
    'licence.accept': 'Принять',
    'licence.decline': 'Отказаться',
    'key.error.wrongRoostIndex': 'Ячейка недоступна',
    'key.speed.passenger': 'Я - пассажир',
    'key.activeObjects.addUnit.question': 'Вы уверены, что хотите сделать {0} защитником этого здания?',
    'key.egg.passedDistance.simple': '{0} / {1} км',
    'key.egg.passedDistance.roost': '{0}:{1:D2} / {2} ч',
    'key.confirm.selectAlliance': 'Вы уверены, что хотите выбрать эту фракцию? Этот выбор нельзя будет изменить в дальнейшем.',
    'key.confirm.giveUpEncounter': 'Вы уверены, что хотите отказаться от боя с диким монстром?',
    'key.confirm.giveUpBattle': 'Вы уверены, что хотите сдаться и закончить сражение?',
    'key.copyright.elyland': '© Elyland LLC 2017',
    'key.copyright.osm': '© OpenStreetMap',
    'key.loading': 'Loading...',
    'key.layerUp.title': 'Новая Лига!',
};
